#!/usr/bin/env python3
"""
🚀 Agent Docs-as-Code Harness Installer
=======================================
Autonomous, zero-dependency installer bringing Docs-as-Code discipline,
Obsidian graph integration, knowledge base linter, and 3-mode AI agent guardrails
to any project in a single command.

Usage:
    curl -sSL https://raw.githubusercontent.com/koudinie101-png/agent-docs-harness/main/install.py | python3
    python3 install.py [options]

Zero external dependencies (requires Python 3.8+ stdlib only).
"""

import sys
import os
import re
import json
import zlib
import base64
import shutil
import argparse
import subprocess
from datetime import date
from pathlib import Path

# Ensure UTF-8 output on Windows consoles
if hasattr(sys.stdout, "reconfigure"):
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass
if hasattr(sys.stderr, "reconfigure"):
    try:
        sys.stderr.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass

# Python version check
if sys.version_info < (3, 8):
    print("❌ Error: agent-docs-harness requires Python 3.8 or newer.")
    print(f"Current version is: {sys.version.split()[0]}")
    sys.exit(1)

# --- BEGIN_EMBEDDED_ASSETS ---
EMBEDDED_ASSETS_B64 = "eNrtvYt2HNd1IPorx2Su2A13NwBSlOWOKAUEQApXfAUAJXsABF3orgbKbHS1q7pBwiTWoqTITq6cSJa8rryU2LK8kjhr5s4siCIt6kHqF8Bf0A9cf8Ldr/Oqqn6Q9COedT0ZsVFV57XPPvu997l5bGZmczXc7XWCfphOry5evHJhbnVxc25hubbbOlZXx6rV6no3atUVPKp+D/633u1H/U5YV+vH1o5+eXR49NnRHfjvg6P7R/fU0eGj24/eOrr/6I2je0dfPHrj0ZuPbsOrh0efHj1U8PPeo3+AF/Dto3c21o+td9N+0B+kdRU0m2GvH7bUcdVL4l6cws9b9uktlYQ/CJv8sxX2krAZ8B/poBcm8HXYWu+24FldnZw5+Vx15rvVk89B9+bt5tY+zhjH7AfbaX29q1RVBa1EfiTNnagPIwyScL1La17vHjdrrqv8UrOrgQYvqqmpo49h7Ye08tfrU1PQ8CP48v7Rg0fvwIuHMOWjX8GPL46+BKg8oOYPN+AptPw5tjs6xFZ2EUphvy98q1pV8MGXj95RRw+pPc7mwaO3H73lzeToc6VhqkFWUfDCn/v6MZkEPKb+arXa+jFVrb6Iy9DLP65ma+roQ5yn7Ofrj95QR/fV0dcw5MOjT2AN946+Ojpc7/L83i3c/EOYM/zgGdyHNjBsRcFrmDb08VDPC5cGfQOu0Nf45CcavDAkNESw/j1M9/bRV4/e1rOFaZ6Eaf7agcE9PaHfwkNaJk5Bt3wTerpPC7iDr3g1ZoMKMFXRrGFqd+Dp7aO78OcXCAi7D4fOZE7VeIf540+h3zdh2m/j4biDxwNaHyJAYQWlZY3Vc51+mHSDfrQXpuX17hSgw9rRu7DdP0VgChjfgKbQhZrdQBThFRJyAZxw/m/rKVnUwtmX6JPX4fl9APvr9PZ3iHa4nY9+KuiBrQ5hbQ9oqrgD8Pot+PTuo7fLvLzRszr5eLOyAHsWAPYRzobQ6S7OChHl0Ts8Irz78tE/w9O3/f7vQe+wmY/+EWbCTQ6z+2ZmffSvNJU3sRc1zTj9lWDxVwgcv/tfEKpytwyPIVhJAxyrqGFUdHn+5aXVxfnVq8uLOXIK76pjyekXPFENOSQPGbqJKAN97PegC5+KNZMQiaSliLPfXe8Oeq38Q5ciel3gk2a824u7Ybfv0MXff/TOv/y/998pPvGHRdSyeCVDaea72Bsh1gOmme9ponOP38j55e7vCwH9Bfx1lwkVdbNWq03Dzix1W+GNW/rHxgaS1CyVe9/s7o81xiIGvCGohRsuJ+bovqYuvEY8Az/RhKdwnUjWHv2EqD8dta/o7EiXSs4m4jh3g4+QLN8jUgQjPKRT5JO7nxMZYZz8CmkwUhcgRHgo8NBC68/dk9RoNHbDZDeIgE+2O/H15k6Q9NXqAu6xUvOdCDZ4DdjCh0jpeOJwUK4urR/bwJHVSpjsRc0QP/mYpn+H5o2n43NNVD6Hj7k/+Zpb9uMk2KaW/66BTBQYDi6exZ8d/ZzawQwdCvoL5jmAXn8vS3mbuMMXzI2oI0S4t/VmfGggeIdPLBE0PtkVRcc/0x8Rw/tIoQX3buMYXxHLQAgCfmWo1K+OPqGBP9GkHxHlH6AP5GJfyEyWw36yXyUM+JJOxn1meLip+AzYzI+JeMDonxBC30FuCN1+jvvI3GIcZTl79XyWoMCjHD35kOj4GwS1e3kxgGegRbFwL0yiPohJu8EP4gQksa1O3LwWJnC2mvAiagYd+Mkv4d+oG4PwZKhDXVMLpBuaPHXD69AP/veWirrA2/rRNjC57jb2GXfbUbJLUlzUrYLYt52EaQp/taMb9PR63O3D7/VuEtKrKO5uAhT6uDb8N53uBf2d6X48jX9t2q9q4Y0+LumJKODWYHu9ey3obgVdAiISkVfoz1uAZAi6T/C/VcQQOrmHGwQ/hzi++ys8oPcI1QBJzd6ob27/XI3bFUMVlxaQiOmmROA+JL76BvEgw8CJ1F2UbbmI2yLkMEdVf4k4TSeWKKqDy/fwyS9gOV/TwzvEih9ssPCJA9uFG8paAJRi2voxEaWv6Vh9JecYzguctzdBEDEiGzFq71vLkX9L1FPoDJwS/BdW/1OhCUALkP49lAU8pLN2h07xfaLhrizwq+zQdphfHX1cETEPacOjd5BGMHPL0N//ROrLMmF21HtEfUX2WgZlJQYaGPZQrgNouALMXdwaWtIdOo80xMmakfYdGs608gtZPbI5kTlP6c9/JZQIydJeimv5HfwN35GMTpj2NY1k5qdHNERXmIrldNRZ6ehfSCwG6ZFQCoBRFekdplcmyt3HEyeU+DdWVXho5nTfCNG43E95YEvyWQZkvvKQBXIWH3H85Tjuq/lgkIZqrht09tMopZO0PD9XHq96eOOy9MbHlrQKbyQEjD60nkx/mqaHAvID5tfeMdGyamPt4uWFpXPf32iohqZM7agTIjlq0Ix5rgUd6K3ATi4tvoY9jKVwTpe0GZ+S9Ps6MTWUPoQ3v8GCrLOa52A17xGw78NqaZOFJQG66hGq56Ik7QN8q2pNbeDyUTs4BB77j6RlTjLk8CPpgRqGXVwo18xQvyiEj6hpX9EDkZPu8JGAvmzrX08wL9HlkIDgf2BRb4h8KSoPqIKKDufXpFDgYKXzy4uLl5xpfkjGDqBLgD9f5LGHmt6mw3cPZR3GsDuqsQD8sqH4T4d24hLvK5LhviYUObQtwr1OvA0Mv1EbJRQsLL564XJOLuCnRiw4+r/12Tj6UtRyT6a5r0o8XHmYltGi10/IXXVj/P2DeAA6b8djne//8rFmKOzpNyQs30dCfpxHUMeld8PCfq1xD75FDdbQgM9EJCeJjrnbUKWBRNiHZNHK0hM8FEe/Gzd1+FQj5ufCvBy59dFbLCZaJIfPah5HPa7Wvg//q168WF1Y2CAScPQBHRVkWsYColbnVl6pDjFd0ZLvkt5yfwPxGcBjOCwyB6J0Rw8BGLxTQ0TszFTFgHOXTEP28D7Q8nhGMdJSbpV35x7A6k2xLRzSWzGheESKNtmd1HvQO5EVc7xJcGeKb6R+ZCOLN6I+SJ2tUM2UnZE/FrPDm5a0/QNywcw4/mcGcRiKh5rL0IH/kvS3MRL80qWFxe9lzyqiGz53hHjQj9jCxKomo0Thpn7k6MejrAQ7g60nPLwgyqC9iv+I8Fx4Z/e3v1ZPPFtjCSCy+eMsZzJC58qVxflb+B8A3YbIub8iEvpQTHMPaOvg68vdrThIWqBt3Mp/kpdUf//RB1+QTUPT9UNtteQTAViFX45WpIlYgKqr6QYIT/+O57+s9Wg7qTXULcbM0SjU3Bl2MJc0d3AAFKwLrS8FbVaD9FqKjVBy/cCe/aLuF5bxQ5AG4VfB++UwDQOZAgptvyBiRkfDteQWTQK1P1r2DIpTv5HD6lty7hU0ZGJP4OKft1wOIUDiRrRQasTKCTWaOblJz4sVFjOgbbscB63doOc3loe3QEh+SFP+nZYvv9D4Ip2JVOti1vtvoFxicAlo26O3MraQQ9FOCF3YGDkWPSqqECSFnIe/zp2gGg/bmJndnHNMf9MNnECxVM0GYjQO3zPqXM4sY/rV8GsIZx25GRX1uBCvqMaVTtCF/uHXSi9s8q+zg23+sRx2wiAFwtswMzq1uRA2I5RxU/RzyVKRARFGPrqddaiUGtoP1CibXp7d1EdBOhhyEgg8nxDH+wnZd26zCNNYXlxZ1EZgp9/Tm3JQpNvfkr5FSPI6cUXD5ryTAwMtnlxUV79nOnK5Dnf1oYx+KIa7e8zpPmHLPO3ZcH71ytyls3OXXIbFNpJqrzPYjrp1tRWkUdOX5d5WQywmvjH3sFCO69N5PM6jqOMwn24XLUfKcIo7j94hHvxA48XdoYjCyDcRRjFf4GP778DQHv2T+C4+VaWzQfOaFjzpm2/e+TRnSSktddUVsWY5X/4ryHbv0ye4aaBPoB5A70GfuLFBJk80P5MOTiKEUcsIfp/hUXO4qlqIm2k1SKvzKNKUrFBYBhkYXplVvPcx9o2E5z4hIwAYxTA61NhpaakZbsU39FRAtdHmbcIuVqFRt7G6tNcFa8rqeNQKg1EYdPnS2ctzywtLl3Iqin1j1ZRfgzD4BYPK+IQekglDkQjpkcJHb6qSpZXq/ADmUv7Dyz+xGYL/3sZxRK+RzUD50jsEH95+qrVYHafA20Cn+jdWAb3D2ivrol8at6vFTrJ0fGEEZLT1sI8CntSLnfeHqoFrQ2L6LIu3vyMt/NDQfTFIAf3Inc37Q9Wpyh+FFwyREGo5m6R3dl4NBp0+kk0rvd7B3UFF/As40AIAXj0qMJ8RjB6SbvIO7NZWGrUiIFLUEZNynCjA8E3Wj1idIeMF2Rq+P3fxgmoncbe/G/T7YaJYMzQEDb52oHY9uhZ1ou611LDrKyiB0iNCgX8j5wGKFYANH1TEWU5a6h3hP7jV9NcDNgS6pgk06rCRlG0srNmgkfRtMgLel1Hn4HBWF5s7MQ36MfpQ2JuPY5z65vb7p7GDN2GIL0QLo0E+e/TPOBCqc19pDU2RYRLVwUN0zNP0sYWMdCHaw3OM/JzHIk3uLdG9XdLYEEmmgXMAnjq3cHGR/+SlAFRFQ80JKRo6VmeDXt/K4ApIzBm0H2KRiNJmvBcm++rbILB2IvxJZ/cWixbUGo3svyEr1qd48kDSwGiQvGeZzfHvoT2ANNtb2E0dJqWK/8HXU1O//+jn/4872Ex9iFBydA9geks1pq9tVRMRYhqkSiH8qpcvXfg+6C0/w63T9rXDMjfxhBYQr0Awgn+YgaCBOhfaYif30cfu5GbrxqJqJ4M8fsKJAEu5hJPAva54YoZq5Bh3w5nFr91ZnKzTibEzQKFjwhloA0vRDArEAncOv3HncKrO8Qh37Swi4J3hbtjt41TQ5k6I/6nhGTBlfEGtKkYgJD/nIRCRN4hEuScYhJIG9IvOuk7YDxtlnIyL5qfITaONrg/JvXQfnSoOgSfrNE2vG8HMpvkP4YlsjB4hw7BojYzQ+FoRX7Lcr2ZGSVhyl47RzPM1WWS/8A6sKokTkwRb1YrS/nRFrbw8Vz15+jmGzdGnZdvr1mBbevw3CuN53QpZvvk2ZwoHHX+hQj4H2xuQYDHDiz2DLVY4E+j1nnip3rAOFcUOaULLLypZFgBMlMxdNAFD2TIU6dlhij/zwjfYOSbkXlgXTdjXCABwnvBfhtOcUwIB9wtlAvrYaHbwlWNQtOyHXOxmr2AIBlxeAVMl+If6dLUq6PZ+sU5FnzqKEqzljWJzAihEMqq1oUO/npnWsciWiYtoxisfGwnDNRXD9pUzG3Na3Cpv+G6L+xxmUMi+mNutJoPutepZQPYWcrvGbhB1GzV4cQ5kVNgHdTYJus2dkJh9ow0PpzXxaRD+o3L4jvbp/0R4+2fKP/LCWhcGQad6EcWelf0ucdflcDfuhypOItDjCJl7g3Tnr9WFuAmfXu529hnDCWcRZI9+Kg4VoQ4YQfVGBhjsY3pAJtPbFhh38AA4MVuO1dVVCUHTSuLr3XYUdlpqrhX3+oAsEhd3PglDebMEGocczlIjQnG/06n19kEdQV1ErR+jsMZGmWSIj9gnhBukGgPY3yZ8hKQbnj0ky4zGGStT4Cv2AIsfHdcLh0oz+0ZFv72NDqPX1TCMNW5kpAzODvksuORyb71h7GpWs/AWqesdHVVEcoTBJF7jL9CGjodQM6uHDGKtQb45TIYVoY+NruT6RlL9ufV+Iy1xCJIzsZMwMesbhZEs3y2L8KbB+7khDYoiuxzkQDnaygBlcdE9oB27b6V8VnXuk4DucFx/RqdgRj+nnfgx6alfinvXE+QAMjy992iv7ntOEeFWLtOlvtBZ82Z210D3daQX/RdLEvovy9FHGllQqskqx1rSGR8o+IB4ztfsJjEeib9nB7fnEDAx1sPCrf2AHE1E3EBsrU3jqte7vR2gXnU1+6SOBeoEf7WZ5EGPQQLg2kxRBdBhODnrJa7p6UJ10EYl2GtBLXE6uYhvA0ovQse0Kg66waCx1ync5K4r3X9MyEUhaoZQPCyOy8m69x5uOIr2aHfJEI/JU4XzFASEi7ADetCVJN4CTFfPqPNx0EnLNjwP5VEiRV7wuJAkkkXgz5coyI526wESIAIB9f7ABjxp60aRbMJ6NhmpKAIPeNVnYsdix+87mUCeou0RpdCJJC797TNzwn/+dtbGC70nwSowMZBms0HuPJJSU+LgtN5ZpwdgpJ+I/idM9WuyErHm58fnvDskuYJ0a1cI4AVI0Lfegg8IL29z4BJhHNnvh/hmK7mQe8eZ60aUm1jZTLD7YVGcuBfH+myNg5zs6J+x8uA5V1UJxUyQgcLgWguEAhOSYjSw6myjbgK4bOxE1tOtfb5+25OP0daIeToOj9zTOiHiPhlUvmDU+1LCN0oL8YKj7WH0ftmJIPGINseE5snCIUkWheiMQ2L4jOiqFXY1OLqqDVcZbjkDtZ7Na2w4wbNJpiORYg+Hhbzkff3ktFcNJiXc250ifdz2+B95LQkPOJ8BjVf6bPqyU9pMol4/Bfa6iXoYCH6jmevy4oXFuZVcIL48ru6tfa/2/dp/23B977823nz9dlgmkNZHib+AaIjaDfEk6fSYyyM1G7Z89bjHY1tJ0O7rfCZr2F/vbkf9TWCb2PGe0zM83hlsbYrGvDlIOjrXaRcEffzNX6wfg4H4J4zSIfk+Bvl+vRsk/agdNPuaIXeDXZY09AsMOKOx0FWKQWn4lrTt4k/S6EciqrDfk2Le7dudANRzei+q+kYmM0vWIkHFO0F3O6S4oSfg9gkjt2kzoSc3b8WfBBlsJMN7NooUyb1uwwz439jQTMz3Uj79y+45vVqFLUfVT/fRMPz/52M8XpMul4Y5H/VfBsy4BNogq5q0v3I+Ni9dXl1coTOdC5xAIQrZ9mc4gnccDPv3Qp59s7ATAYVJBBl2T8K+Nf54YZm8L7/VmRXsYEGJvTSvMUaYNlp7kI4zVNhPPHNp8woeSaNMV9POYPuW/mtjYxhjsKHEP6McDFGatNOefM8Sts1dyh8T9Di3sOzKbjlTiXZEc7/6rzEd6136D5Yg3iA7l/jpVUkOoDZWiy9B3VLuyYU/5Tt88RFx+Z9OZJdu+PQBLZo+TUCjp6EC+LpRQFYabLCkdfz8n/LWNse2z1zyAaPS6+SB+QrTRBqNxlaQ7uB5vhJfD5OVnbADdPJ82K+eizrhy/BOVec623ECBHIXl4urLSJx0MOFqDu4Mb0bNC+v1IWapYPd4q8pHmQUW2KTep4vWVO7p/v9hpMuh9sa8rmSnvLncp0hel6BGofptDk1Dh96RJt1YszYwFW2NsmJD2Rywz4KWok8cegrei6G+CqQyI5b8kZhBIGeznCdZ7QHskj5+cjPfC1yqGual5MnH5JM90mWuuV2a3ruypKTZsuq3ztWWs868H2F5l22a3IOGR6xt2QGn7HVQ1nzBtk9q9p2quf9US5LQMSx1zkGRYf93KGUWtQYKgpkuweiAjzkuUl2rzGEgmj6O5rEA6NHfG6MKhUO1iRDoregUwLyQ8n6s8G296w19rYThHSXzltvv78TE2od/U+yZ30tovpX2nqWtWLeNWpjJlYnm6XwsfhIHthQYt3PoQP50moStMJq3G6ri0E/iW5o+vqemwNMxFSnt+Ifbp6qp8SRZcBLP57MKXj0LrmV9M7qoTBgQz/9tRmDn7pOvEc/O3pguvqZKrn6anlsz4VptnqUXxvN7x7ls8hxNoT+9MR51Doz2QPtuGxk7eiXdEva9t/Zs0qpMmIg5Sx7N9Uvm0yhY5AFEbUfDTHKiEAfuQ+NCcOLg4KufqkTkxRjI072ro9mTvo/MTmQAl4aF228fHlu4eLclRyP4cc26maEkljs9xbpcmiwjQjfT2gXNK21kbBrYm92gWen/bgbph4jkRjep1hHESPhl04Q2nE7fHFAmqYsGZ4zTl8xndlkKKa5xiU7wrSXYVdaySBfO0e26PS/R39PYRocg8HJvqWLr15BYXmKVXJOK2TMfZ+sGXd0KYcf83uO23D4jxs79oETGo/DP8zywjvEmJjkoLWVDTIzM7PWNpDv6eTj9HQy6zgFKeN/SZYZcwSbY85kBal3LrFLlc4NyAn3MgiGPwI5XE0rEzA3NSqwrqIM6XuItEucKoaN31GarZkpGJA6dg7tWqhNCSXhiL4PaLJvitMTzaQnXLeEekEH7b14IuNXMrTnjnCruzq1wiQgsd/FJHXc0REemkcWFHSoaSWGpofk2IkF0EUiHKKcSYLNbmteCXR852R6QnOQlpFRL8pXLwH18H/kQ1Jksw+HhjYz4IgoDCvPobfdbLHD+j0X9AOz1dYEeE/NaEDOqiJoUqP6FALzm1/+lGCZW4QXl1nM6zg93eF1HgQPVfYLw03GMRM8YFlOorXmx0k/99OQXPcUkln2TsmvrEeqBZQXFZag2wQtznqjUN/wvFGF6eniW8LOXd8SB5Jrd84t/YONQU/Ev3A60+jCEg6G85rNGbEe32v1L78mLjfM+2N240kSzk3bYnfWh2y98cJ7RDzNOa4oaIdS5R5kHVfa5+Zws6HgH66/PY7bStiah3VOyjIQgweOguEAKlPgw/UKWEcRZ1kfWpHOqoi+ejbcC6PjIFmgNXnAozKJiyZo8ognSkamcAwyuefyDm1PC4sXFlcXx03Gz6UGTneXsCRf8IdTze9JqNL9QoTSO/NxvkJHrpQHUttKUYCZxHSQ/F4hx8aI8h16gr76+GHGOJkNIs0nsZv4hoLcRVV6NUyidtQMMKBFIcZbb9DHNo6trhq8fD/h3wl1A9bj5DPi3Bumo3dFczFxgUO641xjY1d18ycranZm5v9QvSBN/b4zhjfdM6dMKoQ/l6Y4+nxabxTHtxIAHjJLt9E+uqP7MspwD9unJnXCygToXPO9aXdFitOyREEgB0VPajfZZ3QOv4RZo2/2C+uXeg/lHyec+ZGNE2C1sWh3ZVGfs+mEEmr03loymnOwkXiAkyo18hSzUa5ks8RLnEHOMTKuoiP4yYoOfrd2Y6PheAA/0JBhF7qfpftYmeariyurOQkAno2NU6GYHBqOA49GpKn2ObrvSTmvbo1//DDw81T/O26IM4/iFNX8XLvF6Q2TV5kyPIikvrfYj2uK1bEfw0EtYuekM+j4fJF7ueQJvHwr76U/hIc+yykoNoKhh66WlauJUuG4SKnzZKMqXCLBXOtN4pmmUJqtX3A/Q/IzIM+TgBJnsJkTbWPfrHybLYoyKspD/dX6ej/+KzXl1EKR8Atj+rpHZPzHlkNlhj75JxzaMhEKKaEgUxxCQ+pTop86UXS4uzDneiSvoZRI4xqHhLhX5lZWFhdAnz03t3RhcWHDdGzioJ2ieHnlS1cmMtpCLZZEmOntJOjt1H6Qxl0kETfxFK4fa8adTtBLwyoID6BOrcOrfjIIK/xWPAfH2HOtH+7E11fhUOPjdtBJQ+f5XL8fNHcwpi73eidqhVe7oCrEnT3QDQoaX05AFu+mmTmYGcKPOKluJ/Ggl+uc3p03r9bYo32T/8EPfjgIk31eCIpJdZMLfnlZ0QMmsuZPNOCYP2zmlwCB+6RBsU8zDj4N8MlsxX2UbG/Rw+dOzX5n9vkZ/eqAfxxURs2W3PrGJYJuTJwWxhscx6JYTzWf0889P3P6ieZj4rzNZDRtf5oJnTz5nee/c/op4PO02/Psd76L3rPHHj7jEX6qaZwCFHnu2eefYBY2Tv8p4XB6Zub07JPAwU9VeLpZzM6cOjlz+nR2FvjPRpY0tKIUpKH9LPVCgpQk8fXMc6yLdS5ohRcHnX7U60RM9mbkbReE95XoR5m3s7XZ0/JBJ+oWfZCdUztOmmGOmAFlDJOVfhJ2t/tEWGdqp2ef/87sqZPPPv/d78ycmj0pXyZhL+y4H87O2PGveS+c5wsRyG3dZkin6bRukTaDTsiDPXdq5junvvP8zHdn4eSffu67el6dOA31XNe7B8w78sFcyDmOf2t6kCbTW1F3OuzuKdbLTgGnPMbhTa904+udsLUdKsyeQK88ZtIAOAoSPFOQaF8NOhHKjakyOZUVorsqvAHLCWE5FRV0W/kETex5G8sjQi//LUxiaEAmwQ6Wow6BvHebEXRbGqTwXwRMC6i4ukITVqdUJ9pKgmRfYbQV5Y3IAkB03u3FSV+l+6n5HdufaK2Sn0Gy3QsSDImCee1SDBb0quTtFfiT5dvFborm6qur56rPq3jQ7w2gx656Leq24uspll0Etohek6itdoIUlpeUYPRa2m/B1xXCB6rNuE3nqlzn09BP9uv27NgGNefrEkAhRt51Zv3YoN+uPg/HUoVwLJL0DKFZJ0B8KXM/4Q0MNwc1Fv/BcDnbPeqdnDnfCtuwQd3W5h7u4WYSx/0SgDfpb7aipE7LLmOUPf6QDpqDRJ1R5qOayAElGfb6Du43fvStM/hPja2BzugAmBK+n8YQN8ykP1auRSn2VSorwC3z0kkUkm8Ql0plp69x/WU+xf8lIVC0rvJb+J/ZT+xzXrZdEL+RLwuhoeFLaLVpTkQJ9rOPEIFWiZ7gcXRjYw4S6DvQ13bYv9UJtsIOZ13zk+M7YUC1SswbAJZ+ubFhYgfx4MBUk7CG5lmEWHJifX0N/q+09nfr6xvr67eOb3y7XHqpflz/vTFVfgn+hl/0BP+kFxsnyt46pfcaokzQ6eilOIuFNTSv0T5tOue7RA84rpFwqhDrkZrDxM23AMygtYlPCzB/CJarIFWh06dM/BxJmKq9fmw+HnRaqhvj4Q9aLBWqm+EBkwvBJxyzRpuaXo/6O6V10sOPlb0zBC9htvwpMI++/qqiTpY9bO+E3RJ9XlYvnlGn6oXItoqsBfCRaGiOQGoM9ZezfuxilKYouwEm7AYdoMxY8DVHXflII1UGegn0CqZZ5vW6m4aG9M1WErX7JTwUGQrQAQIuM9fUFX+/HA4SeBM1VTBoRX1iDh1OL8f+FPVXkzLIOEyKENllhhuyyR4edZWNkQZSHDpRVExQxA0LAMD0vVQNulWxUUjnywSZVAU0UxW3YY+7Vaqxi5O5HiTkWYYzB/+ktfxK5Avc07UNDe1eTDQRnmmQyPHHVZhHGM6rzpwx1ESFsD3mtcYrcXMTajsdMqkzYi/9aYGhZxe1GWedPixBJJ5a8jqUiYzpu5iojproZP3qJRNKSTcWmPi17Gdmeeb7wnm5vXmTmriz0YAy3ZQfb/iiLhxiMmLf4LCMX7aceY2fWXQSGowQdgeZgHbS4dukI5Iyw2A6huyiW3rpzPHj6+vpt4Ev6FCHWxTQW8an6+utb9fLJyrZaQCN7QTb6RnobOn8pcvLi/NzK4synjnTm3LszyjREJFq0DyQErjTcsCAwjodTvxRw3PcAwgyvemG2JCa6De8FmoEnyEVdpptePQZt4A+zFBmXFLUHYT2aRuTYTdpvDPcZG3G7wuBSIobQHEs/E5UnB4ryodZXspx+85lrR3emtfgvYUG7Mfpu3Bzvn0GPbzuJ2EHJgFMDuspAb5riNOhoscKHyM09avJx3HohUVoey4mwGZhB5u7KEgJOmto/Z22ZwPop0oA+5vPHlTxn5P6H0Rld3SC2MWrF1aXLixdMgjMpvLiIbQd/cmHMBQjByMQG04SmL1FOtDVz/G/MDHvsxoZ2kqzjlCiFyKfe+syn9NMvBUTW7sEyOWhvNeZO0nu/Yz3QQYjNFGrBT1U80p5fAGRzSlXoxZQnqgbceA6iHtdrKyvB1UgDjVDHhLFwdJNd/SDMgpNhYO0wrQXwXxvZoF/4MgiReJKTc2Dzhe1YA7pPqipMNOLQYpiF064lh3O7HMBWWdpLBl0SUkHsdmXwyoKFroVY+zFVhx3YONIDiTxLDIqFuyI/syRVkHq6ZdgmRTfP4eiGk40o+AHANmbRqoxqszBOmrUZY+hma9Is089hmUGw/CahQg02H4MynkrBtBhW2rijHSAMjOyvTOi94JOW87xP0MkQPHY3G0Rn0yJDKdWYK0l2514CyTxKWbk5bGCnO71uJrrpLFCow/MV9HHu0FCOZGKxyoJ1lWUKYRUUXPnFy+trtDP+QtzVxfwadlyNexnE4ZEnFlz5APEQ9ML/2l64j9Nb/zn+cWLS5eW6M+NjDLtSlZ6vOHqsgs+fewKe7CQmRegYJAmCNZbiCso81qNAs013ZT0ry4K6R0K5iIrSirAQK0OOzijbh5Y+LQRMO6U/LW1cRm6u81+bDa6nNOiOpu9OI1uoAJZK2xRC1L+pFT22+qprZlONrCXcR/VOpjnAsKE/zECZrMbb4oyC/gc7roShHTjfJbpoOiTzFj88VYSXwuJVlxztRZH89ssUGpI2QPqRs2AFw2I1c7oTsdtiq+yazGJ+XV7Ej49idY+lI7lScyHFKu1iFYw0uiRrN1sH4hOXx4m0T0xlj0mfiHLHNIJbq87keOsIHuaO+6GiXKb3hpsTwetZFrXczALCLr7pV4StgH9YedwAGxon6xZbW2asvOYpphnFBuWeYYOKnmUc4psFEinSNl5Ub7lxEQ1+PYT/T/gqJvt3YraTbdREhliPirnG8qQ3L6g42FHQdM8IHodGrZcLtoFY69TpfRa1FN9CdMQXoCYFERkUiCz607cQQmAWvjWHwsBlpkZRqj6rXvhH/wWJlUfj7P6yA8xLToTEP2IFCuuaOj3Tu9IlzGak//BcbW03Y2TML9M7BKQf4A+YhK2ClGCBqDFYvDKMT0PfpQNCsm9/8XRV1jt2n1KUxVyKLhtAMD4SmWJ8AebRvm3fw+BPLvrV5HkpzpQkP/CTFCf5Q5XD4eRV1fFyeKZ4ZX9GK3LZFtCFDuRKrId5XgQWh2QfLhmaP2/Fglbm7xu+KpkWkwT3MpZa31hQyD7mbZAaG9i+wMxj3hW7nGrsnYw90t2ONiZOhaVkTN128lEnaZPNVGUgljwK7XJtC45IKa2t/N32G/Wylm6DkKUXZArU41ckdNOFuQ2nXhF+NGmL3yg0lDisZnZFH9Ph0mIwGaB0JEdqQ1I3dLaR/ZVglHjLTqYHlJVcjhW8faykt3ZiguYSgZKRecRVVEYukgjKZr9apI9uvp/W1gLZb2YnFHrgp7zYpGRB+NkV5sNJz6P3qjS3iyMnGSTnM5xoBgPjhFORE8cE4fiYwCMLXI+xkZdqyYIpXcx1Hk90d4+1nxcYdoXEWijzCEgh4YrVw91nsiWooDCTlr4GPX2kie3o7hdIKW45qCR6vz7/5dajftBR13Uyuo5ElBWmpTaAXIwup9cYb7sy8WuaeAD6es1I/xolz52VMDajGnAE3ncBWZA7dkGztJ3zmgLYZ8zgko0a7ef8gFgcVaeR3KTJs2KErKLdsfhY3vjw+9vbv9GLXXViZvQxcEJtKJINxZPgO7f5IcHmCVSLlrMaGmfv4H1/utb6lIs03OkSxrnW4VgLMKLoeBkPeicoztMY5n8Xpj099VrGl0ZroUINxK+KJ3j8Rs/oyIgE4ABgaCXg6cG4lynA1PB84aIYpUjVIpEON8JgKHvFTpSiyHtH+oxMLZ2yCxc/W6GQrR1nUTnUWMWQrF1fQT0vPVYmjMMkHD6dDhPADBrYVYYVgRSwjw0ojI9zA1rbXIT7NrvP/rnf3RMjWQ+imCXwqDT39knixGGzVCEUP9bw8YSV1FmnONqBabf7VfjbnVl0Gxi/tpu3Ap9DWgCiGd3Wb02t3ypnge6o3aOgDD0c/mVQtorKJoyea4UU1WHPuxRRguSxBnZk3JtDIhGbgfMbHF5+fKyTM4nsd6uV9QIYuFZKYxqnZvYaGbwZCT8D07GJyO1T0EPH5smuiZviiTbZDlok6MMNjcxCGJzc/1YXUf9JCmJ8DqKrTaXbJNifoXelFohRwCCCHdm/ZgXvVcY5Gd9xNS+FrRam4F0SXEuKJCyglzt4b+YVHIm7Scg5odtFORhGNLCd8JOD36jKqKVQdEE0CdAViq69YwUr7HDiigkI+/hv5jWQqtKocdwk8Ie7biL3WCrE2oRSoJUOGzPDAYjGGMKuQXSEEdNLVklg5ZWqPBVDdefk97RGM+fjolFI1VHR9HlwtDIz0qv8pElSCz51bhuC8ml/qIw5s8sF9SG/ialvp1xvVH0vXFCnSE4yB8CAPTfYOOS6aGciz+V0nMThqAWNqSsSAwTrS640aFyGZWaG/TjXXb/Xe0DGQUBKBuzSrULzg26hDt4ZKtqsbsXwXFGVAMcRjmU/IfnI1jyFlUIr6gmDADCW5xQTFE/Ccmz7tT3riip8jZ/YUlx4hVniM1J0SotulDfuuZXM+g0Bx2ascTLYn0/MrC9cnb64lnugoIHlCklqILt7STc5nVSzCoVo4de0cBbUWi/rWC+uczA6AfbYTdMuBmGloJ6SYuJVUEpR2qJayEMgHFDcvmo/3Pl8iXCReMi06GwRGPSJ4vBxYwW8wesFiNwbfOdAWym/XOwBZQD+X1BCK88IGs8UaoRQb30BsgXAkFeLERN2PQLIJAAALv7FXWZVhWAMrg6ADnpf9dIYEZ7U+gytCfCmqTqBhhrCD90SGFEADmhEW5rxAQAahsF0YKs36VkzEkj4gCIRM5AcBZ6wRYe2si4naokbW1HffZ764dAAOk8+k/5qDqzhPlsuP3wefUb8TOu7FnYMKLxdwZbfjua1w5MI/Kfw7Ng0N+B9WAuMkrX7ttc1dBbGPNvy4UeywOOon+0URBkZwS5FyJm/du4K7Xm9ZbHvSgB1N8edMS62RoCY0wdOGfysfRLDevitwxzfIfzqmR7ZegWN7WQL2xu4F7c2sK/+H12H4q/In2Bcl/cTaiYNBWzBUyCatd3oiZ6tgha5ZG+URAQNpFdIKtAxmyIVg34akG0y5r0ytRhr8r0jKWdapRWI4o0qWKXVexz/dhGpcAzcb11xqBE0fugh1k9m0y0zqzqrJaMSTO8MfQdKS1nsqCU+JZc2JqFQY0lW5YtzqgZCRdwPhBip+P7SPZhma5AsGbMXnOQd2OI9U9s/uJgEYQtyA1IN/ndJJs1dsOCrS18loRtfvLy4txC8Y5NsmuT79y43Ru9gwW76Owkgye7j0OUHrM/mkJsUNSc6cXf7CF7lpO5eO7Fu8cjPsnucUu9dT3M+eqAlvWXvl+8rMfdL0vvccfQDOD05e8andGZ4r3z774ZsW0iRD/RoWPmgr9Bv68SJ8E/eNC/9O3j5T3u9rlcd2Okr8vyXzmZMmD2ZI4czmXifMLN38O8Wlr6wRwlHfmgG2m/4wivlYuoWkDIL3SM98r1Wh13FTcHUQu4/o7P9H0eJMJIfi7FsoEIKJOKBmJywSY+0frLkAJktRNgswFqXoJ7ym22F3SR8WZgA1fY6FKAVpQ0MmSbxR4zdLKFmMICJy7EKgGF5prCFr6mkM1DRHQwCp0YG4xGZ4wHJSylncnwQn13zeoIqP4U6XDoWEyVbl9REYYHIWveiVqtUFwwOuNLDBthas0aqvTKWTWtLp7lbBxtA0F1Xw0ome25ZxV8AuOHAZkmmjsDckJ4eV46y6sV4bUKau3m+jGKcThGeZUVSWR3/sSx3T+pqrg8ONioFepcFOksK/Xc796LAkuc7MfahglaNjdAFMLZDd+E7qN+uIs0MY0TQKOSHakfJjRUuZ7zSGAbP7WInuQD8mr5QLyiGDPcELIpiyGmxhBzmUGepiGQN7f2+xSZTeMjSmI2Tn+TNsCP/kdTUtwD6QI/JW4OJ6GM0aDtAqIgqcWIDaquo01Lz50+feq5YbyCF1Hj5IASNc2QJl7VJqHfGf39TnijFW2HaT8vlCKVsIt88YyanTn5rJqif4oIGX4LW0xxu8duOk2nVclpWq7XTrYP4FRk8wUKHDnj+qWp1Gahu1fOWhLhRUpzOEpb7hi5aTDlIDu8wVsdE3EzPxd78kw/laKv9IHUMyj8yBxTWWDxR/bw2u3LfHnwmPHGo0OKNRyUAyuJMS7KXfCosoGhk3MfJ7tB39LjTW1H3eyjv6I0hlwQvYZfHnk+R32m1iRLXSGNFPLv2I7p5AnprRUQPf/CGo+mrR+bOnovexnqPblWoiE3YHMNtkOn6BVe9GiuoqJiV34dV6y1dehfn0Hl9Esr8QBUMW3cL9emLEqblEDXmjPqkg19uZpzj8Uh3x5J91jghVL6vg5pTKWMH9Iqf2fvl3PqofCQowrF628d+o5en6hbCGVakz5sbey7cRO+WzuBKHdi4wCv8OAHeELggTJf8FmQb+QZnjN+YszBZh8pFKL2gzjqlmjUXM0CNwTbq1owxti7Qvcxaq8kLjiXkn4t3K/uBZ1BJoeESn5c2cfPPbQE8h0UGTAPPKyVOY7J3Jf1Y5cakXQyv+mgOJ/fz+V/wUvlL+i1vbspJQ2oxdqsgwE6Z1W+8bJVM9ggqaZ5XcxJXZVwuQynPz6K03vKWN3EWGfJImwUhmZ2zCwENHUEzGw59zF8B/8tVhy5G/ivTdKlf0+sHzuhf8PPnDscgboGvW5waw+NNcAZbwGUSeAIvLthP0A03sWMJozMc4tQTOSyWOQeU879Y3fFjbA5oKDhdLC7i3VnyIcUdDmzDdmFufWMasNhpiKVdOUur2AV8WQPUB9TLbutaj9BHRDniqvRDrqwpVoDkqw1/YZRC+RUbFdo3D9GUzZ2deSbPF9dBu4gm9KXjzP1XozITsdJaLz3xUKbHmT6mTBLqL1rUhwKKFE2y0IWy4cqg8TF0bk45zXTEGFGEsCu8yyDiCJHvIqEi+SDorCtTCzscY1C8K/GmxXBm5Q9wa4/zpRvgeNL+eO1qZdyDeEZpuivwfv19ZWNqZfKpZfOrGOBw1vrVBTz1l+VXvoWvE7gz41y2ZXq8snLMmhFFUI2m2pMmx5c39S4f0b5acPFR5+siZuGYW/ko+I0RXT6HkYVrXoMI/XC1lAK6Qrt8q1PIV8sTkrKdG7adjSNwnYTDTekcwccmtfrFln9hEGxiaHtkeRrA5Zrxu10NGRCRR3g3g+2SoBjf1d6qY5XCmDWutQAmoL/y2GcPOfP2PaE/811PmQSctQM/dkgi1em7cTe6gK64zmwyeLQ5/ztolo2Nlm6wLCBQRR+stw0BS5R16q/E6qdaHsH+heO0B3sboHKyH2cCzqdVG0FzWvYZpZJq04bx7o2FI9WQMTRTpNKbs+oyjCSvZcrdDI0GTubPS2TZ+AoU+PBszqY/oy9wTc3aFNDUYkth7zQT0YyLHdR3kSMMepT3kRYRGlG51ZkF7Mb3Ch5zypE0n0CVS4PzXMYSdizGEjBgBj2T6YtD26ZLHQfeqbN4yVL5iW3PFyGcEw74kjOm9+R0Vz1MXbAZ6rlJ7LdCiZ7vWeq2HHpGMfKmamfwO/hxNZxVhkBsEjR3hhNJ0gcxJFtqIpcyUfnVDIk8/SEEJJyR/WEaiZ+ZbANzec7dGk8LIxCI0MMSyroju7CNE356r85fc08hn7ZJtmrLgtoEIilg06/Pg4k2cCRPpMnvHTQjwoZbBc9xll6jw8ytZJGlZYQHOCZWqP+bE0RQIBEMoF8Kpo6kp7mTz3baIce/oJU6SekAMOTTospZKaQzngCUBDwPKkI7qWoamLQ3q1th6gsyskv+J4PgGYaBRmFOkDb9htxFZFMCNRkDCM/JFEn0zk5s82hLO5jUl6RHwvOT3YsfGTGK2JMxeZfRnuUNkjWQGdQJoxdGWDtco3Aoa7YNhyIm2YOB5tM7XFiBm1IFWzLPjrfFn06gffWh8qwcB2YmvPhsK2Gc7wZtVxki6hiikX5lNwQ2qIDWLg2szHEo01XK7h90YN8d+VhO4I1uAb90KYVU9a6jc41lFvMmen0sJ5eCzGbVQ1gDzHtmPjGCyC0tykD/8XpF3AySD5eHObY72z2Y74hNkMB8rUrMlRxyPKkVkAbM+ynb7oDOKUv1urVUxsHRUWWLItZM0xjY4RbwYkCpMA92erKqC9lv+q8kyM/xdXgl/jvyA+1j71u0cKNFcK7sgBkQ7o4KLYgjEqo9f3VJ2sUyS0VX+DXBAyNS3cYfqZbDWNn8D7LzUyT8cxMt/5T8TIz3h+blZlQssJtRwOAyY8vNABQay5QwTjC4Ur61oSKLtbdKi4vIftdSNwMDEYQo+G0bJLWGfLhAP2/AvVg0fJxiAdD8s9IO/jXH4tKnKqRuC+xBiBhF1KJXB0fQyJ0k2EkAt5nSYRpMpZC6MZ/KgphxvuLoBAU4RyI0lYY5Sx7WkgJzFqfiBJM0to7t3gXU1aTvOn1Mv7wsgL4OIeXF/+/6eHNqbRsz9BOIOvKEre+hAbuhQluAcczufV8tXVDHobdvc2o246zHqLKRHFJXs9ZJ2yhdUBaiHGXpkcWa+MG1+uhaqB+to3kEsGHhQEO5wUkqanIWeBn02RggtQ2N+yBE79wTv3IlmUDIHMcNDoeGeDWB7BniEg/2OYTsnfTtDDnoB+3gn0yiNp1ozqlx6rhjxp9VcJk0ZhjQzTR2OU0TL2NcoI5HrCSiQY0Dn4npjfT0A3VFSLFjbZ3DKZxQy8mZFdiNZ2kJc7cMHlTXgW1uAtw6Cv4VmFnsAE7/X4vdZyC5LbQUccm8Fcy1zi35m9shHCdJ0ud1Ken7YvpbG6+6bgGtMVEvOUydbJzML9BAHnWcU7loILBVubjg+lEq3GAAtM34T/OPQKgn4cBRthysKIYjeXR5m5LTpwgvnaJGa0XT5um1yJYZZhy31bLJg+51aqyZmE7qBNZUqWs+LUTSAdPbBzcwt9RC35tbNQV/kGkFP62af0Za0RBv9ituclRX2LnXepqLuGml85tjHih4zGn6ihoMaod3fDAR3rJ44COJcWcxpODnEiUGcDJcFmgbTlA23KBtjUB0DJ9EsD0dZz2gly6e/CuvSqOYqH0Za6f0q24r+MVdHjRH90+/bXc5YmXdFoQPxDo802adGedjbp66MOb7MUW1CTfPQ6oma/nJMccqIX/Z8vS8nBZUAcOqAMX1MEEoM70SaB+t/hicgR3/opegDndRPsVhbu9lQXsHbq19i6Fs+GlqT91AWpj+zgO78zkQX/OpngX2kZd2IYB56zrqrpY4h0vn+FKAXbUtZmNNR2YuUFSuAn+ozLesA94wddeWPtR1NOUnoqN7G+mXfRE95nc4f9rNBpbQbpDV/ZmrqhFGF1BKXdlJ+x0VEnSn2EJ58N+FWtRvYyhtVUqAMHRpv6kD1R1rrMdJ0CqdzEkEQM7u8NGOot9of+keXkF/r0AysGN9S4HvoHIUTwAdUYhh/QpflcNFAadD/kc7xw22esUgBQ3nXgHE50gOYpsGz36lb5TFKMiMbYQyNvnfGDp7mVF/EFuyf0sU76f7rf9N8Eux8Jas5Nwi43YzfQDx0cEFhY2L667TlVKqlTJuK7W14HluRGI+IBCBwsaUQTLjttIAhBHN8JQRreRhDaOaUS77jXTAZDU0GlVNgF59vAZwdRGQRaCqJytD5M7SAq3wGyTUw6Zkchc4auFVZYT7D2+dFmpgyJ1pS+MUJ6tfb1rhH5YsS9p0nd173tz8a+pXw+aBQndN0nahC9ALtrEOx+xPy28sHDlij302peE6Eudx34Tf9ATF+9uZqF94N0gLJ3xH82doLsddmK5UFgAdI3unqebjteKr6KvYgVXvl97g7ZAbiMxbaRM/y3vIme6Rl5f5CwNnfuLP7ytJtwRfWFx5kJYPudKXkpDemHbmtfOPbOyLeYVTgJvt/2KL8r+hGZkrsOmFicka03cCSdcWf0E7+QJRtMTF0hRuIyeoitB81qwHZ4wQ0EvahXwALps0OwbzvyGAc7czjwRkLP3Nf/+o/ffxouRP8H7fR/ddugkRmHn4o/gBN90qPBBtjPcNLnhme/+5ivJS7omzCVQMZivHofvv/nX/1RHv7TyKX6OvF8u+tb3n2v5HQdv7iSl2ZmyEAor+JYPdKe//+jdf1FHv8CIcRIa9NXfcnPzXffeX1VC6fYcSre5zkVAdDt+518wI2GY7ILXRKNAKJwEAF8CWS7Xr0hD5Rzs3v8PB+H1dDOx+HRFNd9w78XP8+gSP4/r0vHz2PvNjAyUG/nn/wQAg07oFnnoQ9/XzDzSv8AahvkxTZK3x25TUdoAje5LMwdF+PdbhCQlI0BfQ++dl6vn78PHX9EFzS6y0p3WN+yd9oW6jnvys7xfQOuuVp7eUQ17z0ijlh3JzukhjCZbIReI41Y07OW+042yogvKvyY8eWDB+zkiJitfuvv/yIMZL1X/RMu+n+Hx1hIyKnB36dJunPjvuDc8wg2u5aTyV48qLh9GxulGObesAsy7Y9JL4JOHR5/Q+XowKU7qFENsRfds/4TO0KG/av8EfK6yxcGH6lE8vWLvrsfyZRP9kBu+aZJlBudGPrag2NLu6CwRzmwMgWjZlnxGyvMlVu3Y20wtHP1sl+oZFNrWJF+Th0253BPmYlyWO8edioRYqJxsYsJ7znWCvTgJW6bClImFWlvDfZ7ux1Sh89YqCjzACWD4Nf5d0vOe3urEW9M832mCpdsSr1RRJV0DBw0xvSTei1omWHbUUFNT9AcwK6+HCMS33V5/3+mhqFEeRmz9Mf1kDGVmI7K2LqeB/vlk5q5aog2QQ4xfpvsJLWDOzPwHYgsTFSikxeF8DVZyYKVXAUeXPx8XEx50oiDNfHfSfGeiQc0bFmKkoH82up5R9eryBURcLJBjsdWDDzf3PVAIZIAxHgu6a6P4i5Q/Kb66E+T8tZu0oIONkq4zWfYzL3O7U8/Wo1+WwqtPGjoyZH0gn41YW2262PGm3dToENNF1GpYiRx/lOwjEiycS0P03KgkJI2XjSodEtDkDCjz7PhoXoS5BtuMV72o4rf7rXcmsrG5hZ1/Gw+4d6WjUUMHnU7OKqy394Ap2k0maQdM0266PR8MuXXYxyY9SBaf7MdTU/L1lJMZ6eWROJf/3sLbfenuX/jN1wHDn/q23wxXkiwBkx6SPf4VKg5RLvBZ9QZbnahpFMYuCt9/yX6rMe4oXi5bk4Tjb166vLqIl3mhOWY0u1Sl8+culj131B/C72TqWGU8QLoUU5mvWGGZ4CkcRyP4IabyoM0yMAfFUlN4V2PGNkjDRCdeIo97AWBCEW7Y54vTOMFp6QWER5MRGrXb3oAOCy5wShUw4afzOv3J2fCQ4jnTHIM5krnQY8n5z0xOx0V6HWJip8lWdXO+/M1sT7KbN83gB5Ya5rfTpHrabS0iqqP8bf8ljLTW6fdn9PfRVmEyDwHxcfx8Y/2GEykmevxKBtu0RlL+s7oT/yyexIItmdCLONIj+cfcjv/Sjso/i4+yYBMn9E+O9HX+MTfxL9gF+rT+TZ/JSH8oThtvA1+35envmv+4GFLQps1+IzYo0o+pKaBTRHyYo6Cp7T5Zq74oAmvpHPSq5nWvZbLm68Edpkais/UlialbW7WZWWE19OH+CczuVVMFGb004jCT+nH1zYcfq6OfAVqwcZYXhWYzNM+pabbds639S1MZpfS3g6h5TS0x6MvkSjWe41/ygcaCK29yV9Ienbtudfb1bhNFgGo7XbmgbmYEDyx4YsvEY79FE0Hz36N/ZFsocIY3H/0z/kU+ATF8MrU6XO+KndKii6pWuWAUe4IzYPn/XQcWGH8c3wFfzQdomQ73Imivm2+sR9eBG45QRwMe7GEPn6T4pDAsoTY9cWCCIMSo4TFGQQ/MuG/jE4aMRN/ezBGag0JjMZEEq3SjflTKpLWPvQ/EUjf/ZpA/8DULeubjb/VAFXfYPSLOdR56bGmhSmFtu6Zmas/WZlDC36Nf5fG3l3A+ogyHRgczHJdK0beWOBn+KkjTuBlRXRYqn4WlAHRllpI0r6sAoFJtyT1m42eCdqEqXo45ZO187ce4a1Ts8PhiglEBCUeOilFgBaNizcXCUeHF+FH1tStjd3mVTW8auKagGReQGzMKHY/Jx9JrExuOHpP5rl3hCxpkL+YsPOMXbspejJ3NYq60EJrYxu9nsl9NBt3x1+FcwSJ3ecDC+rngrynGdR3IHiaNjh2ZMF2XzB8zOgUfSCEN984HDCWm8nt0r8jYMZtRVcc/jx5veYBsXc0vcUwEUicxws1JEN0f+74h56ahSe8aGnaXg2sUxcyeCe7qcC+RpNt6pBHuVu42Sbx8pdYa7PbSkh4GazcA1e+fOVmBofG2k80gbUYRl/x1Lfv2ArJMGUG+IijN1HFxbqHjDGplmAA65pLwh4MITaRM3u07Q+jtI0Pyi8owDiuC4tpX3Tk+lpHVWJ1SbVuz10Nl7gClAq75j6Ssq9kmwJb8V4xCZbOHctMMKTl28IIsUOuL4Ttis75o12ilnU+2yJmmP6UVIAOA0VKGMW5jvnZ/p5wx3WtASlUOt/CQ1MCj11mrnF6UHk1UN3dqS7Z+JSxXBR3M6trnUmspYmgbeDMXUlOZQmqDbgfvAwxv9IC0gzK+r2LYwoTqFBs81UAvSn3T9dyojhzaxEeWl9M9+dZgCyK5t0VqyDk9Z6okjKhw4MLb68Ipr5IrEOhtxLDBDY/KWqcz25gd1ZZ0ckygui4Bo5O9TYuy3iJQfHFpGSuNAyGXVDgLHlrdSYCeMTpQcYeR9a+dzbLWH307WmEtmZ5fRsYh2jyADf4cl7/l+MLOGLpSKVj4GfPLeasp9BlDqh2Tj57yGfMr1y8u9Iz96byX/TzjbnvFSPECLHbvadvEJG6/v+TlGu4J70HKyjGyzOaX84yOYozVt4GygYigptSzM/SHunL17IWleR0YrEiiVEVf6ltr/Y7dfRjBjA2FA3ED3TK717BwF/+Rcm1/Ptab8TX6s5xph8JgyIm0mbWiXFCQWevYrvIMjR9n2Zr7VJibYZrEzTJSt1Yt7SCPuzynpbNAF6YjV6cnPuJ2bryu+Lwp5ulwMRIw6+qmgbDNgB9yObffVZGyAt05KxrbIZlu5gytbMKx6MTb9sJwY4gd2v6n73p3JnI0+E19QtdO4AOMxR+SnONdlOsbNG0B1KBfDCRiY0PWK5cxOyuwNKIydJpl13DtnqBJ7l81916yMUYuvawF24iC0+k1YHkphYCgYQTvvZheeWXpwgVAY7wDkwxqnGzhfoPmHWObwYh279pWuosOb0VKe3grYzLoIL4+W00Bghg71A6b+0BkKwQpU70c3nZbQdJKa17Qu9cz6Ef4dB7mngQdBZJVX6o4e58B9JKA85FAMagBLrTxzqSU7CK5eajSQpQ2UfzaB4K2EHYi/MlXQFiLQifYx1tn8J5AupWal4XhPRGNqBpz5xcvra7oSEoO5P3t/8S6O7vY1TJNFt/cAjk12t6Gmd9SdN3HLaXv+4SfK7gl6hZ+Nqp0N7xuTF/bqkbdqI9FtZfgX2zdDNpYh0fCPhsVNXsKFPXdHokmFRs0uZ0EvR0sxm37MH3G3a0YdgK7fRl0R/hnIdwLO3hjO+8ZIo+Sr/gajDDopzth2JcebQ+mU6wsjHldDb3qGezXQP4Z9LGm0RZb60rLiyuLc8vzL1e/973vVdRSM9yKbwAud5tlGcHpzgwRtBKn92n0xsGf8F/s5XsKb6lMxEKWhD/gW9rlVlDplXswHeLF7abHWfixfG4eiX9zkKZ0I+qVC3OXsPOampq6FCs8G7WpKelMWpve0CVuejuJm4XXta/OrbyCXfC8kHlxUWcE9EK8UNiz9GSRALNokNQ1pPdTiBH6YWYIMgOaNHXBANOB06v+xswZe12hY9pBZQG3ow5zRKskIAjQ6ArlVXOXTmsHB4iWNhSCUujqLe/eG3pW0XHR3B+quXrTpb3tcmuw3SAEpXKEt9SFeFudvXreLnd5fk4SwrcBZ0gxRyFdeuTmpjcMA8fu5ugy5luc47jvRBhjT1QxHsOQtxPEVe5IWpqTz86NBUM/LhD9UCU5l+h/mpnZXNUnc7qhSu5JLVdUY2Z2cw4TIVG1ADqGh7lhwhnhe846qigJxAdsBISDM+7dsqtVbeowWx+Denx2c1nOEv/tRObDn7yxSNXgj8vmyPtk7sP/BPqzFyRAWPAqiSnA2SthshvwPemAtjKlHk8QgYj+ICo72wXSkgDvwwhLutUC2Q2c0p0QQ4ewCFGNe1w2G1g9hz4K7Pes7oW/5GpzQRu5QsA+AHhI2411LejyH+xqrtuPqovNnRj7uIDBrN9Wp765/f5pmFYHkNaYGNDzBjo93eYz2KWLeKnWjMiYur+VlcurNJ1wJ9iLYuJNxB5waq0QlLawlecRBYyYSdAwFsxvc8x3memaiytK77PSL4UIVuRuLaLauAjQKRRQnFZYjdtt2ZsscfQ5skySXDDOmLDm7KDisFvvXoVzThuKDBjDsPDu7tQQbfUCVYtroOW5Cew0xcuKA8wVdXs3s6xQxBS66zuw2zxZPJlqADIf2Tj9hszE0YbmIux8jCnLIBRpjL2IhI3O6rJe/1yHArjR6k1ovCDyMfEAOAgO/2BpIf0h0LKoHcGLdie4rvFjIWzxtVtO1wvL1OU5WIuZdy+JQVQMOrAPcOhU4+hXj95AD97RZ+ro4aM31AuU3vKZxJ7cP7r3YoOJXEMnVOqtM4fzCt7c1sJrnLuzyEvMvVdqaYFOJpbyaxQXYm1wbNcOHtIbfcBeQSLs/CR2tpDAWaMP4BX2Np+E2PWQ/nT76gtpZ7D9Ih4DuVerYaqgwDf0vDSvsVP3UbHA49IsACXcxPCHA9CFQrpL/BTOSughiBRLcFRuqBXkU5IvUVVTugptfQp5AihfgI5RN5cnY7ObVEnkD4zHaZILhKtk1nSXemLQZdBqoc+iwWj2P5RsId7S8sB1nB8O9XrDvmKm0v3G6FnpwedaeGDbYYJAcJrMbNLqeQFSzV+dwjk/W5O8SgQMARqYHZW6KVswrZCQjFgNjHwXL7huIC/G5RVvrho2U5Wdj3rmGeLr3LGq7ip2JqIvv1zXYpoR2xhZ1o81aurKIN2xcbRiaB1KSYHFjKCk8HYYJZXaxr4YgW6P+QCLXs4BpPbTKAUpdX6O9YQsb1KrCwvEd/KkE8Yl0ikSC8gr23gCnqEowFWQ/a5RRdTRRBM7EaLJTJOrMAcqjdv968J1oPvRFC83a/TBNSMQ2/AsL5JcLrC4eHVlVW2hhAY0qjVoak8zUmmf0fZ3QDM+N7d0YQW+B/oR0vzb0Q0C1JW5lZXFFWHR8qJGNaXpKisUC4yjL8jJbABzNM830V4O89gBdaFv5AMrcVhhhIi2X6m6QOZohZSDrga9uOvcvZgjoXWzWwHuVo6i4g7mqapXEbuhC/Zj/SdNVwXRGtDYp6zLNOc8YfW6lNYFRFUfPCtlGjILjYiIAKianQGI3iury2iL6jGB3UuR0gEvgz1kkQaTEejuAMBQUd2HHglNiK9SqJJiORVXgbQK+aalkO//O0Zy/ZNQyE9V6SwMglFnhNf4zTfvfKqO3uNIv0+QC2Is11IXd4WQo1xEJ3lIIZOj6Z1QOkYPWpeWq4U+UdcYvwS0qeNoFwxvEFp6Q6hSFnnYk5VFn9fQwOcQEIXSt7PlmeOlDyB2I2eztDuAF+0g6pQ1+sz1enBEzkU3sCOrCOIppDKJ5DCjW04HIAp3JGDEP2xGYnb30mLkCojJblFnI4JgJDNpCzr1qa5e+D78r3rxYnVh4UWzIx52AP1jTQO7vggH08MTNDEevU+bTwn0qoRa57idJ3RDU9E+9UPfWXWG6RdlssHbzOJhjqdHY828IAestvRC2ox74YvEu9hZaXCEAm1f1DYHb4wRmFPMz7RGPYKp6U9ynI319zqgBCwArzrVNoGKGrj7oPn2tFbogecoyY/mU285d563GasCMjg9JO6LHpdjsp5Rr3Tj652wBefuLNoAEMTjWJ7p+wU9deB9oup1OlwfSFcjApmulyogXCFjcWs0H7wSUBlyOnkYRMYufhb4yU2JDjJb2Q/N6939/Ih0BMeyo0uG95A8yZWOqAi23E+r5GCYMr1VygEaJtDL1wRlVLOtCLeUOxxSq5tix16c1nB0OEddpcOONRYKxlPN6JI91IwbO6ArYxsqz/ExReSiZPs6rvvoPT8JAk+xU0fkVNloFVm2IcshqoCWLyYNlH46IYN4GjKi7XK0+bjVNLlGya6eZu4RSSn1MmInHEG+zpdVq13c/T4a1hprNzZk3B5iURdpN1GqxtrayD28pf/e2DB0do7i6y15zc7JkkQje2vzR9yW+jdphXmCh/NcF1RsBiTJ4CnQpPNCRKyObJy+BrbU5m3cjVusKovPCO83B60ZrVZzV5ZSUvPTfazc6ir0QOiEYjVWrizO0xbhBBrLi3MLFxfp76jLYmiKkfk0VsqEFyb3HE8OIOoWMLOzw8isCQtEUL2BuNuOkl01o7aS+FpIFxXSjdDf0fxDOMUzWT10SgKx1VmuhQBnRCQOA3NCDBSFG+i9IYYBpC4Jt8hIuhsmQEA5x4J5SUVEWUWlN3XWknxitNWpVaCq16pIeVuqxF0TTzMaXg0PelZFw94cVmfIobEuvyBo8yJH6SDb5BhR3RtOsSG1DhyGh1LL8wgtjmmdt0ft0gBYhIc4SOq58nfEXKI5SNCbqsODULiPr/MJqhA67+4i9sOKuyR5kfIfoKrcZyunc/gdy6d7myKK0o71Wr3AJV1fHG7DM+b0EazafDOUVw8z4HuHEOcZwRpbkRYWq5ZW5Tm0GdVj0WYkzZ/dozGOMdsuXc6MCWgh6EqpjtdkcZNymmDWPSyTAeiHfM+MNJpLEyWZa+2wpcMXbI1WeB2PPeghjtEVp2zGa+gpNmhokBH34gimgVitmklI9AtH86obGnszM28486w0RT7c7HWxGm8QXekQG3z1+kWDvTZJ484J6tPiXkNwD5FsUKip2G3v7MuQmj/aE1TyXDFlG0Qb8KbIflD0GG8sAGq31x8mbZAw/AzISHtReN0hmmgkf1xho4Z7TMQzaLdZ7yQJiHC6CE5smMIZIAE0NWSEtgCoqlWmjUOIDEkXTG2JNfXRk7+979JkjzQucBw0Xt2EtmaSsYhQvhaDPMhmZYzc6wp9rg0h7ag94A7cYCltWsBnaa6h89UtItpZaBkBY1G22T+wrozUQn8Vme1YfSSPCBtaOlKvlo+FNgmeRC6PH3hHERBn7dLia0hEG2sXLy8snfs+/15YvLC4urjRKFv7I55IilNPYjSDesy6Qlkays3SYHkBDRJow+d6Ql3xM7DEoleZwwGfSyNaRx1+2xQvO4flAib2uyDIbg2iDqmiws/pb+DidvbYD0k26SCisHpuL98D3xt0oz590BJXtaqm1CK1nYiXEMMsmMrN8LnCw8/zSrVUtGRItXvgvT28ilYoh3D0RDspLdr+y0NOP2zjcGWJ+BMFZrQ7wCNhx9paG8SGRDqK6AORhajboyt+hzA8gNIoXgevc2wOIxYiHt6L3jCBG6NjFypinEbcE6upKFB5poexEcjvnCEzGmjJncJYnxUHTJDh9YcDUhpBbSJ4DXr0/TXTO1EqrHuqj8cYJhe0w/6+ZTgg8ojHOBdezITaTk+srSRV70tx+V4S7lEaQxP9akAuOhRnTEFlwnhy5xOHXQ47mE9l2CpxHo7PARIChBeUgyt8Rkj457JA56OhfEOOCKfPkP2EdJ7ILo+XRenOQkcwT0BTbRPXkvWo23Mj9jIdsoMrkc5rsWAOebTzVlH7tMDj7jM1crEXPGdmB+0vvnql4DXbfitDi7HZV0Uuen6T8dPnRFbNI2AvOzGAWi8P2DXx2e3Uwkq+yYKHDlYN0y2Ag5rj1ow7cUJxX0C2AyArfev6ko6QXMFhbQbduBuh6mGOrTW9+SDXtF46mEfU1d4PhUmQw2brxyBUCtxdleHKfGWEHs4EJasTa8ItCPyMkvER2f8ASmOIOSZpzSo4qDFKkH1kqFWrgil+mOKGJ10kHiJClQmUtrruyYvhg3nykaJcquG6DK5hBGnH1znSzuEzOSIoETN1HNop21fRqjNXnxIBgaJsHEtUnqzj0ETWM7T8ApUIHEfDOWAH2XQqlQOJIuGXNrZHRCMdF8uyxh4KhaPJeDFRxbFHUNJTai8KVCOPPw2XVJ9lWF3QoTVzcPQaa2sGmhsbZP8QRzVLfeQg0LZpWKrOlLBpdvwdKQPNHcbIQjqOiM7wVSs0T3sGRGrTcbSZ3GYOrJ3khNj2QvuXcDjgZH11mWKwXXldoPGaXj3xTOR0aFnC/BoKLWV/B0XuIGrJtZO6JCBdEGRFd8f4SRlg1OercA5bRM92TZgIYSiGbIRJHwcrNSKiMGTzxx9sOqVH+z16glWmGzZQQXbkXNTFU5h6lg7XnCRxRJy5WyE3DvQYo4WImZ5eEVmKd+geRr4rloxoQesHjABSvg9BbWiOI1VquoSO5J0w6PR3RJUA9Ea9oZs900OJhsR/jqAb8kU+kjhKYRHod9YRp06c6fYApJiCUGInAJWJxw+p1gPVE8zTDelQvPB6mGfUHIW1Wv4yjoKYIFdNRHZYqqbjgXhncrGNZgRTy0FwBBkx1g7slljk8oA5Ix17FOWtjBbQx0TKKM5Z4bICPuYxBlUNDUQrPOlXMMLWgwfKbAJlhzfLftkQFC6oApSTgDQFekcH6xloTYiAoHdQdnmXDdyym5qC4GmUWN5SJoT4GRvwS1q0G0d8zsYR1+jaXqNDAqOBGe4g0Uu9oOJadsRZGZFCeMXf10XLIbrEUQbscszG8rn5mijdxsQF3NuLTfB7Pik9Uwgv9bzY3YZtCRNtLbcqLwluHA78mKOcklGcuN5nMkG94vtG5MnYsSoZn3Nqw3u1A1CAdpKpGBoznABQlz4XhIGODP/0QjFcQ6bucGgUqGTm+hEp6JEjSo8avChIGHFiuvMiQYEe9zCgTPwfSNONkzgtjAVFoxOxlS3YnZCKE6MgEfQtidfHgqrqnEcC5h4e1FUcWmeEZV/KdSRTL64LtXOaQ5ZGDiXMiNAjqDK+LrZHz9bdIxBIvEcFTwCjhQ6FZ5aEe4YkhRA0ZZQVt0aeIOOo1h4NI5kTNo39j6PD1NyEkFKMMTAwcX4QA5SQfQrIterdmOCoxbmF6uVLF77PEQn68EFvvEDktkLW2bJNEhQcy5XV5aX51QvfV1eWL7+8dHZpdXFB5DceY8CS2RXgTV0Q5kkXBv0pBNgA4m1hQCkcGQW7GAB8d6LtnQ78/761mFFkKQM9bmOK8ew3t98/CQ0iKnqCicg2bHWoIZdlIpdwLnGCKCaqwOrcU7woacooWgVilhBzIbmQ7C7grF9slMV15eV07OJ+oPhviRXwmGqbVyeuHuxZR8HiaeJgM9CHgMKEupxyy635UtqL4g7vB4YMzszMzJYrFlgDwNmkj/tKpkfYPoSoSqL0WgXAvb1NQTXiHfK4jF6MKjETKnPJLzyjeyINOpHTEjitQxdruBDCUyNTsWGC8LMrmIQDIMp04utVnlEPtylsudY9S6wuxUoXy8nxpyXOJ9ZcbXToqFoOuuhGB7GThdqtfVzTgDwaRnKZRR0pVEnAYS8sO/fjnnWryTmHpVLBctRSr9GqNW+Y7wSiNhscdyT0fU20cUWY0ohSURMNIm5Mek3NowfphzA7xHxMvUNvTgAYZqKTOFxOTMSgIoXBNUV6DRHkXoyIjQowuQ4r1t8AghFnp9HuRek1Y4O+ins3R24jaFcyweHMsnO1ULDOKZD9v1bxFiKbSezX288MXTiQ9oiJuZINDBJ76pu5i+IIxQRFxJ/jBzXpNQ6I4mhBbqg/HhWEjd9kY4wnjtsbE42n9RuK32BsrZMtE301WO2F4rlpt9gfjP250di4VRQMgf7YPRA48LxNa9sYZ5xqP/9EUc650GYfYGrIYoYGPDf0LriB07lgZzy6NtrZcE/eFVqkhDlsMWTXj+l+M1HQcRJtE8aNDB4T5/UI3m+uPcoFRbPbGzAeN8pQbHZPVLi2NLtWQAOKrznZWzp7XFKWJZkrLwBozzrKAHq4+QHGTFyh0JCJ/NA597zn4Qg8XcMWE+nxhUM2D3e0VGA4oU7hxMJBYjEnUy4JtZcWX11cBhJGnxA1t2U+TGYS2kmJuk+xtqXhej5gB/AVI97jZiPsUN8jaTYJSQEAjoJElxfDURE4etTVQj7xu4ZjSCKBOB1l+b+aUvoNzHS4mark2qhsUTZk+9YTIObUbdDW5i8sjdAy9bq5tN6T2VRLfviN597TUprj5ss47uiAirEG4UoVIDLf2MATsQmK8cjGnaBaiREGFLw1UeqGdO1GSoFKSWFMdS+eCTO1AoylkKBsjJTy9GkbCgV6eIfyoXRgTEbiJbbsJsc/w1L3gq6E4prdqRwWp6U3uOorgNonO7GpHv9ts9kq2AM0QzMAFbdu2IuAc47ss0Q2XgayYcfVR8uSFAE2B7XzbTvkqK1Yayl97CJjxRxtAFNg++MGZYcTdWMeRDvW2rpGjLlORoRlOeMmpFxqARiSpdPDxuKwU8jQlosiqqWkAqC6ZLDEFvM3V9+Mu9PH3DnN3FLi6xqFtwAAKOUSgHMXDelmI05FVx5VclFVWQsrxFN9s7sThIDRsnIu7IXYrcnOBBAEClfU1FyHKaDkMf/y3KXzixcun/dkEw5v5Dhvklv1Gpq6VmdR+LeWEIjBSFVMEbMFn/FYOEF52N7YW0GEj/tsIAkAJxneOqAbY0FYVqZYRmmiF8T5eqiCaL7K77kP5qZTShcLJONC8b5ZvcC5P2/UpP2ptsRwx6GCpgwD2YZp9hqMsJE7hHzasEGRjRTQ/YcNoSShzvheRkgy4gUdJcrwJ8WmjJm6Meezlg00cGcflARYJiqUbu2BMl3CEaZplbMvItIf3LxBnW1ocwQ5B7NIyhER1Zg6ZurDLJdq2SzBkXpE70Q6iAqxmAh0ICNQ6x32vtrVUE5PJybj4pB0WtaKo+4edrMtlg2tPveiPpLDMVIRKWg4sBg1cC2u4VVMjQaMJs9VBdvI1xzjRicCvE3r6vKKWylEl3pNKadYK/l94vggQHfj3X3z5ruo/ocJJQh3da4SkBEyPtSovuIeBs1IXkibJrqPDtbBrs531jIZSJh7yBuDlloEXsu6n5HltFvQSTx2LC9+KjUsuR+jGyh14zISnBZtzi4gVHBtuL1mVN6uGxngp+waRozihMVqE2ovm4IxBCgIADphgDULnzxdmFg3okxrDDim97JHFRVpNd7FpRANCTjPV8mgsJeqxTbMqe+r6kZdw9sv8wluzorceT9ejptumcknftk5HKt64sC0QFy/UaHzyJndbpJxszOgkAyTPjtnTMyXB30gtmGR2exKEpFxYIUy51bCjvCy0nkQ4IHmhZ1WWQf5GAEOyK2TdKGpAzPy/g6VoBTQpSFLehTdh0UGxVAjmXr2pFiL29Vs5LwkmSCD1GOy57hhfQpX4h5j3oobMmj74ASJnThFvSzEieH4FZa3punAa2FV1/xxCREwoVCHQOgAzx2QTlFrc4VgGqYtEjA5+Mi/54bYCdw1dW+hU08if/W+6Dhybwps9cI4iT0gKU4xGcoMIwU9kKxxPwteOlzW/GDPjMwhF6QModzDd4r+L7wxhC/k/VqqvN8/uqPzvjG33y+yTlXPzw0olPRlIOI/wkoD08JqymO0DAaYX7qEz+QSG/nYOWjBdlVTsWl1eQ+9FuyXQguvTnAve2AcDq3EKXOA6mK2OkG5AHYswRlgPVXuvJ2xV8NhMpDpnEA04+qwTSok8IzS9iR7yi+wJcoxPo3LwX+2TvX0AQdwk++aq0Rgs41Wct5YjHLGKYc0jku5H5KiP0Emvl5QuU4juzR4RD7+ZJYo1KJHyG74ulhuO1n3fKV+vLKfImGKtGRqKU3qkaJYWCOmnazb9LqJ0yKoC+OVMkFGoj/4s58++s3RB5zvRFcgyrB/cgfVIoXLGKezjjNgaDKsOJZoK3RL14rlAxlXUdA4mgBM3Ph4+YZATULOCCM4x1tmsumLxB6b72GT6437Qaq5k53ZOdJxkyLnE6M4Zc09tizciJyHzXMUh/OiE5lJoo+HRbnw1Uk6LMilmEAcwlau3sjz2M+elbGB/xVFtWhNmDan66k02u4G8jcnTyHDxKMJiNPqOJxmgeJQrIskk2yDVne8ErcgvD/NhiaIPa+CNh4UC9xcmXJmPIw1bRNbhg5BgMHcT4z7XihPTRXmpGdSTymQquVkoI7MGtUpp2OTU8emmk/kqmA8GeaqmMwjgSRJCL6T02fcEZgZjMnIMvPH80ew9XBaJx+k+rq82v5uB3kAk//8/R1ILaRAO9pW6qbweWrqdVbVib2pE/ghJstGFBvCb3WVrjp53EL85AfxFr8j4bQK69J+A+mPJ8JmSXE/wOqWtW+ESnACja8iXxpsDbr9QZWrPku5TczPcqbG3c3r/B4sn5BGSDlstVHgGyJ1w7yndSrQ3+w9az9BnubVvm6H/eZOtQUHbKduq+naAbE4w6AnFvthQ8GGDnpVttP8zd7pEcPxN1VzQeqJU7XZ2RP5YcWgnYnHXdImHacO8AB6uZUfYmxoaHZEbUe+IpzO2pNHDQbIuqaqeFtlsfk43Vk/pjb+Ggl/5mZdvDVHDW3UdS8THjcIXv5VPEgGFrlmQ4YRezfF7w/rutvbVc0I5T78hcUdqHcPt6I8mHV0ga3K+4zebHMjklPcvVVXbh36UVtBJZFVtUdGztEIUWg1/6ubN5XcEJqEbb6L7eBA2as4cmvRZ1rMvN7RtocECymhmSqd5uNS3d7RlOJv9k66hezrIrS9hhep2qlU1An4L10Hmk6fKI84XT7tK16Q+30LxYg6Ga5CD2JJqGlZ/uVW3NqnesT1YnOyjwEYZOrvkxLLNNDzg/8PnwpZXw=="
# --- END_EMBEDDED_ASSETS ---


# --- STACK PRESETS & METADATA ---

STACK_PRESETS = {
    "swift": {
        "name": "iOS / macOS (Swift, SwiftUI, Xcode)",
        "language": "Swift",
        "build_cmd": "swift build",
        "test_cmd": "swift test",
        "lint_cmd": "swiftlint",
        "file_ext": ".swift",
        "sample_contract": "```swift\npublic protocol ExampleServiceProtocol: Sendable {\n    func execute() async throws -> String\n}\n```",
        "bug_env": "  - OS: iOS 18.x / macOS 15.x\n  - Toolchain: Xcode 16.x / Swift 6.0",
        "research_quirks": "* **Concurrency & Memory:** ARC weak/unowned, Task isolation, Sendable, BGAppRefresh.",
    },
    "ts": {
        "name": "Web / Node (TypeScript, JavaScript)",
        "language": "TypeScript",
        "build_cmd": "npm run build",
        "test_cmd": "npm test",
        "lint_cmd": "npm run lint",
        "file_ext": ".ts",
        "sample_contract": "```typescript\nexport interface ExampleService {\n  execute(signal?: AbortSignal): Promise<string>;\n}\n```",
        "bug_env": "  - OS: macOS / Linux / Windows\n  - Runtime: Node.js 20.x / 22.x",
        "research_quirks": "* **Event Loop & Memory:** Microtasks, uncleaned event listeners, SSR hydration.",
    },
    "python": {
        "name": "Python (Standard / Pytest / FastAPI)",
        "language": "Python",
        "build_cmd": "python -m py_compile scripts/*.py",
        "test_cmd": "pytest",
        "lint_cmd": "ruff check .",
        "file_ext": ".py",
        "sample_contract": "```python\nclass ExampleService:\n    def execute(self) -> str:\n        return \"OK\"\n```",
        "bug_env": "  - OS: macOS / Linux / Windows\n  - Python: 3.10+ / 3.12+",
        "research_quirks": "* **Async & Types:** Asyncio event loop blocking, GIL limitations, type hinting.",
    },
    "dotnet": {
        "name": ".NET / C# (ASP.NET, MAUI, Console)",
        "language": "C#",
        "build_cmd": "dotnet build",
        "test_cmd": "dotnet test",
        "lint_cmd": "dotnet format",
        "file_ext": ".cs",
        "sample_contract": "```csharp\npublic interface IExampleService {\n    Task<string> ExecuteAsync(CancellationToken ct = default);\n}\n```",
        "bug_env": "  - OS: Windows 11 / macOS / Linux\n  - SDK: .NET 8.0 / 9.0",
        "research_quirks": "* **Async & GC:** ConfigureAwait(false), ThreadPool starvation, IDisposable pattern.",
    },
    "generic": {
        "name": "Generic / Other Technology Stack",
        "language": "Source Code",
        "build_cmd": "make build",
        "test_cmd": "make test",
        "lint_cmd": "make lint",
        "file_ext": ".src",
        "sample_contract": "```text\nfunction execute(): Result\n```",
        "bug_env": "  - OS: macOS / Linux / Windows\n  - Runtime: Project runtime",
        "research_quirks": "* **Concurrency & Resources:** Thread safety, race conditions, memory lifecycle.",
    },
    "undecided": {
        "name": "Undecided / Idea-First Research",
        "language": "TBD (Determined in Mode 0 via /kb-research)",
        "build_cmd": "echo 'No build command configured yet (run /kb-research)'",
        "test_cmd": "echo 'No test command configured yet (run /kb-research)'",
        "lint_cmd": "echo 'No lint command configured yet (run /kb-research)'",
        "file_ext": ".txt",
        "sample_contract": "# Архитектурный контракт и интерфейсы будут определены по итогам RESEARCH-001\n",
        "bug_env": "  - ОС: TBD\n  - Стек: TBD (в процессе исследования)\n",
        "research_quirks": "* **Архитектурные ограничения и критерии выбора стека:** будут зафиксированы в ADR-0001.",
    },
}


# --- ASSET UNPACKING ---

def unpack_assets(source_repo_path: Path = None) -> dict:
    """
    Unpacks embedded assets from base64/zlib.
    Falls back to local filesystem if running in source repo and bundle is empty.
    """
    if EMBEDDED_ASSETS_B64:
        try:
            compressed = base64.b64decode(EMBEDDED_ASSETS_B64.encode("ascii"))
            raw_json = zlib.decompress(compressed).decode("utf-8")
            return json.loads(raw_json)
        except Exception as e:
            print(f"⚠️ Error unpacking embedded bundle: {e}")

    # Fallback for local repository development
    repo_root = source_repo_path or Path(__file__).resolve().parent
    templates_dir = repo_root / "templates"
    scripts_dir = repo_root / "scripts"
    skills_dir = repo_root / ".agents" / "skills"

    if templates_dir.is_dir():
        assets = {}
        for tf in templates_dir.glob("*.md"):
            assets[f"00_Templates/{tf.name}"] = tf.read_text(encoding="utf-8")
        graph_json = templates_dir / "graph.json"
        if graph_json.is_file():
            assets[".obsidian/graph.json"] = graph_json.read_text(encoding="utf-8")
        for sname in ["kb_lint.py", "kb_release.py"]:
            sfile = scripts_dir / sname
            if sfile.is_file():
                assets[f"scripts/{sname}"] = sfile.read_text(encoding="utf-8")
        if skills_dir.is_dir():
            for sdir in sorted([d for d in skills_dir.iterdir() if d.is_dir()]):
                skill_md = sdir / "SKILL.md"
                if skill_md.is_file():
                    assets[f".agents/skills/{sdir.name}/SKILL.md"] = skill_md.read_text(encoding="utf-8")
        workflows_dir = repo_root / ".github" / "workflows"
        if workflows_dir.is_dir():
            for wf in workflows_dir.glob("*.yml"):
                assets[f".github/workflows/{wf.name}"] = wf.read_text(encoding="utf-8")
        if assets:
            return assets

    raise RuntimeError("Cannot find assets. Both embedded bundle and local templates directory are unavailable.")


# --- GENERATORS FOR AGENTS & REPO RULES ---

_RULES_BODY = ("## Docs-as-Code (12 Disciplines)\n"
    "Language: {lang}\n"
    "1. Read `SPEC.md`, `docs/00_Index.md`, `docs/Onboarding.md` at session start; sync `SPEC.md`/`README.md` (Living Spec).\n"
    "2. Kanban: move cards with date `(YYYY-MM-DD)`.\n"
    "3. Roadmap: mark `[x]` + link `[[Specs/.../TASK-XXX|TASK-XXX]]`.\n"
    "4. ADR & Rejected-ADR: log all decisions incl. rejected (`status: rejected`).\n"
    "5. Research: worst-case tests; record discarded prototypes in `RESEARCH-XXX`.\n"
    "6. Devlog: write entry at task/session end.\n"
    "7. Obsidian: wikilinks `[[...]]` + tags.\n"
    "8. Permalinks: NEVER move `TASK-XXX`/`BUG-XXX` to Done/Archive.\n"
    "9. Regression-First: failing test BEFORE fixing any bug.\n"
    "10. QA: checklists `- [ ]` in `docs/05_Testing/`, separate from Plans.\n"
    "11. Graph: 7 Obsidian color groups (White/Purple/Cyan/Yellow/Orange/Red/Green).\n"
    "12. Git: Remote/Local/None + Trunk-Based docs + Feature Branching.\n")


def _rules(doc_lang: str) -> str:
    lang = "Documentation/Devlog **Russian**, code/commits **English**." if doc_lang == "ru" else "All documentation **English**."
    return _RULES_BODY.format(lang=lang)




_3MODES = (
    "## 🔄 3-Mode Discipline & Workflow\n\n"
    "**Mode 1 -- Planning (`/kb-plan`):** STRICTLY NO CODE CHANGES. User approval before writing plan docs.\n"
    "**Mode 2 -- Task Spec (`/kb-task`):** STRICTLY NO CODE CHANGES. `[NEW]`/`[MODIFY]`/`[DELETE]` contracts + DoD.\n"
    "**Mode 3 -- Implementation (`/kb-implement`):\n"
    "```bash\n{test_cmd}\npython3 scripts/kb_lint.py --path docs\n```\n"
    "Auto-complete: spec->done · Living Spec sync · Kanban+date · Roadmap `[x]` · Devlog · kb_lint · git push.\n\n"
    "Anti-Echo: NEVER reprint entire files in chat; emit link + 3-5 bullets + next step.\n"
    "Senior Partner: flag risks, propose alternatives. Rejected ADRs: `docs/03_Decisions_ADR/` (`status: rejected`).\n"
)


def _gen_rule(title: str, p: str, s: str, l: str, extra: str = "", tail: str = "") -> str:
    st = STACK_PRESETS.get(s, STACK_PRESETS["generic"])
    return f"# {title} for {p}\n\nStack: **{st['name']}**{extra}\n\n{_rules(l)}\n{_3MODES.format(test_cmd=st['test_cmd'])}{tail}"


def generate_gemini_md(p: str, s: str, l: str = "ru") -> str:
    return _gen_rule("GEMINI.md -- Google Antigravity & Gemini CLI Rules", p, s, l, " | Full Guidelines: `AGENTS.md`", "\nSkills: `/kb-plan` `/kb-task` `/kb-implement` `/kb-complete` `/kb-bug` `/kb-adr` `/kb-research` `/kb-release` `/kb-lint`\n")


def generate_windsurfrules(p: str, s: str, l: str = "ru") -> str:
    st = STACK_PRESETS.get(s, STACK_PRESETS["generic"])
    return _gen_rule(".windsurfrules -- Windsurf Cascade AI Rules", p, s, l, f" | Build: `{st['build_cmd']}` | Test: `{st['test_cmd']}`")


def generate_clinerules(p: str, s: str, l: str = "ru") -> str:
    return _gen_rule("Cline / Roo Code AI Rules", p, s, l, " | Read `AGENTS.md` and `docs/Onboarding.md` first.")


def generate_claude_md(p: str, s: str, l: str = "ru") -> str:
    st = STACK_PRESETS.get(s, STACK_PRESETS["generic"])
    return _gen_rule("CLAUDE.md -- Claude Code Guidelines", p, s, l, f" | Build: `{st['build_cmd']}` | Test: `{st['test_cmd']}` | Lint: `python3 scripts/kb_lint.py --path docs`")


def generate_cursorrules(p: str, s: str, l: str = "ru") -> str:
    return _gen_rule("Cursor Rules", p, s, l, "\nYou are a **Senior Engineering Partner**. Read `AGENTS.md`.")


def generate_copilot_instructions(p: str, s: str, l: str = "ru") -> str:
    return _gen_rule("GitHub Copilot Instructions", p, s, l, " | Read `AGENTS.md` for full guidelines.")


def generate_agents_md(project_name: str, stack_key: str, doc_lang: str = "ru") -> str:
    stack = STACK_PRESETS.get(stack_key, STACK_PRESETS["generic"])
    rules = _rules(doc_lang)
    return f"""# 🤖 AGENTS.md -- AI Agent Guidelines & Operating Modes

> **Project:** {project_name} | **Stack:** {stack['name']}
> **Spec:** [[SPEC|SPEC.md]] | **KB:** [[docs/00_Index|00_Index]] | **Onboarding:** [[docs/Onboarding|Onboarding Guide]]

---

{rules}
### 🎨 Obsidian Graph Color Scheme & Tagging
| Color / Category | Obsidian Path / Query | Tags | Description |
| :--- | :--- | :--- | :--- |
| ⚪ White / Light | `file:00_Index`, `file:Devlog`, `file:SPEC` | — | Entry points & root navigation hubs |
| 🟣 Purple | `path:01_Architecture` | `#arch` | System architecture, contracts & modules |
| 🔵 Blue / Cyan | `path:03_Decisions_ADR` | `#adr` | Architecture Decision Records |
| 🟡 Yellow / Amber | `path:04_Research` | `#research` | Platform research, benchmarks & quirks |
| 🟠 Orange | `path:02_Tasks` | `#task` | Backlog, Roadmap, Plans & Task Specs |
| 🔴 Red | `path:02_Tasks/Bugs` | `#bug` | Defects, bugs, RCA & regression tests |
| 🟢 Green | `path:05_Testing` | `#testing` | Acceptance testing & E2E UX checklists |

---

## 🔇 Anti-Echo Response Protocol

When modifying or creating files on disk:
1. **STRICTLY PROHIBITED:** Dumping complete file contents or repetitive code blocks into chat responses.
2. **REQUIRED RESPONSE FORMAT:**
   - Clickable file link: `[FileName](file:///absolute/path/to/file)`
   - Concise 3–5 bullet summary of what changed and key architectural decisions
   - Next actionable step or prompt for confirmation

---

## 🧠 Senior Engineering Partner Standard

You are a **Senior Engineering Partner**, not a passive assistant:
1. **Critical Review:** Evaluate against best practices ({stack['language']}, Clean Architecture, Zero Dependencies).
2. **Constructive Challenge:** Flag flaws -> justify consequences -> offer 1--2 robust alternatives.
3. **User Confirmation Required (Mode 1 & 2):** NEVER write plan/spec docs without explicit user approval.
4. **Rejected ADRs:** Document discarded directions (`status: rejected`) in `docs/03_Decisions_ADR/`.

---

## 🔄 The 3-Mode Development Cycle

### 🟡 Mode 1 -- Planning (`/kb-plan`)
**🚨 STRICTLY NO CODE CHANGES.** Research, Q&A, critical review. User confirmation before any plan doc.
Output: `docs/02_Tasks/Plans/PLAN-XXX-<slug>.md` + Kanban Backlog card.

### 🟠 Mode 2 -- Task Spec (`/kb-task`)
**🚨 STRICTLY NO CODE CHANGES.** File contracts + verification plan.
Contracts: `[NEW] path/to/file{stack['file_ext']}` / `[MODIFY]` / `[DELETE]` with signatures and DoD.
Output: `docs/02_Tasks/Specs/<Phase>/TASK-XXX-<slug>.md` + Kanban In Progress.

### 🟢 Mode 3 -- Implementation (`/kb-implement` -> `/kb-complete`)
Code strictly per approved spec. Run:
```bash
{stack['build_cmd']}
{stack['test_cmd']}
python3 scripts/kb_lint.py --path docs
```
Completion checklist: spec->done · Kanban->Done(date) · Roadmap `[x]` · Devlog · kb_lint 0 errors · git push.
"""

# --- STARTER DOCS CUSTOMIZATION ---

def customize_templates_for_stack(template_name: str, content: str, stack_key: str, today_str: str) -> str:
    stack = STACK_PRESETS.get(stack_key, STACK_PRESETS["generic"])
    content = content.replace("2026-09-19", today_str).replace("2026-09-26", today_str)

    if template_name == "TEMPLATE_TASK.md":
        # Replace sample contract with stack-specific contract
        contract_marker = "```python\n# Ключевой контракт\n```"
        if contract_marker in content:
            content = content.replace(contract_marker, stack["sample_contract"])
        contract_target = "```csharp\n// Пример ключевого интерфейса или фрагмента контракта\npublic interface IExampleService\n{\n    Task ExecuteAsync(CancellationToken ct);\n}\n```"
        if contract_target in content:
            content = content.replace(contract_target, stack["sample_contract"])
        # Replace build & test command
        content = content.replace("<!-- команда сборки, Exit code 0 -->", stack["build_cmd"])
        content = content.replace("<!-- команда запуска тестов, 100% pass -->", stack["test_cmd"])
        content = content.replace("`dotnet build` или `./gradlew test`", f"`{stack['build_cmd']}`")
        content = content.replace("`dotnet test`", f"`{stack['test_cmd']}`")
        content = content.replace("path/to/file.ext", f"path/to/file{stack['file_ext']}")
        content = content.replace("Path/To/NewFile.cs", f"Path/To/NewFile{stack['file_ext']}")
        content = content.replace("Path/To/ExistingFile.kt", f"Path/To/ExistingFile{stack['file_ext']}")
        content = content.replace("Path/To/OldFile.cs", f"Path/To/OldFile{stack['file_ext']}")

    elif template_name == "TEMPLATE_BUG.md":
        # Replace bug environment and test paths
        env_marker = "* **Окружение:** <!-- ОС, версия, стек -->"
        if env_marker in content:
            content = content.replace(env_marker, f"* **Окружение:**\n{stack['bug_env']}")
        legacy_env = "  - ОС: Windows 11 Build / Android Version\n  - Стек: .NET SDK / Gradle Version / Runtime\n  - Сеть/Конфигурация: Localhost / Wi-Fi / VPN"
        if legacy_env in content:
            content = content.replace(legacy_env, stack["bug_env"])
        content = content.replace("tests/path/to/test_regression.ext", f"tests/path/to/test_regression{stack['file_ext']}")
        content = content.replace("path/to/file.ext", f"path/to/file{stack['file_ext']}")
        content = content.replace("path/to/file.cs", f"path/to/file{stack['file_ext']}")
        content = content.replace("tests/Path/To/RegressionTest.cs", f"tests/Path/To/RegressionTest{stack['file_ext']}")

    elif template_name == "TEMPLATE_RESEARCH.md":
        # Replace sample research code and platform quirks
        quirks_marker = "<!-- Поведение подсистемы в фоне, энергопотребление, жизненный цикл, лимиты -->"
        if quirks_marker in content:
            content = content.replace(quirks_marker, stack["research_quirks"])
        legacy_quirks = "* **Поведение в фоне и энергопотребление (Doze / WakeLock):** ...\n* **Поведение при сбоях сети и роуминге:** ...\n* **Потокобезопасность и нагрузка на память/CPU:** ...\n* **Ограничения прав и безопасности ОС:** ..."
        if legacy_quirks in content:
            content = content.replace(legacy_quirks, stack["research_quirks"])
        content = content.replace("```python\n# Экспериментальный код или бенчмарк\n```", stack["sample_contract"])
        content = content.replace("```kotlin\n// Пример проверочного кода или сниппета решения\n```", stack["sample_contract"])

    return content


def detect_project_stack(target_dir: Path) -> str:
    """
    Эвристический детект стека по маркерным файлам в корне проекта.
    Возвращает ключ стека из STACK_PRESETS ('swift', 'ts', 'python', 'dotnet', 'generic').
    """
    if not target_dir.is_dir():
        return "generic"
    if (target_dir / "Package.swift").is_file():
        return "swift"
    if (target_dir / "package.json").is_file():
        return "ts"
    if any((target_dir / f).is_file() for f in ["pyproject.toml", "requirements.txt", "Pipfile", "setup.py"]):
        return "python"
    try:
        if list(target_dir.glob("*.sln")) or list(target_dir.glob("*.csproj")):
            return "dotnet"
    except Exception:
        pass
    return "generic"


def handle_readme(target_dir: Path, project_name: str, doc_lang: str = "ru"):
    readme_path = target_dir / "README.md"
    if doc_lang == "en":
        docs_block = """

---

## 🧠 AI Agent Documentation & Discipline (Docs-as-Code)
This project uses the Docs-as-Code knowledge base and strict 3-mode workflow for AI agents:
* **Documentation Vault:** `docs/` (open as Obsidian Vault).
* **Universal Agent Rules:** [AGENTS.md](AGENTS.md).
* **Knowledge Map (MOC):** [docs/00_Index.md](docs/00_Index.md).
* **Integrity Linter:** `python scripts/kb_lint.py --path docs`.
"""
    else:
        docs_block = """

---

## 🧠 Документация и дисциплина AI-агентов (Docs-as-Code)
В проекте развернута база знаний Docs-as-Code и строгий 3-режимный регламент работы с AI-агентами:
* **Каталог документации:** `docs/` (открывается как Vault в Obsidian).
* **Главный регламент агентов:** [AGENTS.md](AGENTS.md).
* **Карта заметок:** [docs/00_Index.md](docs/00_Index.md).
* **Проверка базы знаний:** `python scripts/kb_lint.py --path docs`.
"""
    if readme_path.is_file():
        content = readme_path.read_text(encoding="utf-8")
        if "AGENTS.md" not in content and "Docs-as-Code" not in content:
            readme_path.write_text(content.rstrip() + "\n" + docs_block, encoding="utf-8")
            print("📝 Appended Docs-as-Code section to existing README.md.")
    else:
        new_content = f"# {project_name}\n\nProject repository.\n{docs_block}"
        readme_path.write_text(new_content, encoding="utf-8")
        print("📝 Created root README.md with Docs-as-Code section.")


def handle_gitignore(target_dir: Path):
    gitignore_path = target_dir / ".gitignore"
    obsidian_rules = """
# Obsidian Workspace (preserve graph.json)
.obsidian/*
!.obsidian/graph.json
"""
    if not gitignore_path.exists():
        gitignore_content = """# System & IDE
.DS_Store
Thumbs.db
.idea/
.vscode/*
!.vscode/settings.json
""" + obsidian_rules
        gitignore_path.write_text(gitignore_content.strip() + "\n", encoding="utf-8")
        print("📁 Created .gitignore (with Obsidian graph retention rules).")
    else:
        content = gitignore_path.read_text(encoding="utf-8")
        if ".obsidian" not in content:
            gitignore_path.write_text(content.rstrip() + "\n" + obsidian_rules, encoding="utf-8")
            print("📁 Appended Obsidian retention rules to existing .gitignore.")


def create_starter_docs(target_dir: Path, project_name: str, stack_key: str, assets: dict = None, force: bool = False, idea: str = None):
    stack = STACK_PRESETS.get(stack_key, STACK_PRESETS["generic"])
    today_str = date.today().isoformat()
    docs_dir = target_dir / "docs"

    # 1. SPEC.md (Root)
    spec_path = target_dir / "SPEC.md"
    if not spec_path.exists() or force:
        is_undecided = (stack_key == "undecided")
        spec_status = "discovery" if is_undecided else "active"
        if is_undecided:
            concept_text = idea.strip() if idea else "*Краткое описание продуктовой идеи, решаемой проблемы и целевой аудитории (зафиксировано для исследования в Режиме 0).*"
            arch_text = (
                "* **Статус стека:** Не определен. Требуется провести первичное исследование через команду агента: `/kb-research выбор-стека-и-архитектуры`.\n"
                "* **Сборка проекта:** `TBD (после завершения RESEARCH-001)`\n"
                "* **Запуск тестов:** `TBD (после завершения RESEARCH-001)`\n"
                "* **Проверка базы знаний:** `python3 scripts/kb_lint.py --path docs`"
            )
        else:
            concept_text = idea.strip() if idea else "*Краткое описание назначения проекта, решаемой проблемы и целевой аудитории.*"
            arch_text = (
                f"* **Платформа и технологии:** {stack['name']} ({stack['language']})\n"
                f"* **Сборка проекта:** `{stack['build_cmd']}`\n"
                f"* **Запуск тестов:** `{stack['test_cmd']}`\n"
                f"* **Проверка базы знаний:** `python3 scripts/kb_lint.py --path docs`"
            )

        spec_content = f"""---
id: SPEC
title: "Мастер-спецификация: {project_name}"
status: {spec_status}
type: specification
created: {today_str}
updated: {today_str}
tags:
  - spec
  - master
  - {project_name.lower().replace(" ", "-")}
---

# 🚀 Мастер-спецификация: {project_name}

> **Проект:** {project_name}  
> **Стек:** {stack['name']}  
> **Связанные документы:** [[docs/00_Index|00_Index]], [[docs/Onboarding|Онбординг]], [[docs/02_Tasks/Kanban|Канбан]], [[docs/02_Tasks/Roadmap|Дорожная карта]].

---

## 1. Концепция и цели проекта
{concept_text}

---

## 2. Архитектура и стек технологий
{arch_text}

---

## 3. Этапы разработки
План реализации разбит на фазы в [[docs/02_Tasks/Roadmap|Дорожной карте]]:
* **Фаза 1: Инициализация и MVP** -- Базовый каркас и проверка сборки.
* **Фаза 2: Основная функциональность** -- Ключевые пользовательские сценарии.
"""
        spec_path.write_text(spec_content, encoding="utf-8")

    # 2. docs/00_Index.md
    index_path = docs_dir / "00_Index.md"
    if not index_path.exists() or force:
        tpl = (assets or {}).get("00_Templates/TEMPLATE_INDEX.md", "")
        index_content = tpl.replace("[Название Проекта]", project_name).replace("2026-09-19", today_str) if tpl else f"# {project_name}\n"
        index_path.write_text(index_content, encoding="utf-8")

    # 3. docs/Onboarding.md
    onboarding_path = docs_dir / "Onboarding.md"
    if not onboarding_path.exists() or force:
        tpl = (assets or {}).get("00_Templates/TEMPLATE_ONBOARDING.md", "")
        onboarding_content = (
            tpl.replace("[Название Проекта]", project_name)
            .replace("2026-09-19", today_str)
            .replace("dotnet build", stack["build_cmd"])
            .replace("dotnet test", stack["test_cmd"])
        ) if tpl else f"# Onboarding: {project_name}\n"
        onboarding_path.write_text(onboarding_content, encoding="utf-8")

    # 4. docs/Devlog.md
    devlog_path = docs_dir / "Devlog.md"
    if not devlog_path.exists() or force:
        tpl = (assets or {}).get("00_Templates/TEMPLATE_DEVLOG.md", "")
        devlog_content = tpl.replace("2026-09-19", today_str) if tpl else f"# Devlog: {project_name}\n"
        devlog_path.write_text(devlog_content, encoding="utf-8")

    # 5. docs/02_Tasks/Kanban.md
    kanban_path = docs_dir / "02_Tasks" / "Kanban.md"
    if not kanban_path.exists() or force:
        kanban_content = f"""---
kanban-plugin: basic
---

# 📋 Канбан-доска: {project_name}

> **Теги:** #tasks #kanban #planning  
> **Связанная дорожная карта:** [[Roadmap|Дорожная карта]]  

## 📥 Бэклог (Backlog)

<!-- Начните с создания первого плана через команду агента /kb-plan <название> -->

## ⏳ В работе (In Progress)


## ✅ Готово (Done)

- [x] Инициализация структуры базы знаний Docs-as-Code ({today_str}) #docs

## 💡 Идеи и гипотезы (Icebox / Future Ideas)

- [ ] [Идея 1]: краткая формулировка задумки или гипотезы #idea
"""
        kanban_path.write_text(kanban_content, encoding="utf-8")

    # 6. docs/02_Tasks/Roadmap.md
    roadmap_path = docs_dir / "02_Tasks" / "Roadmap.md"
    if not roadmap_path.exists() or force:
        roadmap_content = f"""---
id: ROADMAP
title: Дорожная карта разработки (Roadmap)
status: active
type: roadmap
created: {today_str}
updated: {today_str}
tags:
  - roadmap
  - planning
  - milestones
---

# 🗺️ Дорожная карта разработки (Roadmap): {project_name}

> **Теги:** #roadmap #planning #milestones  
> **Связанный канбан:** [[Kanban|Канбан-доска]]  
> **Первоисточник:** [[../../SPEC|SPEC.md (Мастер-спецификация)]]  

---

## Фаза 1: Первичный MVP и проверка сборки
**Цель:** Создание базового каркаса проекта и проверка сборки/тестов.  
*Сформируйте концептуальный план первой фазы через команду `/kb-plan`.*

---

## 🔮 Перспективные направления (Future Horizons / Later)
*Идеи и гипотезы, находящиеся на стадии осмысления. Прорабатываются через Режим 1 (`/kb-plan`).*

* 💡 **[Идея 1]:** Краткое описание проблемы и ценности.
"""
        roadmap_path.write_text(roadmap_content, encoding="utf-8")



# --- GIT SETUP ---

def setup_git(target_dir: Path, git_choice: str):
    """
    Handles git initialization according to user choice: 'local', 'github', or 'none'.
    """
    if git_choice == "none":
        print("⏭️ Git setup skipped.")
        return

    # Check if git command exists
    git_cmd = shutil.which("git")
    if not git_cmd and sys.platform == "win32":
        # Check standard Windows paths
        win_candidates = [
            r"C:\Program Files\Git\cmd\git.exe",
            r"C:\Program Files\Git\bin\git.exe",
            os.path.expandvars(r"%LOCALAPPDATA%\Programs\Git\cmd\git.exe"),
        ]
        for cand in win_candidates:
            if os.path.isfile(cand):
                git_cmd = cand
                break

    if not git_cmd:
        print("⚠️ Warning: 'git' executable not found in PATH. Skipping automated Git operations.")
        print("   You can initialize Git manually later with: git init")
        return

    is_git_repo = (target_dir / ".git" / "HEAD").is_file()

    if not is_git_repo:
        try:
            subprocess.run([git_cmd, "init"], cwd=str(target_dir), check=True, capture_output=True, text=True, encoding="utf-8", errors="replace")
            print("📦 Initialized local Git repository.")
        except Exception as e:
            print(f"⚠️ Git init warning: {e}")

    # Prepare .gitignore if not present
    handle_gitignore(target_dir)

    # Scope git operations strictly to target_dir
    git_env = os.environ.copy()
    git_env["GIT_DIR"] = str((target_dir / ".git").resolve())
    git_env["GIT_WORK_TREE"] = str(target_dir.resolve())

    # Initial commit
    try:
        subprocess.run([git_cmd, "add", "-A"], cwd=str(target_dir), env=git_env, check=True, capture_output=True, text=True, encoding="utf-8", errors="replace")
        res = subprocess.run([git_cmd, "commit", "-m", "feat: initialize docs-as-code harness"], cwd=str(target_dir), env=git_env, capture_output=True, text=True, encoding="utf-8", errors="replace")
        subprocess.run([git_cmd, "branch", "-M", "main"], cwd=str(target_dir), env=git_env, check=False, capture_output=True, text=True, encoding="utf-8", errors="replace")
        if res.returncode == 0:
            print("✅ Created initial Git commit with Docs-as-Code harness (branch: main).")
    except Exception as e:
        print(f"⚠️ Git commit notice: {e}")

    if git_choice == "github":
        print("\n🐙 GitHub Remote Setup Instructions:")
        print("   1. Go to https://github.com/new and create a new repository.")
        print("   2. (Do NOT check README, .gitignore or license options).")
        print("   3. Run the following commands to link your repository:")
        print(f"      cd \"{target_dir.resolve()}\"")
        print("      git remote add origin https://github.com/<your-username>/<repo-name>.git")
        print("      git push -u origin main\n")


def deploy_ci_workflow(target_dir: Path, ci_provider: str = "none", assets: dict = None):
    if ci_provider == "github":
        wf_dir = target_dir / ".github" / "workflows"
        wf_dir.mkdir(parents=True, exist_ok=True)

        # 1. kb-lint.yml
        wf_lint = wf_dir / "kb-lint.yml"
        if assets and ".github/workflows/kb-lint.yml" in assets:
            wf_lint.write_text(assets[".github/workflows/kb-lint.yml"], encoding="utf-8")
        else:
            wf_lint_content = (
                "name: Docs-as-Code Knowledge Base Audit\n\n"
                "on:\n"
                "  push:\n"
                "    branches: [ main, master ]\n"
                "  pull_request:\n"
                "    branches: [ main, master ]\n\n"
                "jobs:\n"
                "  kb-lint:\n"
                "    runs-on: ubuntu-latest\n"
                "    steps:\n"
                "      - name: Checkout repository\n"
                "        uses: actions/checkout@v4\n\n"
                "      - name: Set up Python\n"
                "        uses: actions/setup-python@v5\n"
                "        with:\n"
                "          python-version: '3.11'\n\n"
                "      - name: Run Knowledge Base Linter\n"
                "        run: |\n"
                "          python scripts/kb_lint.py --path docs\n"
            )
            wf_lint.write_text(wf_lint_content, encoding="utf-8")

        # 2. release.yml
        wf_release = wf_dir / "release.yml"
        if assets and ".github/workflows/release.yml" in assets:
            wf_release.write_text(assets[".github/workflows/release.yml"], encoding="utf-8")
        else:
            wf_release_content = (
                "name: Release Automation\n\n"
                "on:\n"
                "  push:\n"
                "    tags:\n"
                "      - 'v*'\n\n"
                "permissions:\n"
                "  contents: write\n\n"
                "jobs:\n"
                "  build-and-release:\n"
                "    name: Build & Publish Release\n"
                "    runs-on: ubuntu-latest\n"
                "    steps:\n"
                "      - name: Checkout Repository\n"
                "        uses: actions/checkout@v4\n"
                "        with:\n"
                "          fetch-depth: 0\n\n"
                "      - name: Set up Python\n"
                "        uses: actions/setup-python@v5\n"
                "        with:\n"
                "          python-version: '3.11'\n\n"
                "      - name: Verify Knowledge Base Integrity\n"
                "        run: |\n"
                "          python scripts/kb_lint.py --path docs\n\n"
                "      - name: Execute Project Build Hook\n"
                "        run: |\n"
                "          if [ -f \"scripts/build_release.sh\" ]; then\n"
                "            bash scripts/build_release.sh\n"
                "          elif [ -f \"scripts/build_release.py\" ]; then\n"
                "            python scripts/build_release.py\n"
                "          elif [ -f \"package.json\" ]; then\n"
                "            npm ci && npm run build\n"
                "          fi\n\n"
                "      - name: Inspect Artifacts & Verify Checksums\n"
                "        id: release_meta\n"
                "        run: |\n"
                "          mkdir -p dist\n"
                "          python scripts/kb_release.py --version ${{ github.ref_name }} --ci-mode\n\n"
                "      - name: Publish GitHub Release\n"
                "        uses: softprops/action-gh-release@v2\n"
                "        if: startsWith(github.ref, 'refs/tags/')\n"
                "        with:\n"
                "          name: Release ${{ github.ref_name }}\n"
                "          draft: false\n"
                "          prerelease: false\n"
                "          body_path: dist/RELEASE_NOTES.md\n"
                "          files: |\n"
                "            dist/*\n"
            )
            wf_release.write_text(wf_release_content, encoding="utf-8")
        print("✅ Deployed GitHub Actions CI workflows (.github/workflows/kb-lint.yml, release.yml).")


# --- INSTALLATION ORCHESTRATOR & INFRASTRUCTURE HELPERS ---

def get_agent_rule_specs(target_dir: Path, project_name: str, stack_key: str, doc_lang: str):
    return [
        ("all", target_dir / "AGENTS.md", generate_agents_md(project_name, stack_key, doc_lang), "root AGENTS.md (Universal Agent Standard)"),
        ("gemini", target_dir / "GEMINI.md", generate_gemini_md(project_name, stack_key, doc_lang), "GEMINI.md (Google Antigravity & Gemini CLI)"),
        ("cline", target_dir / ".clinerules", generate_clinerules(project_name, stack_key, doc_lang), ".clinerules (VS Code Cline & Roo Code)"),
        ("claude", target_dir / "CLAUDE.md", generate_claude_md(project_name, stack_key, doc_lang), "CLAUDE.md (Claude Code CLI)"),
        ("cursor", target_dir / ".cursorrules", generate_cursorrules(project_name, stack_key, doc_lang), ".cursorrules (Cursor IDE)"),
        ("copilot", target_dir / ".github" / "copilot-instructions.md", generate_copilot_instructions(project_name, stack_key, doc_lang), ".github/copilot-instructions.md (GitHub Copilot)"),
        ("windsurf", target_dir / ".windsurfrules", generate_windsurfrules(project_name, stack_key, doc_lang), ".windsurfrules (Windsurf Cascade)"),
    ]


def deploy_infrastructure(target_dir: Path, assets: dict, stack_key: str, today_str: str) -> tuple:
    docs_dir = target_dir / "docs"
    tpl_dir = docs_dir / "00_Templates"
    tpl_dir.mkdir(parents=True, exist_ok=True)
    tpl_count = skills_count = 0

    for rel_path, content in assets.items():
        if rel_path.startswith("00_Templates/"):
            tpl_name = Path(rel_path).name
            customized = customize_templates_for_stack(tpl_name, content, stack_key, today_str)
            (tpl_dir / tpl_name).write_text(customized, encoding="utf-8")
            tpl_count += 1
        elif rel_path.startswith(".agents/skills/"):
            target_file = target_dir / rel_path
            target_file.parent.mkdir(parents=True, exist_ok=True)
            target_file.write_text(content, encoding="utf-8")
            skills_count += 1
        elif rel_path == ".obsidian/graph.json":
            target_file = docs_dir / ".obsidian" / "graph.json"
            target_file.parent.mkdir(parents=True, exist_ok=True)
            target_file.write_text(content, encoding="utf-8")
        elif rel_path.startswith("scripts/"):
            target_file = target_dir / rel_path
            target_file.parent.mkdir(parents=True, exist_ok=True)
            target_file.write_text(content, encoding="utf-8")
            try:
                target_file.chmod(0o755)
            except Exception:
                pass
    return tpl_count, skills_count


def run_linter_audit(target_dir: Path, docs_dir: Path):
    kb_lint_path = target_dir / "scripts" / "kb_lint.py"
    if kb_lint_path.is_file():
        print("\n🔍 Running knowledge base audit with kb_lint.py...")
        res = subprocess.run(
            [sys.executable, str(kb_lint_path), "--path", str(docs_dir)],
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
        )
        if res.returncode == 0:
            print("✅ Linter check passed: 0 broken links, valid YAML frontmatter!")
        else:
            print(f"⚠️ Linter reported warnings:\n{res.stdout}\n{res.stderr}")


def install_harness(
    target_dir: Path,
    project_name: str,
    stack_key: str,
    agent_choice: str,
    git_choice: str,
    doc_lang: str = "ru",
    force: bool = False,
    ci_choice: str = "none",
    idea: str = None,
):
    print(f"\n🚀 Installing Agent Docs-as-Code Harness into: {target_dir.resolve()}")
    print(f"   • Project Name: {project_name}")
    print(f"   • Stack: {STACK_PRESETS.get(stack_key, STACK_PRESETS['generic'])['name']}")
    print(f"   • AI Agent configs: {agent_choice}")
    print(f"   • Documentation language: {doc_lang}")
    print(f"   • Git mode: {git_choice}")
    if ci_choice != "none":
        print(f"   • CI mode: {ci_choice}")
    print()

    docs_dir = target_dir / "docs"
    if docs_dir.exists() and not force:
        print(f"⚠️ Warning: Directory '{docs_dir}' already exists.")
        print("   Existing files will be preserved. Only missing templates and directories will be created.")

    # 1. Unpack assets
    assets = unpack_assets()

    # 2. Create directory skeleton
    dirs_to_create = [
        docs_dir / "00_Templates",
        docs_dir / ".obsidian",
        docs_dir / "01_Architecture",
        docs_dir / "02_Tasks" / "Plans",
        docs_dir / "02_Tasks" / "Specs",
        docs_dir / "02_Tasks" / "Bugs",
        docs_dir / "02_Tasks" / "Releases",
        docs_dir / "03_Decisions_ADR",
        docs_dir / "04_Research",
        docs_dir / "05_Testing",
        target_dir / "scripts",
    ]

    for d in dirs_to_create:
        d.mkdir(parents=True, exist_ok=True)
        # Ensure .gitkeep in empty dirs so Git tracks them
        if not list(d.glob("*")):
            (d / ".gitkeep").touch()

    # 3. Write unpacked templates and scripts
    today_str = date.today().isoformat()
    tpl_count, skills_count = deploy_infrastructure(target_dir, assets, stack_key, today_str)
    print(f"✅ Deployed {tpl_count} templates and Obsidian graph configuration.")
    print("✅ Deployed scripts/kb_lint.py and scripts/kb_release.py.")
    if skills_count > 0:
        print(f"✅ Deployed {skills_count} AI agent skills (.agents/skills/).")

    # 4. Generate starter knowledge base documents
    create_starter_docs(target_dir, project_name, stack_key, assets=assets, force=force, idea=idea)
    print("✅ Created starter knowledge base docs (SPEC.md, 00_Index.md, Onboarding.md, Kanban.md, Roadmap.md, Devlog.md).")

    # 4.1. Handle README.md and .gitignore (non-destructive)
    handle_readme(target_dir, project_name, doc_lang)
    handle_gitignore(target_dir)

    # 5. Generate Agent rule files
    for agent_key, rule_path, content, desc in get_agent_rule_specs(target_dir, project_name, stack_key, doc_lang):
        if agent_choice == "all" or agent_choice == agent_key or agent_key == "all":
            rule_path.parent.mkdir(parents=True, exist_ok=True)
            rule_path.write_text(content, encoding="utf-8")
            print(f"✅ Created {desc}.")

    # 6. Verify knowledge base integrity with kb_lint.py
    run_linter_audit(target_dir, docs_dir)

    # 6.1. CI setup
    deploy_ci_workflow(target_dir, ci_choice, assets=assets)

    # 7. Git setup
    setup_git(target_dir, git_choice)

    # 8. Success banner and instructions
    print("\n" + "=" * 70)
    print(f"🎉 Agent Docs-as-Code Harness installed successfully in '{project_name}'!")
    print("=" * 70)
    print("\n📚 Next Steps for You & Your AI Agent:")
    print("  1. Open the project folder in VS Code / Cursor / Obsidian:")
    print(f"     code \"{target_dir.resolve()}\"")
    print("  2. In Obsidian: Open Vault -> choose folder 'docs/' to view the colored graph!")
    if stack_key == "undecided":
        print("  3. Ask your AI Agent (Start with Mode 0 Discovery & Tech Stack Research):")
        print("     \"Please read AGENTS.md and start Mode 0: /kb-research <исследование идеи и выбор стека>\"")
    else:
        print("  3. Ask your AI Agent:")
        print("     \"Please read AGENTS.md and let's start Mode 1 (Planning) for our first task.\"")
    print("  4. Verify your documentation anytime:")
    print("     python3 scripts/kb_lint.py --path docs\n")


# --- SAFE HARNESS UPDATE ---

def record_devlog_update(docs_dir: Path, today_str: str, doc_lang: str = "ru"):
    devlog_path = docs_dir / "Devlog.md"
    if not devlog_path.is_file():
        return
    content = devlog_path.read_text(encoding="utf-8")
    if doc_lang == "en":
        entry = (
            f"### [{today_str}] — Docs-as-Code Harness Components Update (`install.py --update`)\n"
            "- **What was updated:**\n"
            "  - Note templates in `docs/00_Templates/` refreshed to latest version.\n"
            "  - Standalone utilities (`scripts/kb_lint.py`, `scripts/kb_release.py`) updated.\n"
            "  - AI agent skills in `.agents/skills/` synchronized.\n"
            "  - Obsidian graph configuration `docs/.obsidian/graph.json` refreshed.\n"
            "- **Integrity verification:**\n"
            "  - Link integrity audit performed with `kb_lint.py`.\n\n---\n\n"
        )
    else:
        entry = (
            f"### [{today_str}] — Обновление компонентов Docs-as-Code Harness (`install.py --update`)\n"
            "- **Что обновлено:**\n"
            "  - Шаблоны заметок в `docs/00_Templates/` обновлены до актуальной версии.\n"
            "  - Автономный линтер и утилиты релизов в `scripts/` обновлены.\n"
            "  - Скиллы AI-агентов в `.agents/skills/` актуализированы.\n"
            "  - Конфигурация графа `docs/.obsidian/graph.json` актуализирована.\n"
            "- **Проверка:**\n"
            "  - Проведен контрольный аудит целостности ссылок через `kb_lint.py`.\n\n---\n\n"
        )
    if "### [" in content:
        idx = content.find("### [")
        new_content = content[:idx] + entry + content[idx:]
    else:
        new_content = content.rstrip() + "\n\n---\n\n" + entry
    devlog_path.write_text(new_content, encoding="utf-8")
    print("📝 Appended update record to docs/Devlog.md.")


def update_agent_rules_safe(target_dir: Path, project_name: str, stack_key: str, doc_lang: str, backup: bool = True):
    for _, rule_path, new_content, _ in get_agent_rule_specs(target_dir, project_name, stack_key, doc_lang):
        if rule_path.is_file():
            existing = rule_path.read_text(encoding="utf-8")
            if existing.strip() != new_content.strip():
                if backup:
                    bak = rule_path.with_name(rule_path.name + ".bak")
                    bak.write_text(existing, encoding="utf-8")
                    print(f"⚠️ Backed up modified {rule_path.name} to {bak.name} and updated to latest version.")
                rule_path.write_text(new_content, encoding="utf-8")
            else:
                print(f"ℹ️ {rule_path.name} is already up to date.")


def update_harness(
    target_dir: Path,
    assets: dict = None,
    stack_key: str = None,
    doc_lang: str = None,
    project_name: str = None,
    ci_provider: str = None,
    backup: bool = True,
) -> int:
    docs_dir = target_dir / "docs"
    if not (docs_dir / "00_Index.md").is_file():
        print(f"❌ Error: 'docs/00_Index.md' not found in {target_dir.resolve()}.")
        print("   This directory does not appear to be an initialized Agent Docs-as-Code project.")
        return 1

    print(f"\n🔄 Updating Agent Docs-as-Code Harness components in: {target_dir.resolve()}")

    if assets is None:
        assets = unpack_assets()

    today_str = date.today().isoformat()

    # Detect project attributes if not specified
    if not project_name:
        spec_path = target_dir / "SPEC.md"
        if spec_path.is_file():
            spec_txt = spec_path.read_text(encoding="utf-8")
            m = re.search(r'title:\s*["\']?(?:Мастер-спецификация:\s*)?([^"\'\n]+)', spec_txt)
            if m:
                project_name = m.group(1).strip()
        if not project_name:
            project_name = target_dir.name or "Project"

    if not stack_key or stack_key == "auto":
        stack_key = detect_project_stack(target_dir)

    if not doc_lang:
        agents_path = target_dir / "AGENTS.md"
        if agents_path.is_file() and ("Russian" in agents_path.read_text(encoding="utf-8") or "Русский" in agents_path.read_text(encoding="utf-8")):
            doc_lang = "ru"
        else:
            doc_lang = "en"

    print(f"   • Project: {project_name}")
    print(f"   • Stack: {STACK_PRESETS.get(stack_key, STACK_PRESETS['generic'])['name']}")
    print(f"   • Language: {doc_lang}\n")

    # Ensure Releases directory exists (safely preserving any existing releases)
    releases_dir = docs_dir / "02_Tasks" / "Releases"
    releases_dir.mkdir(parents=True, exist_ok=True)
    if not list(releases_dir.glob("*")):
        (releases_dir / ".gitkeep").touch()

    # Refresh templates, skills, linter, graph
    tpl_count, skills_count = deploy_infrastructure(target_dir, assets, stack_key, today_str)
    print(f"✅ Refreshed {tpl_count} templates and Obsidian graph configuration.")
    print("✅ Refreshed scripts/kb_lint.py and scripts/kb_release.py.")
    if skills_count > 0:
        print(f"✅ Refreshed {skills_count} skills in .agents/skills/.")

    # Safe update of agent rules with .bak
    update_agent_rules_safe(target_dir, project_name, stack_key, doc_lang, backup=backup)

    # Record update in docs/Devlog.md
    record_devlog_update(docs_dir, today_str, doc_lang)

    # Refresh CI workflow if requested or already existing
    if ci_provider == "github" or (target_dir / ".github" / "workflows" / "kb-lint.yml").is_file():
        deploy_ci_workflow(target_dir, "github", assets=assets)

    # Run kb_lint audit
    run_linter_audit(target_dir, docs_dir)

    print("\n" + "=" * 70)
    print("🎉 Docs-as-Code Harness components successfully updated to latest version!")
    print("=" * 70 + "\n")
    return 0


# --- INTERACTIVE CLI WIZARD ---

def prompt_user_input(prompt_text: str, default: str = "") -> str:
    default_hint = f" [{default}]" if default else ""
    try:
        val = input(f"{prompt_text}{default_hint}: ").strip()
        return val if val else default
    except (EOFError, KeyboardInterrupt):
        return default


def run_interactive_wizard(args) -> tuple:
    print("""
╭──────────────────────────────────────────────────────────╮
│  ✨ Agent Docs-as-Code Harness Installer                 │
│  Zero-Dependency AI Agent Discipline & Obsidian Vault   │
╰──────────────────────────────────────────────────────────╯
""")

    # Try reopening TTY if piped through curl
    if not sys.stdin.isatty():
        try:
            if os.name != "nt" and os.path.exists("/dev/tty"):
                sys.stdin = open("/dev/tty", "r")
            elif os.name == "nt":
                sys.stdin = open("CONIN$", "r")
        except Exception:
            pass

    target_dir = Path(args.target_dir).resolve()
    default_name = args.name or target_dir.name or "MyProject"

    # 1. Project Name
    project_name = prompt_user_input("? Enter Project Name", default=default_name)

    # 2. Documentation & Agent Communication Language
    print("\n? Preferred documentation & agent communication language:")
    print("  [1] Russian (Русский) [Recommended for RU teams]")
    print("  [2] English")
    print("  [3] Custom language (type name)")
    lang_choice_input = prompt_user_input("Select [1-3]", default="1")
    if lang_choice_input == "1":
        doc_lang = "ru"
    elif lang_choice_input == "2":
        doc_lang = "en"
    elif lang_choice_input == "3":
        doc_lang = prompt_user_input("Enter language name", default="ru")
    else:
        doc_lang = "ru"

    # 3. Technology Stack
    if getattr(args, "idea", None) and not args.stack:
        detected_stack = "undecided"
    else:
        detected_stack = detect_project_stack(target_dir)
        if args.stack and args.stack != "auto":
            detected_stack = args.stack
    stack_choice_map = {"swift": "1", "ts": "2", "python": "3", "dotnet": "4", "generic": "5", "undecided": "6"}
    detected_num = stack_choice_map.get(detected_stack, "1")

    print("\n? Select Technology Stack:")
    print(f"  [1] iOS / macOS (Swift, SwiftUI, Xcode) [Target Apple Stack]{' (Detected)' if detected_stack == 'swift' else ''}")
    print(f"  [2] Web / Node (TypeScript, JavaScript, Next.js){' (Detected)' if detected_stack == 'ts' else ''}")
    print(f"  [3] Python (Pytest, FastAPI, CLI){' (Detected)' if detected_stack == 'python' else ''}")
    print(f"  [4] .NET / C# (MAUI, ASP.NET, CoreCLR){' (Detected)' if detected_stack == 'dotnet' else ''}")
    print(f"  [5] Generic / Other{' (Detected)' if detected_stack == 'generic' else ''}")
    print(f"  [6] 💡 Undecided / Idea-First (Стек будет определен через /kb-research){' (Detected)' if detected_stack == 'undecided' else ''}")
    stack_choice = prompt_user_input("Select [1-6]", default=detected_num)
    stack_map = {"1": "swift", "2": "ts", "3": "python", "4": "dotnet", "5": "generic", "6": "undecided"}
    stack_key = stack_map.get(stack_choice, detected_stack)

    # If stack is undecided and no idea provided via flag, ask for idea
    if stack_key == "undecided" and not getattr(args, "idea", None):
        user_idea = prompt_user_input("? Enter your project idea / concept (or press Enter to describe later)", default="")
        if user_idea:
            args.idea = user_idea

    # 4. AI Agent Setup
    print("\n? Select AI Agent / IDE Setup:")
    print("  [1] All AI Agents (AGENTS.md, GEMINI.md, Cline, Claude, Cursor, Copilot, Windsurf) [Recommended]")
    print("  [2] VS Code Cline & Roo Code (.clinerules)")
    print("  [3] Claude Code CLI (CLAUDE.md)")
    print("  [4] Cursor IDE (.cursorrules)")
    print("  [5] GitHub Copilot (.github/copilot-instructions.md)")
    print("  [6] Google Antigravity & Gemini CLI (GEMINI.md)")
    print("  [7] Windsurf Cascade (.windsurfrules)")
    print("  [8] Universal AGENTS.md only")
    agent_choice_input = prompt_user_input("Select [1-8]", default="1")
    agent_map = {"1": "all", "2": "cline", "3": "claude", "4": "cursor", "5": "copilot", "6": "gemini", "7": "windsurf", "8": "generic"}
    agent_choice = agent_map.get(agent_choice_input, "all")

    # 5. Git Setup
    print("\n? Git Version Control Setup:")
    print("  [1] Local Git (Initialize repository & commit initial docs) [Recommended]")
    print("  [2] Connect to GitHub (Local commit + setup guidance)")
    print("  [3] Skip Git")
    git_choice_input = prompt_user_input("Select [1-3]", default="1")
    git_map = {"1": "local", "2": "github", "3": "none"}
    git_choice = git_map.get(git_choice_input, "local")

    # 6. CI Setup
    print("\n? Continuous Integration (CI) Workflow:")
    print("  [1] None (Local-Only / Skip CI) [Default]")
    print("  [2] GitHub Actions (.github/workflows/kb-lint.yml)")
    ci_choice_input = prompt_user_input("Select [1-2]", default="1")
    ci_map = {"1": "none", "2": "github"}
    ci_choice = ci_map.get(ci_choice_input, "none")

    return project_name, stack_key, agent_choice, git_choice, doc_lang, ci_choice


# --- MAIN ENTRY POINT ---

def main():
    parser = argparse.ArgumentParser(
        description="Agent Docs-as-Code Harness Installer",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""Examples:
  python3 install.py
  python3 install.py -y -n MyApp -s swift -a all -g local
  python3 install.py -y -d ../project -s ts -l en --ci github
""",
    )

    parser.add_argument("--name", "-n", type=str, help="Project name (default: current directory name)")
    parser.add_argument(
        "--idea",
        type=str,
        default=None,
        help="Краткое описание продуктовой идеи для Greenfield-инициализации (автоматически активирует пресет undecided, если --stack не указан)",
    )
    parser.add_argument(
        "--doc-lang", "-l",
        type=str,
        default=None,
        help="Preferred documentation & agent communication language (e.g. ru, en, custom; default: ru)",
    )
    parser.add_argument(
        "--stack", "-s",
        choices=["auto", "swift", "ts", "python", "dotnet", "generic", "undecided"],
        default=None,
        help="Target technology stack preset (default: auto)",
    )
    parser.add_argument(
        "--agent", "-a",
        choices=["all", "cline", "claude", "cursor", "copilot", "gemini", "windsurf", "generic"],
        default=None,
        help="AI agent / editor configuration files to generate (default: all)",
    )
    parser.add_argument(
        "--git", "-g",
        choices=["local", "github", "none"],
        default=None,
        help="Git version control strategy (default: local)",
    )
    parser.add_argument(
        "--ci",
        choices=["github", "none"],
        default=None,
        help="Continuous Integration workflow to deploy (default: none)",
    )
    parser.add_argument(
        "--target-dir", "-d",
        type=str,
        default=".",
        help="Target directory where the harness will be installed (default: current directory)",
    )
    parser.add_argument(
        "--non-interactive", "-y", "--yes",
        action="store_true",
        help="Run without interactive prompts, accepting flags or defaults",
    )
    parser.add_argument(
        "--force", "-f",
        action="store_true",
        help="Overwrite existing configuration files if present",
    )
    parser.add_argument(
        "--update", "-u",
        action="store_true",
        help="Update harness infrastructure (templates, linter, skills, graph) safely in existing project",
    )

    args = parser.parse_args()
    target_dir = Path(args.target_dir).resolve()

    # Handle --update mode directly
    if args.update:
        exit_code = update_harness(
            target_dir=target_dir,
            stack_key=args.stack,
            doc_lang=args.doc_lang,
            project_name=args.name,
            ci_provider=args.ci,
        )
        sys.exit(exit_code)

    # Determine whether to run interactively
    is_interactive = not args.non_interactive and (sys.stdin.isatty() or os.name == "nt" or os.path.exists("/dev/tty"))

    # If flags were all explicitly passed, run directly
    if args.stack and args.agent and args.git and args.name:
        is_interactive = False

    if is_interactive:
        project_name, stack_key, agent_choice, git_choice, doc_lang, ci_choice = run_interactive_wizard(args)
    else:
        project_name = args.name or target_dir.name or "MyProject"
        if args.idea and not args.stack:
            stack_key = "undecided"
        else:
            stack_key = detect_project_stack(target_dir) if (not args.stack or args.stack == "auto") else args.stack
        agent_choice = args.agent or "all"
        git_choice = args.git or "local"
        doc_lang = args.doc_lang or "ru"
        ci_choice = args.ci or "none"

    install_harness(
        target_dir=target_dir,
        project_name=project_name,
        stack_key=stack_key,
        agent_choice=agent_choice,
        git_choice=git_choice,
        doc_lang=doc_lang,
        force=args.force,
        ci_choice=ci_choice,
        idea=args.idea,
    )


if __name__ == "__main__":
    main()
