#!/usr/bin/env python3
"""
🚀 Agent Docs-as-Code Harness Installer
=======================================
Autonomous, zero-dependency installer bringing Docs-as-Code discipline,
Obsidian graph integration, knowledge base linter, and 3-mode AI agent guardrails
to any project in a single command.

Usage:
    curl -sSL https://raw.githubusercontent.com/koudinie101-png/agent-docs-harness/main/install.py | python3
    python3 install.py [options]

Zero external dependencies (requires Python 3.8+ stdlib only).
"""

import sys
import os
import re
import json
import zlib
import base64
import shutil
import argparse
import subprocess
from datetime import date
from pathlib import Path

# Ensure UTF-8 output on Windows consoles
if hasattr(sys.stdout, "reconfigure"):
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass
if hasattr(sys.stderr, "reconfigure"):
    try:
        sys.stderr.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass

# Python version check
if sys.version_info < (3, 8):
    print("❌ Error: agent-docs-harness requires Python 3.8 or newer.")
    print(f"Current version is: {sys.version.split()[0]}")
    sys.exit(1)

# --- BEGIN_EMBEDDED_ASSETS ---
EMBEDDED_ASSETS_B64 = "eNrtvQtzHNd1LvpXtslccQaeGQCkKNsTUQpIgBSu+AoAWfYBEExjpgG0OZiBp2dAIiSr9Iic5MqJZMl17VJiyXIlceqce05RFGlRD1J/AfgL/gPXP+Gub6397O55kPQjPnV9ckRMd++1X2uv91r75rGZmY2VeHevHfXjdHpl4dLVi3MrCxtz80u13daxujpWrVbXOkmrruhR9Xv0v7VOP+m347paO7Z6+IvDO4efHd6l/z48fHB4Xx3eOXrt6K3DB0dvHN4//OLojaM3j16jV48OPz18pOjP+0f/QC/o26N31teOrXXSftQfpHUVNZvxXj9uqeNqr9fd66b05y339JbqxT+Im/JnK97rxc1IfqSDvbhHX8ettU6LntXVyZmTz1VnvlM9+RyBt283Ng8wYvTZj7bT+lpHqaqKWj39R6+5k/Sph0EvXuvwnNc6x+2c6yo/1exsqMELamrq8GOa+x2e+ev1qSlq+BF9+eDw4dE79OIRDfnwQ/rji8MvaVUecvNH6/SUWv4U7Q7voJWbhFKA+/w3qlVFH3x59I46fMTtMZqHR28fvRWM5PBzZdbULFlF0Ytw7GvH9CDoMcOr1Wprx1S1+gKmYaZ/XM3W1OEHGKfez9eP3lCHD9Th19Tlo8NPaA73D786vLPWkfG9W7j5d2jM9IeM4AG1oW4ril7TsAnGIzMuTI1gE67w13jy92Z5qUtqiGX9Oxrua4dfHb1tRkvDPEnD/KW3BvfNgH5ND3maGIJp+SZBesATuItXMhu7QQWYqnjUNLS79PS1w3v08wsshNuHO95gTtVkh+XjTwnumzTst3E47uJ4UOs7WFCaQWnJYPVcux/3OlE/2Y/T8lpnitBh9fBd2u4fYzH1Mr5BTQmEml0HisgMGblonTD+t82QHGph9CX+5HV6/oCW/XV++xugHbbz6McaPdDqDs3tIQ8VO0Cv36JP7x29XZbpjR7VyccblVuwZ2nBPsJoGJ3uYVRAlKN3pEd69+XRP9PTt0P49wk6bebRP9JIpMmd7L7ZUR/+Kw/lTUBR04LTX2ks/gqLE4L/OaOqgJX1GIKV3MGxihpGRZfOvbS4snBu5ZWlhRw5pXfVseT0CxmoWTmQhwzdBMoQjIM9AhFSsWYvBpF0FHH2O2udwV4r/9CniAEIPGl2d/e6nbjT9+ji7z5651/+3wfvFJ/4O0XUsngmQ2nmu4DGiPVQaOZ7hujclzf6/Ar4B5qA/px+3RNCxWBWa7Vp2pnFTiu+ccv8sb4Okpqlcu/b3f2RwVhgwBsatbDh+sQcPjDUReaIM/D3hvAUzhNk7ejvmfrzUfuKz44GqfTZBI4LGDwCWb7PpIh6eMSnKCR3P2UyIjj5FWgwqAsRIhwKHFpq/bl/khqNxm7c240S4pNb7e715k7U66uVeeyxUufaCW3wKrGFD0DpZOB0UF5ZXDu2jp7VctzbT5oxPvmYh3+Xx43T8bkhKp/TxwJPfy0t+91etM0t/90sMlNgOrg4iz85/Cm3oxF6FPTnwnMIvf5OT+Vt5g5fCDdiQEC4t81mfGBX8K6cWCZocrIrio9/Bh4Twweg0Br3XkMfXzHLwAoSfmWo1IeHn3DHnxjSD0T5B4IBLvaFHslS3O8dVBkDvuST8UAYHjYVz4jN/IiJB/X+CSP0XXBDAvs59lG4xTjKcvaVC1mCQo9y9OQDpuNv8Krdz4sBMgIjisX7cS/pk5i0G/2g2yNJbLPdbV6Le3S2mvQiaUZt+lNe0r9Jp0vCk6UOdUMtQDcMeerE1wkO/ntLJR3ibf1km5hcZxswu52tpLfLUlzSqZLYt92L05R+bSU3+On1bqdPf691ejG/SrqdDVqFPuaGf9Ppvai/M93vTuPXhvuqFt/oY0pPRAE3B9trnWtRZzPq8CKCiLzMP28RkmHpPsF/q8AQPrl31nn9POL47oc4oPcZ1QhJ7d6o3772UzVuVyxVXJwHETNNmcB9wHz1DeZBloEzqbukt+UStkWTwxxV/QVwmk8sU1QPl+/jyc9pOl/zw7vMih+ui/CJjt3ELWUtWJRi2voxE6Wv+Vh9pc8xnRc6b2+SIGJFNmbUwbeOI/+aqaemM3RK8C/N/seaJhAtAP17pCfwiM/aXT7FD5iG+7LAh9muXTcfHn5c0WIeaMPRO6ARwtwy9Pc/QX1FJsz2ep+pr5a9lkhZ6RINjPcg19Fq+ALMPWwNT+kun0fu4mTNSvseDRda+YWePdicljlPmc8/1JQIZGk/xVx+Q7/pO5bRGdO+5p7s+EyPluhqpuI4HQMrHf4Li8UkPTJK0WJUtfROwysz5e7jxGlK/CunKjyyY3pghWhM91Pp2JF8kQGFrzwSgVzER/S/1O321blokMZqrhO1D9Ik5ZO0dG6uPF71CPoV6U2OLWsVQU9YGHNoA5n+NA8PAvJD4dfBMTGyamP10pX5xfPfX2+ohqFMW0k7Bjlq8IhlrAUAzFYAyOWFVwFhLIXzQPJmfMrS7+vM1CB9aN78hgiy3myeo9m8x4v9gGbLm6xZEqGr6aF6PumlfVrfqlpV65g+tIM7xGP/kbXMSbocfiSDpaZuF+bLNdvVzwvXR6tpX/EDLSfdlSNBsFzrX04wLq3LgYDgPzSpN7R8qVUeUgUVH86vWaFAZ6ULSwsLl71hfsDGDqJLhD9f5LGHm77Gh+8+ZB3BsLuqMU/8sqHkp0c7McUHimW4rxlF7rgW8X67u00Mv1EbJRTML3z34pWcXCBPrVhw+H+bs3H4pVbLA5nmgSpJd+VhWkaLX0/EXWdnqjOnAu5qGuPvH3QHpPO2A9b5/i8ea4SaPf3S4BUtM7RTe74/0+I2S2vCuQoUgoBlHVer36f/VS9dqs7Pr/MZO/wZ4yK4gjUxqJW55ZerQ2xD3O89VgwerANhaIyWhYH6Mik5fEQjkqUYIsPizDiENxaSe2x7cafjoRF4M5qHESOrskT3aR3f1Mr7HX6rbRQBFTh8kBnUewSdz609PywZC0m1YjXo9MKNpE9iXStWM+VMzzI2DJZ4Hs6E0xuEDVqy8g/gQMRzPPaFw+lxPgycpeujH7NEfZeFKWz8O+XM2LEvlmwcvVZXjelrm9WETk68SzKr7CFtdsNwCX7fi9txlNIZHSOEL16eX/he9rgBq/Dck8NJxREjkWiLYqYrRJuPPBV3lKK/M9h8QumWpBGYnORHAvQPjt+vf6meeLRWmWfK96Msc7Fy4/LVhXO38B9aunUtqn7IVPCRtq49PPxUvr7S2exGvRYpDLfyn+SFzd999LMv2CxhSPMdY3iUM0e4gi9H68JME0hbNeSBcPHfQX3KRhV2g1qFejBmjFYnFmAAMNdr7qADyMaFBpSCNitRei1FIwifP3PUpQj8/BI+JIGO/ip4vxSncaSHALnr58wo+SD6xtiiQUCB42nPQCL6lSYHoTHmfkFDode8XPLnLZ/I60WSRjxRbiT6BTeaObnBz4t1Dtuha7vUjVq70V7YWD+8RXLuIx7yb4yI+IXBFw1MC6Y+Zr3/BkQLi0tEhI7eypgz7mgFg9FF7Ilj0aOiCpekkO/J17kTVJNuGzOzG3Oe9W66gQEUC8Zi44V9977VyHKWFQvXrF9DM9CRm1FRj7viFdW42o46BJ/+Wt6Lm/LX2cG2/LEk5Jh+2BGd2piPmwnE1BSuKj1VMBrGyKPXsj6RUsO4chplC+XZDXMUNIAhJ4GX5xPmqX/PJprXRAppLC0sLxg7rgf39IY+KBrsr1llYiR5nfmuZaTByaGOFk4uqFe+ZwH5XEdAfaB7v6Ntb/eFYX4ixnXes+H86uW5y2fnLvsMS8wc1b32YDvp1NVmlCbNUBx7Ww0xeoT22DuW+v+K7ZYQItTxPp/H49KLOk7j6XRg/FGWU9w9eodlpYcGL+4NRRRBvokwSviCHNt/J4Z29E/a/UCCxdmoec3IjvzNb9/5NGcMKS121FVtkPK+/Ne31OH7/Ak2jVQCiPL8nlSCG+tstYQFmdXoL1l6M5oVr99nOGoeV1Xz3WZajdLqOQhNJSd2ltXxFr2ys3jvY8AG4XnAyEgLDBGIDzWAlhab8Wb3hhkKaSdG/hHxiLVgqCdOHQ5AiLKrjietOBqFQVcun70ytzS/eDmnZbg3TtP4JYl6X8hSWbfOI5bdFAupASk8elOVHK1UFwY0lvLvX/7p2i7k9zb60aqJ3gxIsMEh+OC1p5qLU1MKHAZ8qn/ldMi7ooCKOvml9Zw67GRjxRdWBIe5RtwM9KRe7H+/oxqYG4jps6K3/4Yl4juW7lvJupY7mw+Gak2VPwgvGCIh1HJmxeDsfDcatPsgm056vYvdgS79BR1ovQAyeygPn/EaPWLt5x3arc00aSVEpBiQkHIMlNbwTVFcRGESRQLmgu/PXbqotnrdTn836vfjHjt5XncEjb72Vu16ci1pJ51rqWXXVyGB8iNGgX9j+z/ECsKGn1W0v5tDJ+5q/oOt5l8PxZbnWxdglxE7p+g7ooHCzvk22/Ee6F7n6HBWF5o7Xe70Y7hBxCGPPk799rX3TwPAm9TFF1rP404+O/pndASF8SujAypWzqBw3oFvnYePFrqni8k+zjH4ufTFuuJbvPMPA9LY0JIMlDDi9gtz85cW5KdMhVZV68A5IcWsDg/SENy39AiWqf92XAX2qbNRr5fEPYwk1ABZ0xZfzUPaOuiamifD5jPrafJHb1aUtovqfTEn9m2thvJgvOUPLQYPMihMgnzmNA6xdSRps7sf9w7UN0mObif4k0nKLZF4uDXM979iRfdTEAQSgBBnkvdZi6H/PYSNsEp/C2DqNChV/A9eT0397qOf/j9+ZzP1IbLS4X1a4FtGixbZqsEaHra1euXyxe+TOvUTYJSx3N0pS5NAliKpj+Q1+kf4GkzfuaAZN7iPPvYHN1u3tlo3GIgeEw6EON1lDAIoWAmkH9XIyRMNbxS/9Edxss4H2Y0AstCEIzCWpaIRFEgr/hh+5Y/hVF0iHe65UVjEx1BgzWdk/9SyMhoyXnCripVT2YNK+MwHLiQsJCs1CC7cgO24HzfKGIyP5qfYAWTMuY/YcfUA7hqP77Ddm4fXSWhk0/JDs2oxc48QrUTiB3+2XlzgS5Yp12wv1r7DgGHf+pptvV8EdESVtHuU5W3VStL+dEUtvzRXPXn6OVmbw0/LDurmYFtD/DcOEHrdyX6hYThnZFcr8/MV9mY4aMQZtIFfm1nEVIeRENT72v/1hnPVKHF1M1p+UclyJuLtbOfjAViCm6FIzw6zRwiLfkPcbpoLaY7KAw4VFVq4QCcp02nO6aaE+4WiCn9sFU76yrOkOq7Iznu7V9SFLFxeL1Ql+odh+soegX1QrOrxp57+RnN5o9jKQXqa7tVZ5wnub3wd/nXrhPi8zMzNyAP6Yyv4+IZq2r5yZmNOa4fNG6FD5IEEMBRyVWGBK71B51r1LCF7C6yvsRslnUaNXpwn0Zn2QZ3tRZ3mTswySGOLHk4b4tNg/IfO+o6JFvh7LXJ8psIjr/nt/CBqVy9BGls+6DDTX4p3u/1YdXsJqZeMzHuDdOcv1cVukz690mkfCIYzzmLJjn6sXTWaOiA2643MYoj36iHbjV9zi3EXB8CLBvNsyr6mSgpgr3u9s5XE7Zaaa3X3+oQsOuLuQi+O9ZtFUoT04Sw1Emgh7XZt74C0JKhIau0YB0w2yizafCTeJhYeGgPa3yZ9BNJNzx6xwcjgjBN18Ep8y9pDj/nSoTLMvlExb1+DSPK6Goax1kENyuDtUMiCSz73NhsmTmwSckpMXe+aeCWWIywmyRx/DucBDqFhVo9kiY1i++Yw0VoLQ2ILZqc6SPXnzq8OWuIRJG9gJ2lgzutKPTm+W9YypVnezy1pUCy6ecgB8d7JAGXt/HvIO/bAKR+igT1gvcHjuOGITtGIfso78SNWn7/UjuNAkKOVkeG9x3v1IPAGaW7lM12GhQCwN7O7Riq5J72YXyJJmF+Oo4+0/UCqyersRtIZH4L4kHnO1+IfMiYEbKk4uDw/hY3eHhbIHYb6GCLih3gbJR+zXuvs7RD1qqvZJ/V3MBD8tSUkjyBGPVqujRSaiQnwyRlVMaenCwKC6Uxjr1tqHQGUiyW3SxnE/thWxeE8CEd7nQNZ7vnS/ceMXBz8ZgnFo+KIn6xf89G6p/+P9uIMceQ8VaBQQai5FnZID7ra624Spqtn1IVu1E7LLvAP8iiToiAsXZMklkXo54scvse79RAEiJeAoT90oVTG6FIkm4j6z7azId7HTIhQ0fZoXdWLUS799TNzmv/89ayLRHpPh8HQwEiazYbPS09KTWn/qnNLexCIkX6i9T/NVL9m45VofmHkz7tD0jZY5feFAJmADic3W/AzxsvXJCSKMU48vMVO6UoumN/zYvux6jYKNxNGf6coAj2IkH22JuFTrvfPRHkwMQFMjVVJbANEV661SCiwwS5WA6vONuo2NMxFZWRd/MbZHbY9+RhtrZhnIvzYL29SLR6wnecLQb0vdWBIab4772l7yAsoe7EpAdGWaNM8WbjDkkUhOqNLBOZoXbUiHhBPV3WBMMMNeqTWi9VP7Dk4m2I5ESn2zrBgmnyQA0crqIaQEoF2t0gfdxD/I68l4YDLGTB4Zc5mKDulzV6y10+JvW5ADyPBbzRzXVq4uDC3nAvx14+r+6vfq32/9t/W/ZCAXxrlRZm3w3KMjD7K/IVEQ2g3zJM00GM+jzRs2PHV4wGPbfWirb7JlHL+hrXOdtLfILYJwPseZHq8M9jc0BrzxqDXNllUuyTo42/5Yu0YdSR/Ui9tlu+7JN+vdaJeP9mKmn3DkDvRrkga5gVC2bgveHAR7oa3rG0Xf5Imf6tFFXHHcmSHe7sTkXrO77Wqvp7J+dJz0eHKO1FnO+aIpCfg9j1BbttmQgdz3rkwCTK4AIv3XHwqyL1pIwz438T+zcz3cj6xzO05v1qhLYfqZ2A0LP//6RhH3KTT5W4uJP2XCDMukzYoqibvrz4fG5evrCws85nOxXNAiALb/gw9BMfBsv8gmDq0VrusChhnP8+wexb2nfEnCPiUffm1ydkQ6y4k9tI5gzGaacPaAzouqyLu65nLG1dxJK0yXU3bg+1b5tf6+jDG4IKUf8LZHVppMrEE7BLXAeECUv+YAOLc/JIvu+VMJcY/LnDNrzGAzS79h0gQb7CdS4cPqJI+gMZYrV0c6pbyTy791N/hxUfM5X88kV26EdIHWDRDmgCjp6UCeN0oICsNMVjyPH76T3lrm+dyEC75UFDpdXYMfYUElEajsRmlOzjPV7vX497yTtwmOnkh7lfPJ+34JXqnqnPt7W6PCOQupovZFpE4gnAx6QxuTO9GzSvLdU3N0sFu8dccpjKKLYlJPc+XnKk90P1+Jemcw20N+SzMQPnzuc4QPa9AjUOibk6Nw8OAaItOjFwQzLK1wbEFRCbX3aOo1dNPPPoKz8UQXwWI7LgprxcGNpjhDNd5RjtGi5Sfj8Kc2iI/v6F5OXnyEct0n2SpW263pueuLnoJvKL6veOk9WxcQajQvCt2TclOwxF7S4/gM7F6KGfeYLtn1dhOzbg/yuUfaHHsdQmNMdFIdzlZFxpDRZFs91CrAI9kbDpv2BpCSTT9DQ/iodUjPrdGlYpEqbIhMZjQKb3kd3Q+oUkLsPI50xAvNuoen7e9g/5Ol1Hr8H+yPetrLap/ZaxnWSvmPas2ZkKIsvkPH2sfyUMXyGzg3PFWvrTSi1pxtbu1pS5F/V5yw9DX9/zsYiamJnEWP/wM2ECJY8tAkNg8mVPw8F12K5mdNV0hjsQ8/aXtQ576Tryjnxw+tKB+okq+vloeC7kwgdf0kgk4NsfZEvrTE2dom5znYGnH5Tmb+AOdyMnb/ht3VjkJRxtIJX/fTyLMpmmY4GuNiMaPBoyyItBH/kNrwgjCswjUL0zKkxJsxGDvhWjmFRZgJkdSwIvjgqCXrszNX5q7muMx8tgFA41QEov93lq6HBoDpIXvJ7QL2tbGSNixIUG7xLPTfrcTpwEj0aHFTzGPIkYiL73YuOOu++I4OUNZMjxnnL5igbk0K6G51iU7wrSXYVdGyWBfuwTcmMTCo7/j6BEJDZE04tKl716FsDwlKrkkLArmvs/WjLumSMSP5L2Ek3j8xw9pc7HP0v2jLC+8y4xJSA6srWKQmZmZdbaBPKSTjwPpZNZxSlLG/9L5a8IRXPa6kJWHOg8hSBlTpfMDdsK9RILh35IcrqaVjeObGhXvV1GW9D0C7dJOFcvG7yrD1uwQ7JJ6dg7jWqhNaUoigYY/48G+qZ2eMJOe8N0S6nkTS/jCiYxfydKeu5pb3TM5JTa1SfwuNpvlronwMDyyoFREzSgxPDyQYy8WwJSf8IhyJr02u615JdDznbPpCeYgIyNDL8rXRSH18H/kQ1L0Zt8ZGnEtC8dEYVjhD7Ptdos91h+4oB/arXYmwPtqxizkrCpaTW5Un8Ji/vYXP+a1zE0iCBct5nWS+O7xumAF76jsF5abjGMmOGBZTmK05sdJbA/zr3z3FMiseKf0X1mPVIsoLxSWqNMkLc55o6BvBN6owsR37VsCcN+3JPHtxp1zy/whxqAn4l8YzjRcWJqDYVyzOSPW43ut/uWXzOWGeX/sbjxJKrttW+zO+kCsN0F4jxZPc46r91zUXtZxZXxuHjcbuvzD9bfHcVtpthZgnZcMTcTgoadgeAuVKR3iewWco0jyt+84kc6piKF6NtwLY8IzRaC1GcajcpSLBmgzlCdKc+ZwDDa5Z7IYiRRYSPMLFxdWFsYNJszSJk53j7EkX0pIktjv61ClB4UIZXbm43ztj1yREFDbSlGAmY7pYPm9wo6NEYVBzABD9fGDjHEyG9uaT4+38Q0FSZuq9N24l2wlzQgBLQoY77xBH7s4trpqyPTDUgJeqBuxHi+RE2NvWEDvas3FxgUOASdZzNau6ieOVtTszMz/ofaiNA1hZwxvBrJOCMX6S9GLw8+nzUZJfCsvwCNh6S7axwB6oHsZ7mH71GZ0OJkAzrXQm3ZPS3FGligI5ODoSeMm+4zP4Zc0avhmv3B+qfcg/3hR1kcuTkDUxqLd1ZP6XEwnnOdj9taR0ZyDjcUDDKrUyFPMRrmSzT8vSW66xMj4io7GT1F08N3qjfWG5wH8mVkZcaGH6cmPlcO+srC8kpMA6NnYOBWOyeHuJPBoRPZsX6L7npTzmtb48cMoTJ/979gQbxzFmbP5sXaKsy4mr19leRBLfW+JH9eWwRM/hodazM5ZZzBpA1rulWIq9PKtvJf+Dj0MWU5BGROEHvpaVq7aSkXiInUFKRdV4RMJ4VpvMs+0JdhcZYQHGZKfWfI8CShJYp090S72zcm32XIro6I81F+srfW7f6GmvDR1HX5hTV/3mYz/yHGoTNcn/4hdOybCISUcZIouzEp9yvTT5K8OdxfmXI/sNdTF16R6IiPu1bnl5YV50mfPzy1eXJhft4BtHLRXbi+vfJmaR1ZbqHV1fs70di/a26n9IO12QCJu4hSuHWt22+1oL42rJDyQOrVGr/q9QVyRt9pzcEw81+bhTvf6Ch1qPN6K2mnsPZ/r96PmDmLqcq93klb8SodUhW57n3SDgsZXeiSLd9LMGOwI6Y9ur7rd6w72csD53QX7alU82jflH3zww0HcO5CJQEyq2xT1K0uKHwiRtT9hwLE/XEKaXgSByZ0Cpu0HTyM8ma34j3rbm/zwuVOz35r99ox5dVv+uF0ZNVp261uXCNyYGBbiDY6j3NZTjef0c9+eOf1E47Fx3nYwhrY/zYBOnvzWt791+inW52m359lvfQfes8fuPuMRfqphnCIUee7Zbz/BKFyc/lOuw+mZmdOzT7IOYarC041idubUyZnTp7OjwD/rWdLQSlKShg6y1AsEqdfrXs88R8Wt81ErvjRo95O9diJkb0a/7ZDwvpz8bebtbG32tP6gnXSKPsiOaavba8Y5YkaUMe4t93txZ7vPhHWmdnr229+aPXXy2W9/51szp2ZP6i978V7c9j+cnXH9XwteeM/nE5LbOs2YT9Np0yJtRu1YOnvu1My3Tn3r2zPfmaWTf/q575hxtbtpbMa61rktvCMfzAXOcfwb04O0N72ZdKbjzr4SvewUccpjEt70cqd7vR23tmOF7Al45ZFJQ8tRkHeakkT73aidQG5MlU31rDDdVfENmk5M06moqNPK540C8jYKLxKU/xb3utSATYJtFLqOibx3mgmBLQ1S+i8WpkVUXF3lAatTqp1s9qLegUK0FeeN6AmQ6Ly71+31VXqQ2r+77k9Yq/SfUW97L+ohJIrGtcsxWARV6bdX6afItwudFObqV1bOV7+tuoP+3oAgdtSrSafVvZ6ioCOxRXhNki21E6U0vV6Jeq+l/RZ9XWF84KqP23yuynU5Df3eQd2dHdeg5n1dolXognedWTs26G9Vv03HUsV0LHrpGUazdgR8KQuc+AbCzUmNxT8Il3PgoXdKQn8r3qIN6rQ29rGHG71ut1+i5e31N1pJr87TLiPKHn9oAM1BT51R9qOalgNKutvrO9hvfPSNM/inJtZAr3damBLeTyPEDQn+x8q1JAWsUlkRbtmXXqKQ/ga4VCp7sMbBy3yK//ViomgdFbYIP3OfuOcybTcheaO/LFwNs76MVhv2RJRoP/tYEWrVMwM8Djc2cpBI3yFY23H/VjvajNuSDC5Pju/EEZdQsW9osczL9XUbO4iDQ0PtxTWYZ7FivRNra6v0f6XVv1lbW19bu3V8/Zvl0ov14+b3+lT5RfpNf/ET/OQX6yfKwTw19BpQJmq3zVS8ydIcmtd4nza8813iBxLXyDhViPWg5jRw+y0tZtTawNMCzB+C5SpKVezB1AM/zxKm2lo7dq47aLdUp4vDH7VEKlQ349tCLjQ+oc8ab2p6PenvlNZYDz9WDs4QvaTRyqfEPPrmq4o6WQ6wvR13Svx5Wb1wRp2qFyLbClgL4SPT0ByBNBgaTmft2KUkTSG7ESbsRm2izCglm6OucqRBlYleEr2iYZZlvv6mwZC+0eolW/0SDkWGArSJgOuRG+qKv1+KBz16kzRVNGglfWYObcl6BzzF8Gq6wDK6SbEiu8JwYzHZ06OOcjHSRIpjL4pKCIp2w9ICIH0vVYNOVdsoNPAlXplURTxS1d2iPe5UuXovBnM96rFnmc4c/ZPW8jPRX2BPV9fNau91mSbSM7Mk+vhjFvYRwnnVmTOWmqiYtse+Nnil3dyM2h5AIXVW7OWfbjHM6JItwVkPhiOIzFNLAUA9kDGwi4nqqIFOBtdMmVFKg3GLia/1fmamZ78vHJcPLRjUxMBGL5QFU3687otAeMRkxL7RYRk/bX3mDX5m0UnTYKyw38kEtJMP3wYfkVQYhtAxsItO6cUzx4+vraXfJL5gQh1ucUBvGU/X1lrfrJdPVLLDIBrbjrbTMwRs8cLlK0sL5+aWF3R/9kxv6GN/RmkNEVSDxwFK4A/LWwYI63w48UcN53iPVlDoTSdGQ25i3shcuBF9BirsNVsP6DO2gD/MUGZMKekMYvd0C8mwG9zfGWmyOhPCwiKy4karOHb9TlQ8iBUVrlleyvFh57LW7tw6Z5b3FgzYjwO7cHO+eQYeXv+TuE2DICaHMk+E72bF+VDxY4XHWE3zavJ+PHrhENqdiwmwWbODjV0IUhqdzWr9jbFn09JPlWjtbz57u4p/Tpp/gMp+77xil165uLJ4cfGyRWAxlRd3YezoT96FpRi5NSKx4SQvczBJb3XNc/yXBhZ8VmNDW2nWE0rMRPTnwbzs5zySYMbM1i4TcgUoHwDzBynQzwQfZDDCELVatAc1r5THFxLZvCo6ah7yRN2KA9dJ3OugZr/pVJE41IylS4iDpZt+77fLEJoKO2nF6V5C472ZXfzbnixSJK7U1DnS+ZIWjSE9IDWVRnopSiF2YcC1bHd2nwvIui+NSY3gjZTkHaJCzY3tAWm8jyGYLTcjkoasw0lILCSrE4cfDyk4Wz8BhnTiMsRwFGun30Qut7fjXqrF9Z2IKGVERz6+QdS1SfLezoDGV70eJWxC3I161+jrCtKe97sseMURtSfhsN+tNndIdKNnf0CJTa9aEZe2S5ERE7wmhey3GKQRAzOQJxELHbzx4xgtsHgdlx9j7CPAPNbKDBFMQqXOUXMf3BNoduM7dko0I7rGXav1RAZLByk91TdvCJXgwzVCgfa6PvE3IPBV/GdtDf8H/j7sRN2yZ6lcf1E+x7/EIF78Ro1bPnqSCs+3eCqpmcguHcHWrXB6SWdv0C8Ty/FXzRMB5LFHjNobgq7BNuGRk9CSihW14s5gN+4RRTUmgEDcqohB5MxsOTT7GPOBZpr4uvwkDGGxo07cNEO+fUJGdTO5XZeNJ+K7Z3e/FfclyNCgAS8Pb3gvStq1Yfzgai/eog9P/CmqdxPd7RIJJb5GBydDOvPsZCQz6Q06bPGNexneUVHENTe7COTb7HbbtPFsVGCWklh7HW2a+cwzfRBB7pdojThZbA56P/AuYy2OiE3ftLTQ2sVur8E8Ww4JjfmKzcRpQGRsZ4jVnE96tJnd3gE1oWOOttzE6+k2DDAgVWe0ETXu9co50mElzqjd3thtMW1LWaZPnfWj1ttudzdLa8emhMSWx1oFHCWaa6ddBQ8CjVfxx+CNSLBX0ldJizAVZYv9VdTchYXLK8v857mLc6/M42nZHUDA2aAucQJXPWUTQo2FIj8tJPlpocnPCwuXFi8v8s/1jGXWV9NNf8Ntr/7ymSNbCMGtzDm9KIj4J56/CVzBOXbmKdj+Oykb8zqw+LQ5MphN8loQYRMhAJxRN2+79dnCwvhDCue2hWkYcBv9rt3ocs4k197Y66bJDVgja4UtalEqn5TKYVsztFULZB1Qxn1UayNpkjTT8GMszEanu6Eto4TP8a6vjmow3mcZAEWfZPqSjzd73Wsx04prvkDlmRE3CuQtllVJVOZmpNgMmNPPGKDjNiUUFUJxYWsSIWESE/BQOpYnMR9w4O8CXCpsHgZZu7l1WxuIy8PMA0+MZY+JX5AfhwARTu3eHRdra2AGxm7YkOnpzcH2dNTqTZviQHYCUeegRMxni9Cfdg4doKF7supMf9Oc6i00xT7jQOPMM0Q76Ec5D/t6gakDlF0mFZrhbYhcaIw3/yP1bGNrt6J2022otUN8EeV8Q92ltC8APOwoGJpHRK/N3ZbLRbtgnT+qlF5LSDjRMX+aFwCThL8r9uHtdNtQJ7lF6EpwKyAGGFkjqG1rQSyhvKVB1cfjrDnyQ/xU3gC0sY2tdFK1N4TO79gwZs1w4QfH1eJ2p0siWm6aAEnIP0DAEcvkhSjBHfBkEQl5zIxDHmUjDHPvf04y2zvhUx6qJocat+0CCL5yjTv8IX42+Tu8Ukc/uxdWSpanJupcfqGsQMhyh9sah5FX316WxTPLK0l+bA56rKECxU6kih0ROR4EbRDkw/dpWuWRha0NmTd9VbItpnndylnXb2FDIvuZtkRob6L9ba24Bi7TcbNyThX/S/Feu5F6mu7Ikfrt9EC9pk81UEhBIviVtthPqxMK7f0V3u+436yVs3SdhCg3IV+mGjkjr52ekN904hnho41Q+IDSUJK+nVqY/54PkyYCGwVCR7anLULqltE+sq96SEFq8cEMkKqSw7FKsJeV7M5W/IWpZFap6DzCrkldF2kkRaNf6WWPrvnfJgprrRWTM25dADkvFll5sNvbNeacic9j0KtubyfGEReTnM5xSzF+OUZYdAJxTEenPMaCiXsnxNik49QETel9DPVeT7S3jzUeX5gORQTeKHsI2Dvuy9VDPfHlwL6ZazHaWqwbQ7qRcCFqB6W/FAj9kNULRBzfMTHSFvD+/6VWuv2orS4ZTfc8SzewRHeQS3ATgRC+JlAOhWrfrvAzDetVKzmZ4DIAKuCL1q4QyEv+BDP7FBgWzvJ3Xm/zxmxU4lH7cMq36QhklQHQqrTXrChNs+EBG9530D/9/dvXfqXYqEUgbp+ACUaDcUhGTOOmPLyNfMVy0WRGqwryDc33X99Sl7t6eJ5oyv18o3AZi/Bi6HKKEnXeUzymcY/MXtzrH6hXDebKuhYi3Mj1hWiPszt+REWLzAtMCERQbj/1Is612zQUHFYgitOsoFFpyX4nImlgvzCkp3ilQ4owZo2dRyy7riGYoSvaus5y96g+C1exdX3E6oXzCQnWmAnp0P1lTcbUBZCx3NxCkOMmN3IATzk7R1GHoQnRFhM2GxFGtJB9jcp7SvNVcwyFVeS6debKCXDydx/98z96Vli2rCWEg3HU7u8csDEN4akcidv/xrC+dEhGpp/japmG3+lXu53q8qDZRJ74brcVh8rhBPiU3XL16tzS5Xp+0SfdwUnheRr+iB0jOFdeLuRU+kCnwswqxTzIo6b7nIkKBjKj97hcG7PkI7eXRrawtHRlSQ8uZEgBFlXUCNIaGISsFSM3sNGs88kY3u+d6U3GmJ6Cezw2B/G9CxwBviEi54a4gTc2ELy4sbF2rG6cjb2UtSUTfV6b622zDeQqvyFaJ5H7JC2fWTsWRN0XBue72C5uX4tarY1Ig+T4VHY7sy2iuod/kQx6Ju33SKOKt6AzUTds8NiJ23v0N7Q+o3drpQvuFzYI8iWqrOOO7VYLjrrnffyLdFSeVUoQ4w1OV3D9LnSizXZsBE4dXCrh9rYz6sHardgDk8boNXVkmm2HRnfFqxrmn1OU4PeQT8fEkLNWaaLfc+HjHB/Fr/KufxBfeTUObCH5NV8Uxurb6ZKG1t/glPUzvuOPv7f+vjO8DvqHXgC4ytC4ZCGUc3kjumTshKkjhQ25mgHSO6rzflaHvttSzQ36Xe2Qf6VPZJTExWyuCdccOj/oMO7gyFbVQmc/oePMF1mJs5fjfi4kNOVNvtmjoprUAYm63R5HlvR7MUfEefdyVJSuznru4qKShGnJ7J7TxSaNoMewTa3OZtRuDto8Yp3ngrq8bMt8+ez0pbMCgoP+lC0BrKLt7V68LfPkXBO+RIagwpZeUTCVV1AnRo/AalPbcQcudzRD8AJp8jyZrioowcwtMRfGAOo3Zu+a+j+Xr1xmXLTeSJPCwjQmfbLcGWSi2h80W2TOuOY7A9pM93OwSZQD8kNB6o1+wI4PCZAZnozDb4h8YRH0i/mkSZt+kQQcWsDOQUVd4VlFpHevDEju+t81g0fQ3haojt2JcNa/ul2MVawffH+I5GN/P9ZtlZkArdp6QTCZaMMp283ShDkAkMjriM7CXrSJQ5tYD1+Vpa3tpC8hBuYhEUA+j+FTOareKGk86z4cOa9hI3kmFbkLGybc/85gM2zH49qhYSThc3oWDfo7MZQPMTX4b3PVvm8hV8+V+T6WXziO2jX2V5LFseRBIJMLJcCu1JrXWwH34sIN4fbA5+1nWeo1RsrfeZtHbV6atS5+K2uOdxhXJQtVVre4qVv5wuZ23Ytbu/Uvfp/dh+KvWP/gnFV/Eyo2vdRugZCg2vWdpAknIq9WeaQbmgSEDbALsAowZku0asRXC4KSVjVUoQ77VaFnIu1Uk7SacIRoFSCrgLl2bL1S4AS63jpjUaLofbSHbNwNIVpnVkw2asZ6HN8Y+o6VljPZpfQCiYJwc7cGNZFsRbY4o2Z0ZIb3gSZ2Ji6fZR+R6QoEa8HsVQ9514cYWrV7RfuyNMIW5PSlG/Juks0au2HR5iae9eItefLSwtx88Y5NsmuT79y43Ru9gwW76O2kLE92H4coPXZ/DIVY53hICyXc7CF7lpO5ZOzFuyc9PsnuSUuzdXvI1W6TlvXnvl8yrcfdL0fvsWMwA3iwwl3jMzpTvHfhnXUjtk0L0U906IS54G/S76vMSfBDOv1z3z6Z3uNun89110e6FR3/1SdTd5g9mSO785m4nHD7e5gD0Ug/CI02QSamkXHxjnAQ+ohqBIT8RMc4Cn0H4XFfcfMQtYDr74RMP+RBWhjJj6VYNtACyqSigTa5oElItP48pAA92wmw2S5qXoJ7ym12F2uy8WbgYoTE6FKAVpw7MWSbtT1m6GALMUUETkzEKQGF5prCFqGmkK0fAHSwCp02NliNzhoPSrgCI5MABH131ekIUH/WhyYEmfYVlSASC6x5J2m1Yu2wMpna2rARp86soUovn1XT6tJZSUoxNhCo+2rASejPPavoE+o/jtg00dwZsFMjyPYxuT6tBNchqdWba8c4nOQY10Oo6AI03k/07f/k20D0g9vrtUKdi4PK9UyDSIfgRYElTu/H6rqND7c3NxWusx8piwyJfrwLmph2e4RGJddTP+5xV5mECM6VpDZhSjA/ycc+1vIxj0XhfNgQtilrQ0xNVsxnBnmahkXe2DzocxA89w+URBZtf4M3IEzSgCmpu0fSBT5lbk4noYzA260CoqBLggAbVN0E9paeO3361HPDeIVMoiZJfSVumiFNMqsNRr8z5vud+EYr2Y7Tfl4oBZVwk3zhjJqdOfmsmuJ/iggZvqUt5hDpYze9ptOq5DUt12snt27TqcgmZhQ4csbB5aHUZgncy2cdiQiC0iXyZ0vfDXbTYsrtbPcWb034yc38WNzJs3AqRV+ZA2lGUPiRPaZ6gsUfucPrti/z5e3HDO0eHb1t1kF5a6XDuYvSRAKqbNfQq5XTRcqYo8cbxo660Ye/ojSGXDC9pr8C8nyeYabOJMugQCM1+fdsx3zyNOmtFRC98KK5gKatHZs6fC97ifl9fR1UQ3HtU1079Y5XrBIXNNsrJLlIZVh/HTUy74TXXvE1OKXl7oBUMWPcL9emHErbVH7fmjPqcixzKap3/9QdufWZ75/CRZDmni3dmK8geMSz/I27F9arYyZdjrrgxXzr0Xd4fZJO4SrznMxh2wLsxk36bvUEUO7E+m1cvSUPcELogbJfyFnQ3+hnOGfyxJqD7T5y4EjtB92kwyl0aa7WkB/tHlQbGmPsXeZ7lI1XEhPOlZK5Fh9U96P2IJOuw6W6rh7g8wAtiXxHRQbM2wHW2hzCkRV39PwB0iCSKcITJCHm6/CENXieD0rwFEDd2t3QpYi4xeqshwEmAVJ/E6Q9ZrBBl4jI62JeyQkdmZjh9MdHcfpAGavbcPYsWaSNQhRs245CL00dCzNbzn1M39F/ixVHAUP/dcU1+N8Ta8dOmL/pz5w7HIu6SlDXpXWAxmbBBW9pKXuRJ/Duxv0IaLyL5DHEMfrFoyZyWSwIxFRy9sVdcSNuDjg+Ox3s7qJeHPuQoo4kEYJd2NtKuaYr582jFLuAvIrbP3r7hPookdBpVfs96IAYK2ZjHHRxS7UGLFkb+k29FsipaFdo3D/GQ7Z2dfBNGa8p33o7mz2ZD+kNXoxI3sYgxiZudyevwiHnx2aTFFCibEKLnqwcqgwSFwdCY8yrtiHWjCWAXe9ZBhG1HPFdEC6WD4rCwDJhx8cNCtG/Bm+WNd6k4gn2/XE2a5yOL9d9qU29mGtIz1BaZ5Xer60tr0+9WC69eGYNhYlvrXEx61t/UXrxG/S6Rz/Xy2VfqssXHdGdVlThymZLhPCmR9c3DO6fUWG5j+Kjz9bEDcuw1/NhdoYierCHUUWnHlNPe3FrKIX0hXb9bUghXyjO/8oAt23bhkah3UTdDQHuLYfh9aZFVj+RpdhAFkGi66wQlhvG7QEaMqAiANj7wWaJcOxvSi/WcRUQigno2n2oLpDDOP1cPhPbE/6bAz5kEPqoWfqzzhavTNuJvdUFdCdwYLPFoS91V4pKnbi89ALDBoIowrzEaQ5cYtCqvxOrnWR7h+BrjtAZ7G6SyigwzkftNspGNK+hzayQVlPuBTUFOB6tgIjDTpPqNKpRFd10omSuQNnQvPdsoroevCyOsrWZAquDhWftDaG5wZgaikpjeuSF/xQkQ5mq8gYwxqpPeRNhEaUZncaSncxudKMUPKswSQ8JVLk8NKVkJGHPYiAHAyLDgk1bwbplEv7D1bNtHi8vNS+55ddlCMd0PY7kvPkdGc1VH2MHQqZafiLbrcbkAHqm+qyUfPOsnJlSFfKeTmwdo8oIgEWK9vpoOsHiIHp2oSr6Kl0+pzoZNU9PGCE5TdcMqGbjVwbb1Pwcqi+3EEvJoZExwpIKwPEd1rapXNk718RS4ja0+SWvSfaK6gIaRGLpoN2vj1uSbOBIX8gTLgsOo0IG20WPMcrg8e1MjcNRVTw0DshInVF/tqZ4QYhECoF8Kpo6kp7mT73YaIce/oKs9CekAMPze4spZKYA3ngCUBDwPKkIHmQDG2KwtVvbjqEs6pNf8L0cAMM0CpI3TYC2g5tIwZZMCNRkDCPfJVMnC5yd2fZQFsOYlFfk+6Lzk+0Lj2x/RYyp2PwraA9pg2UNOIMyYezKLtau1PYd6ordogNx047h9oZQewzMog2rglt6H71viz6dwHsbrsqwcB0UenIfDttqOscbSctHtoSL0ziUT9kNYSw6hIWrM+tDPNp8JZIPix/kwZWH7QhqZw76scvg5gIBLjrXUm5tzkynh0F6NUbiMKpMKWR4M994noT2LS528ML08xgMyMcLwxz77Y1+V252z1CAfJmQDFUcMj1dlmELxQymb/odeFVGVuvVU+u3i4phORazapnG+gi3ghcFyIF7eqsro77U+1WXnRz5KWaDL/HvyA+Nj73u0MKPFcIdl7RkQ0DcLrYgjMpdDv3VJ2scya2L69BfEzA0qZJi+ZlpNYyd0fssN7NNxjMz0/qPxctsf39oVmZDyQq3HQYAW4qg0ADAraUWiOCIhCuZ244q5pKNVnElD73fhcTNrsEIYjSclk3SOkM+vEX/r0A9RLR8HOIhK/knpB3y1x+KSpyqsbivYw1Iwi6kErmSSZZEmCbDSAS9z5II22QshTCN/1gUwvb3Z0EhOMI50kpbYZSz3tNCSmDn+kSUYJLWwbnFHYpZTfJmAGX84RUF8HEOr0z+f9PDm1NpxZ5hnEDOlaXd+jo0cD/uYQsknsmvw2+sG/ph3NnfSDpb3ayHqDJRXFIAOeuELbQO6BbauMvDY4u1dYOb+XAV7zDbRucS0YeFAQ4X9JKktpJ2gZ/NkIEJUtv8sAdJ/MKY+omrgEeLLHHQcDzKgjsfwL4lIv1oW07I/k3bwp6DfrcVHbBB1M0b6pTpq4Y/avxVCcmiXYkNMURjV9IwzTbqEyzxgJVMNKB18HsxvZmGfqiuJlLSaHvHYpo0DGJCdnWsppe0JJkbNm8qKFbX7dA69BV9qwCMNmCn399LPacguy1M1LEN/NWZa5Jb81cuQrgug2Ug9elp92I6m5tvAdeIttiIt1ymTnYM9m8SQJ71nFO5VUGwlf349nTPqHGEAtM36T/e/T+kn8cRImwlWFEbjfWjjd2WPnEa8Y1LzGq9OG2GXmvBKsOU++6WC/aQO60qaxZ2nXqRJVXOil89ATp4Yv32LfydtOiv9fW6wg8mpfTbpfVnrBEFcAHW3sBsLp8NLmPn6J7PULn4bniLMi5iPuYVeCUtRm0lN4LlY73kcZZOJMWcxpNbOS1RZhZOd5ddtE1v0Tb9RducYNEyMHnBzDXa7mJ7vjP4nrvilWOhzCXsn/Jt9q/j6lhc0PsZrhr+Wt/Bjcu13RI/1KsvN2DzXbMu6upRuN5sL3ZLzfLd4yy18PWc5Jhbas3/sxWApbvsUkfeUkf+UkcTLHUGJi/1u0evHb0ld5abK+hN+NkDiRTTd3rz0t5VfIP8Vxzu9lZ2Ye/ybfP3OJwNl53/2F9QF9sncXhnJg/68zYluIg+6dA2DCRn3RQwxtUsuDROV123MFZn1ldNYOY6S+E2+I+vD6B9wMWc+3Htb5M9Q+m52MjBRtqBJ7ov5A7/r9FobEbpDrKes1fLY42uQspd3onbbVXS6c80hQtxv4rKXS8htLbKBSAk2jQc9G1VnWtvd3tEqncRkojAzs6wns4CFvwnzSvL9O9FUg5urHUk8I1EjuIOGBiHHPKn+K4aKQSdD/mcpuuy1zkAqdv04h1sdILOURTb6OGH5i5wREUitlAKu+PAfgncUswf9O32n2Wu3eF76f9NY5dnYa25QfjFRtxmhoHjIwILC5sXl8fnKiVVLhpdV2trxPL8CEQ84NDBgkYcwbLjN9IBiKMbIZTRb6RDG8c04l0PmpkASG7otSrbgDx3+Kxg6qIgC5eonK0PkztICltgt8mrPC1IxHfLJ0RIjbAqckKHyRcCsfhaAA9F6spc9KQCW/taxwr9NONQ0uTv6sH3HZP3be+dIc2Che6bLG3SFyQXbeCuZsAzwosIV77Yw69DSYi/NHnsN/EHP/Hx7mZ2tTHlSNfHqRpxWH40d6LOdtzubstPvUDXos5mxJPlQqcv889bhx8w8/oE/62iWC7zyzvrvAX6FjHbRl+vc+vwp/TdaxzEKyG/TNARbawb8iaBUPzuow9eUxPuCDV4oeAidznnSr/UDfmFa2tfe/fD622xrzAI3PzwFW6Wf5NmjBFh3KAxD7jFCZ21pt0JJ3xZ/YTs5AlB0xMXWVG4Ak/R1ah5LdqOT9iuCIpaITwgkA0efcMb37CF48vpJ15kAHTLjHV+n9johzSrz9DKo5OIws7FH9EJvulR4dtZYNi0X0NMUiJ3clT6I1UyNWEuk4ohfPU4ff/bf/1PdfgLJ5/ic/B+GTpYOcliqmTkd3Te3OmVZmfKmlA4wbd82wD93Ufv/os6/DkixllouMs3enBwO/rwhDki8SVIt+ch3eaAawHRB/zOvyAjYZjsQtBZINSchBa+RLJcDq6Whsq5tXv/PzyEN8PNxOJD5nkgd48E8fPSu46fx7xM/Dyg38zIQLmef/pPtGAE5HWAJBhfALWBOMwjvw74P3XzIx6kbI/bpqK0Ae49lGZuF+Hfr/lCFiQjvI6rVaSvByItm4PGE/+ahev7LAk+CJAVFXJWb6yrw/do54fpOv7Jz/J+vbT+bPXTu6rh7gdr1LI9uTE9ot70VrzBmgGjWGPm9MZKzAHJ042yInR5ndWEf+B0DN3h50BMUb4M+P/IL/PRjxVTXJZ9P8PxNhIyFLh79KEM/DcCDUe4IbWcVP7KcCXlw9g43SjnplWAeXdtegl98ujwEz5fDyfFSZNiiFbQmrA1nLsSzDo8AZ+rbB32oXqUDK/YuxuwfL2JYciN3BAtMoN3d5tYUFwVfThLNGe2hkBYtnU+I+f5Mqv27G22Fo55tsv1DAptazpfU7pNpdwTcjGubKZJK4n8+q6oCc82Mc17zrej/W4vbtkKUzYWanUV+zzd73I901srEHiIE1D3q/J3yYx7erPd3ZyW8U7zWvotcXuNKpkaODDE4F64pGWDZUd1NTXFP4hZBRASEt929/oHHoSiRvk1EuuPhZMxlNmNyNq6vAbmzyczd9V6xgA5xPhlwU9oAfNGFj7QtjBTMZonh/FarJTAyqACjqk0Py4mPGonUZr57qT9zkaD2jcixOi7E7LR9YKqryxdBOKiQI7D1mB9pHnogcIi0xrjWPC1JsVfpPJJ8ZXbJOev3uQJ3V4vmTqT5TDzMrc79Wzp/yVdyPVJQ0eGzI/ksxFzq00XO96MmxoOMVNErYai7/ij5B6xYOHdz2LGxiUhub9sVOmQgCavQz3OdojmRZhrsc161YuKq/vfBmciG5tbCPybOODBVcxWDR202zmrsNne20LRbgpJuy007aYPOecoK8Qm00kWn9zHU1P66ykvMzLII1lbW6X/K63+zdrarbW19fVvljnO/xY/wc/yi/Qv/u9YxiXFWQI2PSR7/CtcHKJc4LPaG2y2k6ZVGDsQvv+c/VZj3FEyXbEmaY6/cfnKygLuTYM5ZjS7VKUL5y+VA3fU78PvZOtYZTxAphRTWW6zEZngKRxHI/ghUnlgs4zsQXHUlN7VhLHhIkWTeAke9zytCUe4AeYL0xjgtIZCwqPNCE22toIOPRZc4JQqYMJP53X6o7PhIcVzpiUGcyRz4cc65z8zOBMXGQBEYqfNVvVzvsLN3JpkN2/azm87apjfTpvq6ba1iKiO8rf9lzDSOqffn9Dfx1uFZB5exMfx8431G06kmJj+KxlsMxpJ+U/qTvyTeBILtmRCL+JIj+Qfcjv+Szsq/yQ+yoJNnNA/OdLX+YfcxD9jF+jT+jdDJqPhQZy23ga52SzQ3w3/8TGkoM2W+I3EoMh/TE0RnWLiY+5z/hpWRdiQipa1dJ6gqnMGapmt+aZzj6mx6Ox8SdrUbazawqxQDX24fwLZvWqqIKOXexxmUj+ufvvBx+rwJ4QWYpyVScFsBvOcmhbbvdjav7SVUUp/PUia19SiLH2ZXanWc/wLfUP1O2yKFAscP4Jz16/OvtZpQgSobqXLF9XNjOCBgieuTDzgFg0E5r+jfxRbKHEGuVX7PvsEtOFTqNWdtY62Uzp0UdWqFIwST3BmWf5/14FbjD+M70BuQSS0TId7EYzXLTTWw3XghyPUYcCjPdzDkxRPCsMSatMTByZohBjVPWIUTMeC+y4+YUhP/O3NHKG5XWgsZpLglG7oR6VMWvvY+0AcdQtvBvk9X7NgRj7+Vg+ouMPuEfGu8zB96xaqFNe2a2qm9mxtBhL+Pv9VHn97ieQj6u5gdLDdSakUc2uJl+GvojTtNhOuy8Lls1AKwFRmKenmdRXRqlRb+ta38SOBXaiKe0iHzF2u/Rh3jYrrHi8m6JWQcGSviAIr6BU1Fwt7pRfjezXXrozd5RUxvZnFtQXNpIDcmF74eEzel5mbtuGYPoXvuhk+b5bshZyFZ/zEbdmLsaNZyJUWgolt/H72Dqq9QWf8dThXUeQuv7A0fyn4a4txXSeyh6TRsT0zppuS+WN65+ADXUjDv/MBocRcfo/vFRnbZzOpmvjn0f0tDcDW1blFiYkAddJGuDkdRPeHvm/Iu2lo0ruGht3l4BtFkdkzwV0d/pWbfFuPboTdyt29ictXaq3B7l5aMt2gdgNR/f6ZkxXqGredbERpM0mk5K9v2XcXkGXKCMoVQWmmjot3q51kUCvLBOCY68U/HCQwkQp5d+8soXePLMkvKsM4rAiKb1/1x/hYRlZrdUqNbc1dD5W9bhUFXPMf6bKudpsIW/JfCQqV7R7qm2ZYyXGdF2SBOl+MXMeb9UX7RivjfHJFzgz9KS0TGSCM1mUYu1vI1+7vlDOme7OQuiqHX3hI18Dj11mrnJmU6U2rbv7QFl39SpquitrI6jqQUmspMHSLeLMUUlOZQmqDThv3C8Y39oi0kzJ+oLq0hT2uU2zx1Cx6UeqbqefGdeRgEx9ZXs5ACq3Bbon0vS26hpwHOVMlYUSFA3+9AxBeeZVcgcBgI4Z1bnlU1jqd2cZsr66kk2cCNXUJBJ3cbVqc9ZaQ4oupZaw03gr5pMKb8NDqTnrRM0YHLu4wsv61t1nO+mNuRyusJbMXlpHxiLZ04II/x+Vveb6wM5auVAomfsb+5b01FPqMJdWeyccM+Yz9KwcXEz3j/vTe6/084297xUrxerHEvWdsE5O4/f6cp2u5J70nKSvHyDKbX84zOo4xVt8kykYigppSz87wD3X1lbMXF8+ZwGDFEqUq+tLc8RsC9vdhBDO2FI7EDbhldq+hcJf8SKW2vxzrje41/lnOtIMwGEsibWaukAsKMms921WeocnjLFvzn2rmZpkmc7OM1G1US9fJ407Pa+lN0F/TkbMzAx9xlzkud75gi3l6XIwFzLq6aVfYZcAPuco8BFWkrBA4b0ZjAbLpZs7SyiYdi3Z3212vbg2xQ9v/+N3gzkSJBr9pTujqCTxALP6Q5JzgotzQoOkKoEb94kViNjZkvvp6Z28GjkZUhg6z7Buu/RM0yf2r9t5LMcboSy9r0TZQcDq9Riwv5RAQGEZw78X08suLFy8SGuMOTDaoSbKF/w3MO9Y2g4j24NpWvosOtyKle7iVsTdoA1+fraa0gogd2oqbB0RkK7xStno5ve20ol4rrQVB7wFk0o/w9ByNvRe1FUlWfV3FOfiMVq8XST4SKQY1woUt3JmUsl0kNw5Vmk/SJsSvAyJo83E7wZ9yBYSzKLSjA9w6g3sC+ZZrmRbCexLuUTXmLixcXlk2kZQSyPvr/4m6O7sAtcSDxZtbJKcm29s08luKr/u4pcx9n/TnMrZE3cJno0p30+vG9LXNatJJ+iiqvUj/onUz2kIdHh322aio2VOkqO/usWhScUGT271obwfFuB0MC7Pb2ezSTgDsS6Q70j/z8X7cxv32smdAHqW/kmsw4qif7sRxX0N0ECxQVBZGXlfDzHoGcO3KPwMfa5psirWutLSwvDC3dO6l6ve+972KWmzGm90bhMudZln34IGzXUStngd9Gt44+kn/BZTvKdxS2dMWsl78A7nTXt8KqqEKBAsQ19xbiLP0x9L5cyD+zUGa8o2oVy/OXQbwmpqautxVOBu1qSkNTLe20OASt9BOYrNwuf3K3PLLACHjAvOSos5Y6PnufCFkDckhAbJoQOoaGvopYIR5mOmCzYA2TV1jgAXgQTXf2DED6jIf0zaUBWxHncYIq6Rca1/hvGoB6bX2cIBpaUNhKTVdvRXce8PPKiYuWuBBzTWbrts7kJuD7QYjKJcjvKUudrfV2VcuuOkunZvTCeHbhDOsmENI1xCluYWGMHCAm+PLmG9JjuOBF2EMSFwxHmHI2z3gqgDSLe3JF+fGvKUfF5l+qJI+l/A/zcxsrJiTOd1QJf+kliuqMTO7MYdESKgWRMdwmBs2nJG+l6yjitKB+ISNhHB0xoNbdo2qzQCz9TEY4rMbS/osyW8vMp9+ysaCqtGPK/bIh2Tug/8k+rMf9Yiw4CqJKcLZq3FvN5J70glt9ZD2ZIBYRPiDuOxsh0hLj3gfIiz5VguwGzqlOzFCh1CEqCYQl+wGVs/DRwG4Zw0U+VKqzUVb4AqR+ADoIW836lrw5T8ANdfpJ9WF5k4XMC4imPWb6tRvX3v/NA2rTUhrTQzwvJFOz7f5DHb5Il6uNaNlTANvefnKCg8n3on2ky7zJmYPGForJqUtbuV5RAEjFhI0jAXL2xzzXRK65uOKMvuszEtNBCv6bi2m2pgE6RSKKE4rrna3tvTeZIljyJH1INkF4/VJc852qh12a51X6JzzhoIBIwwLd3enlmir57laXAOW5yax0xSXFUfIFfWh21FWOGIK7vo27bYMFidTDUjmYxtn2FCYOGxoPsKe6yJlmYQig7GXQNj4rC6Z+c+1OYAbVm9G43ktHzMPoIPg8Q+RFtIfEi1LthJ6sdWOrhv8mI9bcu2WB3p+iUGep7nYce/1uiQqRm3aBzp0qnH44dEb8OAdfqYOHx29oZ7n9JbPdOzJg8P7LzSEyDVMQqXZOns4r+Lmthauce7MgpfYe6/U4jyfTJTyaxQXYm1IbNcODumNPmGvRiIAPwlg8z06a/wBvQK0c70YoIfAM+2rz6ftwfYLOAb6Xq2GrYJC3/Dz0jmDnQZGxS2elGahVcImxj8ckC4U813ipzAqTQ9JpFiko3JDLYNP6XyJqpoyVWjrU+AJpHwROiadXJ6My25SJS1/IB6nyS4QqZJZMyDNwAhk1GrBZ9EQNPsfSm8hbml56DvO7wz1etO+IlPpQWP0qEzncy0c2K24h0Xwmsxs8OxlArqavzqFMT9b03mVWBheaGJ2XOqm7JZpmYVkYDUx8l1ccN0AL8b0ijdXDRupyo5HPfMM83UBrKq7SpyJ8OWX60ZMs2KbIMvasUZNXR2kOy6OVhtah1JSYjEjKCm9HUZJdW3jUIyA2+NchKKXc7RSB2mSkpR6bk70hCxvUivz88x38qST+mXSqSUWkle2cQKe4SjAFZL9rnFF1NFEE0A00RSmKVWYI5V2t/rXNdch8KMpXm7U8ME1ExLbcJYXWC7Xa3HpleUVtQkJjWhUa9A0nmZQ6ZDR9ndIMz4/t3hxmb4n+hHz+LeSG7xQV+eWlxeWNYvWL2pcU5qvsoJYYB19UU5mozWHeb4JezmNY4fUhb6VD5zE4YQRJtphpeoCmaMVcw66Gux1O97dizkSWre7FWG3chQVO5inqkFF7IYp2I/6T4auakRrUOOQsi7xmPOENQCpWxcQVXPwnJRpySw1YiJCS9VsD0j0Xl5Zgi1qTwjsfgpKR7yM9lBEGiQj8N0BhKFadR96JAwhfoVDlZTIqZgFaBX4pqOQ7/87Irn+SVPIT1XpLHWCqDPGa3zz23c+VYfvSaTfJ+CCiOVa7GBXGDnKRXRSutRkcjS905RO0IPnZeRqTZ8YNOKXiDa1Pe1C1puElr0hVCmLPOLJyqLPqzDweQREQfr2tjxzvMwBBBh9Nku7A3qxFSXtskGfub09OiLnkxsA5BRBnEIuk8gOM77ldECicFsHjISHzUrM/l46jFwmMdkv6mxFEEQys7ZgUp/q6vnv0/+qly5V5+dfsDsSYAfRP9E0APoSHcwAT2BiPHyfN58T6FUJWue4nWd0g6nogOHwd06dEfrFmWz0NjN5GuPp0VhzTiMHzbb0fNrs7sUvMO8SZ6XFEQ60fcHYHII+RmBOMT8zGvUIpmY+yXE20d/rhBI0AVx1amwCFTXw98Hw7Wmj0BPPUTo/Wk6949x53matCmBwpkvsi+lXYrKeUS93utfbcYvO3VnYALDE41iehf28GTrxPq3qtdtSH8hUIyKZbi9VRLhiweLWaD4ofuQqD/Rs1OslcY9Fc7NWrFViSHDZiXQPC0yN9AH2Ym7GuEOc6JVcv4UImU0RS/ty6YLhUBGXO+cTjmA1CSUQxYIBwRHnKgjCjN85yM+Mj/pYtnfZ8jiWW6WiEs9A34Or9AG05YCrnGs0THHQX/MiQZ13ouJi7hDqmuAco/bCtNkvj0PVVTqMfKAgMaiHoGWWeAgO7pBOjjZcBuRjjvyFBP065n34XphsAWrh1Ss5VbbaS5Y96ekw9cG2CQniNNcJGdHTkCtj/+PNx1bz4BolN3seeUCMdUmZETvhKQx1uRRb7WL3+zDgNVZvrOt+94BFHSAsU8TG6urIPbxlfq+vW3o+x3H8joxnx+RIr5XxjZmlu6Xr7KQV4T0Bzkv9UWubAPFByGdLpCc+ESLwpDHNoZ80dSy/8eg0qqZkjVzyCaS4d/QmylOYgHjENN/TodiIgT/6B9pkkkYOP2S0uUe/7qPOggC4wwDelgoTiBf+TIePQ5n78ugdZhBra6FpVigubSa9qDU0f7mYsDzAhuBQTV3cEhzc7baE4mjHGi6B32pHMO3NXV1M2RaSHqC8rW/1IG6gyXpj+erCOcYvrF5jaWFu/tIC/046IqunSF/gvlLhTrShz8ngaNR+lTc3OoSvTVhFg4sydDtbSW9XzajNXvdazLc5MlX8lmGymp0+k1XWp3S0ujorBSNoYbVYZhGGsRr6QgMuLuaqxA968SZbknfjHnEZSUQRhlvR8r7i+qQmtUt/YlX6qRViPdeqYE8tVRLQvK9WDa6BSmX1WEDz5AFLy60J/nmN8y9IKBNkCwmkNdAwxIYuCOFJBRDtvo3VksDfc45OXB4QHw0QB/xQyqMnwkqbgx5cziaGChpQ97oc/4o7UWC2HRZP2UISwZ7QF1OwR7k887B/5ST0Dc/Er56Xurcs7n0H415hlYcWfJkObJ3+24WF5vtJ3G6BI/d73baHXzjgPeBNM2H1QttrXexXYxWR8pcJd9f54pL69HStVivTfHxDbmptNFfZtKY1rqb2yRFqspQhwXxDzqtoIr77wgIlpWnx3MrF79MfV64Su2i3pahvt03sVabWlKnZrtDt9Yj2eYvlBQn/gjK7u9cfKvnZQY0Q/ew3Q2W/YQ6hgNhifAmhQysxykfV8aS8xOeWyxf5bE9G3vOpyDhBz4H0JT0kNELMSk38r6gvnCNHo95D2RU6qVpCk57GSH0gunOtHbGchYqStTJcB4UkvdYz4mPItr+GGWKDuyadY7+b0DBAAFSzF8d7tZEy5oKRGE2HVy4vOOgiZYokJ1uxEyUSE52RMJ3RpOOwihdW47oeRlC007pRpAecNrYFJOH2uVuQzUkHgWGyaylMABd+KONpwag1seI1fhW7PkRgh6xecdjXPrACtYhjjuaVAg9j2cWGR4IbGi04KFKWwZ6wQuGWdbxniOzsJ/F1nwxFrceWbWtANWZ30daWmFNY4OajVbROQkowArAsWxpJcwNaqmpVuNkQtsDCrPBHFib6CFDZPvC5aMDM5iW8HzeSwYXCIj2ztle7pH6ItwQBqR3NUWtDmDGUYuzADVEKpvXyOS5pOXN1k9lsdrWsPGtOQUg3fJG8BTcsW6PFKmJVMlla1AaW02ks3SchVHo6m15y4huXF14F22usXroyv3j++/L3/MLFhZWFdUfahTBw+kWvC+t+IF5VOPlI+clHIp7CzgbpU8pkdbT7TARkM8scDoRyFdA6actbw6g0g2p1+x3SmzYHSZstLFoC498kd7nRAw4L0ukg4WwRaa+/J0ll0En6/EFLR2CoasotUgdEO78RPSTEdkbOFQ6/jCs1dpJFyzH8Ay+0H5zezfAV2Fg9+rGndeLSguumXEwEhpsBaJe2jLKOPWdyUUQTmBQknT1zW3VVXYGU48MlQEm6g/20NDnP3XmvD7IM3jCz4XycVn0UC6fXOe6NwJ5EphYEOdn4ptEhPhXtwwEua+eC1v/zvBwhRGDjXpcZQ03JH8JY167EFbF/glgVbB6k9fNeDPb4+2sWOlM+lAc2x20M74624v6BY2Ak9OrAilwUvhB+NzztlGC96kDfwbDXi/c526cJ9zORnzaH43PspWZkufOObpfiNtIOLaIwJ5MwNiJJRMhJUr0qZw67IJ5kJPoM40P6yEmWGZsZWWVP3PRkWlwVQNMlpNMYLmDDv7KBJ+4AarOyiWzDTDTwWldjDgd+5J0H7mlBYErIJDkSpeC5ME9qf+m7Vwtei4ukMrRmoXtVFMkibzLhLDmlxfAc2st2l5baTI8oFfPt7dStlf4muzx8sGrISiKObI9bs9vu9jg8kthARLSk7zzEGhDoHh3WZtTpdhIon/bYOgt1uOSGd2gA54C6xkmooAENG20YqlMp8ApXhtuiKiPMSEJQsiYdwwg0Aj+jdP9A9t+D2SBGKlZacyoubAY6FyWx1KpVQSYsMkFx0rUExUSoMoHaXjeQglBXGqccKU45HB62gzmMIO14nSPtEmWWI4I6sKyOrr3qlhVjPJEibVrg4GA0z5CaJ+vomsl6hpZf5Eqa42i4xLWB7ae6wCZTJHzpQuC0qGXCx0V22YeQOZqMFxNV9D2Ckp5S+0mkGnn8afik+qys1UUTgTZHR6+xumpXc32dLWA6nkOkSPajGRcOTdUkFLlsVPmOlYvmjmBkIR0Hosv6qmUepzsDWgq0xsmwBIDEn09yQlx7TfsX0R1xsr66wqkKvvyvV+NVM3vmmeB0sC0iDY0jsMUtyAFuQC19O6upnMn3aDlVwLPdc6Ikw/wuncMW07NdG03FGIrIprjXR2elRsIUhl1j+EMs//zoYI+foBh7w8Xz6B05n3RwCtPA1uUbFHW4nSS4V9jbSRC7sBEK0zMzYkfHDl9XKlcqsxk1av1AEEBXucRSW5rjiaeGLiHeYieO2v0drZoQekMP6WTP9FCiocOkR9AN/UU+4D5JaRIIzzCB2V449vaApJiCiHsvTluIxw+5JAqX3czTDQ1QB6uYbp5Rcxz97fjLOApiY8ENEdnpXsfp4uMBvLMlC6ymRUPLreAIMmKNOADLLHJpIJyRjz1SEZyMFvHHqZHXn1WYViTHvIvYw6HxmoUn/SoC0YP1gMymV9njzXq/XKSW1B0iysmLNNVQaRtlP4xmxYtgdlDv8q74Z/RuGgqC06hD3kuZSPtnXFw8a+V+uP15F25f49utrU5KjIZGuAOilwax97Vsj7O6R450127xDmzHiByBDNiR0Kal8+dqWom3ljvi3kEITwj5pIbMke4MeaGzTdsS94y/xKnQz4j9mC8NebxeTulevPD3ZzKx7zpEBMiTsYtVMqEZqYuCN35yvWgnhYrBOOLFSfv0uSBaemSUdBCx5NtnDcChwdI6gT0M3IJDmSk9LAJaQUJglgUXBEwTPd5D3KU2xoOm21iKtDBkGkYsZiubtDsx1/CGIBH1HYk3x4KLT10AAfMPD3QVj9ZZYTmUcj3JNAh/hObPY8jSyKGEGQg9girjdbGZfbbuH4FIh0VVcAIELUzGiLAk7BlICiNoKiirHVt5goxenZmderInbBrwx9Fhbm4jrTkUnxiYdn8xA9SZLRy37tS7MTGEC3Pz1SuXL35fAnfM4SNoMkFwW03WxWDPEhQdS+s7ubp05aXFs4srC/NafpM+BiKZXSXe1BFb+bkd0p9iWhtYvxF3TUdG0S5GtL47yfZOm/5/31ngOABbFr27hUz82d++9v5JapBwbSDk67vo7qGGYZGJfMK5KHnUyOei2fmneMEY3km0irRZwoWMlLxdwKhfaJS18zJIfdrFfkD8d8SKeEx1S2annX2AbILFcZokJpP0IaIwsak63vJLI5X2k25b9gORtTMzM7PlilusAeFsr499ZVMmbR9WVPWS9FqFlnt7m2PPtH8w4DJmMqokTKgslfFwRve1NOglGFgfvkT41jAR7abQMpUYJhg/OxqT0AFQpt29XpUR7WGb4pZvJnTE6nJXmZpSOf60KGn3hquNjrBWS1EHUSAkdopQu3mAOQ3YQ2Ill1noSLHqRRIdJrIzvJvWsarPOU2V6/pDS71mDIXMG861I602Wxz3JPQDQ7QxI2T+QipqwiDip27U1Dk4xn5IowPmI0MVbqSIMMwG8UlUqTY5k4oUR9cU6zVMkPe6QGwowOxSqjj/BQlGksTJu5dIRJME8WHv5thfRe1KNoei7JxbfskglAMmsv+XqrsJZHOuKr39wtA1BzKOPm2uFAODDtEOzeZF4bbaBMXEX8JsDem1Do3ioFppaD4elauAb7Kh+BOHt44JWjX6DYcfCbbW2ZYJ3w8cgOL9w25JRADg+UkL2CqO5YHXep8EDpy3aWMbk8RsE+kxUTJALgMgXDA1ZDJD8wIaZhf8/IJcTgCOrksKsNxTdoUnqQNdNmVl144ZuJlkgW4v2WaMGxljqV38I3i/vR0slzsggQ+E8dgoS7HFz1GREuziqiENqHvNS3I0RRZ0Zr/OecwLACa2AjKA6e7cAFEzVzk4aCL3ei5AI/CeRIGu4Wru7Mm9XC5dfbRUYDmhyXRGfS1tMWdTLgu1lxe+u7BEJIw/YWruquHYBD7YSZm6T4m2Zdb1QiQO5atWvMdmY+2g77E024tZASCOAqIrkxFvOXpPOkbIZ37X8AxJLBCnoyz/r6ScpUYjHW6mKvk2Kle7EGzfeQK0OXWbtLVzFxdHaJlm3lKB8slsqqUwACtwFxopzXMbZhyBfEC1sQbryoVSMt+40CNtE9TGIxd5BLUSgRMcezhRhpMG7cfKkUrJgWz1IKINrrgIISI6dwGxcoE+7YLhSA9vc9qgCY3KSLzMlv0aEs+I1D1vCgb5ZneuGifVGxpSHJmWOiQ7XXvJwjftZqton9AMZgCuAd9w92XnHONnmWy8RGTD9WuOliMperEl90MupWLHb8VZS/ljHxkr9mjTMkUOnjQoe5yo05VOjGNty5RSsrcuaWFZn3GbeaFLZliSZbIox+KwV+/TVVVjqqV0oUx12WKJu/PC3hA17uorezW7cEsdYdkovCyDllLflXH+kiXdYsSpmAK9St/nVjbCCvPU0OzuBTUg2FufC3dvfGuyM0EEgaNtDTU3YQ+QPM69NHf5wsLFKxcC2USicyUdguVWM4emKWlblCVhJARmMLp4rBazNT7jWHhhmWhv7a0kwnf7YiCJCCdlvU3eA2JLRFbmaFbdxExI0lqhghi+Ku8FhnDTKWVqarJxoXjfnF7gXTM5atDhUFvacCfBorZaCduGefRmGWkjdxj5jGGDY1s5h+D3G0TLQp31vYyQZLQXdJQoI58UmzJm6tacL1o20cCdA1ISaJpQKP0SHWWOlojTtCpJSgnrD356rUnKdam0kqpcJOVoEdWaOmbqwyyXaslOwZN6tN4JOgiFWJsITCgrUesd8b662XDqW7vLxsUhWeeiFSedfYDZ1pYNoz7vJX2QwzFSESto6FgbNTAX3/CqTY12GW06uIq2wdc840Y7IbxN6+rKsl9Qx1RETjn13ij5feb4JEB3ursH9s13oP7HPQ6V75iUPiIjbHyocRnSfUTf6PSpLR7oARysg11TFsDIZCRh7oM3Ri21QLxWdD8ryxm3oJef71lewooDNOV+F26g1I/L6GFYvDm7hFDRteH2mlHp7X5kQJjZbhkxxAmH1TZTRG8KYgggCBA6IcRehE8ZLg2sk3BBAoSc83u9RxWVGDXex6UYhgSM87tsUNhP1cIWjakfqupWXcMlsfk8UG9G/rgfLxXUtMyk3b/kHY4VM3BiWiSu36jweZQCCH4ufrM94JAMm2U+Z03MVwZ9IrZxkdnsai9h48AyJ5gux23Ny0oXSIAnmhe3W2UT5GMFOCK3Xs6QoQ7CyPs7XKlVL10ai6TH0YKoxakNNTqh1Z0UZ3F7JZs7oXOkwCBNn+I5bjifwtXunmDesh+C6GBIfs9ON4VeFmNg6L8i8tY0H3gjrJrSWD4hIiYUmxAIEzC6Q9IptDZfCOZutrQEzA4+9u/5IXt63Q11b8Gpp0OOzb6YTIJgCGL1QpzEPpEUr+YSJ1Cygh7p4gphsQgNcMnwg33bs4RcsDIEuUeu3v1fuFhH7q3+Wl+G8ODwrimPgBIY4V0EfDnA+QGHpr5ERPxvUZBjWrOa8hgtQxYsrPAjZ3JRjHziHHTL9oqhYtPqyj68FuKXgoXX1IEoB8s4fLV6XjUQqIvZIh7lgrUTCc4u1lOVmHAjDkqdTLZkJnUWZlwTBsr1Np5Rxp7kTvlFsUR5xqdxpSqerfO1EyY5y964Q5tttZIL1mKUM055pHFcZYohlSwmKFhhJlSuc88+DR5RtmIySxS06BGyG14Xy20n64GvNIx/DjM/bC2jTMmxST1SHGdrxbSTdZcdOnG2B4OwXikbZKT1h3D004e/OvyZZLzxTaG62z+6g2qBw2Ws09nEGchqylpJLNFm7Fd41pYPMK6iIHSYAGwc+nj5hpeahZwRRnCJt8wUnSgSe1wai6tBYd0P+tIDtjN7R7rb5Ej8nlWcsuYeVz1xRA7FxnmOw3nBi8xk0SfAolz46iQAC3IzJhCH0MrXG2UcB9mzMjaRoKK4ZLMN05aETZUm251I/5b0OTBMHE1CnFbb4zTzHIfiXCSZ5B1Y3XFzdEG6QJoNTdD2vApsPBAL/NybcqY/xJpuMVsmgCTAIHUZcd/z5ampwtINmcxpDqRqeQnUI5OeTcb02NzqsRUZJnJVCJ4Mc1VM5pEASdIE38vqtO4IJLYjl16P/PH8EWI9nIYFe6vdvZ6aWyVrB7tt8AAh//lrbkAt9D0GsK3U7f0AqS1rW1Un9qdO4EPkeiccGyJvTTG7OnvcYnzyg+6mvGPhtErzMn4DDU8GImZJ7X6g2S0Z3whXqiUaXwVfGmwOOv1BVYqj66q0yPfyhibgzpl8IVQZSRNQDleUl/iGlrpp3NMmteiv9p91n4CnBSXit+J+c6faogO2U3dFp12HqGEy2NMW+2Fd0YYO9qpip/mr/dMjupNvqvYe4ROnarOzJ/LdaoN2Jh530Zh0vHLZA4JyK9/F2NDQbI/GjnxVczpnTx7VGSHrqqriUtdi83G6s3ZMrf8lCH/mAmpcLqWGNur4d26P6wR35BV3klmLXLMh3Wh7N8fvDwPd2dtVzQRyH/5CDRSGHuBWkl9mE13gilc/YzbbXhzm3YHQqiv/uoZRW8GVw1V1j42coxGi0Gr+FzdvKn2Rbi/ekisLb99W7saa3FzMmdZm3uBou0OCemMwU6XTclyq2zuGUvzV/kn/voe6FtpexX3DbigVdYL+y7fmptMnyiNOV0j7iifkf9+CGFFnw1UcrFgvNrQs/3Kz2zrgst31YnNyiAEIMg33SWnLNNHz2/8fb3mUtg=="
# --- END_EMBEDDED_ASSETS ---


# --- STACK PRESETS & METADATA ---

STACK_PRESETS = {
    "swift": {
        "name": "iOS / macOS (Swift, SwiftUI, Xcode)",
        "language": "Swift",
        "build_cmd": "swift build",
        "test_cmd": "swift test",
        "lint_cmd": "swiftlint",
        "file_ext": ".swift",
        "sample_contract": "```swift\npublic protocol ExampleServiceProtocol: Sendable {\n    func execute() async throws -> String\n}\n```",
        "bug_env": "  - OS: iOS 18.x / macOS 15.x\n  - Toolchain: Xcode 16.x / Swift 6.0",
        "research_quirks": "* **Concurrency & Memory:** ARC weak/unowned, Task isolation, Sendable, BGAppRefresh.",
    },
    "ts": {
        "name": "Web / Node (TypeScript, JavaScript)",
        "language": "TypeScript",
        "build_cmd": "npm run build",
        "test_cmd": "npm test",
        "lint_cmd": "npm run lint",
        "file_ext": ".ts",
        "sample_contract": "```typescript\nexport interface ExampleService {\n  execute(signal?: AbortSignal): Promise<string>;\n}\n```",
        "bug_env": "  - OS: macOS / Linux / Windows\n  - Runtime: Node.js 20.x / 22.x",
        "research_quirks": "* **Event Loop & Memory:** Microtasks, uncleaned event listeners, SSR hydration.",
    },
    "python": {
        "name": "Python (Standard / Pytest / FastAPI)",
        "language": "Python",
        "build_cmd": "python -m py_compile scripts/*.py",
        "test_cmd": "pytest",
        "lint_cmd": "ruff check .",
        "file_ext": ".py",
        "sample_contract": "```python\nclass ExampleService:\n    def execute(self) -> str:\n        return \"OK\"\n```",
        "bug_env": "  - OS: macOS / Linux / Windows\n  - Python: 3.10+ / 3.12+",
        "research_quirks": "* **Async & Types:** Asyncio event loop blocking, GIL limitations, type hinting.",
    },
    "dotnet": {
        "name": ".NET / C# (ASP.NET, MAUI, Console)",
        "language": "C#",
        "build_cmd": "dotnet build",
        "test_cmd": "dotnet test",
        "lint_cmd": "dotnet format",
        "file_ext": ".cs",
        "sample_contract": "```csharp\npublic interface IExampleService {\n    Task<string> ExecuteAsync(CancellationToken ct = default);\n}\n```",
        "bug_env": "  - OS: Windows 11 / macOS / Linux\n  - SDK: .NET 8.0 / 9.0",
        "research_quirks": "* **Async & GC:** ConfigureAwait(false), ThreadPool starvation, IDisposable pattern.",
    },
    "generic": {
        "name": "Generic / Other Technology Stack",
        "language": "Source Code",
        "build_cmd": "make build",
        "test_cmd": "make test",
        "lint_cmd": "make lint",
        "file_ext": ".src",
        "sample_contract": "```text\nfunction execute(): Result\n```",
        "bug_env": "  - OS: macOS / Linux / Windows\n  - Runtime: Project runtime",
        "research_quirks": "* **Concurrency & Resources:** Thread safety, race conditions, memory lifecycle.",
    },
    "undecided": {
        "name": "Undecided / Idea-First Research",
        "language": "TBD (Determined in Mode 0 via /kb-research)",
        "build_cmd": "echo 'No build command configured yet (run /kb-research)'",
        "test_cmd": "echo 'No test command configured yet (run /kb-research)'",
        "lint_cmd": "echo 'No lint command configured yet (run /kb-research)'",
        "file_ext": ".txt",
        "sample_contract": "# Архитектурный контракт и интерфейсы будут определены по итогам RESEARCH-001\n",
        "bug_env": "  - ОС: TBD\n  - Стек: TBD (в процессе исследования)\n",
        "research_quirks": "* **Архитектурные ограничения и критерии выбора стека:** будут зафиксированы в ADR-0001.",
    },
}


# --- ASSET UNPACKING ---

def unpack_assets(source_repo_path: Path = None) -> dict:
    """
    Unpacks embedded assets from base64/zlib.
    Falls back to local filesystem if running in source repo and bundle is empty.
    """
    if EMBEDDED_ASSETS_B64:
        try:
            compressed = base64.b64decode(EMBEDDED_ASSETS_B64.encode("ascii"))
            raw_json = zlib.decompress(compressed).decode("utf-8")
            return json.loads(raw_json)
        except Exception as e:
            print(f"⚠️ Error unpacking embedded bundle: {e}")

    # Fallback for local repository development
    repo_root = source_repo_path or Path(__file__).resolve().parent
    templates_dir = repo_root / "templates"
    scripts_dir = repo_root / "scripts"
    skills_dir = repo_root / ".agents" / "skills"

    if templates_dir.is_dir():
        assets = {}
        for tf in templates_dir.glob("*.md"):
            assets[f"00_Templates/{tf.name}"] = tf.read_text(encoding="utf-8")
        graph_json = templates_dir / "graph.json"
        if graph_json.is_file():
            assets[".obsidian/graph.json"] = graph_json.read_text(encoding="utf-8")
        for sname in ["kb_lint.py", "kb_release.py"]:
            sfile = scripts_dir / sname
            if sfile.is_file():
                assets[f"scripts/{sname}"] = sfile.read_text(encoding="utf-8")
        if skills_dir.is_dir():
            for sdir in sorted([d for d in skills_dir.iterdir() if d.is_dir()]):
                skill_md = sdir / "SKILL.md"
                if skill_md.is_file():
                    assets[f".agents/skills/{sdir.name}/SKILL.md"] = skill_md.read_text(encoding="utf-8")
        workflows_dir = repo_root / ".github" / "workflows"
        if workflows_dir.is_dir():
            for wf in workflows_dir.glob("*.yml"):
                assets[f".github/workflows/{wf.name}"] = wf.read_text(encoding="utf-8")
        if assets:
            return assets

    raise RuntimeError("Cannot find assets. Both embedded bundle and local templates directory are unavailable.")


# --- GENERATORS FOR AGENTS & REPO RULES ---

_RULES_BODY = ("## Docs-as-Code (13 Disciplines)\n"
    "Language: {lang}\n"
    "1. Read `SPEC.md`, `docs/00_Index.md`, `docs/Onboarding.md` at session start; sync `SPEC.md`/`README.md` (Living Spec).\n"
    "2. Kanban: move cards with date `(YYYY-MM-DD)`.\n"
    "3. Roadmap: mark `[x]` + link `[[Specs/.../TASK-XXX|TASK-XXX]]`.\n"
    "4. ADR & Rejected-ADR: log all decisions incl. rejected (`status: rejected`).\n"
    "5. Research: worst-case tests; record discarded prototypes in `RESEARCH-XXX`.\n"
    "6. Devlog: write entry at task/session end with next step awaiting user command.\n"
    "7. Obsidian: wikilinks `[[...]]` + tags.\n"
    "8. Permalinks: NEVER move `TASK-XXX`/`BUG-XXX` to Done/Archive.\n"
    "9. Regression-First: failing test BEFORE fixing any bug.\n"
    "10. QA: checklists `- [ ]` in `docs/05_Testing/`, separate from Plans.\n"
    "11. Graph: 7 Obsidian color groups (White/Purple/Cyan/Yellow/Orange/Red/Green).\n"
    "12. Git: Remote/Local/None + Trunk-Based docs + Feature Branching.\n"
    "13. Single-Task Barrier: `/kb-implement` executes ONE task; stop tool calls on complete, never auto-chain.\n")


def _rules(doc_lang: str) -> str:
    lang = "Documentation/Devlog **Russian**, code/commits **English**." if doc_lang == "ru" else "All documentation **English**."
    return _RULES_BODY.format(lang=lang)




_3MODES = (
    "## 🔄 3-Mode Discipline & Workflow\n\n"
    "**Mode 1 -- Planning (`/kb-plan`):** STRICTLY NO CODE CHANGES. User approval before writing plan docs.\n"
    "**Mode 2 -- Task Spec (`/kb-task`):** STRICTLY NO CODE CHANGES. `[NEW]`/`[MODIFY]`/`[DELETE]` contracts + DoD.\n"
    "**Mode 3 -- Implementation (`/kb-implement`):\n"
    "```bash\n{test_cmd}\npython3 scripts/kb_lint.py --path docs\n```\n"
    "Auto-complete: spec->done · Living Spec sync · Kanban+date · Roadmap `[x]` · Devlog · kb_lint · git push · STOP tool calls (Stop & Yield).\n\n"
    "Single-Task Barrier: strictly ONE task per `/kb-implement`. Never auto-chain next tasks. Stop tool calls on completion.\n"
    "Anti-Echo: NEVER reprint entire files in chat; emit link + 3-5 bullets + next step.\n"
    "Senior Partner: flag risks, propose alternatives. Rejected ADRs: `docs/03_Decisions_ADR/` (`status: rejected`).\n"
)


def _gen_rule(title: str, p: str, s: str, l: str, extra: str = "", tail: str = "") -> str:
    st = STACK_PRESETS.get(s, STACK_PRESETS["generic"])
    return f"# {title} for {p}\n\nStack: **{st['name']}**{extra}\n\n{_rules(l)}\n{_3MODES.format(test_cmd=st['test_cmd'])}{tail}"


def generate_gemini_md(p: str, s: str, l: str = "ru") -> str:
    return _gen_rule("GEMINI.md -- Google Antigravity & Gemini CLI Rules", p, s, l, " | Full Guidelines: `AGENTS.md`", "\nSkills: `/kb-plan` `/kb-task` `/kb-implement` `/kb-complete` `/kb-bug` `/kb-adr` `/kb-research` `/kb-release` `/kb-lint`\n")


def generate_windsurfrules(p: str, s: str, l: str = "ru") -> str:
    st = STACK_PRESETS.get(s, STACK_PRESETS["generic"])
    return _gen_rule(".windsurfrules -- Windsurf Cascade AI Rules", p, s, l, f" | Build: `{st['build_cmd']}` | Test: `{st['test_cmd']}`")


def generate_clinerules(p: str, s: str, l: str = "ru") -> str:
    return _gen_rule("Cline / Roo Code AI Rules", p, s, l, " | Read `AGENTS.md` and `docs/Onboarding.md` first.")


def generate_claude_md(p: str, s: str, l: str = "ru") -> str:
    st = STACK_PRESETS.get(s, STACK_PRESETS["generic"])
    return _gen_rule("CLAUDE.md -- Claude Code Guidelines", p, s, l, f" | Build: `{st['build_cmd']}` | Test: `{st['test_cmd']}` | Lint: `python3 scripts/kb_lint.py --path docs`")


def generate_cursorrules(p: str, s: str, l: str = "ru") -> str:
    return _gen_rule("Cursor Rules", p, s, l, "\nYou are a **Senior Engineering Partner**. Read `AGENTS.md`.")


def generate_copilot_instructions(p: str, s: str, l: str = "ru") -> str:
    return _gen_rule("GitHub Copilot Instructions", p, s, l, " | Read `AGENTS.md` for full guidelines.")


def generate_agents_md(project_name: str, stack_key: str, doc_lang: str = "ru") -> str:
    stack = STACK_PRESETS.get(stack_key, STACK_PRESETS["generic"])
    rules = _rules(doc_lang)
    return f"""# 🤖 AGENTS.md -- AI Agent Guidelines & Operating Modes

> **Project:** {project_name} | **Stack:** {stack['name']}
> **Spec:** [[SPEC|SPEC.md]] | **KB:** [[docs/00_Index|00_Index]] | **Onboarding:** [[docs/Onboarding|Onboarding Guide]]

---

{rules}
### 🎨 Obsidian Graph Color Scheme & Tagging
| Color / Category | Obsidian Path / Query | Tags | Description |
| :--- | :--- | :--- | :--- |
| ⚪ White / Light | `file:00_Index`, `file:Devlog`, `file:SPEC` | — | Entry points & root navigation hubs |
| 🟣 Purple | `path:01_Architecture` | `#arch` | System architecture, contracts & modules |
| 🔵 Blue / Cyan | `path:03_Decisions_ADR` | `#adr` | Architecture Decision Records |
| 🟡 Yellow / Amber | `path:04_Research` | `#research` | Platform research, benchmarks & quirks |
| 🟠 Orange | `path:02_Tasks` | `#task` | Backlog, Roadmap, Plans & Task Specs |
| 🔴 Red | `path:02_Tasks/Bugs` | `#bug` | Defects, bugs, RCA & regression tests |
| 🟢 Green | `path:05_Testing` | `#testing` | Acceptance testing & E2E UX checklists |

---

## 🛑 Single-Task Execution Barrier (No Auto-Chaining)

- The command `/kb-implement <TASK-XXX>` authorizes work **strictly on that single task specification**.
- Even if subsequent tasks are listed in plans, backlog, or Devlog, the agent is **strictly prohibited** from starting their implementation without an explicit user command (e.g. `/kb-implement TASK-YYY`).
- "Next Step" sections in devlogs, plans, and summaries are developer guidance only and are **never** an execution mandate for the agent.
- Once task verification and commit are complete, the agent must **cease all tool calls immediately** and return control to the user.

---

## 🔇 Anti-Echo Response Protocol

When modifying or creating files on disk:
1. **STRICTLY PROHIBITED:** Dumping complete file contents or repetitive code blocks into chat responses.
2. **REQUIRED RESPONSE FORMAT:**
   - Clickable file link: `[FileName](file:///absolute/path/to/file)`
   - Concise 3–5 bullet summary of what changed and key architectural decisions
   - Next actionable step or prompt for confirmation

---

## 🧠 Senior Engineering Partner Standard

You are a **Senior Engineering Partner**, not a passive assistant:
1. **Critical Review:** Evaluate against best practices ({stack['language']}, Clean Architecture, Zero Dependencies).
2. **Constructive Challenge:** Flag flaws -> justify consequences -> offer 1--2 robust alternatives.
3. **User Confirmation Required (Mode 1 & 2):** NEVER write plan/spec docs without explicit user approval.
4. **Rejected ADRs:** Document discarded directions (`status: rejected`) in `docs/03_Decisions_ADR/`.

---

## 🔄 The 3-Mode Development Cycle

### 🟡 Mode 1 -- Planning (`/kb-plan`)
**🚨 STRICTLY NO CODE CHANGES.** Research, Q&A, critical review. User confirmation before any plan doc.
Output: `docs/02_Tasks/Plans/PLAN-XXX-<slug>.md` + Kanban Backlog card.

### 🟠 Mode 2 -- Task Spec (`/kb-task`)
**🚨 STRICTLY NO CODE CHANGES.** File contracts + verification plan.
Contracts: `[NEW] path/to/file{stack['file_ext']}` / `[MODIFY]` / `[DELETE]` with signatures and DoD.
Output: `docs/02_Tasks/Specs/<Phase>/TASK-XXX-<slug>.md` + Kanban In Progress.

### 🟢 Mode 3 -- Implementation (`/kb-implement` -> `/kb-complete`)
Code strictly per approved spec. Run:
```bash
{stack['build_cmd']}
{stack['test_cmd']}
python3 scripts/kb_lint.py --path docs
```
Completion checklist: spec->done · Kanban->Done(date) · Roadmap `[x]` · Devlog · kb_lint 0 errors · git push · STOP tool calls (Stop & Yield).
"""

# --- STARTER DOCS CUSTOMIZATION ---

def customize_templates_for_stack(template_name: str, content: str, stack_key: str, today_str: str) -> str:
    stack = STACK_PRESETS.get(stack_key, STACK_PRESETS["generic"])
    content = content.replace("2026-09-19", today_str).replace("2026-09-26", today_str)

    if template_name == "TEMPLATE_TASK.md":
        # Replace sample contract with stack-specific contract
        contract_marker = "```python\n# Ключевой контракт\n```"
        if contract_marker in content:
            content = content.replace(contract_marker, stack["sample_contract"])
        contract_target = "```csharp\n// Пример ключевого интерфейса или фрагмента контракта\npublic interface IExampleService\n{\n    Task ExecuteAsync(CancellationToken ct);\n}\n```"
        if contract_target in content:
            content = content.replace(contract_target, stack["sample_contract"])
        # Replace build & test command
        content = content.replace("<!-- команда сборки, Exit code 0 -->", stack["build_cmd"])
        content = content.replace("<!-- команда запуска тестов, 100% pass -->", stack["test_cmd"])
        content = content.replace("`dotnet build` или `./gradlew test`", f"`{stack['build_cmd']}`")
        content = content.replace("`dotnet test`", f"`{stack['test_cmd']}`")
        content = content.replace("path/to/file.ext", f"path/to/file{stack['file_ext']}")
        content = content.replace("Path/To/NewFile.cs", f"Path/To/NewFile{stack['file_ext']}")
        content = content.replace("Path/To/ExistingFile.kt", f"Path/To/ExistingFile{stack['file_ext']}")
        content = content.replace("Path/To/OldFile.cs", f"Path/To/OldFile{stack['file_ext']}")

    elif template_name == "TEMPLATE_BUG.md":
        # Replace bug environment and test paths
        env_marker = "* **Окружение:** <!-- ОС, версия, стек -->"
        if env_marker in content:
            content = content.replace(env_marker, f"* **Окружение:**\n{stack['bug_env']}")
        legacy_env = "  - ОС: Windows 11 Build / Android Version\n  - Стек: .NET SDK / Gradle Version / Runtime\n  - Сеть/Конфигурация: Localhost / Wi-Fi / VPN"
        if legacy_env in content:
            content = content.replace(legacy_env, stack["bug_env"])
        content = content.replace("tests/path/to/test_regression.ext", f"tests/path/to/test_regression{stack['file_ext']}")
        content = content.replace("path/to/file.ext", f"path/to/file{stack['file_ext']}")
        content = content.replace("path/to/file.cs", f"path/to/file{stack['file_ext']}")
        content = content.replace("tests/Path/To/RegressionTest.cs", f"tests/Path/To/RegressionTest{stack['file_ext']}")

    elif template_name == "TEMPLATE_RESEARCH.md":
        # Replace sample research code and platform quirks
        quirks_marker = "<!-- Поведение подсистемы в фоне, энергопотребление, жизненный цикл, лимиты -->"
        if quirks_marker in content:
            content = content.replace(quirks_marker, stack["research_quirks"])
        legacy_quirks = "* **Поведение в фоне и энергопотребление (Doze / WakeLock):** ...\n* **Поведение при сбоях сети и роуминге:** ...\n* **Потокобезопасность и нагрузка на память/CPU:** ...\n* **Ограничения прав и безопасности ОС:** ..."
        if legacy_quirks in content:
            content = content.replace(legacy_quirks, stack["research_quirks"])
        content = content.replace("```python\n# Экспериментальный код или бенчмарк\n```", stack["sample_contract"])
        content = content.replace("```kotlin\n// Пример проверочного кода или сниппета решения\n```", stack["sample_contract"])

    return content


def detect_project_stack(target_dir: Path) -> str:
    """
    Эвристический детект стека по маркерным файлам в корне проекта.
    Возвращает ключ стека из STACK_PRESETS ('swift', 'ts', 'python', 'dotnet', 'generic').
    """
    if not target_dir.is_dir():
        return "generic"
    if (target_dir / "Package.swift").is_file():
        return "swift"
    if (target_dir / "package.json").is_file():
        return "ts"
    if any((target_dir / f).is_file() for f in ["pyproject.toml", "requirements.txt", "Pipfile", "setup.py"]):
        return "python"
    try:
        if list(target_dir.glob("*.sln")) or list(target_dir.glob("*.csproj")):
            return "dotnet"
    except Exception:
        pass
    return "generic"


def handle_readme(target_dir: Path, project_name: str, doc_lang: str = "ru"):
    readme_path = target_dir / "README.md"
    if doc_lang == "en":
        docs_block = """

---

## 🧠 AI Agent Documentation & Discipline (Docs-as-Code)
This project uses the Docs-as-Code knowledge base and strict 3-mode workflow for AI agents:
* **Documentation Vault:** `docs/` (open as Obsidian Vault).
* **Universal Agent Rules:** [AGENTS.md](AGENTS.md).
* **Knowledge Map (MOC):** [docs/00_Index.md](docs/00_Index.md).
* **Integrity Linter:** `python scripts/kb_lint.py --path docs`.
"""
    else:
        docs_block = """

---

## 🧠 Документация и дисциплина AI-агентов (Docs-as-Code)
В проекте развернута база знаний Docs-as-Code и строгий 3-режимный регламент работы с AI-агентами:
* **Каталог документации:** `docs/` (открывается как Vault в Obsidian).
* **Главный регламент агентов:** [AGENTS.md](AGENTS.md).
* **Карта заметок:** [docs/00_Index.md](docs/00_Index.md).
* **Проверка базы знаний:** `python scripts/kb_lint.py --path docs`.
"""
    if readme_path.is_file():
        content = readme_path.read_text(encoding="utf-8")
        if "AGENTS.md" not in content and "Docs-as-Code" not in content:
            readme_path.write_text(content.rstrip() + "\n" + docs_block, encoding="utf-8")
            print("📝 Appended Docs-as-Code section to existing README.md.")
    else:
        new_content = f"# {project_name}\n\nProject repository.\n{docs_block}"
        readme_path.write_text(new_content, encoding="utf-8")
        print("📝 Created root README.md with Docs-as-Code section.")


def handle_gitignore(target_dir: Path):
    gitignore_path = target_dir / ".gitignore"
    obsidian_rules = """
# Obsidian Workspace (preserve graph.json)
.obsidian/*
!.obsidian/graph.json
"""
    if not gitignore_path.exists():
        gitignore_content = """# System & IDE
.DS_Store
Thumbs.db
.idea/
.vscode/*
!.vscode/settings.json
""" + obsidian_rules
        gitignore_path.write_text(gitignore_content.strip() + "\n", encoding="utf-8")
        print("📁 Created .gitignore (with Obsidian graph retention rules).")
    else:
        content = gitignore_path.read_text(encoding="utf-8")
        if ".obsidian" not in content:
            gitignore_path.write_text(content.rstrip() + "\n" + obsidian_rules, encoding="utf-8")
            print("📁 Appended Obsidian retention rules to existing .gitignore.")


def create_starter_docs(target_dir: Path, project_name: str, stack_key: str, assets: dict = None, force: bool = False, idea: str = None):
    stack = STACK_PRESETS.get(stack_key, STACK_PRESETS["generic"])
    today_str = date.today().isoformat()
    docs_dir = target_dir / "docs"

    # 1. SPEC.md (Root)
    spec_path = target_dir / "SPEC.md"
    if not spec_path.exists() or force:
        is_undecided = (stack_key == "undecided")
        spec_status = "discovery" if is_undecided else "active"
        if is_undecided:
            concept_text = idea.strip() if idea else "*Краткое описание продуктовой идеи, решаемой проблемы и целевой аудитории (зафиксировано для исследования в Режиме 0).*"
            arch_text = (
                "* **Статус стека:** Не определен. Требуется провести первичное исследование через команду агента: `/kb-research выбор-стека-и-архитектуры`.\n"
                "* **Сборка проекта:** `TBD (после завершения RESEARCH-001)`\n"
                "* **Запуск тестов:** `TBD (после завершения RESEARCH-001)`\n"
                "* **Проверка базы знаний:** `python3 scripts/kb_lint.py --path docs`"
            )
        else:
            concept_text = idea.strip() if idea else "*Краткое описание назначения проекта, решаемой проблемы и целевой аудитории.*"
            arch_text = (
                f"* **Платформа и технологии:** {stack['name']} ({stack['language']})\n"
                f"* **Сборка проекта:** `{stack['build_cmd']}`\n"
                f"* **Запуск тестов:** `{stack['test_cmd']}`\n"
                f"* **Проверка базы знаний:** `python3 scripts/kb_lint.py --path docs`"
            )

        spec_content = f"""---
id: SPEC
title: "Мастер-спецификация: {project_name}"
status: {spec_status}
type: specification
created: {today_str}
updated: {today_str}
tags:
  - spec
  - master
  - {project_name.lower().replace(" ", "-")}
---

# 🚀 Мастер-спецификация: {project_name}

> **Проект:** {project_name}  
> **Стек:** {stack['name']}  
> **Связанные документы:** [[docs/00_Index|00_Index]], [[docs/Onboarding|Онбординг]], [[docs/02_Tasks/Kanban|Канбан]], [[docs/02_Tasks/Roadmap|Дорожная карта]].

---

## 1. Концепция и цели проекта
{concept_text}

---

## 2. Архитектура и стек технологий
{arch_text}

---

## 3. Этапы разработки
План реализации разбит на фазы в [[docs/02_Tasks/Roadmap|Дорожной карте]]:
* **Фаза 1: Инициализация и MVP** -- Базовый каркас и проверка сборки.
* **Фаза 2: Основная функциональность** -- Ключевые пользовательские сценарии.
"""
        spec_path.write_text(spec_content, encoding="utf-8")

    # 2. docs/00_Index.md
    index_path = docs_dir / "00_Index.md"
    if not index_path.exists() or force:
        tpl = (assets or {}).get("00_Templates/TEMPLATE_INDEX.md", "")
        index_content = tpl.replace("[Название Проекта]", project_name).replace("2026-09-19", today_str) if tpl else f"# {project_name}\n"
        index_path.write_text(index_content, encoding="utf-8")

    # 3. docs/Onboarding.md
    onboarding_path = docs_dir / "Onboarding.md"
    if not onboarding_path.exists() or force:
        tpl = (assets or {}).get("00_Templates/TEMPLATE_ONBOARDING.md", "")
        onboarding_content = (
            tpl.replace("[Название Проекта]", project_name)
            .replace("2026-09-19", today_str)
            .replace("dotnet build", stack["build_cmd"])
            .replace("dotnet test", stack["test_cmd"])
        ) if tpl else f"# Onboarding: {project_name}\n"
        onboarding_path.write_text(onboarding_content, encoding="utf-8")

    # 4. docs/Devlog.md
    devlog_path = docs_dir / "Devlog.md"
    if not devlog_path.exists() or force:
        tpl = (assets or {}).get("00_Templates/TEMPLATE_DEVLOG.md", "")
        devlog_content = tpl.replace("2026-09-19", today_str) if tpl else f"# Devlog: {project_name}\n"
        devlog_path.write_text(devlog_content, encoding="utf-8")

    # 5. docs/02_Tasks/Kanban.md
    kanban_path = docs_dir / "02_Tasks" / "Kanban.md"
    if not kanban_path.exists() or force:
        kanban_content = f"""---
kanban-plugin: basic
---

# 📋 Канбан-доска: {project_name}

> **Теги:** #tasks #kanban #planning  
> **Связанная дорожная карта:** [[Roadmap|Дорожная карта]]  

## 📥 Бэклог (Backlog)

<!-- Начните с создания первого плана через команду агента /kb-plan <название> -->

## ⏳ В работе (In Progress)


## ✅ Готово (Done)

- [x] Инициализация структуры базы знаний Docs-as-Code ({today_str}) #docs

## 💡 Идеи и гипотезы (Icebox / Future Ideas)

- [ ] [Идея 1]: краткая формулировка задумки или гипотезы #idea
"""
        kanban_path.write_text(kanban_content, encoding="utf-8")

    # 6. docs/02_Tasks/Roadmap.md
    roadmap_path = docs_dir / "02_Tasks" / "Roadmap.md"
    if not roadmap_path.exists() or force:
        roadmap_content = f"""---
id: ROADMAP
title: Дорожная карта разработки (Roadmap)
status: active
type: roadmap
created: {today_str}
updated: {today_str}
tags:
  - roadmap
  - planning
  - milestones
---

# 🗺️ Дорожная карта разработки (Roadmap): {project_name}

> **Теги:** #roadmap #planning #milestones  
> **Связанный канбан:** [[Kanban|Канбан-доска]]  
> **Первоисточник:** [[../../SPEC|SPEC.md (Мастер-спецификация)]]  

---

## Фаза 1: Первичный MVP и проверка сборки
**Цель:** Создание базового каркаса проекта и проверка сборки/тестов.  
*Сформируйте концептуальный план первой фазы через команду `/kb-plan`.*

---

## 🔮 Перспективные направления (Future Horizons / Later)
*Идеи и гипотезы, находящиеся на стадии осмысления. Прорабатываются через Режим 1 (`/kb-plan`).*

* 💡 **[Идея 1]:** Краткое описание проблемы и ценности.
"""
        roadmap_path.write_text(roadmap_content, encoding="utf-8")



# --- GIT SETUP ---

def setup_git(target_dir: Path, git_choice: str):
    """
    Handles git initialization according to user choice: 'local', 'github', or 'none'.
    """
    if git_choice == "none":
        print("⏭️ Git setup skipped.")
        return

    # Check if git command exists
    git_cmd = shutil.which("git")
    if not git_cmd and sys.platform == "win32":
        # Check standard Windows paths
        win_candidates = [
            r"C:\Program Files\Git\cmd\git.exe",
            r"C:\Program Files\Git\bin\git.exe",
            os.path.expandvars(r"%LOCALAPPDATA%\Programs\Git\cmd\git.exe"),
        ]
        for cand in win_candidates:
            if os.path.isfile(cand):
                git_cmd = cand
                break

    if not git_cmd:
        print("⚠️ Warning: 'git' executable not found in PATH. Skipping automated Git operations.")
        print("   You can initialize Git manually later with: git init")
        return

    is_git_repo = (target_dir / ".git" / "HEAD").is_file()

    if not is_git_repo:
        try:
            subprocess.run([git_cmd, "init"], cwd=str(target_dir), check=True, capture_output=True, text=True, encoding="utf-8", errors="replace")
            print("📦 Initialized local Git repository.")
        except Exception as e:
            print(f"⚠️ Git init warning: {e}")

    # Prepare .gitignore if not present
    handle_gitignore(target_dir)

    # Scope git operations strictly to target_dir
    git_env = os.environ.copy()
    git_env["GIT_DIR"] = str((target_dir / ".git").resolve())
    git_env["GIT_WORK_TREE"] = str(target_dir.resolve())

    # Initial commit
    try:
        subprocess.run([git_cmd, "add", "-A"], cwd=str(target_dir), env=git_env, check=True, capture_output=True, text=True, encoding="utf-8", errors="replace")
        res = subprocess.run([git_cmd, "commit", "-m", "feat: initialize docs-as-code harness"], cwd=str(target_dir), env=git_env, capture_output=True, text=True, encoding="utf-8", errors="replace")
        subprocess.run([git_cmd, "branch", "-M", "main"], cwd=str(target_dir), env=git_env, check=False, capture_output=True, text=True, encoding="utf-8", errors="replace")
        if res.returncode == 0:
            print("✅ Created initial Git commit with Docs-as-Code harness (branch: main).")
    except Exception as e:
        print(f"⚠️ Git commit notice: {e}")

    if git_choice == "github":
        print("\n🐙 GitHub Remote Setup Instructions:")
        print("   1. Go to https://github.com/new and create a new repository.")
        print("   2. (Do NOT check README, .gitignore or license options).")
        print("   3. Run the following commands to link your repository:")
        print(f"      cd \"{target_dir.resolve()}\"")
        print("      git remote add origin https://github.com/<your-username>/<repo-name>.git")
        print("      git push -u origin main\n")


def deploy_ci_workflow(target_dir: Path, ci_provider: str = "none", assets: dict = None):
    if ci_provider == "github":
        wf_dir = target_dir / ".github" / "workflows"
        wf_dir.mkdir(parents=True, exist_ok=True)

        # 1. kb-lint.yml
        wf_lint = wf_dir / "kb-lint.yml"
        if assets and ".github/workflows/kb-lint.yml" in assets:
            wf_lint.write_text(assets[".github/workflows/kb-lint.yml"], encoding="utf-8")
        else:
            wf_lint_content = (
                "name: Docs-as-Code Knowledge Base Audit\n\n"
                "on:\n"
                "  push:\n"
                "    branches: [ main, master ]\n"
                "  pull_request:\n"
                "    branches: [ main, master ]\n\n"
                "jobs:\n"
                "  kb-lint:\n"
                "    runs-on: ubuntu-latest\n"
                "    steps:\n"
                "      - name: Checkout repository\n"
                "        uses: actions/checkout@v4\n\n"
                "      - name: Set up Python\n"
                "        uses: actions/setup-python@v5\n"
                "        with:\n"
                "          python-version: '3.11'\n\n"
                "      - name: Run Knowledge Base Linter\n"
                "        run: |\n"
                "          python scripts/kb_lint.py --path docs\n"
            )
            wf_lint.write_text(wf_lint_content, encoding="utf-8")

        # 2. release.yml
        wf_release = wf_dir / "release.yml"
        if assets and ".github/workflows/release.yml" in assets:
            wf_release.write_text(assets[".github/workflows/release.yml"], encoding="utf-8")
        else:
            wf_release_content = (
                "name: Release Automation\n\n"
                "on:\n"
                "  push:\n"
                "    tags:\n"
                "      - 'v*'\n\n"
                "permissions:\n"
                "  contents: write\n\n"
                "jobs:\n"
                "  build-and-release:\n"
                "    name: Build & Publish Release\n"
                "    runs-on: ubuntu-latest\n"
                "    steps:\n"
                "      - name: Checkout Repository\n"
                "        uses: actions/checkout@v4\n"
                "        with:\n"
                "          fetch-depth: 0\n\n"
                "      - name: Set up Python\n"
                "        uses: actions/setup-python@v5\n"
                "        with:\n"
                "          python-version: '3.11'\n\n"
                "      - name: Verify Knowledge Base Integrity\n"
                "        run: |\n"
                "          python scripts/kb_lint.py --path docs\n\n"
                "      - name: Execute Project Build Hook\n"
                "        run: |\n"
                "          if [ -f \"scripts/build_release.sh\" ]; then\n"
                "            bash scripts/build_release.sh\n"
                "          elif [ -f \"scripts/build_release.py\" ]; then\n"
                "            python scripts/build_release.py\n"
                "          elif [ -f \"package.json\" ]; then\n"
                "            npm ci && npm run build\n"
                "          fi\n\n"
                "      - name: Inspect Artifacts & Verify Checksums\n"
                "        id: release_meta\n"
                "        run: |\n"
                "          mkdir -p dist\n"
                "          python scripts/kb_release.py --version ${{ github.ref_name }} --ci-mode\n\n"
                "      - name: Publish GitHub Release\n"
                "        uses: softprops/action-gh-release@v2\n"
                "        if: startsWith(github.ref, 'refs/tags/')\n"
                "        with:\n"
                "          name: Release ${{ github.ref_name }}\n"
                "          draft: false\n"
                "          prerelease: false\n"
                "          body_path: dist/RELEASE_NOTES.md\n"
                "          files: |\n"
                "            dist/*\n"
            )
            wf_release.write_text(wf_release_content, encoding="utf-8")
        print("✅ Deployed GitHub Actions CI workflows (.github/workflows/kb-lint.yml, release.yml).")


# --- INSTALLATION ORCHESTRATOR & INFRASTRUCTURE HELPERS ---

def get_agent_rule_specs(target_dir: Path, project_name: str, stack_key: str, doc_lang: str):
    return [
        ("all", target_dir / "AGENTS.md", generate_agents_md(project_name, stack_key, doc_lang), "root AGENTS.md (Universal Agent Standard)"),
        ("gemini", target_dir / "GEMINI.md", generate_gemini_md(project_name, stack_key, doc_lang), "GEMINI.md (Google Antigravity & Gemini CLI)"),
        ("cline", target_dir / ".clinerules", generate_clinerules(project_name, stack_key, doc_lang), ".clinerules (VS Code Cline & Roo Code)"),
        ("claude", target_dir / "CLAUDE.md", generate_claude_md(project_name, stack_key, doc_lang), "CLAUDE.md (Claude Code CLI)"),
        ("cursor", target_dir / ".cursorrules", generate_cursorrules(project_name, stack_key, doc_lang), ".cursorrules (Cursor IDE)"),
        ("copilot", target_dir / ".github" / "copilot-instructions.md", generate_copilot_instructions(project_name, stack_key, doc_lang), ".github/copilot-instructions.md (GitHub Copilot)"),
        ("windsurf", target_dir / ".windsurfrules", generate_windsurfrules(project_name, stack_key, doc_lang), ".windsurfrules (Windsurf Cascade)"),
    ]


def deploy_infrastructure(target_dir: Path, assets: dict, stack_key: str, today_str: str) -> tuple:
    docs_dir = target_dir / "docs"
    tpl_dir = docs_dir / "00_Templates"
    tpl_dir.mkdir(parents=True, exist_ok=True)
    tpl_count = skills_count = 0

    for rel_path, content in assets.items():
        if rel_path.startswith("00_Templates/"):
            tpl_name = Path(rel_path).name
            customized = customize_templates_for_stack(tpl_name, content, stack_key, today_str)
            (tpl_dir / tpl_name).write_text(customized, encoding="utf-8")
            tpl_count += 1
        elif rel_path.startswith(".agents/skills/"):
            target_file = target_dir / rel_path
            target_file.parent.mkdir(parents=True, exist_ok=True)
            target_file.write_text(content, encoding="utf-8")
            skills_count += 1
        elif rel_path == ".obsidian/graph.json":
            target_file = docs_dir / ".obsidian" / "graph.json"
            target_file.parent.mkdir(parents=True, exist_ok=True)
            target_file.write_text(content, encoding="utf-8")
        elif rel_path.startswith("scripts/"):
            target_file = target_dir / rel_path
            target_file.parent.mkdir(parents=True, exist_ok=True)
            target_file.write_text(content, encoding="utf-8")
            try:
                target_file.chmod(0o755)
            except Exception:
                pass
    return tpl_count, skills_count


def run_linter_audit(target_dir: Path, docs_dir: Path):
    kb_lint_path = target_dir / "scripts" / "kb_lint.py"
    if kb_lint_path.is_file():
        print("\n🔍 Running knowledge base audit with kb_lint.py...")
        res = subprocess.run(
            [sys.executable, str(kb_lint_path), "--path", str(docs_dir)],
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
        )
        if res.returncode == 0:
            print("✅ Linter check passed: 0 broken links, valid YAML frontmatter!")
        else:
            print(f"⚠️ Linter reported warnings:\n{res.stdout}\n{res.stderr}")


def install_harness(
    target_dir: Path,
    project_name: str,
    stack_key: str,
    agent_choice: str,
    git_choice: str,
    doc_lang: str = "ru",
    force: bool = False,
    ci_choice: str = "none",
    idea: str = None,
):
    print(f"\n🚀 Installing Agent Docs-as-Code Harness into: {target_dir.resolve()}")
    print(f"   • Project Name: {project_name}")
    print(f"   • Stack: {STACK_PRESETS.get(stack_key, STACK_PRESETS['generic'])['name']}")
    print(f"   • AI Agent configs: {agent_choice}")
    print(f"   • Documentation language: {doc_lang}")
    print(f"   • Git mode: {git_choice}")
    if ci_choice != "none":
        print(f"   • CI mode: {ci_choice}")
    print()

    docs_dir = target_dir / "docs"
    if docs_dir.exists() and not force:
        print(f"⚠️ Warning: Directory '{docs_dir}' already exists.")
        print("   Existing files will be preserved. Only missing templates and directories will be created.")

    # 1. Unpack assets
    assets = unpack_assets()

    # 2. Create directory skeleton
    dirs_to_create = [
        docs_dir / "00_Templates",
        docs_dir / ".obsidian",
        docs_dir / "01_Architecture",
        docs_dir / "02_Tasks" / "Plans",
        docs_dir / "02_Tasks" / "Specs",
        docs_dir / "02_Tasks" / "Bugs",
        docs_dir / "02_Tasks" / "Releases",
        docs_dir / "03_Decisions_ADR",
        docs_dir / "04_Research",
        docs_dir / "05_Testing",
        target_dir / "scripts",
    ]

    for d in dirs_to_create:
        d.mkdir(parents=True, exist_ok=True)
        # Ensure .gitkeep in empty dirs so Git tracks them
        if not list(d.glob("*")):
            (d / ".gitkeep").touch()

    # 3. Write unpacked templates and scripts
    today_str = date.today().isoformat()
    tpl_count, skills_count = deploy_infrastructure(target_dir, assets, stack_key, today_str)
    print(f"✅ Deployed {tpl_count} templates and Obsidian graph configuration.")
    print("✅ Deployed scripts/kb_lint.py and scripts/kb_release.py.")
    if skills_count > 0:
        print(f"✅ Deployed {skills_count} AI agent skills (.agents/skills/).")

    # 4. Generate starter knowledge base documents
    create_starter_docs(target_dir, project_name, stack_key, assets=assets, force=force, idea=idea)
    print("✅ Created starter knowledge base docs (SPEC.md, 00_Index.md, Onboarding.md, Kanban.md, Roadmap.md, Devlog.md).")

    # 4.1. Handle README.md and .gitignore (non-destructive)
    handle_readme(target_dir, project_name, doc_lang)
    handle_gitignore(target_dir)

    # 5. Generate Agent rule files
    for agent_key, rule_path, content, desc in get_agent_rule_specs(target_dir, project_name, stack_key, doc_lang):
        if agent_choice == "all" or agent_choice == agent_key or agent_key == "all":
            rule_path.parent.mkdir(parents=True, exist_ok=True)
            rule_path.write_text(content, encoding="utf-8")
            print(f"✅ Created {desc}.")

    # 6. Verify knowledge base integrity with kb_lint.py
    run_linter_audit(target_dir, docs_dir)

    # 6.1. CI setup
    deploy_ci_workflow(target_dir, ci_choice, assets=assets)

    # 7. Git setup
    setup_git(target_dir, git_choice)

    # 8. Success banner and instructions
    print("\n" + "=" * 70)
    print(f"🎉 Agent Docs-as-Code Harness installed successfully in '{project_name}'!")
    print("=" * 70)
    print("\n📚 Next Steps for You & Your AI Agent:")
    print("  1. Open the project folder in VS Code / Cursor / Obsidian:")
    print(f"     code \"{target_dir.resolve()}\"")
    print("  2. In Obsidian: Open Vault -> choose folder 'docs/' to view the colored graph!")
    if stack_key == "undecided":
        print("  3. Ask your AI Agent (Start with Mode 0 Discovery & Tech Stack Research):")
        print("     \"Please read AGENTS.md and start Mode 0: /kb-research <исследование идеи и выбор стека>\"")
    else:
        print("  3. Ask your AI Agent:")
        print("     \"Please read AGENTS.md and let's start Mode 1 (Planning) for our first task.\"")
    print("  4. Verify your documentation anytime:")
    print("     python3 scripts/kb_lint.py --path docs\n")


# --- SAFE HARNESS UPDATE ---

def record_devlog_update(docs_dir: Path, today_str: str, doc_lang: str = "ru"):
    devlog_path = docs_dir / "Devlog.md"
    if not devlog_path.is_file():
        return
    content = devlog_path.read_text(encoding="utf-8")
    if doc_lang == "en":
        entry = (
            f"### [{today_str}] — Docs-as-Code Harness Components Update (`install.py --update`)\n"
            "- **What was updated:**\n"
            "  - Note templates in `docs/00_Templates/` refreshed to latest version.\n"
            "  - Standalone utilities (`scripts/kb_lint.py`, `scripts/kb_release.py`) updated.\n"
            "  - AI agent skills in `.agents/skills/` synchronized.\n"
            "  - Obsidian graph configuration `docs/.obsidian/graph.json` refreshed.\n"
            "- **Integrity verification:**\n"
            "  - Link integrity audit performed with `kb_lint.py`.\n"
            "- **Recommended Next Step (Awaiting user command):** Review updated components or resume task work via `/kb-task` or `/kb-implement`.\n\n---\n\n"
        )
    else:
        entry = (
            f"### [{today_str}] — Обновление компонентов Docs-as-Code Harness (`install.py --update`)\n"
            "- **Что обновлено:**\n"
            "  - Шаблоны заметок в `docs/00_Templates/` обновлены до актуальной версии.\n"
            "  - Автономный линтер и утилиты релизов в `scripts/` обновлены.\n"
            "  - Скиллы AI-агентов в `.agents/skills/` актуализированы.\n"
            "  - Конфигурация графа `docs/.obsidian/graph.json` актуализирована.\n"
            "- **Проверка:**\n"
            "  - Проведен контрольный аудит целостности ссылок через `kb_lint.py`.\n"
            "- **Рекомендуемый следующий шаг (Ожидает команды пользователя):** Ознакомиться с обновлениями или продолжить работу через `/kb-task` или `/kb-implement`.\n\n---\n\n"
        )
    if "### [" in content:
        idx = content.find("### [")
        new_content = content[:idx] + entry + content[idx:]
    else:
        new_content = content.rstrip() + "\n\n---\n\n" + entry
    devlog_path.write_text(new_content, encoding="utf-8")
    print("📝 Appended update record to docs/Devlog.md.")


def update_agent_rules_safe(target_dir: Path, project_name: str, stack_key: str, doc_lang: str, backup: bool = True):
    for _, rule_path, new_content, _ in get_agent_rule_specs(target_dir, project_name, stack_key, doc_lang):
        if rule_path.is_file():
            existing = rule_path.read_text(encoding="utf-8")
            if existing.strip() != new_content.strip():
                if backup:
                    bak = rule_path.with_name(rule_path.name + ".bak")
                    bak.write_text(existing, encoding="utf-8")
                    print(f"⚠️ Backed up modified {rule_path.name} to {bak.name} and updated to latest version.")
                rule_path.write_text(new_content, encoding="utf-8")
            else:
                print(f"ℹ️ {rule_path.name} is already up to date.")


def update_harness(
    target_dir: Path,
    assets: dict = None,
    stack_key: str = None,
    doc_lang: str = None,
    project_name: str = None,
    ci_provider: str = None,
    backup: bool = True,
) -> int:
    docs_dir = target_dir / "docs"
    if not (docs_dir / "00_Index.md").is_file():
        print(f"❌ Error: 'docs/00_Index.md' not found in {target_dir.resolve()}.")
        print("   This directory does not appear to be an initialized Agent Docs-as-Code project.")
        return 1

    print(f"\n🔄 Updating Agent Docs-as-Code Harness components in: {target_dir.resolve()}")

    if assets is None:
        assets = unpack_assets()

    today_str = date.today().isoformat()

    # Detect project attributes if not specified
    if not project_name:
        spec_path = target_dir / "SPEC.md"
        if spec_path.is_file():
            spec_txt = spec_path.read_text(encoding="utf-8")
            m = re.search(r'title:\s*["\']?(?:Мастер-спецификация:\s*)?([^"\'\n]+)', spec_txt)
            if m:
                project_name = m.group(1).strip()
        if not project_name:
            project_name = target_dir.name or "Project"

    if not stack_key or stack_key == "auto":
        stack_key = detect_project_stack(target_dir)

    if not doc_lang:
        agents_path = target_dir / "AGENTS.md"
        if agents_path.is_file() and ("Russian" in agents_path.read_text(encoding="utf-8") or "Русский" in agents_path.read_text(encoding="utf-8")):
            doc_lang = "ru"
        else:
            doc_lang = "en"

    print(f"   • Project: {project_name}")
    print(f"   • Stack: {STACK_PRESETS.get(stack_key, STACK_PRESETS['generic'])['name']}")
    print(f"   • Language: {doc_lang}\n")

    # Ensure Releases directory exists (safely preserving any existing releases)
    releases_dir = docs_dir / "02_Tasks" / "Releases"
    releases_dir.mkdir(parents=True, exist_ok=True)
    if not list(releases_dir.glob("*")):
        (releases_dir / ".gitkeep").touch()

    # Refresh templates, skills, linter, graph
    tpl_count, skills_count = deploy_infrastructure(target_dir, assets, stack_key, today_str)
    print(f"✅ Refreshed {tpl_count} templates and Obsidian graph configuration.")
    print("✅ Refreshed scripts/kb_lint.py and scripts/kb_release.py.")
    if skills_count > 0:
        print(f"✅ Refreshed {skills_count} skills in .agents/skills/.")

    # Safe update of agent rules with .bak
    update_agent_rules_safe(target_dir, project_name, stack_key, doc_lang, backup=backup)

    # Record update in docs/Devlog.md
    record_devlog_update(docs_dir, today_str, doc_lang)

    # Refresh CI workflow if requested or already existing
    if ci_provider == "github" or (target_dir / ".github" / "workflows" / "kb-lint.yml").is_file():
        deploy_ci_workflow(target_dir, "github", assets=assets)

    # Run kb_lint audit
    run_linter_audit(target_dir, docs_dir)

    print("\n" + "=" * 70)
    print("🎉 Docs-as-Code Harness components successfully updated to latest version!")
    print("=" * 70 + "\n")
    return 0


# --- INTERACTIVE CLI WIZARD ---

def prompt_user_input(prompt_text: str, default: str = "") -> str:
    default_hint = f" [{default}]" if default else ""
    try:
        val = input(f"{prompt_text}{default_hint}: ").strip()
        return val if val else default
    except (EOFError, KeyboardInterrupt):
        return default


def run_interactive_wizard(args) -> tuple:
    print("""
╭──────────────────────────────────────────────────────────╮
│  ✨ Agent Docs-as-Code Harness Installer                 │
│  Zero-Dependency AI Agent Discipline & Obsidian Vault   │
╰──────────────────────────────────────────────────────────╯
""")

    # Try reopening TTY if piped through curl
    if not sys.stdin.isatty():
        try:
            if os.name != "nt" and os.path.exists("/dev/tty"):
                sys.stdin = open("/dev/tty", "r")
            elif os.name == "nt":
                sys.stdin = open("CONIN$", "r")
        except Exception:
            pass

    target_dir = Path(args.target_dir).resolve()
    default_name = args.name or target_dir.name or "MyProject"

    # 1. Project Name
    project_name = prompt_user_input("? Enter Project Name", default=default_name)

    # 2. Documentation & Agent Communication Language
    print("\n? Preferred documentation & agent communication language:")
    print("  [1] Russian (Русский) [Recommended for RU teams]")
    print("  [2] English")
    print("  [3] Custom language (type name)")
    lang_choice_input = prompt_user_input("Select [1-3]", default="1")
    if lang_choice_input == "1":
        doc_lang = "ru"
    elif lang_choice_input == "2":
        doc_lang = "en"
    elif lang_choice_input == "3":
        doc_lang = prompt_user_input("Enter language name", default="ru")
    else:
        doc_lang = "ru"

    # 3. Technology Stack
    if getattr(args, "idea", None) and not args.stack:
        detected_stack = "undecided"
    else:
        detected_stack = detect_project_stack(target_dir)
        if args.stack and args.stack != "auto":
            detected_stack = args.stack
    stack_choice_map = {"swift": "1", "ts": "2", "python": "3", "dotnet": "4", "generic": "5", "undecided": "6"}
    detected_num = stack_choice_map.get(detected_stack, "1")

    print("\n? Select Technology Stack:")
    print(f"  [1] iOS / macOS (Swift, SwiftUI, Xcode) [Target Apple Stack]{' (Detected)' if detected_stack == 'swift' else ''}")
    print(f"  [2] Web / Node (TypeScript, JavaScript, Next.js){' (Detected)' if detected_stack == 'ts' else ''}")
    print(f"  [3] Python (Pytest, FastAPI, CLI){' (Detected)' if detected_stack == 'python' else ''}")
    print(f"  [4] .NET / C# (MAUI, ASP.NET, CoreCLR){' (Detected)' if detected_stack == 'dotnet' else ''}")
    print(f"  [5] Generic / Other{' (Detected)' if detected_stack == 'generic' else ''}")
    print(f"  [6] 💡 Undecided / Idea-First (Стек будет определен через /kb-research){' (Detected)' if detected_stack == 'undecided' else ''}")
    stack_choice = prompt_user_input("Select [1-6]", default=detected_num)
    stack_map = {"1": "swift", "2": "ts", "3": "python", "4": "dotnet", "5": "generic", "6": "undecided"}
    stack_key = stack_map.get(stack_choice, detected_stack)

    # If stack is undecided and no idea provided via flag, ask for idea
    if stack_key == "undecided" and not getattr(args, "idea", None):
        user_idea = prompt_user_input("? Enter your project idea / concept (or press Enter to describe later)", default="")
        if user_idea:
            args.idea = user_idea

    # 4. AI Agent Setup
    print("\n? Select AI Agent / IDE Setup:")
    print("  [1] All AI Agents (AGENTS.md, GEMINI.md, Cline, Claude, Cursor, Copilot, Windsurf) [Recommended]")
    print("  [2] VS Code Cline & Roo Code (.clinerules)")
    print("  [3] Claude Code CLI (CLAUDE.md)")
    print("  [4] Cursor IDE (.cursorrules)")
    print("  [5] GitHub Copilot (.github/copilot-instructions.md)")
    print("  [6] Google Antigravity & Gemini CLI (GEMINI.md)")
    print("  [7] Windsurf Cascade (.windsurfrules)")
    print("  [8] Universal AGENTS.md only")
    agent_choice_input = prompt_user_input("Select [1-8]", default="1")
    agent_map = {"1": "all", "2": "cline", "3": "claude", "4": "cursor", "5": "copilot", "6": "gemini", "7": "windsurf", "8": "generic"}
    agent_choice = agent_map.get(agent_choice_input, "all")

    # 5. Git Setup
    print("\n? Git Version Control Setup:")
    print("  [1] Local Git (Initialize repository & commit initial docs) [Recommended]")
    print("  [2] Connect to GitHub (Local commit + setup guidance)")
    print("  [3] Skip Git")
    git_choice_input = prompt_user_input("Select [1-3]", default="1")
    git_map = {"1": "local", "2": "github", "3": "none"}
    git_choice = git_map.get(git_choice_input, "local")

    # 6. CI Setup
    print("\n? Continuous Integration (CI) Workflow:")
    print("  [1] None (Local-Only / Skip CI) [Default]")
    print("  [2] GitHub Actions (.github/workflows/kb-lint.yml)")
    ci_choice_input = prompt_user_input("Select [1-2]", default="1")
    ci_map = {"1": "none", "2": "github"}
    ci_choice = ci_map.get(ci_choice_input, "none")

    return project_name, stack_key, agent_choice, git_choice, doc_lang, ci_choice


# --- MAIN ENTRY POINT ---

def main():
    parser = argparse.ArgumentParser(
        description="Agent Docs-as-Code Harness Installer",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""Examples:
  python3 install.py
  python3 install.py -y -n MyApp -s swift -a all -g local
  python3 install.py -y -d ../project -s ts -l en --ci github
""",
    )

    parser.add_argument("--name", "-n", type=str, help="Project name (default: current directory name)")
    parser.add_argument(
        "--idea",
        type=str,
        default=None,
        help="Краткое описание продуктовой идеи для Greenfield-инициализации (автоматически активирует пресет undecided, если --stack не указан)",
    )
    parser.add_argument(
        "--doc-lang", "-l",
        type=str,
        default=None,
        help="Preferred documentation & agent communication language (e.g. ru, en, custom; default: ru)",
    )
    parser.add_argument(
        "--stack", "-s",
        choices=["auto", "swift", "ts", "python", "dotnet", "generic", "undecided"],
        default=None,
        help="Target technology stack preset (default: auto)",
    )
    parser.add_argument(
        "--agent", "-a",
        choices=["all", "cline", "claude", "cursor", "copilot", "gemini", "windsurf", "generic"],
        default=None,
        help="AI agent / editor configuration files to generate (default: all)",
    )
    parser.add_argument(
        "--git", "-g",
        choices=["local", "github", "none"],
        default=None,
        help="Git version control strategy (default: local)",
    )
    parser.add_argument(
        "--ci",
        choices=["github", "none"],
        default=None,
        help="Continuous Integration workflow to deploy (default: none)",
    )
    parser.add_argument(
        "--target-dir", "-d",
        type=str,
        default=".",
        help="Target directory where the harness will be installed (default: current directory)",
    )
    parser.add_argument(
        "--non-interactive", "-y", "--yes",
        action="store_true",
        help="Run without interactive prompts, accepting flags or defaults",
    )
    parser.add_argument(
        "--force", "-f",
        action="store_true",
        help="Overwrite existing configuration files if present",
    )
    parser.add_argument(
        "--update", "-u",
        action="store_true",
        help="Update harness infrastructure (templates, linter, skills, graph) safely in existing project",
    )

    args = parser.parse_args()
    target_dir = Path(args.target_dir).resolve()

    # Handle --update mode directly
    if args.update:
        exit_code = update_harness(
            target_dir=target_dir,
            stack_key=args.stack,
            doc_lang=args.doc_lang,
            project_name=args.name,
            ci_provider=args.ci,
        )
        sys.exit(exit_code)

    # Determine whether to run interactively
    is_interactive = not args.non_interactive and (sys.stdin.isatty() or os.name == "nt" or os.path.exists("/dev/tty"))

    # If flags were all explicitly passed, run directly
    if args.stack and args.agent and args.git and args.name:
        is_interactive = False

    if is_interactive:
        project_name, stack_key, agent_choice, git_choice, doc_lang, ci_choice = run_interactive_wizard(args)
    else:
        project_name = args.name or target_dir.name or "MyProject"
        if args.idea and not args.stack:
            stack_key = "undecided"
        else:
            stack_key = detect_project_stack(target_dir) if (not args.stack or args.stack == "auto") else args.stack
        agent_choice = args.agent or "all"
        git_choice = args.git or "local"
        doc_lang = args.doc_lang or "ru"
        ci_choice = args.ci or "none"

    install_harness(
        target_dir=target_dir,
        project_name=project_name,
        stack_key=stack_key,
        agent_choice=agent_choice,
        git_choice=git_choice,
        doc_lang=doc_lang,
        force=args.force,
        ci_choice=ci_choice,
        idea=args.idea,
    )


if __name__ == "__main__":
    main()
