#!/usr/bin/env python3
"""
🚀 Agent Docs-as-Code Harness Installer
=======================================
Autonomous, zero-dependency installer bringing Docs-as-Code discipline,
Obsidian graph integration, knowledge base linter, and 3-mode AI agent guardrails
to any project in a single command.

Usage:
    curl -sSL https://raw.githubusercontent.com/koudinie101-png/agent-docs-harness/main/install.py | python3
    python3 install.py [options]

Zero external dependencies (requires Python 3.8+ stdlib only).
"""

import sys
import os
import re
import json
import zlib
import base64
import shutil
import argparse
import subprocess
from datetime import date
from pathlib import Path

# Ensure UTF-8 output on Windows consoles
if hasattr(sys.stdout, "reconfigure"):
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass
if hasattr(sys.stderr, "reconfigure"):
    try:
        sys.stderr.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass

# Python version check
if sys.version_info < (3, 8):
    print("❌ Error: agent-docs-harness requires Python 3.8 or newer.")
    print(f"Current version is: {sys.version.split()[0]}")
    sys.exit(1)

# --- BEGIN_EMBEDDED_ASSETS ---
EMBEDDED_ASSETS_B64 = "eNrdvQt3W9d1LvpXVqReC2AAkJQsJ0Etu5RIybzW65CykxySBTaBTXJHIMBgA5RYSWPIdp2012nt2Bk3GW4Txxlt03HOPWfIshTTD8l/gfwL+QM3P+HOb8713HsDoKSkbW5Oj0Xsvddcr7nme85169jMTONavL3TiQZxOn1t4dLVi3PXFhpz80u17faxujpWrVZXu0m7ruhR9Xv0v9XuIBl04rpaPbZy8MuDewefHdyn/z462D94qA7uHd49fPtg//DNg4cHXxy+efjW4V169fjg04PHiv58ePh39IK+PXx3bfXYajcdRINhWldRqxXvDOK2Oq52+r2dXkp/3nZPb6t+/IO4JX+2451+3IrkRzrcifv0ddxe7bbpWV2dnDn5QnXmO9WTLxB4+7axvocRo89BtJnWV7tKVVXU7us/+q2tZEA9DPvxapfnvNo9budcV/mpZmdDDV5SU1MHH9Pc7/HM36hPTVHDj+jL/YNHh+/Si8c05INf0R9fHHxJq/KImz9eo6fU8mdod3APrdwklALcF79RrSr64MvDd9XBY26P0Tw6fOfw7WAkB58rs6ZmySqKXoRjXz2mB0GPGV6tVls9pqrVlzANM/3jaramDj7EOPV+vnH4pjrYVwdfU5ePDz6hOTw8+Org3mpXxvde4ebfozHTHzKCfWpD3VYUvaZhE4zHZlyYGsEmXOGv8eTHZnmpS2qIZf1bGu7dg68O3zGjpWGepGH+2luDh2ZAv6WHPE0MwbR8iyDt8wTu45XMxm5QAaYqHjUN7T49vXvwgH5+gYVw+3DPG8ypmuywfPwpwX2Lhv0ODsd9HA9qfQ8LSjMoLRmsnusM4n43GiS7cVpe7U4ROqwcvEfb/RMspl7GN6kpgVCza0ARmSEjF60Txv+OGZJDLYy+xJ+8Qc/3adnf4Le/A9phOw9/otEDre7R3B7xULED9Ppt+vTB4Ttlmd74UZ18slG5BXueFuwjjIbR6QFGBUQ5fFd6pHdfHv4jPX0nhP+QoNNmHv49jUSa3Mvumx31wT/zUN4CFDUtOP2VxuKvsDgh+F8wqgpYWY8RWMkdHKuoUVR06dwri9cWzl17bWkhR07pXXUiOf1CBmpWDuQhQzeBMgRjb4dAhFSs1Y9BJB1FnP3Oane4084/9CliAAJPWr3tnV437g48uviHj979p/93/93iE3+viFoWz2QkzXwP0BixHgnNfN8QnYfyRp9fAb+vCegv6NcDIVQMZqVWm6adWey245u3zR9rayCpWSr3gd3dHxmMBQa8qVELG65PzMG+oS4yR5yBHxvCUzhPkLXDHzP156P2FZ8dDVLpswkcFzB4BLL8kEkR9fCYT1FI7n7GZERw8ivQYFAXIkQ4FDi01Ppz/yQ1m83tuL8dJcQnNzq9G62tqD9Q1+axx0qd6yS0wSvEFj4EpZOB00F5bXH12Bp6VstxfzdpxfjkYx7+fR43Tsfnhqh8Th8LPP21tBz0+tEmt/xXs8hMgeng4iz+9OBn3I5G6FHQXwjPIfT6Wz2Vd5g7fCHciAEB4d4xm/GhXcH7cmKZoMnJrig+/hl4TAz3QaE17t1FH18xy8AKEn5lqNSvDj7hjj8xpB+I8ncEA1zsCz2SpXjQ36syBnzJJ2NfGB42Fc+IzfyIiQf1/gkj9H1wQwL7OfZRuMUkynL2tQtZgkKPcvTkQ6bjb/KqPcyLATICI4rFu3E/GZCYtB39oNcnSWy902tdj/t0tlr0ImlFHfpTXtK/SbdHwpOlDnVDLUA3DHnqxjcIDv57WyVd4m2DZJOYXHcTMHvdjaS/zVJc0q2S2LfZj9OUfm0kN/npjV53QH+vdvsxv0p63QatwgBzw7/p9E402Joe9Kbxq+G+qsU3B5jSU1HA9eHmavd61F2PuryIICKv8s/bhGRYuk/w3yowhE/uvTVeP484vvcrHNCHjGqEpHZv1O/v/kxN2hVLFRfnQcRMUyZwHzJffZN5kGXgTOou6W25hG3R5DBHVX8JnOYTyxTVw+WHePILms7X/PA+s+JHayJ8omM3cUtZCxalmLZ+zETpaz5WX+lzTOeFzttbJIhYkY0ZdfCt48i/Zeqp6QydEvxLs/+JpglEC0D/HusJPOazdp9P8T7TcF8W+FW2a9fNrw4+rmgxD7Th8F3QCGFuGfr776C+IhNme33I1FfLXkukrPSIBsY7kOtoNXwB5gG2hqd0n88jd3GyZqV9j4YLrfxCzx5sTsucp8znv9KUCGRpN8Vcfke/6TuW0RnTvuae7PhMj5boaqbiOB0DKx38E4vFJD0yStFiVLX0TsMrM+Ue4MRpSvwbpyo8tmPat0I0pvupdOxIvsiAwlcei0Au4iP6X+r1BupcNExjNdeNOntpkvJJWjo3V56segT9ivQmx5a1iqAnLIw5tIFMf5qHBwH5kfDr4JgYWbW5cunK/OL57681VdNQpo2kE4McNXnEMtYCAGYrAOTywncBYSKF80DyZnzK0u8bzNQgfWje/KYIst5sXqDZvM+LvU+z5U3WLInQ1fRQPZ/00wGtb1WtqDVMH9rBPeKxf89a5lG6HH0kg6WmbhfmyzXb1S8K10eraV/xAy0n3ZcjQbBc618fYVxalwMBwX9oUm9q+VKrPKQKKj6cX7NCgc5KF5YWFi57w/yQjR1Elwh/vshjDze9y4fvIWQdwbD7qjlP/LKp5KdHOzHFfcUy3NeMIvdci3i309skht+sjRMK5hdev3glJxfIUysWHPzf5mwcfKnV8kCm2Vcl6a48Ssto8+sjcdfZmerMqYC7msb4+we9Iem8nYB1fvDLJxqhZk+/NnhFywzt1J7vz7S4zdKacK4ChSBgWcfVyvfpf9VLl6rz82t8xg5+zrgIrmBNDOra3PKr1RG2Ie73ASsG+2tAGBqjZWGgvkxKDh7TiGQpRsiwODMO4Y2F5AHbXtzpeGQE3ozmYcTIqizRQ1rHt7Tyfo/fahtFQAUO9jODep+g87m154clYyGpVqwGnV64mQxIrGvHaqac6VnGhsESz8OZcHqDsEFLVv4OHIh4jse+cDg9zoeBs3R9+BOWqO+zMIWNf7ecGTv2xZKNw7t11Zy+vl5N6OTE2ySzyh7SZjcNl+D3/bgTRymd0QlC+OLl+YXvZY8bsArPPTmcVBwxEom2KGa6QrT5yFNxxyn6W8P1p5RuSRqByUl+JED/4Pj99tfqqUdrlXmmfD/KMhcrNy5fXTh3G/+hpVvTouqvmAo+1ta1RwefytdXuuu9qN8mheF2/pO8sPmHj37+BZslDGm+ZwyPcuYIV/DleF2YaQJpq4Y8EC7+K6hP2ajCblArUA8mjNHqxAIMAOb6rS10ANm40IBS0OZalF5P0QjC588ddSkCP7+ED0mgo78K3i/FaRzpIUDu+gUzSj6IvjG2aBBQ4HjaM5CIfqPJQWiMeVjQUOg1L5f8edsn8nqRpBFPlBuJfsGNZk42+HmxzmE7dG2XelF7O9oJG+uHt0nOfcxD/p0REb8w+KKBacHUx6wP3oRoYXGJiNDh2xlzxj2tYDC6iD1xInpUVOGSFPI9+Tp3gmrSbXNmtjHnWe+mmxhAsWAsNl7Ydx9ajSxnWbFwzfo1NQMduxkV9aQrXlHNq52oS/Dpr+WduCV/nR1uyh9LQo7phx3RqcZ83EogpqZwVempgtEwRh7ezfpESk3jymmWLZTnG+YoaAAjTgIvzyfMU3/MJpq7IoU0lxaWF4wd14N7uqEPigb7W1aZGEneYL5rGWlwcqijhZML6rXvWUA+1xFQH+re72nb20NhmJ+IcZ33bDS/enXu8tm5yz7DEjNHdacz3Ey6dbUepUkrFMfeUSOMHqE99p6l/r9huyWECHV8wOfxuPSijtN4ul0Yf5TlFPcP32VZ6ZHBiwcjEUWQ70gYJXxBju2/EkM7/AftfiDB4mzUum5kR/7m9+9+mjOGlBa76qo2SHlf/vPb6uAD/gSbRioBRHl+TyrBzTW2WsKCzGr0lyy9Gc2K1+8zHDWPq6r5XiutRmn1HISmkhM7y+p4m17ZWbz/MWCD8OwzMtICQwTiQw2gpcVWvN67aYZC2omRf0Q8Yi0Y6olThwMQouyq40k7jsZh0JXLZ6/MLc0vXs5pGe6N0zR+TaLeF7JU1q3zmGU3xUJqQAoP31IlRyvVhSGNpfzHl396tgv5vYl+tGqiNwMSbHAIPrz7THNxakqBw4BP9W+cDnlfFFBRJ7+0nlOHnWys+MKK4DDXiJuBntSL/e/3VBNzAzF9XvT237FEfM/SfStZ13Jnc3+k1lT5k/CCERJCLWdWDM7O69GwMwDZdNLrfewOdOkv6EDrBZDZQ3n4jNfoMWs/79JuradJOyEixYCElGOgtIZvieIiCpMoEjAXfH/u0kW10e91B9vRYBD32cnzhiNo9LW3ajeS60kn6V5PLbu+CgmUHzEK/Avb/yFWEDb8vKL93Rw6cV/zH2w1/3oktjzfugC7jNg5Rd8RDRR2znfYjreve52jw1ldaG31uNOP4QYRhzz6OPX7ux+cBoC3qIsvtJ7HnXx2+I/oCArjV0YHVKycQeG8B986Dx8tdE8Xk12cY/Bz6Yt1xbd55x8FpLGpJRkoYcTtF+bmLy3IT5kKrarWgXNCilkdHqQhuG/rESxT/524CuxTZ6N+P4n7GEmoAbKmLb6aR7R10DU1T4bNZ9bT5A/fqihtF9X7Yk7sO1oN5cF4yx9aDPYzKEyCfOY0jrB1JGmrtxv399Q3SY7uJPiTScptkXi4Ncz3v2FF91MQBBKAEGeS91mLof99hI2wSn8bYOo0KFX8D15PTf3ho5/9P35nM/URstLBQ1rg20aLFtmqyRoetrV65fLF75M69VNglLHc3StLk0CWIqmP5DX6R/gaTN+5oBk3uI8+9gc3W7e2WjcYiB5HHAhxussYBFCwEkg/qpmTJ5reKH7tj+JknQ+yGwFkoSOOwFiWikZQIK34Y/iNP4ZTdYl0eOBGYREfQ4E1n5H9U8vKaMh4wa0qVk5lDyrhMx+4kLCQrNQkuHADduJB3CxjMD6an2IHkDHnPmbH1T7cNR7fYbs3D6+b0Mim5Ydm1WLmHiNaicQP/my9uMCXLFOu2V6sfYcBw771Ndt6vwjoiCpp9yjL26qdpIPpilp+Za568vQLsjYHn5Yd1PXhpob4Lxwg9IaT/ULDcM7Irq7Nz1fYm+GgEWfQBn5tZhFTHUZCUB9q/9ebzlWjxNXNaPlFJcuZiLeznY8HYAluhiI9P8oeISz6TXG7aS6kOSoPOFRUaOECnaRMpzmnmxLuF4oq/LFVOOkrz5LquCI77+1eUReycHm9UJXoH4bpK3sEdr9Y1eNPPf2N5vJmsZWD9DTdq7POE9zf+Tr8G9YJ8XmZmZuRB/THVvDxDdW0feXMxpzWDps3Q4fIvgQwFHJVYYHX+sPu9epZQvY2WF9zO0q6zRq9OE+iM+2DOtuPuq2tmGWQ5gY9nDbEp8n4D531XRMt8GMtcnymwiOv+e38MOpUL0EaW97rMtNfird7g1j1+gmpl4zMO8N06y/VxV6LPr3S7ewJhjPOYskOf6JdNZo6IDbrzcxiiPfqEduN77rFuI8D4EWDeTZlX1MlBbDfu9HdSOJOW821ezsDQhYdcXehH8f6zSIpQvpwlpoJtJBOp7azR1oSVCS1eowDJptlFm0+Em8TCw/NIe1viz4C6aZnj9lgZHDGiTp4Jb5l7aHHfOlQGWbfrJi3dyGSvKFGYax1UIMyeDsUsuCSz73NhokTm4ScElPX+yZeieUIi0kyx1/AeYBDaJjVY1lio9i+NUq01sKQ2ILZqQ5S/bnzq4OWeATJG9hJGpjzulJPju+WtUxplvdzSxoUi24eckC8dzJAWTv/HvGO7TvlQzSwfdYbPI4bjugUjehnvBM/YvX5S+04DgQ5WhkZ3vu8V/uBN0hzK5/pMiwEgL2V3TVSyT3pxfwSScL8chx9rO0HUk1WZzeSzuQQxEfMc74W/5AxIWBLxcHl+Sls9PaoQO4w1McQET/E2yj5mPVqd2eLqFddzT6tv4OB4K8NIXkEMerTcjVSaCYmwCdnVMWcni0ICKYzjb1uqXUEUC6W3C5lEPtjWxWH8yAc7Q0OZHngS/cfM3Jx8JslFI+LI36yfs3Ha57+P96LM8KR80yBQgWh5lrYIT3oar+3TpiunlMXelEnLbvAP8ijTIqCsHRNklgWoZ8vc/ge79YjECBeAob+yIVSGaNLkWwi6j/bzkZ4HzMhQkXbo3VVL0a59N+em9P857/Nukik93UYDA2MpNls+Lz0pNSU9q86t7QHgRjpJ1r/00z1azZeieYXRv68NyJtg1V+XwiQCehwcrMFP2e8vCshUYxx4uEtdkpXcsH8nhfbj1W3UbiZMPp7RRHoQYTs8zUJn3K9fybKg4kJYGqsSmIbILpyvU1CgQ12sRpYdbZZt6FhLioj6+I3zu6w7cknaGvFPBPhx355k2qxz3aeLwT1vtSBIaX53ryn7SEvoOzFpgREW6JN82ThHksWheiMLhGYo3XVinhAPF3VBcKMNuiRWi9WP7Hn4GyK5USk2HujgmnyQQ4craCaQkoE2v0ifdxB/Le8loQDLmfA4JU5m6HslLb6yc4gJfbagB5Ggt945rq0cHFhbjkX4q8fV3dXvlf7fu2/r/khAb82yosyb0flGBl9lPkLiYbQbpgnaaDHfB5p2LDjq8cDHtvuRxsDkynl/A2r3c1k0CC2CcC7HmR6vDVcb2iNuTHsd0wW1TYJ+vhbvlg9Rh3Jn9RLh+X7Hsn3q92oP0g2otbAMORutC2ShnmBUDbuCx5chLvhLWvbxZ+kyd9oUUXcsRzZ4d5uRaSe83utqq9lcr70XHS48lbU3Yw5IukpuH1fkNu2OaKDOe9cOAoyuACL9118Ksi9aSMM+F/E/s3M93I+scztOb+6RlsO1c/AaFr+/7MJjrijTpe7uZAMXiHMuEzaoKiavL/6fDQuX7m2sMxnOhfPASEKbPsz9BAcB8v+g2Dq0FrtsipgnP08w+5Z2HfGnyDgU/bltyZnQ6y7kNhL5wzGaKYNaw/ouKyKuK9nLjeu4khaZbqadoabt82vtbVRjMEFKf+Uszu00mRiCdglrgPCBaT+cQSIc/NLvuyWM5UY/7jANb9GA8442LXkwAo4fv6tdneWLNuAI4Xjz951mT2SbPeGBk1bUA724IN/E8nkTbaf6bAEVdIH2xjBtetE3VY+RaCf+ju8+Iilh58cyd7dDOkOLKUhrYEx1VIXvG4WkKumGEJ5Hj/7h7wVz3NlCPd9JCj6BjucvkJiS7PZXI/SLdCJq70bcX95K+4Q/b0QD6rnk078Cr1T1bnOZq9PhHcb08Vsi0gnQbiYdIc3p7ej1pXluqaS6XC7+GsOfxnH7sRUn+d3zoQf6JS/kTTR0TaMfHZnoFT63GyE/ligHiIBOKce4mHADETXRo4JZtlucMwCkd819yhq9/UTj27DIzLCBwLiPWnKa4UBE2Y4o3Wp8Q7XIqXqozBXtyh+wNDSnJz6mGXFT7JUM7db03NXF73EYFEp33VaQDZeIVSU3hN7qWS94Yi9rUfwmVhTlDObsD21amyyZtwf5fIatJj3hoTcmCin+5wEDE2kokhmfKRVi8cyNp2PbA2sJPL+jgfxyOonn1tjTUWiX9lAGUzolF7yezpP0aQbWLmfaYgXc/WAz9vO3mCrx6h18L/YTva1VgG+Mla5rHX0gVVHM6FJ2byKj7Xv5ZELkDZw7nkrX7rWj9pxtbexoS5Fg35y09DX9/2sZSamJiEXP/zM2kA5ZItDkDB9NGfjwXvsrjI7a7pCfIp5+mvbhzz1nYOHPz14ZEH9lPiPpweXJ0IuTAw2vWQCmc1xtoT+9JEzv00udbC0k/KnTVyDThDlbf+dO6uc3KMNr1IXwE9OzKZ/mKBujYjGPweMsqLVR/5DaxoJwr4I1C9NKpUSbMRgH4Ro5hUsYCZH0sXLk4Krl67MzV+au5rjMfLYBRmNUT6L/elaah0ZW6SF+qe0N9rWxvjYtaFG28Sz00GvG6cBI9Ehy88wjyJGIi+9mLvjrvvi+DtDWTI8Z5IeZIG59C2hudbVO8ZkmGFXRnlhH74E8piExcO/5agUCTmR9OTSpdevQgifElVfEiEFcz9gK8l9U3ziR/LeSaWm0IUXKudiqqX7x1leeJ8Zk5AcWHHF0DMzM+tsDnlIJ58E0smsQ5akjP+t8+KEI7iseCErj3R+Q5CKpkrnh+zce4UEw78h+V5NKxsfODUujrCiLOl7DNqlnTWWjd9Xhq3ZIdgl9ewnxmVRm9KURAIYf86DfUs7U2F+PeG7O9SLJkbxpRMZf5WlPfc1t3pgclVsypT4c2yWzH0TOWJ4ZEEJippRjnh4IMdejIEpa+ER5UzabnZb88ql55NnkxbMTEZGhr6Vr7dCauf/zIe66M2+NzKSWxaOicKogiJm2+0We6w/cG0/slvtTIsP1YxZyFlVtJrcqD6Fxfz9L3/Ca5mbRBCGWszrJKHe43XBCt5T2S8sN5nETHDAspzEaONPkjAf5nX5bi+QWfF66b+ynq42UV4oLFG3RVqc83JB3wi8XIUJ9dpnBeC+z0ri5o2b6Lb5Q4xMT8W/MJxpuMY0B8O4ZnPGsSf3hv3Tr5nLjfIq2d14mhR527bYTfahWIWCsCEtnuYcYu+7aMCsQ8z48jxuNnL5R+tvT+IO02wtwDovyZqIwSNPwfAWKlOSxPc2OAeU5IXfcyKdUxFD9Wy0d8eEfYpAazOXx+U+Fw3QZj4fKX2awzzYlJ/JjiRSYCHNL1xcuLYwaTBh9jdxugeMJfkSRZIc/1CHQO0XIpTZmY/zNUVyxUdAbStFgWs6VoTl9wo7TMYUHDEDDNXHDzNGz2zMbD7t3sZNFCSDqtLrcT/ZSFoRAmUUMN55mT528XF11ZTphyUKvBA6Yj1egijG3rSA3tOai403HAFOsqOtvdZPSK2o2ZmZ/0PtRGkaws4Y3gxknWiK9ZdiGgefT5uNkrhZXoDHwtJdFJEBtK97Ge25+9RmijiZAE670Ev3QEtxRpYoCBDhqExjR/2Mz+GXNGoYX79w/q73If940duHLv5A1Mai3dWT+lxMJ5w/ZPbWkdGc447FAwyq1MxTzGa5ks1rL0nOu8Te+IqOxk9RdPDdys21pudZ/LlZGXHNh2nPT5Qbf21h+VpOAqBnE+NfONaHu5OApjFZuQOJGnxazmta48cPozAt939gQ7xxFGfk5sfaLc7mOHpdLMuDWOp7W/zDtrye+Ec81GJ2zjqDSUfQcq8UaaGXb+e9//foYchyCsqjIKTR17JyVVwqEm+pK1O5aA2fSAjXeot5pi3t5iou7GdIfmbJ8ySgJAl79kS7mDon32bLuIyLHlF/sbo66P2FmvLS33VYhzV9PWQy/iPHoTJdn/wP7NoxEQ5V4eBVdGFW6lOmnyYvdrQbMufSZG+kLuomVRkZca/OLS8vzJM+e35u8eLC/JoFbOOrvTJ+eeXL1FKy2kKtp/N+pjf70c5W7QdprwsScQuncPVYq9fpRDtpXCXhgdSpVXo16A/jirzVnoNj4hE3D7d6N67RocbjjaiTxt7zucEgam0hVi/3eitpx691SVXodXZJNyhofKVPsng3zYzBjpD+6PWrm/3ecCcHnN9dsK9WxFN+S/7BBz8cxv09mQjEpLpNfb+ypPiBEFn7EwYc+8MluulFEJjcKWDafvA0wpPZiv+ov7nOD184Nfut2W/PmFd35I87lXGj5XAB6xKBexTDQhzDcZTxeqbxnH7h2zOnn2o8Nn7cDsbQ9mcZ0MmT3/r2t04/w/o86/Y8/63vwHv2xN1nPM3PNIxThCIvPP/tpxiFi/9/xnU4PTNzevZp1iFMgXi2UczOnDo5c/p0dhT4Zy1LGtpJStLQXpZ6gSD1+70bmeeo5HU+aseXhp1BstNJhOzN6LddEt6Xk7/JvJ2tzZ7WH3SSbtEH2TFt9PqtOEfMiDLG/eVBP+5uDpiwztROz377W7OnTj7/7e98a+bU7En9ZT/eiTv+h7Mzrv/rwQvv+XxCclu3FfNpOm1apK2oE0tnL5ya+dapb3175juzdPJPv/AdM65OL43NWFe7d4R35IPEwDmOf2N6mPan15PudNzdVaKXnSJOeUzCpl7t9m504vZmrJCVAa88MnRoOQryWVOSaF+POgnkxlTZFNIK010V36TpxDSdioq67Xw+KiBvoqAjQfnvcb9HDdgk2EEB7ZjIe7eVENjSMKX/YmHaRMXVVR6wOqU6yXo/6u8pRHFxPoqeAInO2zu9/kCle6n9u+f+hLVK/xn1N3eiPkKtaFzbHNtFUJV+e5V+iny70E1hrn7t2vnqt1VvONgZEsSu+m7SbfdupCgUSWwRXpNkQ21FKU2vX6Lea+mgTV9XGB+4muQmn6tyXU7DoL9Xd2fHNah5X5doFXrgXWdWjw0HG9Vv07FUMR2LfnqG0awTAV/KAie+iTB2UmPxD8LwHHjonVIooB1v0AZ1241d7GGj3+sNSrS8/UGjnfTrPO0yovfxhwbQGvbVGWU/qmk5oKS7vbGF/cZH3ziDf2piDfR6p4Up4f00QudQOOBYuZakgFUqK8It+9JLQNLfAJdKZQ/WJHiZT/G/fkwUravCFuFn7hP3XKbtJiRv9JeFq2HWl9GqYU9EifZzgBWhVn0zwONwYyO3ifQdgrUZD253ovW4I0nm8uT4VhxxaRb7hhbLvFxbszGJODg01H5cg3kWK9Y/sbq6Qv9XWvnr1dW11dXbx9e+WS69XD9ufq9NlV+m3/QXP8FPfrF2ohzMU0OvAWWiTsdMxZsszaF1nfep4Z3vEj+QeEnGqUKsBzWngdtvaTGjdgNPCzB/BJarKFWxB1MP/DxLmGpj9di53rDTVt0eDn/UFqlQ3YrvCLnQ+IQ+a7yp6Y1ksFVaZT38WDk4Q/SSRiufEvMYmK8q6mQ5wPZO3C3x52X10hl1ql6IbNfAWggfmYbmCKTB0HA6q8cuJWkK2Y0wYTvqEGVGidocdZUjDapM9JLoFQ2zLPP1Nw2G9Ea7n2wMSjgUGQrQIQKuR26oK/5+JR726U3SUtGwnQyYOXQkmx7wFMOr6cLN6CbFimwLw43FZE+PusrFXhMpjr0oKiEo2g1LC4C0wFQNu1Vto9DAl3hlUhXxSFVvg/a4W+WqwBjMjajPnmU6c/RPWsvPRH+BPV1ZM6u902OaSM/Mkujjj1nYRwgTVmfOWGqiYtoe+9rglXZzM2p7AIXUWbGXf7rFMKNLNgRnPRiOIDJPLQUA9UAmwC4mquMGejS4ZsqMUhqMW0x8rfczMz37feG4fGjBoI4MbPxCWTDlJ+u+CIRHTMbsGx2WydPWZ97gZxadNA3GCvudHIF28uFr8BFJhWEIHQO76JZePnP8+Opq+k3iCybU4TYHCpfxdHW1/c16+UQlOwyisZ1oMz1DwBYvXL6ytHBubnlB92fPdEMf+zNKa4igGjwOUAJ/WN4yQFjnw4k/ajjHO7SCQm+6MRpyE/NG5sKN6DNQYa/ZWkCfsQX8YYYyY0pJdxi7pxtIsm1wf2ekycpMCAuLyIobreLE9TtR8SBWVLhmeSnHh53Lhrt3+5xZ3tswYD8J7MLN+eYZeHj9T+IODYKYHMpHEb6bFedDxY8VHmM1zauj9+PRC4fQ7lwcAZs1O2hsQ5DS6GxW66+NPZuWfqpEa3/r+TtV/HPS/ANU9nvnFbv02sVrixcXL1sEFlN5cRfGjv70XViKkVsjEhtO8jIHk/RW1zzHf2lgwWc1NrSVZj2hxExEfx7My37OIwlmzGztMiFXgPIBMH+QAv1M8EEGIwxRq0U7UPNKeXwhkc2rzqPmIU/UrThwg8S9Lu4CMJ0qEodasXQJcbB0y+/9ThlCU2En7TjdSWi8t7KLf8eTRYrElZo6Rzpf0qYxpHukptJIL0UpxC4MuJbtzu5zAVn3pTGpPdxISd4hKtRqbA5J430CwWy5FZE0ZB1OQmIhWZ04+HhEIdv6CTCkE5chhqMIPP0mcrm5GfdTLa5vRUQpIzry8U2iri2S97aGNL7qjShhE+J21L9OX1eQTr3bY8Erjqg9CYeDXrW1RaIbPfsTSmx61Yq4tF2KjJjgNSlkv8UgjRiYgXwUsdDBmzyO8QKL13H5CcY+BswTrcwIwSRU6hw198E9hWY3uWOnRDOia9y1Wk9ksHSY0lN9o4dQCT5cYxRor+sTfw0CX8V/Vlfxf+Dvo07UbXuWyvWX5XP8Swzi5W/UuOXjp6kcfZunkpqJbNMRbN8Op5d0d4aDMrEcf9U8EUAee8So0xB0DbYJj5yEllSsqBV3h9txnyiqMQEE4lZFDCJnZsuh2ceYDzTTxNflp2EIi1114pYZ8p0TMqpbyZ26bDwR3x27++14IEGGBg14eXjD+1HSqY3iB1f78QZ9eOI/oyo40d0ekVDia3RwMqQzz07GMpP+sMsW37if4R0VRVxzvYdAvvVer0Mbz0YFZimJtdfRppnPPNMHEeRBidaIk8XmoPcD7zLW4ojY9C1LC61d7M4qzLPlkNCYr9hMnAZExnaGWM35pE+b2evvURM65mjLTbye7sAAA1J1RhtR436/nCMdVuKMOp3GdptpW8oyfeqsH7X+Zqe3Xlo9NiUktjzRKuAo0Vwn7Sl4EGi8ij8Gb0TivpK+SlqEqShbRLCi5i4sXL62zH+euzj32jyelt0BBJwGdYkTuOIpmxBqLBT5aSHJTwtNfl5YuLR4eZF/rmUss76abvobbXv1l88c2UIIbmXO6UVBxD/x/HXgCs6xM0/B9t9N2ZjXhcWnw5HBbJLXggibCAHgjLp1x63PBhbGH1I4tw1Mw4BrDHp2o8s5k1ynsdNLk5uwRtYKW9SiVD4plcO2ZmgrFsgaoEz6qNZB0iRppuHHWJhGt9fQllHC53jbV0c1GO+zDICiTzJ9ycfr/d71mGnFdV+g8syIjQJ5i2VVEpW5GSk2Q+b0MwbopE0JRYVQXNg4ipBwFBPwSDqWJzEfcuDvAlwqbB4GWbu1cUcbiMujzANPjWVPiF+QH0cAEU7t3h0Xa2tgBsZu2JDp6fXh5nTU7k+bokN2AlF3r0TMZ4PQn3YOHaChe7LiTH/TnEIuNMU+40DjzDNEO+hHOQ/7WoGpA5RdJhWa4W2IXGiMN/8j9ayxsV1R2+km1NoRvohyvqHuUtoXAB51FAzNI6LX4W7L5aJdsM4fVUqvJySc6Jg/zQuAScLfFfvwtnodqJPcInQluBUQA4ysEdS21SCWUN7SoOqTcdYc+RF+Km8A2tjGVjqpBhxC53dsGLNmuPCD42pxs9sjES03TYAk5B8i4Ihl8kKU4A54soiEPGbGIY+yEYa5978gme3d8CkPVZNDjdt2AQRfuXYe/hA/m/wdXtWjnz0IKzDLUxN1Lr9QriBkuaNtjaPIq28vy+KZ5ZUkP7aGfdZQgWInUsWOiBwPgjYI8uH7NK3yyMJWQ+ZNX5Vsi2let3LW9VvYkMh+pi0R2ltof0crroHLdNKsnFPF/1K8126knqY7dqR+Oz1Qr+kzDRRSkAh+pQ320+qEQnsvhvc7HrRq5SxdJyHKTciXqcbOyGunJ+Q3PfKM8FEjFD6gNJSkb6cW5r/nw6SJQKNA6Mj2tEFI3TbaR/ZVHylIbT6YAVJVcjhWCfaykt3Zir8wlcwqFZ1H2DWp6yKNpGj01/rZo2v+t46CXavF5IxbF0DOi0VWHuz1t40558jnMehVt7cT44iLo5zOSUsxeTnGWHQCcUxHpzzBgol7J8TYpOvUBE3pfQz1Xh9pb59oPL4wHYoIvFH2ELB33JerR3riy4F9M9divLVYN4Z0I+FC1A5KfykQ+iGrF4g4vmNirC3gg/9LXesNoo66ZDTd8yzdwBLdRS7BLQRC+JpAORSqfbvCzzWs71rJyQSXAVABX7R2hUBe8ieY2afAsHCWv/N6mzdmoxKP2odTvkNHIKsMgFal/VZFaZoND9jovoP+6e/f3/2NYqMWgbhzAiYYDcYhGTGNW/LwDvIVy0WTGa8qyDc0339+W13u6eF5oin3843CZSzCi5HLKUrUeU/xmMb9NDtxf7CnvmswV9a1EOHGri9Ee5zdySMqWmReYEIggnLnmRdxrtOhoeCwAlGcZgWNSkv2WxFJA7uFIT3FKx1ShAlr7Dxi2XUNwYxc0fYNlrvH9Vm4iu0bY1YvnE9IsCZMSIfuL2sypi6AjOXmFoKcNLmxA3jG2TmKOgpNiLaYsNmIMKKN7GtU9FOar5pjKKwi160zVx4BJ//w0T/+vWeFZctaQjgYR53B1h4b0xCeypG4g2+M6kuHZGT6Oa6WafjdQbXXrS4PWy3kiW/32nGoHB4Bn7Jbrr47t3S5nl/0o+7gUeF5Gv6YHSM4V14t5FT6QKfCzCrFPMijpruciQoGMqP3uFybsORjt5dGtrC0dGVJDy5kSAEWVdQY0hoYhKwVIzew8azz6RjeH53pHY0xPQP3eGIO4nsXOAK8ISJnQ9zAjQaCFxuN1WN142zsp6wtmejz2lx/k20gV/kN0TqJ3Cdp+czqsSDqvjA438V2cfta1G43Ig2S41PZ7cy2iOoO/kUy6Jl00CeNKt6AzkTdsMFjK+7s0N/Q+ozerZUuuF/YIMiXs7KOO7FbLTjqnnfxL9JReVYpQYwbnK7g+l3oRuud2AicOrhUwu1tZ9SDtVuxByaN0WvqyDTbDo3uilc1zD+nKMHvIZ9OiCFnrdJEv+fCxzk+il/lXf8gvvJqEthC8mu+KIzVt9MlDW3Q4JT1M77jj7+3/r4zvA76h14AuMrQuGQhlHN5I7oU7RFTRwobcjUDpHdU5/2sDn1nppobDnraIf/agMgoiYvZXBOuOXR+2GXcwZGtqoXubkLHmS/IEmcvx/1cSGjK63xjSEW1qAMSdXt9jiwZ9GOOiPPu+6goXfX13MVFJQnTktk9p4tNGkGPYZtana2o0xp2eMQ6zwX1ftmW+erZ6UtnBQQH/SlbWlhFm5v9eFPmybkmfDkNQYUtvaJgKq+gTowegdWmNuMuXO5ohuAF0uR5Mj1VUNqZW2IujAHUb8zeNfV/Ll+5zLhovZEmhYVpTPp0uTPIRLU/aLbInHHNt4a0me7ncJ0oB+SHgtQb/YAdHxIgMzoZh98Q+cIi6BfzSYs2/SIJOLSA3b2KusKzikjvvjYkuev/rxk8gva28HXsToSz/tXtYqxg/eD7QyQf+/uxbivMBGjV1gqCyUQbTtlulibMAYBEXkd0FnaidRzaxHr4qixtbSYDCTEwD4kA8nkMn8pR9UZJ41nz4ch5DRvJM6n0Xdgw4f63huthOx7XFg0jCZ/Ts2g42IqhfIipwX+bqyJ+G7l6rnz4sfzCcdSusb+SLI4lDwKZXCgBdqXWutEOuBcXbgi3Bz5vP8tSrzFS/s7bPGrz0qx18VtZc7zDuCpZqLK6xU3dyhc2t+te3Nqtf/H77D4Uf8X6B+es+ptQsemldguEBNVubCUtOBF5tcpj3dAkIDTALsAqwJgt0aoRXy0ISlrRUIU67FaFnom0U03SasIRolWArALm6rG1SoET6Eb7jEWJovfRDrJxG0K0zlwz2agZ63F8c+Q7VlrOZJfSCyQKws3dGtREshXZ4oya0ZEZ3gea2Jm4fJZ9RKYrEKwFs1c85F0bYWjV7hXty9IIW5DTlzbk3VE2a+KGRevreNaPN+TJKwtz88U7dpRdO/rOTdq98TtYsIveTsryZPdxhNJj98dQiDWOh7RQws0esWc5mUvGXrx70uPT7J60NFu3g1ztDmlZf+77JdN60v1y9B47BjOAByvcNT6jM8V7F96FN2bbtBD9VIdOmAv+Jv2+ypwEP6TTP/ftk+k96fb5XHdtrFvR8V99MnWH2ZM5tjuficsJt79HORCN9IPQaBNkYhoZF+8YB6GPqEZAyE90gqPQdxAe9xU3D1ELuP5WyPRDHqSFkfxYimUDLaAcVTTQJhc0CYnWn4cUoGd7BGy2i5qX4J5xm92FnWy8GboYITG6FKAV506M2GZtjxk52EJMEYETE3FKQKG5prBFqClk6wcAHaxCp40NVqOzxoMSrsDIJABB311xOgLUn7WRCUGmfUUliMQCa95K2u1YO6xMprY2bMSpM2uo0qtn1bS6dFaSUowNBOq+GnIS+gvPK/qE+o8jNk20tobs1AiyfUyuTzvBNUtq5dbqMQ4nOcb1ECq6AI33E337P/k2EP3gzlqtUOfioHI90yDSIXhRYInT+7GyZuPD7Y1QhevsR8oiQ2IQb4Mmpr0+oVHJ9TSI+9xVJiGCcyWpTZgSzE/ysY+1fMxjUTgfNoRtytoQU5MV85lBnqZhkRvrewMOguf+gZLIoh00eAPCJA2Ykno7JF3gU+bmdBLKCLzdKCAKuiQIsEHVTWBv6YXTp0+9MIpXyCRqktRX4qYZ0iSzajD6nTHfb8U328lmnA7yQimohJvkS2fU7MzJ59UU/1NEyPAtbTGHSB+75TWdViWvableO7lxh05FNjGjwJEzCS4PpTZL4F4960hEEJQukT8b+s6xWxZT7mS7t3hrwk9u5cfiTp6FUyn6yhxIM4LCj+wx1RMs/sgdXrd9mS/vPGFo9/jobbMOylsrHc5dlCYSUGW7hl6tnB5Sxhw9bhg7amMAf0VpArlgek1/BeT5PMNMnUmWQYFGavLv2Y755GnSWysgeuEFdgFNWz02dfB+9nL0h/o6qKbi2qe6duo9r1glX3llrqbkIpVh/XXUyLwXXnvF1+CUlntDUsWMcb9cm3IobVP5fWvOuMuxzGWr3v1T9+Q2ab5/ChdMmnu2dGO+guAxz/J37r5Zr46ZdDnughfzrUff4fVJuoWrzHMyh20DsJu36LuVE0C5E2t3cPWWPMAJoQfKfiFnQX+jn+GcyRNrDrb7yIEjtR/0ki6n0KW5WkN+tHtQbWiCsXeZ72c2XklMOFdK5nq8V92NOsNMug6X6rq6h88DtCTyHRUZMO8EWGtzCMdW3NHzB0iDSKYIT5CEmK/DE9bgeTEowVMAdWO7oUsRcYuVWQ8DTAKk/iZIe8xggy4RkdfFvJITOjIxw+mPj+P0gTJWt+HsWbJIG4Uo2I4dhV6aOhZmtpz7mL6j/xYrjgKG/uuKa/C/J1aPnTB/0585dzgWdYWgrknrAI3Nggve0lL2I0/g3Y4HEdB4G8ljiGP0i0cdyWWxIBBTydkXd8XNuDXk+Ox0uL2NenHsQ4q6kkQIdmFvQeWarpw3j1LsAvIqbv/o7xLqo0RCt10d9KEDYqyYjXHQxW3VHrJkbeg39Vogp6JdoXH/GA/Z2tXBN2W8pnzrnWz2ZD6kN3gxJnkbg5iYuN07ehUOOT82m6SAEmUTWvRk5VBlkLg4EBpjXrENsWYsAWx7zzKIqOWI10G4WD4oCgPLhB0fNyhE/xq8WdZ4k4on2PfH2axxOr5c96U29XKuIT1DaZ0Ver+6urw29XK59PKZVRQmvr3Kxaxv/0Xp5W/Q6z79XCuXfakuX3REd1pRhSubLRHCmx7daBjcP6PCch/FR5+tiQ3LsNfyYXaGInqwR1FFpx5TTztxeySF9IV2/W1IIV8qzv/KALdtO4ZGod2RuhsB3FsOw+tNi6x+IkvRQBZBouusEJYbxu0BGjGgIgDY++F6iXDsr0sv13EVEIoJ6Np9qC6Qwzj9XD4T2xP+mwM+YhD6qFn6s8YWr0zbI3urC+hO4MBmi8NA6q4UlTpxeekFhg0EUYR5idMcuMSg1WArVlvJ5hbB1xyhO9xeJ5VRYJyPOh2UjWhdR5tZIa2m3AtqCnA8WgERh50m1WlU4yq66UTJXIGykXnv2UR1PXhZHGVrMwVWBwvP2htCc4MxNRSVxvTIC/8pSIYyVeUGMMaqT3kTYRGlGZ/Gkp3MdnSzFDyrMEkPCVS5PDKlZCxhz2IgBwMiw4JNW8G6ZRL+w9WzbZ4sLzUvueXXZQTHdD2O5bz5HRnPVZ9gB0KmWn4q263G5AC6Z+pMcWVtgzZFn3ttd6NnTuSruIe+PlPx69jRea5jzMFD/vrmgJfONGFSgriOEYEuiKuKU8mEVlELE8QdZfNLaj3u9BCHTiQC9ATbIzG+bgQCZrZGK6MrJJ3Q12VdPoHNABhvizVFOVlT16JN/enlExX9VxV/oiTTcf3CQDD6jrQ+VeOHSVuV4tpmTZ3AhdgzM7PfOsGiIBCI4xFRPEBxWRNUYm7bWnucuoCiTUjc5g51Ub8CejcCU72dcTrXaCwscqowkuRxDp4Gu7w5/Bt58K1hvZ+B50co4K2FXc66s01Wp1mjzTSz/F6Ij60DR5o/CuuSOLde5oYr1cbay7dsL3foBUe/ugUbU5zPqw2bHRV1i6EszmO/eGeTVCESiw6jv7f6BKiSt8m2amPZnasEAtPGdm0zhpaYtM0gWfAHfO9b7u5M+HrEYtB0b9GTOG1FO3FJOiqbRcif0exacOb2ql2QSbB5nEeHPn6l/Vq7mWrZAtrzymRK64QUKaOwFhkG18bLNay+omcXWqev/ma5QifP5+UfZqBcVsAMqGbj7Yab1PwcqsW3EfvNodwxwigLwCEmddo2lSvG5zzK6DXJlHeYZiV4NyJFctDLDcOfLinXw86gPmmhsuFvAxGycOV5GNs23Cx6jLEHj+9kKrWOq0WkMUJGam1QPCceBiNZg41G2v6LMWu9yRzfWdB6+pjEQhEKn0mOHCtD5iUd8UuNFHgKKnE8pdQzuqZBsVSYKfo5WegpSPI4qtkhqIBgBCBL+jSnKPhedtoIygUJ6yYpxcFNpEhVJuzzaEJyvkvmjhb4KNb4NPJxvi/mnGFfIbssEMaLXV6C9tCwWL+CAzyTuqPsYm1LPfOR4SdE9Wc8ZtoQ2QIDs2gjMo/eR5/xFnx6hIiVcFVGhSiiuJ37cJQSUkgpjB1hNJ4ymlCrQh7tjkvKbltjAScMXplZGwUNV8j5sPhBHlx5VPBRpzHoyUwyJzZfyihDxUaA1KVjNlBwZfqW34FXCWmlXj21dqeoYJ9jICuWJayNcX16kcocXKyXtzLuS71GdVm9sZ9iNvgS/4790MQB1d1W+PGMuIeXlmwEiDvFVs5x9RXCmBpTii2UFCXlArqARPm6S+KzWlUBp+MCesWIblLEAPkInE6XkbKczrYbxenwQZbTuUYTGZ1t/qdldNyN43au1yfkdtKwmOX5fYxqaviehjOR+TFh4zudx/I+D/az8r6gR7A+B/uPzfqCrpjNhV1N5nzCm/hSZcdz6jOn2prvhNg1lkVlEHE8iwpGPoY7ue/GMqfgZBv6OQadnpDkmMsC+JQ+xRUYfvtCr1aBYWG74IaEJz1w24HfpSAUWqv97Pgx1f7xt7e59dvymtMBs+/KY31C5SBuIT+zope+ojsxyLPIQjgGIba1TXbmKS2Cec2cnSNeXENB555d5mSNsyR14Ur66wjsRCoQWkwyrUYxE3qf5SW2yWSlybT+j9KZbH9/apXJpmkUiitwrtkyX4XONW4tdfZEtpFUAHOTaMVcYNcurpKn97tQELZrMEZwHS33HqV1Ruz1Fv2/gtQrBo8nEXplJf8TZV75608l3YpZPOXqZoTVcVut7wnpcabMYsqRK1FqyYZpMopssCsjJBu2yUSqYRr/R1EN29+fBdXgjELjjinMKjRezqxHyczTBkp4BtoiM/E4c8A4U/kk+jGeAh0VQkAzcDd61uJ6K4A0knAExEPMokchHj4BkcWoTPr4yETkiQjJExGTPwJByRl/xR9ggr5c6JoO49Vi4m7cx9ZM9FfG3d1G0t3oZSPCKkfKQwggZ4MuC+3ouoUO5uDhiRBmRE0zH761J8yu17UDjC81G9B8QS9Jam/OKYirM2ToCKUs/DBnKfSAMQ0SV/GaFlnyHhFoKAvuYn52LREbRJtycnZv2Rb2fAx67WiP5Xw3b+hppq8a/qjxVyUUh+lJLLghWttSdsVsoz7dkv9TyWT/2IBeL4cv09BPzdNEUhptbllMk4ZBDPi2zs3yihRIpratkxAUp+51aR0Gir5VAEYbsDUY7KReECCHKZksQ5vopytVSC79X7mMwLoMloHUp6fdi+lsLS4LuEb0xma45DLzs2Owf5NQ9LwXjJZbFSRX2I/vTOuX6TShwPQt+o933+dxdT6OkFEnyUnaz60fNbbbeVdOYPHFaTO0XAt7GaFg4G6144hYZ6HMhoG4Tr1I8ipXwVo5AXp4Yu3ObfydtOmvtbW6wg8mq/TblfHKWOIL4ALswUcHX3IY/+OD+4fvIPwfZa0fHNw7/PHBvuJo/s9wUwleSjD9Iy5t/U7Nq1t4HKqY2khuBsvHutKTLJ1IrzktLLdyWsrNLJzuLrto696irfuLtn6ERcvA5AX78PDuwf7hm/T/f3zwkPMi9pH/8IBzHx7a3Aes3l36/Sn+e/gGfYh7YbC6uPblIYDQdw+8JX6kV5+e7BOYN4Isi8fherNQ65aa5csnWWrh9TnJNbfUWibI3vgh3WWXOvKWOvKXOjrCUmdg8lK/d3j38G1ebF7Xw7doQXS6yb5khgg2ytLex4KjJDvSW97OLux9+n+03py+8pj24yf+grpcHsm7OXP0JB9vU17ncn8tKc+UdGkbhlKjylxYgqsYcUm0vmXJwliZWVsxiVhrrAXYZB++Loz2od/aIu2y9jfJjqH0XFxwr5F2EXk6EHKH/9dsNtejdAtVjg4+0hgEdPsCmHdfXYWUvbwVdzqqpMsd0RQuxIMqKvW+glS6Khd8k+yycNB3VHWus9nrE6neRgoSErm6o3o6C1iIP2hdWaZ/L5JycnO1K4kuJHIUd8DAOMWIP8V31UghyXTE5zRdV62KEw56LS++2UYj64gfMboe/AqH7PBH1NM9ySWSi5xwYL8EbinmD3xBk1BE/5rNfTrbYuAj7PIseDU3CL+4oNvMMFF0TCJRYfPi67C4KmGVL4mpI0zmWJBxhAdsUitoxBHrW34jnXA0vhFSl/xGOpVpQiPe9aCZSXjihl6rsk3AcYfPCqbOOli4ROVsPcjcQVLYArtN3k0zgkRIGuomREiNsCpyQpfJFxIv+BowD0Xqyph6VWDEX+1aoZ9mHEqaOhjQ/75r6jzZeyZJs2Ch+xZLm/QFyUVEezYZnhFeRLjyxR5+HUpC/KWpW3ULf/ATH+9uZVcbU450PcyqEYflR2sr6m7Gnd6m/NQLdD3qrkc8Wb7Y4FX+efvgQ2Zen+C/VVyOwfzy3hpvgTbE2zba2n/74Gf03V1O2pMUPyboyC7UDXmTQCj+8NGHd9URd4QavIRr3N7ngwzm+m59akqfc6Vf6ob8wrW1r38meZPSjrfFvsIgcNPbV0QzDt+iGWNEGDdozD63OKGrVOhsyBO+rH5CdvKEoOmJi6woXEGUxNWodT3ajE/YrggKAkUBssmjb3rjG7Vw+ProiwyAbpmxzh8QG/0VzeoztPLoJLIuc/kGdIJveVT4ThYYNu23EJOUyJ2chfpYlUwNyMukYghfPU7f//6f/10d/NLJp/gcvF+GDlZOspgqGfkdnbe2+qXZmbImFE7wLd8xQP/w0Xv/pA5+gQxRFhru8w1+nMyKPjxhjkh8CdLteUi3OeBaQPQBv/tPyEAeJbsQdBYINSehhS+RLJeDq6Whcm7tPvg3D+HNcDO5t5B59uWuwSBfVnrX+bKYl8mXBfRbGRko1/PP/oEWjIC8AZAE4wugNhCHeeTXAf+nbn7Eg5TtcdtUlCbMvYfSzJ0i/PstX8CI5OM3cJWi9LUv0rI5aDzxr1m4fsiS4H6ArKiIuXJzTR28Tzs/StfxT36W9+ul9Wern95XTeeubNayPbkxPabe9Fa8yZoBo1hz5nTjWswJiNPNsiJ0eYPVhL/j9Gvd4edATFG+DPh/yy/z4U8UU1yWfT/D8TYSMhS4B/ShDPx3Ag1HuCm1W5VXsRV1Y1GuVcoFs3G8Wc5NqwDz7tt0cvrk8cEnfL4eHRUnTUkRtILWhK3hXPVg1uEJ+Fxl710aqUfJ8IK41iVjFghYvt7EMDiVjX828Nve1SwWFHdrFhw4mjNbQ6BLPpCCj8yqPXubrX1pnm1z/bJC25quzyLdplLeFbnXV9bTpJ1E/n0OuAOKbWKa95zvRLs9uEFMRVkbS7yygn2eHvT4/oLb1yDwECeg7lfk75IZ9/R6p7c+LeOd5rX0W+K2SlUyNS9hiME90EnbJseN62pqin8QswogJCS+be8M9jwIRY3yayTWHwsnYyizG5G1dXkNzJ9PZ+6q9Y0BcoTxy4I/ogXMG1n4QNvCzA0xPDmM12KlJFIFcRLmZqlJOaBRJ4nSzHcnXRKFiSyxb0SI0XelZbNpBVVfW7oIxEVBTIetwfpI89ADhkWmNcax4GsMi79I5ZPiZBCS81du8YTurJVMXflyWGkltzv17FVfS/riBnvZFztkXCHnPHHJOfqKRk/y2Zi51aaLHX/GdQ6HnCmaXMMlT/ij5B6xYOHdx2jGxiXgub9sFtmIYF6vQz3OTojmRZhrsc16+osuU/K/Dc5ENhevEPg3ccB1tFBGDR12OjmrsNneO0LRbglJuyM07ZYPOedAK8Qm00kWn9zHU1P66ymvEkqQN766ukL/V1r569XV26ura2vfLHNe721+gp/ll+lf/N+xjEuKs4JtOnj2+Fe4GFy5wGe1M1zvJC2rMHYhfP85+60muKNkumJN0hy/cfnKtQXckwxzzHh2qUoXzl8qB+6oP4bfydatzXiATOlVyYHSMsEzOI7G8EOk7sNmGdmD4qgpvasJY8PF6SbxEDzuRVqTuP/S9IuA+dI0BjitoZDwaCvAJBsbQYceCy5wShUw4WfzOv2Hs+ERxTKnJbhzLHPhx7rGV2ZwJq4/AIhCLrY6jV/jIdzMjaPs5i3b+R1HDfPbaUu7uG0tIqrj/G3/JYy0zun3n+jv462SXMon9PNN9BseSTEx/Vcy2GY0kvJ/qjvxP8WTWLAlR/QijvVI/im347+oo/LZ/GrP6jQLKZeGBxnNmrDletxAKTREzcedgjYb4owQKxX/MTVFyM8YLWQK9pt9NoF8UeSuLJ0nqOqcgVpmE7Hp3KOULI85B4W2nxpTqVBAXKkz2uiNEjGkJOfLwnCPo+y0x9XvP/xYHfz08B1t8ZNJwRYDm4+aFoOwGHC/tOX1Sv9tmLSuq0VZ+jL756w78peCJaja95aA0u3hMfSv+FnttsBXqhvp8kV1K8PNUDXP3TUEuEUDgU3p8O/FwEbk5q3Df8QvNjRra5ocgXurXW38cuiiqlWpOiruxcyy/NnYo71B/2kMx1KGgNAnHW1CNi6X0FILu7Hvi67DekNrvYMnKZ4U+qRr00f2SuuNG9c9HNSmY8FR55we0RN/eytHEO4UWgr56DqNC8JxKVPDaOLlb44KhdfA/ZHv1DIjn3yFG/SbUZfGeXe3mb51C12VZKb2fG0G4t0u/1WefFWd5KLp7qBx2u6kLp65os4r56SiNO21Ei7Cx7VSUafFlOEr6eZ1FdGqVNv6it/JI4FRoIpL50fMXe54m3RnnuseL47QKyHh2F4RAlTQKwpsF/ZKLyb3au7Ym7jL18TuYhbXVq+VasETeuHjcfS+zNy0Am/6FP7oZviiWbKXcur95InbGmcTR7OQqyMJ+8rk/ezvVfvD7uS7D6+ionF+YWn+cruDrbx6g8gesuUn9syYbu5HmtA7e5511TT/gi/EkXKtZb5EbmKfraRqgl/H97c0BPtV5xbFIQ7qpC0wczqC6k99uaR3reRRL5YcdXGXbxFDWskRLmbz71fnqxl1I+xW7qJ13LRXaw+3d9KS6QaFuojqD86crFDXuNquEaWtJJH7HXyzrrttNlMzWu6DTDNF+7wrjCV/VlkmAK9MP/7hMIF9TMi7e2cJvXtkSX5Rze1RFe9845o/xieysFmTQ2oMK+4uUJP0UzaWKlQny32ka/jbbSJsyX8lKFS2e6ivFWRlxHVelOZqDfH0k8afdUT6FgvjeXAVbQ39KS0TGSCM1jW3extIBR5slTN2W7OQugSbX2VSJ2Hy66xJxkzK9KZVLH9oi65YOU1XRR2kFO1JXd0UGLpBvFmq5qpM1dxht4PLpGNdL42IT4+2sM+XUlg8NYtelHdlivdy0WAYRMfWEjaQQlOgWyJ9SZ8uGOxBzmTIj0lv99c7AOHVIctVgw42YlTnlkdlTZOZbcz26up3evYvU5BF0MldncopVwkpqJhaxs7irZBPKrwJjyzlqRc9Yxzg1P6xl514m+XsN+Yq3MJCXDthDS6PaEsHLvJvUvKO5wg5Y+lKpWDiZ1xCmYeYmkKfsaTa86uaIZ+xf+XgYqJn3J/ee72fZ/xtr1gpXi+W+HaMDeEoPp8/5+la7knvScrKMbLM5pfzjI4DTNU3ibKRiKCm1PMz/ENdfe3sxcVzJipUsUSpir5kADnA/j6MYcaWwpG4AZv89nVUaZUfqVzkJMe60bvOP8uZdhAGY8nizMwVckFBWqdnY8ozNHmcZWv+U83cLNNkbpaRuo1q6Tp50ul5Lb0J+ms6dnZm4FrUy2EFrg3557fVBVu53eNiLGDW1S27wi4l+07BPudAFSkrBM6b0USAbLqZs7SyRcei09vEvbS3cKGBM5iObP+T94ILsiUU+JY5oSsn8ACB2CMyMyykK6/WM4ZHV+0+GhQvErOxEfNVpewMHI2ojBxm2Tcw+yeIL2tusJ2m0ZAEuEYDRpdGw6YK20vOxRijbzivRZtAwen0OrG8lP3/MIzgkrPp5VcXL14kNMaF52xQk0h7/xuYd6xtBuHMvmVF8cXDuAIz3cEV3P1hB/j6fDWlFUTgyEbc2mshMRkrZa+qobfddtRvp7Ug4jmATPoRnp6jsfejjiLJaqCv7Ag+o9XrR5KMQopBjXBhAxdkpmwXyY1DleaTtAXxa48I2nzcSfCn3PflLAqdaA9XDKJWbkTCfFumhdiOhHtUzbkLC5evLZswOoni/O3/Uud6RL4J1BIPFm9uk5yabG7SyG8rvtvttjKXu9Ofy9gSdRufjbunhV43p6+vV5NuMsANKov0L1q3oo2NXqetY/6aFTV7ihT17R0WTSouYm6zH+1s4eYVB8PC7HXXe7QTAPsK6Y70z3y8G3d6OzA1Yc+APEp/JXeexdEg3YrjgYboIFiguEYCST1NM+sZwLUr/xwcbGmyLta60tLC8sLc0rlXqt/73vcqarEVr/duEi53W2XdgwfOdhG1+x70aS4Vexv/BZTvKVxJ3tcWsn78AzaDmSvgNVSBYAGiBpCFOEt/LJ0/B+LfGqYQFyqKSx8R7JqamrrcUzgbtakpDUy3ttDgD7XQTmKzSAJU1+aWXwUIGReYl9zggYWe780XQtaQHBIghQKkrqmhnwJGmIeZLtgMaHOUNQZYAB5U840dM6Au8zHtQFnAdtRpjLBKEoIQja5wUq2A9Fp7OMC0tKmwlJqu3g4uOeRnFRMUK/Cg5ppN1+0dyPXhZpMRlGu53lYXe5vq7GsX3HSXzs3pbOBNwhlWzCGka4jS3EJDDDDAzQ3bPBFOcNvzwksBia8HQgzqZh+4KoB0S3vyJSh+3tKPi0w/VEmfS/iJZmYa18zJnG6qkn9SyxXVnJltzCELDqoF0TEc5qaNZaPvJeWkonQUNmGjlLLmaqkVLhZUMcssALNFExji840lfZbktxeWTT9lY0HV6McVe+RDMvfhvxP92Y36RFhwb9gU4ezVuL8d8ZrB66aHpGttYxHht+E7BrpEWvrE+xBex1eYgd3QKd2KETeCqjg1gbhkN7B6Hj4KwD1roMiXUmYz2gBXiMQHQA95u1HUgG96BKi57iCpLrS2eoBxEZGM31Snfn/3g9M0rA4hrTUxwENGOj1f3Tjc3gGt40InWsY08JaXr1zj4cRb0W7SY97E7AFDa8ektElx6pBHFDBiIUGjWLC8zTHfJaFrPq4os8/KvNREsKIvUmWqLdU/KoooTjuu9jY29N5kiWPIkfUg2QXj9UlzznaqEz1Wu6/ROecNBQNGDA4tD9FcQ7TVi5jfS01YnlvETlOFS++QKOhDt6PkYu3sVu/QbstgcTLVkGQ+tnGGDYWJw4bmI+y5HvJVSSgyGHsJhI3P6pKZ/1yHo3dh9WY0ntfyMfMAOgge/xBpIf0h0TKpjr/RiW4Y/JiP23LHqgd6folBnqe52HHv9HskKkYd2gc6dKp58KvDN+HBO/hMHTw+fFO9yLkNn+nAg/2Dhy81hcg1TTad2Tp7OK/imt42ocRqdxa8xF5yqhbn+WS2aOGaxVWsmxLYs4VDenNA2KuRCMBPAth8n84af0CvAO1cPwboEfBM++qLaWe4+RKOgb5EtWlLYNA3/Lx0zmCngVFxiyd1OWiVsInxD4eo7J8iV+MURqXpIYkUi3RUbqpl8CkdLF9VU6aEd30KPIGUL0LHpJtLknCpLaqk5Q+ksLbYBSIFlWoGpBkYgYzabfgsmoJm/1PpLcSVfI98B/e9kdlStK9IU9lvjh+V6Xyu3XbXG3hNZho8e5mAvrpJncKYn6/ppDosDC80MTuuc1J2y7TMQjKwmhj5dkIqYRO8GNMbUfJ81EhVdjzqueeYrwtgVd1W4kxEDli5bsQ0K7YJsqwea9bU1WG65YIotaF1JCUlFjOGktLbUZRUF4YPxQi4Pc5FQ3iXaaX20iQlKfXcnOgJWd6krs3PM9/Jk07ql0mnllhIXtnECXiOQ8Cukex3nUtBjyeaAKKJpjBNKWEfqbS3MbihuQ6BH0/xcqOGD66VkNiGs7zAcrlei0uvLV9T65DQiEa1hy3jaQaVDhntYIs04/NzixeX6XuiHzGPfyO5yQt1dW55eWFZs2j9osYF+fneUogF1tEX5WQ2WnOY51uwl9M4tkhdGFj5wEkcThhhoh2W+S+QOdoxJyCr4U6v6120nSOhdbtbEXYrR1Gxg3mqGlwn0DS3M/F9K5quakRrUuOQsi7xmPOENQCpWxcQVXPwnJRpySw1YiJCS9XqDEn0Xr62BFvUjhDY3RSUjngZ7aGINIhE54uiCEO16j7ySBhC/BqHFCmRUzEL0CrwTUchP/hXRFz9g6aQn6rSWeoE0WGM1/jm9+9+qg7el0oXn4ALIuZqsYtdYeQoF9FJ6VKTyfH0TlM6QQ+el5GrNX1i0IgzItrU8bQLWW8SWnZGUKUs8ognK4s+34WBzyMgCtK3t+WZ42UOIMDos1naHtKLjSjplA36zO3s0BE5n9wEIKcI4hRyjT52mPGV9kMShTs6YCQ8bFZi9vfSYeRyPAiq2VsRBGGsrC2YvJe6evH79L/qpUvV+fmX7I4E2EH0TzQNgL5EBzPAE5gYDz7gzefsaVWC1jlp5xndYCraYzj8nVNnhH5xGhO9zUyexnh6PNac08hBsy29mLZ6O/FLzLvEWWlxhENlXzI2h6CPMZhTzM+MRj2GqZlPcpxN9Pc6oQRNAPfaG5tARQ39fTB8e9oo9MRzlE6OlVPvOHeet1mrAhic6RL7YvqVmKzn1Kvd3o1O3KZzdxY2ACzxJJZnYb9ohk68T6t6nY4UhzGlaEim20kVEa5YsLg9ng+KH7nKAz0b9ftJ3GfR3KwVa5Xh3VewwNRIH2Av5jqJkV3QK7lrFREy6yKWDuTGGsOhIr7ngU84gtUklEAUCwYER5wrH8d3ce3lZ8ZHfSLbu2x5HMutUk6HZ8AqbFpT+gDa+rRVTjQZpTjor3mRoM47UXExdwjlIp4XOUbtpWmzXx6Hqqt0FPlAhVxQD0HLLPEQHNwinRxtuAbExxyhCwn6Dcz74P0w0h7UwitWcapstZcse9LTYeqDbRMSxDmOR2REz0KujP2PNx9bzYNrltzseeQBMdb1RMbshKcw1GGmJQ6+jd0fwIDXXLm5pvvdARZ1gbBMEZsrK2P38Lb5vbZm6fkcR+I7Mp4dkyO9VsY3Zpbehi6yklaE9wQ4L8UnrW0CxAchn22RnvhEiMCTxjSHQdLSMffGo9OsmnolcqM7kOLB4VuoTWAC1xF7/ECHTCNW/fDvaJNJGjn4FaPNA/r1EEn2AuAeA3hHygsgXvgzHeYNZe7Lw3eZQayuhqZZobi0mfSi1tT85WLC8gAbgkM1dXFDcHC719a37Ylj7dzFRZgWYNqbu7ooF9ele3w3mWf1IG6gyXpz+erCOcYvrF5zaWFu/tIC/066IqunSDPgvlLhTrShL8jgaNR+iS83OoSvHbGEAmfk97obSX9bzaj1fu96zFd3M1X8lmGymp0+l1XWp3RUuTor1QJoYbVYZhGGsRr6QhMuLuaqxA/68TpbkrfjPnEZSSURhlvR8r7i4pQmr0d/YlX6qWvEeq5XwZ7aqiSgeV+tGlwDlcrqsYDmyQOWllsT/Isa51+SUCbIFhJIa6BhiE1dDcCTCiDafRurJYG/5xyduDwkPhogDvih1OtOhJW2hn24nE0MFTSg3g05/hV3osBsuyyesoUkgj1hIKZgj3J55mH/fnHoG56JX70oRU9Z3PsOxn2NVR5a8GU6sHX6bw8Wmu8ncacNjjzo9zoefuGA94E3rYTVC22vdbFfzRVEyl8m3F3jG5vq09O1Wq1M8/ENuam10Vxl05rWuFraJ0eoyVKGBPONOK+iifjuCwuUlKbFc9cufp/+uHKV2EWnIxVdex1irzK1lkzNdoVub0S0zxssL+jrMkmm394ZjJT87KDGiH72m5Gy3yiHUEBsMb6E0KGdGOWj6nhSXuJzy+WLfLYnI+/5VGSSoOdA+pIestkgZqUm/lfUFy4rR6PeQc0NOqlaQpOeJkh9ILpz7S2xnIWKkrUy3ACFJL3WM+JjyLa/phlik7smnWO3l9AwQABUqx/HO7WxMuaCkRhNh1cuLzjoImWKJCdbsRUlEhOdkTCd0aTrsIoXVuO6HkZQsdG6UaQHnDa2BSTh9hnQ7qSDwDDZtRQmgAs/lPG0YNSaWPEafxe7PkJgh6xecdjX2bMCtYhjjuaVAg9j2cWGR4IbGi04KFKWwZ6wQuGWdbzniOzsJvENnwxF7SeWbWtANWZ30caGmFNY4OajVbROQkowArAsWxdHcwNaqmpVuNkItsDCrPBHFiYGCFDZ3PO5aMDM5iW8H1cxwoXCIj2ztu/2SP0QbwkCUruao9ZGMGMoxdiBm6IUTOvlc1zScubqOrPZ7GpZedacgpBu+CJ5G25YtkaLVcSqZLK0KAwrp9NYuk9CqPR0Nr3kxDcuL3wXbK+5cunK/OL578vf8wsXF64trDnSLoSB0y/6PVj3A/GqwslHyk8+EvEUdjZIn1IjqavdZyIgm1nmcCCUq4DWSUfeGkalGVS7N+iS3rQ+TDpsYdESGP8mucuNHnBYkE6HCWeLSHv9PUkqw24y4A/aOgJDVVNukTog2vmN6CEhtjNyrnD4ZVypsZMsWo7hH3ih/eD0boavwcbq0Y8drROXFlw35WIiMNoMQLu0YZR17DmTiyKawKQg6e4MB2aSVyDl+HAJUJJuYT8tTc5zd97rvSyDN8xsNB+nVR/Hwul1jnsjsCeRqQVBTja+aXyIT0X7cIDL2rmg9f88L0cIEdi412XGUFPyhzDRtStxReyfIFYFmwdp/bwXwx3+/rqFzpQPtWHNcZvAu6ONeLDnGBgJvTqwIheFL4TfDU87JViv2tMF+Hf68S5n+7Tgfiby0+FwfI691Iwsd97R7VLcQdqhRRTmZBLGRiSJCDlJqlflzGEXxJOMRJ9RfEgfOckyYzOjufbaTE+mxXn9mi4hncZwARv+lQ08cQdQm5VNZBtmooHXehpzOPAj7zxwTwsCU0ImyZEoBc+FeVL7S69fLXgtLpLKyIJ17lVRJIu8yYSz5JQWw3NoLzs9WmozPaJUzLc3U7dW+pvs8vDBqiEriTiyPW6tXqfX5/BIYgMR0ZKB8xBrQKB7dFhbUbfXTaB82mPrLNThkhveoQGcA+oaJ6E6z7zvOXUpYid2aJXTLThdyxkBWOAvtruZUDyaE4vGiOmFSye9DnW51yWqbG/WbrrU8aZ1EdWKVi0MGaoUeKcro21ilTHmLCFsWdOSYUj6ID2ndP84dH8E80WMlLC05lRt2C50TkxiqWa7goxcZKSC4mhJjolh5Qjmg7qBFITc0jjlaHPq4+jwIcxhDIvB6xyLkWi3HDHWAW51dO2VWKwYI45UCtOCDwfFeYiVZy/omtlLhqdc5HKOk3iJxNdB/Eh1lUemjPjSheJpkc+EsYsMtQthdzw7KSbu6HsMRT+ldpOIzk8Of5o+yzgra3XRRMLNEQlorqzY1VxbY0ucjisRaZb9ecaVRFM1iU0uK1a+YyWntSUYWchPgOiyvmqZx+nOgJZGrZE0LEUgcfBHOSGuveZBi+iOOOpAXeGUCV8P0avxXTN75t3guLBxIh2OI8HFPcmBdkAtfT22Kd/Ilzw5lcSjZZywyTBfp3PYZrq6baO6GEMRYRX3B+is1EyYwrCLDn8IJeRHezv8BBXBmy6uSO/I+aSLU5gGNjffsKnD/iTRvsJeV4LYg61SmK+ZETtctuhQx3JlvZhzo/YPBAF0qUUstaU5nphs6BLiPrbiqDPY0ioSoTf0oW72TI8kGjpcewzd0F/kA/+TlCaBMBETIO6FhW8OSZoqiPz34sWFePyQS6hw7cc83dAAddCM6eY5NcdR6I6/TKIgNibdEJGt3g2cLj4ewDtbOsFqfDS03AqOISPWmASwzKqXEAVqjj1SIpysGPHHqdEbnleYViTHvIcYyJFxo4Un/SoC4oP1gOyoV9mTCvR+uYgxqVNElJMXaaqp0g7KjxgNjxfB7KDe5W3xE+ndNBQEp1GH3pcyEf/Pufh8tg74Yf/nXdh/ja9YtroxMRoa4RaIXhrkANSyPc7qHjniXrvnu7BhI4IFsmhXQqyWzp+raWOCtSAS9w5CiULIJzVkjrhnyAvdTdqWuG/8Nk6Vf07s2HxzxZP1ckr34oXhP5eJwdehKkCejH2ukgkRSV00vvHX60U7KVQMRhovXtunzwVR22OjtYPIKd9ObACODNrWifRhABkc20zpYZnQihoCxCy4IHCb6PEO4j+1UwA03cZ0pIWh2zCmMVtZp92JuZA0BIlo4Ei8ORZcrOoCCJh/eKAzebTOCu2hlOtJpkEYJiwQPIYsjRxJmIHQY6gyXheb+2fr/hGIdHhWBSdA0MJkrghLwp6BpDCCpoKy2sGWJ8h877Y191NP9oRNA/4kOszNbcQ3pwQQA9NuOGaAOsOG4+edmjkhlnFhbr565fLF70sAkTl8BE0mCG6rybo4DliComNpfThXl668snh28drCvJbfpI+hSGZXiTd1xWZ/bos0n5jWBlZ4xH/TkVG0ixGt71ayudWh/z9wlkAOBJdF722gIsDs7+9+cJIaJFyjCHUDXJT5SAO1yEQ+4VyUfG7kldHs/FMcqG9iQShxsaTlAaSPC0PCvbIxm1jVkL41cgmt2laUFumGFfosHdKxVcu9jYH2PdI6bG5ycJp2IAbkX7046O0krZdIrxT2UMa52dUSmrhTgnh9CTQUY+8eq5mwRLmBluy4RGpulg2taMfxDmMURsGoZFQ3seO24rhtDdyOqiwYhwmJopFeFxfqU/KwFrv8UrOsnc5Byto28BfqkiPuxJOrG4IN2kkLyCbIH9RHYmlJfySKHJtS4W2/pFWJNOuO4C8iomdmZmbLFYdcQzrj/QHOAZugsXHUn+on6fXKpG2Rybhd4cpf4d7YxBAbeyGR2TVMRLuXtAwqy2pXH0NBB0CrTu9GVUZk9sAz77ptuNxTphZYjp8vSrkEIwWMj4xXS1EX0TskposSsL6HOQ3Zs2UlvVnolLHqRxLVJ7oGvNLWIa7pIk2Vi/FDq79uDLzMS891Im1msDTB02j2DJPDjJCxDSmyBUOWn3JTU+fg0PwhjQ6UApnFcP9FhGE2+FKigbWrgFTKOLquWA9kBrbTAyGAwYBdgRXndyJBUpJvefcSiUST4Evs3Rz7Galdyea+lJ1T0i/1hBq+xCb/UvXWgWzOxai3XwQgfQqNg1abmcUgo0PrQ3dHUZi0Nh0ys5TwaMOqrCOqOBhaGpqPx+WY4JtsCsWRw5InBBsbfZDDxgRb62yDhs8Ojlvx2mK3JJID8PxkE2wVx2Ah2mCXBDSct2lj05SEehOhc6QkjlzmRrhgasRkRuZzNM0u+HkhuVwOHF2XzGGlDdkVnqQOUFqXlV09ZuBmkjx6/WSTMW5sbKwOzRgjK9krvXI5HxKwQhiPjbIUW/xTFambLi420hh7173kVFMcQ1dk0LmqeYHJxMRAZjLdnRsi2ukqB3UdKSwiF1gTeL2iQDdztZJ25DItV2ZgvBRlOaHJUEddNO3pYBM8KwGXF15fWCISxp8wNXdVjGziJezbTN2nRDs163ohkkCAq1YdwmZj7aAfs/Tfj1lhIo4CoiuTkSgH9J50jVLE/K7pGd5YgUjHeWxeSzm7kEY62qxX8m16ruYk2L7z4Gjz8yZpt+cuLo7Rys28pXLo09mgS2HgXODmNVKt5+7NOHD5gGrjFtaVC9xkvnEhY9qGqo1tLmIMajgCXjhm9EiZaRq0H+NIKjgHINaDSES4UCOE9uicE8Q4BvYHJ/v1440Op3uakLaMhsBs2a/98ZxoKfOm0JPvIOFqf1J1oyllqWmpQ7LTszcjfNNutop2Cc1gNuHC7U13yXUuoOEsk41XiGy4fs3RciRFL7bk7MhNUuywrzjrMn/sI2PFHm1apsjBkwZljxN1e9KJcYhumBJY9qokrVzoM24zZnSpE0uybPZriTP2iVYgY+Y59Qrhd3X58lJ5InJ7BVxdmTwmZ0pXPlWXLfq4GyzsfU+TLrKyF60j5REhWJJny7JEEAMpWXs6pLZZeDUGgTATM1dknL9U58nygaaVDCo/V2xt/YqUKraMQkxsf+lMf/FNjrNKuUDFOqHP9bIRk5ibhw4SLwwG6QH6RLpr5ttHO41Eijg+2/AREygDmefcK3OXLyxcvHIhkIoknlsSaFhiNvNpmSLIRXk1RjZh1qbLDWsBX58kHEgvkBftrWWclIfeQExZEZ0G2VCTKYNoJJHSOf5ZNzETkkRoKD+Go8t7gSF8fEqZKqxsBireeKeReLdSjht0ONS2NrFKeLGtb8NWfB69WUbayC3GbmOC4mhozjr544ZdszhpvWRjZCjtNx8nRMknxUanmbp1vIg9hIjD1h6pJzRNqLJ+UZcyx9fEaVqVtLaENRc/Idukcbvka0luL5KvtHBsjVIz9VE2ZrVkp+DJW1rjBQWGKq6NOSb4mfjElvjr3Ww4WbLTYzPwiDoFoo8n3V2A2dQ2KKO47yQDEOIJ8hirhuhYm58wF99Ero3CdhltAQEVbYKjemaoTkJ4m9bVlWW/BJOpoZ1ysQZjXhiwrEGie7e3vWfffAeGh7jPyRVdkwRKZITNHjUuXLuLeC2dcLfBA92DK3y4bQpJGGmQZNtdcOWorRaIy4vWaaVI48D1Kjp4NrKwRgVNedCDwy71I3n6GBZvzjYhVHR9tGVtXEEEP5YkrIVgRQAIMg6rbW6R3hREnUAEIXRCUoaIvTJcGlg34RIWSFLg93qPKioxBgQfl2KYMDDO19mUsZuqhQ0a0yA0ElhFEXfK5jOHvRn5436y5GHTMlOo4RXvcFwzAyemRWzvZoXPo5TM8Ks3ECPkIB5bl2DOOgOuDAdEbOMiA+fVfsJmiWW2FC7HHc3LShdIdSCaF3cK7JsjLJrCULa4tq9eujQWGZPjS1G9VZuItGXSnRRn63stm22js+rAIDPWSuf9udrbEcxb9oNWM8E6ra1eCo0wxsDQf0UkvWk+8EZMNsXUfEJETCg2wSomxHiL5GK2pnrit8QEadmbXbHsifWDPPW6G+rehvtVB6mbfTG5J8EQxN6GiJZdIilelS5OuWXTQKTLcYTlRTTAJcMPdm3PEhzDahjkHrmp93/jHh655vprfc3F/sF9U1ADRVPCWyb4GuLzQw5mfoWI+N+ghMu0ZjXlCfqNLFhYE0rO5KKYF8WN65btNUPFptWVXfiXxIMI27KpHFIOlnH0avW9+jGeIdyWfSkXrJ1IcHaxnqkoiRtxUBznaEtmkq1hQDaBw1yh5TllLFnulF8UG5hn9ppU3OT5Ol8oYtL57AU9tNlWH7pgbVU5s5hHGifVMhlR++QIJU7MhMp17tmnwWMKnRzNBgb9fYzshtfFctvJeuDVDiPmw1whW/0qU6TuqL5Djsy2YtrJussnPnJ+EIOw/kMbDqb1h3D00we/Ofi55EjyxaK62/9wV+ICBzbZ8AATESKrKWslUV/rsV8TXNtcwLiK0hZgfLCZCyM9h5xbKtxojC8wYzLyvYI7OrSEQ5g50LGIj7KfRKIh6QP7vMhhqG5EffYRcf5p7KGepKFy2EG61Rt22riKd7Pras2IM9YLeA28fDq8n/2i2hmhPU5Cj0+GAh/jHkt9Y/wRErKcqdtSJAe6TDAu48IymfUE6XtD2OTv0bhei5NZ+laTzFreXAHSMWlIjfMcQvaSFy7MsmBwrHIR4EcBWJDedAT5EK18RVrGsZclHhNzcSqKq57bTAfJeVYpYYSxtEgGKiQI0Co6Se2Ox3rnOYTKeasy+W9wgODm7YKMmzQbVaNNq4iB7kJO8tPXypn+EK69wXIKASSJDtn/SJ2YL09NGcY3rvgAxwC2vRoEY+sGmKIDE8sT/HG8RoIno7xGR3MO4YRrDuglRlvPEGpDoByFHvmTuYbEkDsNZ8JGp3cjNbdy1va2O2CKwg/zN0WBfOqrQGBsqtsrNlJbGbqqTuxOncCHKJeQcFiTvDX1IOvs/IzxyQ966/KOpfUqzcu4cDQ8GYhYiLUniGa3ZNxUXOyZmF4VjHq4PuwOhlW5X0AXdkbKpDc0AXfOpNyhUE+agHK4utZEHrUaQuOeNtl5f7X7vPsEhDa4ZWEjHrS2qm06YFt1V7fddYgyQMMd7TwZ1RVt6HCnKoarv9o9PaY7+aZq72E+cao2O3si363mU5lQ8kVj4/Iqzg8Jyu18FxOjmrM9GpP+Vc36nWl/XGeErCuqiktxiy356dbqMbX2lyD8mQu8cT+bGtmo699ZPqkTXAdZ3ElmLXLNRnSjXQ+cAjMKdHdnW7USCML4C2WEGHqAW0l+mU2gh6v//pzZbHv3nneNSLuu/BtPxm0FF99X1R22+o5HiEI/xV/cuqX0RcT9eENu57xzR7lLn3JzMWda272Do+0OCUr2wW6XTstxqW5uGUrxV7sn/StT6lqK/S7ua3ZDqagT9F++dTidPlEec7pC2lc8If/7NsSIOlvy4mDF+rGhZfmX6732Hle+rxfb10MMQHx0uE9Km+qJnt/5/wBUfsnK"
# --- END_EMBEDDED_ASSETS ---


# --- STACK PRESETS & METADATA ---

STACK_PRESETS = {
    "swift": {
        "name": "iOS / macOS (Swift, SwiftUI, Xcode)",
        "language": "Swift",
        "build_cmd": "swift build",
        "test_cmd": "swift test",
        "lint_cmd": "swiftlint",
        "file_ext": ".swift",
        "sample_contract": "```swift\npublic protocol ExampleServiceProtocol: Sendable {\n    func execute() async throws -> String\n}\n```",
        "bug_env": "  - OS: iOS 18.x / macOS 15.x\n  - Toolchain: Xcode 16.x / Swift 6.0",
        "research_quirks": "* **Concurrency & Memory:** ARC weak/unowned, Task isolation, Sendable, BGAppRefresh.",
    },
    "ts": {
        "name": "Web / Node (TypeScript, JavaScript)",
        "language": "TypeScript",
        "build_cmd": "npm run build",
        "test_cmd": "npm test",
        "lint_cmd": "npm run lint",
        "file_ext": ".ts",
        "sample_contract": "```typescript\nexport interface ExampleService {\n  execute(signal?: AbortSignal): Promise<string>;\n}\n```",
        "bug_env": "  - OS: macOS / Linux / Windows\n  - Runtime: Node.js 20.x / 22.x",
        "research_quirks": "* **Event Loop & Memory:** Microtasks, uncleaned event listeners, SSR hydration.",
    },
    "python": {
        "name": "Python (Standard / Pytest / FastAPI)",
        "language": "Python",
        "build_cmd": "python -m py_compile scripts/*.py",
        "test_cmd": "pytest",
        "lint_cmd": "ruff check .",
        "file_ext": ".py",
        "sample_contract": "```python\nclass ExampleService:\n    def execute(self) -> str:\n        return \"OK\"\n```",
        "bug_env": "  - OS: macOS / Linux / Windows\n  - Python: 3.10+ / 3.12+",
        "research_quirks": "* **Async & Types:** Asyncio event loop blocking, GIL limitations, type hinting.",
    },
    "dotnet": {
        "name": ".NET / C# (ASP.NET, MAUI, Console)",
        "language": "C#",
        "build_cmd": "dotnet build",
        "test_cmd": "dotnet test",
        "lint_cmd": "dotnet format",
        "file_ext": ".cs",
        "sample_contract": "```csharp\npublic interface IExampleService {\n    Task<string> ExecuteAsync(CancellationToken ct = default);\n}\n```",
        "bug_env": "  - OS: Windows 11 / macOS / Linux\n  - SDK: .NET 8.0 / 9.0",
        "research_quirks": "* **Async & GC:** ConfigureAwait(false), ThreadPool starvation, IDisposable pattern.",
    },
    "generic": {
        "name": "Generic / Other Technology Stack",
        "language": "Source Code",
        "build_cmd": "make build",
        "test_cmd": "make test",
        "lint_cmd": "make lint",
        "file_ext": ".src",
        "sample_contract": "```text\nfunction execute(): Result\n```",
        "bug_env": "  - OS: macOS / Linux / Windows\n  - Runtime: Project runtime",
        "research_quirks": "* **Concurrency & Resources:** Thread safety, race conditions, memory lifecycle.",
    },
    "undecided": {
        "name": "Undecided / Idea-First Research",
        "language": "TBD (Determined in Mode 0 via /kb-research)",
        "build_cmd": "echo 'No build command configured yet (run /kb-research)'",
        "test_cmd": "echo 'No test command configured yet (run /kb-research)'",
        "lint_cmd": "echo 'No lint command configured yet (run /kb-research)'",
        "file_ext": ".txt",
        "sample_contract": "# Архитектурный контракт и интерфейсы будут определены по итогам RESEARCH-001\n",
        "bug_env": "  - ОС: TBD\n  - Стек: TBD (в процессе исследования)\n",
        "research_quirks": "* **Архитектурные ограничения и критерии выбора стека:** будут зафиксированы в ADR-0001.",
    },
}


# --- ASSET UNPACKING ---

def unpack_assets(source_repo_path: Path = None) -> dict:
    """
    Unpacks embedded assets from base64/zlib.
    Falls back to local filesystem if running in source repo and bundle is empty.
    """
    if EMBEDDED_ASSETS_B64:
        try:
            compressed = base64.b64decode(EMBEDDED_ASSETS_B64.encode("ascii"))
            raw_json = zlib.decompress(compressed).decode("utf-8")
            return json.loads(raw_json)
        except Exception as e:
            print(f"⚠️ Error unpacking embedded bundle: {e}")

    # Fallback for local repository development
    repo_root = source_repo_path or Path(__file__).resolve().parent
    templates_dir = repo_root / "templates"
    scripts_dir = repo_root / "scripts"
    skills_dir = repo_root / ".agents" / "skills"

    if templates_dir.is_dir():
        assets = {}
        for tf in templates_dir.glob("*.md"):
            assets[f"00_Templates/{tf.name}"] = tf.read_text(encoding="utf-8")
        graph_json = templates_dir / "graph.json"
        if graph_json.is_file():
            assets[".obsidian/graph.json"] = graph_json.read_text(encoding="utf-8")
        for sname in ["kb_lint.py", "kb_release.py"]:
            sfile = scripts_dir / sname
            if sfile.is_file():
                assets[f"scripts/{sname}"] = sfile.read_text(encoding="utf-8")
        if skills_dir.is_dir():
            for sdir in sorted([d for d in skills_dir.iterdir() if d.is_dir()]):
                skill_md = sdir / "SKILL.md"
                if skill_md.is_file():
                    assets[f".agents/skills/{sdir.name}/SKILL.md"] = skill_md.read_text(encoding="utf-8")
        workflows_dir = repo_root / ".github" / "workflows"
        if workflows_dir.is_dir():
            for wf in workflows_dir.glob("*.yml"):
                assets[f".github/workflows/{wf.name}"] = wf.read_text(encoding="utf-8")
        if assets:
            return assets

    raise RuntimeError("Cannot find assets. Both embedded bundle and local templates directory are unavailable.")


# --- GENERATORS FOR AGENTS & REPO RULES ---

_RULES_BODY = ("## Docs-as-Code (14 Disciplines)\n"
    "Language: {lang}\n"
    "1. Read `SPEC.md`, `docs/00_Index.md`, `docs/Onboarding.md` at session start; sync `SPEC.md`/`README.md` (Living Spec).\n"
    "2. Kanban: move cards with date `(YYYY-MM-DD)`.\n"
    "3. Roadmap: mark `[x]` + link `[[Specs/.../TASK-XXX|TASK-XXX]]`.\n"
    "4. ADR & Rejected-ADR: log all decisions incl. rejected (`status: rejected`).\n"
    "5. Research: worst-case tests; record discarded prototypes in `RESEARCH-XXX`.\n"
    "6. Devlog: write entry at task/session end with next step awaiting user command.\n"
    "7. Obsidian: wikilinks `[[...]]` + tags.\n"
    "8. Permalinks: NEVER move `TASK-XXX`/`BUG-XXX` to Done/Archive.\n"
    "9. Regression-First: failing test BEFORE fixing any bug.\n"
    "10. QA: checklists `- [ ]` in `docs/05_Testing/`, separate from Plans.\n"
    "11. Graph: 7 Obsidian color groups (White/Purple/Cyan/Yellow/Orange/Red/Green).\n"
    "12. Git: Remote/Local/None + Trunk-Based docs + Feature Branching.\n"
    "13. Single-Task Barrier: `/kb-implement` executes ONE task; stop tool calls on complete, never auto-chain.\n"
    "14. Zero-State & Spec Genesis: When `SPEC.md` is missing or in `status: discovery`, never invent requirements; crystallize via Mode 0 (`/kb-research`) before `status: active`.\n")


def _rules(doc_lang: str) -> str:
    lang = "Documentation/Devlog **Russian**, code/commits **English**." if doc_lang == "ru" else "All documentation **English**."
    return _RULES_BODY.format(lang=lang)




_3MODES = (
    "## 🔄 3-Mode Discipline & Workflow\n\n"
    "**Mode 1 -- Planning (`/kb-plan`):** STRICTLY NO CODE CHANGES. User approval before writing plan docs. Soft Nudge if `SPEC.md` is in status: discovery.\n"
    "**Mode 2 -- Task Spec (`/kb-task`):** STRICTLY NO CODE CHANGES. `[NEW]`/`[MODIFY]`/`[DELETE]` contracts + DoD.\n"
    "**Mode 3 -- Implementation (`/kb-implement`):\n"
    "```bash\n{test_cmd}\npython3 scripts/kb_lint.py --path docs\n```\n"
    "Auto-complete: spec->done · Living Spec sync · Kanban+date · Roadmap `[x]` · Devlog · kb_lint · git push · STOP tool calls (Stop & Yield).\n\n"
    "Single-Task Barrier: strictly ONE task per `/kb-implement`. Never auto-chain next tasks. Stop tool calls on completion.\n"
    "Zero-State Guard: when `SPEC.md` is missing or discovery, never invent requirements; suggest Mode 0 (`/kb-research`).\n"
    "Anti-Echo: NEVER reprint entire files in chat; emit link + 3-5 bullets + next step.\n"
    "Senior Partner: flag risks, propose alternatives. Rejected ADRs: `docs/03_Decisions_ADR/` (`status: rejected`).\n"
)


def _gen_rule(title: str, p: str, s: str, l: str, extra: str = "", tail: str = "") -> str:
    st = STACK_PRESETS.get(s, STACK_PRESETS["generic"])
    return f"# {title} for {p}\n\nStack: **{st['name']}**{extra}\n\n{_rules(l)}\n{_3MODES.format(test_cmd=st['test_cmd'])}{tail}"


def generate_gemini_md(p: str, s: str, l: str = "ru") -> str:
    return _gen_rule("GEMINI.md -- Google Antigravity & Gemini CLI Rules", p, s, l, " | Full Guidelines: `AGENTS.md`", "\nSkills: `/kb-plan` `/kb-task` `/kb-implement` `/kb-complete` `/kb-bug` `/kb-adr` `/kb-research` `/kb-release` `/kb-lint`\n")


def generate_windsurfrules(p: str, s: str, l: str = "ru") -> str:
    st = STACK_PRESETS.get(s, STACK_PRESETS["generic"])
    return _gen_rule(".windsurfrules -- Windsurf Cascade AI Rules", p, s, l, f" | Build: `{st['build_cmd']}` | Test: `{st['test_cmd']}`")


def generate_clinerules(p: str, s: str, l: str = "ru") -> str:
    return _gen_rule("Cline / Roo Code AI Rules", p, s, l, " | Read `AGENTS.md` and `docs/Onboarding.md` first.")


def generate_claude_md(p: str, s: str, l: str = "ru") -> str:
    st = STACK_PRESETS.get(s, STACK_PRESETS["generic"])
    return _gen_rule("CLAUDE.md -- Claude Code Guidelines", p, s, l, f" | Build: `{st['build_cmd']}` | Test: `{st['test_cmd']}` | Lint: `python3 scripts/kb_lint.py --path docs`")


def generate_cursorrules(p: str, s: str, l: str = "ru") -> str:
    return _gen_rule("Cursor Rules", p, s, l, "\nYou are a **Senior Engineering Partner**. Read `AGENTS.md`.")


def generate_copilot_instructions(p: str, s: str, l: str = "ru") -> str:
    return _gen_rule("GitHub Copilot Instructions", p, s, l, " | Read `AGENTS.md` for full guidelines.")


def generate_agents_md(project_name: str, stack_key: str, doc_lang: str = "ru") -> str:
    stack = STACK_PRESETS.get(stack_key, STACK_PRESETS["generic"])
    rules = _rules(doc_lang)
    return f"""# 🤖 AGENTS.md -- AI Agent Guidelines & Operating Modes

> **Project:** {project_name} | **Stack:** {stack['name']}
> **Spec:** [[SPEC|SPEC.md]] | **KB:** [[docs/00_Index|00_Index]] | **Onboarding:** [[docs/Onboarding|Onboarding Guide]]

---

{rules}
### 🎨 Obsidian Graph Color Scheme & Tagging
| Color / Category | Obsidian Path / Query | Tags | Description |
| :--- | :--- | :--- | :--- |
| ⚪ White / Light | `file:00_Index`, `file:Devlog`, `file:SPEC` | — | Entry points & root navigation hubs |
| 🟣 Purple | `path:01_Architecture` | `#arch` | System architecture, contracts & modules |
| 🔵 Blue / Cyan | `path:03_Decisions_ADR` | `#adr` | Architecture Decision Records |
| 🟡 Yellow / Amber | `path:04_Research` | `#research` | Platform research, benchmarks & quirks |
| 🟠 Orange | `path:02_Tasks` | `#task` | Backlog, Roadmap, Plans & Task Specs |
| 🔴 Red | `path:02_Tasks/Bugs` | `#bug` | Defects, bugs, RCA & regression tests |
| 🟢 Green | `path:05_Testing` | `#testing` | Acceptance testing & E2E UX checklists |

---

## 🛑 Single-Task Execution Barrier (No Auto-Chaining)

- The command `/kb-implement <TASK-XXX>` authorizes work **strictly on that single task specification**.
- Even if subsequent tasks are listed in plans, backlog, or Devlog, the agent is **strictly prohibited** from starting their implementation without an explicit user command (e.g. `/kb-implement TASK-YYY`).
- "Next Step" sections in devlogs, plans, and summaries are developer guidance only and are **never** an execution mandate for the agent.
- Once task verification and commit are complete, the agent must **cease all tool calls immediately** and return control to the user.

---

## 🛡️ 6. Zero-State Anti-Hallucination & Spec Genesis

- When `SPEC.md` is missing or in `status: discovery`, the agent is **strictly prohibited** from inventing arbitrary product requirements, features, or technology stacks out of thin air.
- Requirements must be crystallized through interactive dialogue with the user or Mode 0 (`/kb-research`) resulting in an approved `ADR-0001` before transitioning `SPEC.md` to `status: active`.
- Planning (`/kb-plan`) and task specification (`/kb-task`) must issue a Soft Nudge if `SPEC.md` is unvalidated.

---

## 🔇 Anti-Echo Response Protocol

When modifying or creating files on disk:
1. **STRICTLY PROHIBITED:** Dumping complete file contents or repetitive code blocks into chat responses.
2. **REQUIRED RESPONSE FORMAT:**
   - Clickable file link: `[FileName](file:///absolute/path/to/file)`
   - Concise 3–5 bullet summary of what changed and key architectural decisions
   - Next actionable step or prompt for confirmation

---

## 🧠 Senior Engineering Partner Standard

You are a **Senior Engineering Partner**, not a passive assistant:
1. **Critical Review:** Evaluate against best practices ({stack['language']}, Clean Architecture, Zero Dependencies).
2. **Constructive Challenge:** Flag flaws -> justify consequences -> offer 1--2 robust alternatives.
3. **User Confirmation Required (Mode 1 & 2):** NEVER write plan/spec docs without explicit user approval.
4. **Rejected ADRs:** Document discarded directions (`status: rejected`) in `docs/03_Decisions_ADR/`.

---

## 🔄 The 3-Mode Development Cycle

### 🟡 Mode 1 -- Planning (`/kb-plan`)
**🚨 STRICTLY NO CODE CHANGES.** Research, Q&A, critical review. User confirmation before any plan doc.
Output: `docs/02_Tasks/Plans/PLAN-XXX-<slug>.md` + Kanban Backlog card.

### 🟠 Mode 2 -- Task Spec (`/kb-task`)
**🚨 STRICTLY NO CODE CHANGES.** File contracts + verification plan.
Contracts: `[NEW] path/to/file{stack['file_ext']}` / `[MODIFY]` / `[DELETE]` with signatures and DoD.
Output: `docs/02_Tasks/Specs/<Phase>/TASK-XXX-<slug>.md` + Kanban In Progress.

### 🟢 Mode 3 -- Implementation (`/kb-implement` -> `/kb-complete`)
Code strictly per approved spec. Run:
```bash
{stack['build_cmd']}
{stack['test_cmd']}
python3 scripts/kb_lint.py --path docs
```
Completion checklist: spec->done · Kanban->Done(date) · Roadmap `[x]` · Devlog · kb_lint 0 errors · git push · STOP tool calls (Stop & Yield).
"""

# --- STARTER DOCS CUSTOMIZATION ---

def customize_templates_for_stack(template_name: str, content: str, stack_key: str, today_str: str) -> str:
    stack = STACK_PRESETS.get(stack_key, STACK_PRESETS["generic"])
    content = content.replace("2026-09-19", today_str).replace("2026-09-26", today_str)

    if template_name == "TEMPLATE_TASK.md":
        # Replace sample contract with stack-specific contract
        contract_marker = "```python\n# Ключевой контракт\n```"
        if contract_marker in content:
            content = content.replace(contract_marker, stack["sample_contract"])
        contract_target = "```csharp\n// Пример ключевого интерфейса или фрагмента контракта\npublic interface IExampleService\n{\n    Task ExecuteAsync(CancellationToken ct);\n}\n```"
        if contract_target in content:
            content = content.replace(contract_target, stack["sample_contract"])
        # Replace build & test command
        content = content.replace("<!-- команда сборки, Exit code 0 -->", stack["build_cmd"])
        content = content.replace("<!-- команда запуска тестов, 100% pass -->", stack["test_cmd"])
        content = content.replace("`dotnet build` или `./gradlew test`", f"`{stack['build_cmd']}`")
        content = content.replace("`dotnet test`", f"`{stack['test_cmd']}`")
        content = content.replace("path/to/file.ext", f"path/to/file{stack['file_ext']}")
        content = content.replace("Path/To/NewFile.cs", f"Path/To/NewFile{stack['file_ext']}")
        content = content.replace("Path/To/ExistingFile.kt", f"Path/To/ExistingFile{stack['file_ext']}")
        content = content.replace("Path/To/OldFile.cs", f"Path/To/OldFile{stack['file_ext']}")

    elif template_name == "TEMPLATE_BUG.md":
        # Replace bug environment and test paths
        env_marker = "* **Окружение:** <!-- ОС, версия, стек -->"
        if env_marker in content:
            content = content.replace(env_marker, f"* **Окружение:**\n{stack['bug_env']}")
        legacy_env = "  - ОС: Windows 11 Build / Android Version\n  - Стек: .NET SDK / Gradle Version / Runtime\n  - Сеть/Конфигурация: Localhost / Wi-Fi / VPN"
        if legacy_env in content:
            content = content.replace(legacy_env, stack["bug_env"])
        content = content.replace("tests/path/to/test_regression.ext", f"tests/path/to/test_regression{stack['file_ext']}")
        content = content.replace("path/to/file.ext", f"path/to/file{stack['file_ext']}")
        content = content.replace("path/to/file.cs", f"path/to/file{stack['file_ext']}")
        content = content.replace("tests/Path/To/RegressionTest.cs", f"tests/Path/To/RegressionTest{stack['file_ext']}")

    elif template_name == "TEMPLATE_RESEARCH.md":
        # Replace sample research code and platform quirks
        quirks_marker = "<!-- Поведение подсистемы в фоне, энергопотребление, жизненный цикл, лимиты -->"
        if quirks_marker in content:
            content = content.replace(quirks_marker, stack["research_quirks"])
        legacy_quirks = "* **Поведение в фоне и энергопотребление (Doze / WakeLock):** ...\n* **Поведение при сбоях сети и роуминге:** ...\n* **Потокобезопасность и нагрузка на память/CPU:** ...\n* **Ограничения прав и безопасности ОС:** ..."
        if legacy_quirks in content:
            content = content.replace(legacy_quirks, stack["research_quirks"])
        content = content.replace("```python\n# Экспериментальный код или бенчмарк\n```", stack["sample_contract"])
        content = content.replace("```kotlin\n// Пример проверочного кода или сниппета решения\n```", stack["sample_contract"])

    return content


def detect_project_stack(target_dir: Path) -> str:
    """
    Эвристический детект стека по маркерным файлам в корне проекта.
    Возвращает ключ стека из STACK_PRESETS ('swift', 'ts', 'python', 'dotnet', 'generic').
    """
    if not target_dir.is_dir():
        return "generic"
    if (target_dir / "Package.swift").is_file():
        return "swift"
    if (target_dir / "package.json").is_file():
        return "ts"
    if any((target_dir / f).is_file() for f in ["pyproject.toml", "requirements.txt", "Pipfile", "setup.py"]):
        return "python"
    try:
        if list(target_dir.glob("*.sln")) or list(target_dir.glob("*.csproj")):
            return "dotnet"
    except Exception:
        pass
    return "generic"


def handle_readme(target_dir: Path, project_name: str, doc_lang: str = "ru"):
    readme_path = target_dir / "README.md"
    if doc_lang == "en":
        docs_block = """

---

## 🧠 AI Agent Documentation & Discipline (Docs-as-Code)
This project uses the Docs-as-Code knowledge base and strict 3-mode workflow for AI agents:
* **Documentation Vault:** `docs/` (open as Obsidian Vault).
* **Universal Agent Rules:** [AGENTS.md](AGENTS.md).
* **Knowledge Map (MOC):** [docs/00_Index.md](docs/00_Index.md).
* **Integrity Linter:** `python scripts/kb_lint.py --path docs`.
"""
    else:
        docs_block = """

---

## 🧠 Документация и дисциплина AI-агентов (Docs-as-Code)
В проекте развернута база знаний Docs-as-Code и строгий 3-режимный регламент работы с AI-агентами:
* **Каталог документации:** `docs/` (открывается как Vault в Obsidian).
* **Главный регламент агентов:** [AGENTS.md](AGENTS.md).
* **Карта заметок:** [docs/00_Index.md](docs/00_Index.md).
* **Проверка базы знаний:** `python scripts/kb_lint.py --path docs`.
"""
    if readme_path.is_file():
        content = readme_path.read_text(encoding="utf-8")
        if "AGENTS.md" not in content and "Docs-as-Code" not in content:
            readme_path.write_text(content.rstrip() + "\n" + docs_block, encoding="utf-8")
            print("📝 Appended Docs-as-Code section to existing README.md.")
    else:
        new_content = f"# {project_name}\n\nProject repository.\n{docs_block}"
        readme_path.write_text(new_content, encoding="utf-8")
        print("📝 Created root README.md with Docs-as-Code section.")


def handle_gitignore(target_dir: Path):
    gitignore_path = target_dir / ".gitignore"
    obsidian_rules = """
# Obsidian Workspace (preserve graph.json)
.obsidian/*
!.obsidian/graph.json
"""
    if not gitignore_path.exists():
        gitignore_content = """# System & IDE
.DS_Store
Thumbs.db
.idea/
.vscode/*
!.vscode/settings.json
""" + obsidian_rules
        gitignore_path.write_text(gitignore_content.strip() + "\n", encoding="utf-8")
        print("📁 Created .gitignore (with Obsidian graph retention rules).")
    else:
        content = gitignore_path.read_text(encoding="utf-8")
        if ".obsidian" not in content:
            gitignore_path.write_text(content.rstrip() + "\n" + obsidian_rules, encoding="utf-8")
            print("📁 Appended Obsidian retention rules to existing .gitignore.")


def create_starter_docs(target_dir: Path, project_name: str, stack_key: str, assets: dict = None, force: bool = False, idea: str = None):
    stack = STACK_PRESETS.get(stack_key, STACK_PRESETS["generic"])
    today_str = date.today().isoformat()
    docs_dir = target_dir / "docs"

    # 1. SPEC.md (Root)
    spec_path = target_dir / "SPEC.md"
    if not spec_path.exists() or force:
        is_undecided = (stack_key == "undecided")
        spec_status = "discovery" if is_undecided else "active"
        if is_undecided:
            concept_text = idea.strip() if idea else "*Краткое описание продуктовой идеи, решаемой проблемы и целевой аудитории (зафиксировано для исследования в Режиме 0).*"
            arch_text = (
                "* **Статус стека:** Не определен. Требуется провести первичное исследование через команду агента: `/kb-research выбор-стека-и-архитектуры`.\n"
                "* **Сборка проекта:** `TBD (после завершения RESEARCH-001)`\n"
                "* **Запуск тестов:** `TBD (после завершения RESEARCH-001)`\n"
                "* **Проверка базы знаний:** `python3 scripts/kb_lint.py --path docs`"
            )
        else:
            concept_text = idea.strip() if idea else "*Краткое описание назначения проекта, решаемой проблемы и целевой аудитории.*"
            arch_text = (
                f"* **Платформа и технологии:** {stack['name']} ({stack['language']})\n"
                f"* **Сборка проекта:** `{stack['build_cmd']}`\n"
                f"* **Запуск тестов:** `{stack['test_cmd']}`\n"
                f"* **Проверка базы знаний:** `python3 scripts/kb_lint.py --path docs`"
            )

        spec_content = f"""---
id: SPEC
title: "Мастер-спецификация: {project_name}"
status: {spec_status}
type: specification
created: {today_str}
updated: {today_str}
tags:
  - spec
  - master
  - {project_name.lower().replace(" ", "-")}
---

# 🚀 Мастер-спецификация: {project_name}

> **Проект:** {project_name}  
> **Стек:** {stack['name']}  
> **Связанные документы:** [[docs/00_Index|00_Index]], [[docs/Onboarding|Онбординг]], [[docs/02_Tasks/Kanban|Канбан]], [[docs/02_Tasks/Roadmap|Дорожная карта]].

---

## 1. Концепция и цели проекта
{concept_text}

---

## 2. Архитектура и стек технологий
{arch_text}

---

## 3. Этапы разработки
План реализации разбит на фазы в [[docs/02_Tasks/Roadmap|Дорожной карте]]:
* **Фаза 1: Инициализация и MVP** -- Базовый каркас и проверка сборки.
* **Фаза 2: Основная функциональность** -- Ключевые пользовательские сценарии.
"""
        spec_path.write_text(spec_content, encoding="utf-8")

    # 2. docs/00_Index.md
    index_path = docs_dir / "00_Index.md"
    if not index_path.exists() or force:
        tpl = (assets or {}).get("00_Templates/TEMPLATE_INDEX.md", "")
        index_content = tpl.replace("[Название Проекта]", project_name).replace("2026-09-19", today_str) if tpl else f"# {project_name}\n"
        index_path.write_text(index_content, encoding="utf-8")

    # 3. docs/Onboarding.md
    onboarding_path = docs_dir / "Onboarding.md"
    if not onboarding_path.exists() or force:
        tpl = (assets or {}).get("00_Templates/TEMPLATE_ONBOARDING.md", "")
        onboarding_content = (
            tpl.replace("[Название Проекта]", project_name)
            .replace("2026-09-19", today_str)
            .replace("dotnet build", stack["build_cmd"])
            .replace("dotnet test", stack["test_cmd"])
        ) if tpl else f"# Onboarding: {project_name}\n"
        onboarding_path.write_text(onboarding_content, encoding="utf-8")

    # 4. docs/Devlog.md
    devlog_path = docs_dir / "Devlog.md"
    if not devlog_path.exists() or force:
        tpl = (assets or {}).get("00_Templates/TEMPLATE_DEVLOG.md", "")
        devlog_content = tpl.replace("2026-09-19", today_str) if tpl else f"# Devlog: {project_name}\n"
        devlog_path.write_text(devlog_content, encoding="utf-8")

    # 5. docs/02_Tasks/Kanban.md
    kanban_path = docs_dir / "02_Tasks" / "Kanban.md"
    if not kanban_path.exists() or force:
        kanban_content = f"""---
kanban-plugin: basic
---

# 📋 Канбан-доска: {project_name}

> **Теги:** #tasks #kanban #planning  
> **Связанная дорожная карта:** [[Roadmap|Дорожная карта]]  

## 📥 Бэклог (Backlog)

<!-- Начните с создания первого плана через команду агента /kb-plan <название> -->

## ⏳ В работе (In Progress)


## ✅ Готово (Done)

- [x] Инициализация структуры базы знаний Docs-as-Code ({today_str}) #docs

## 💡 Идеи и гипотезы (Icebox / Future Ideas)

- [ ] [Идея 1]: краткая формулировка задумки или гипотезы #idea
"""
        kanban_path.write_text(kanban_content, encoding="utf-8")

    # 6. docs/02_Tasks/Roadmap.md
    roadmap_path = docs_dir / "02_Tasks" / "Roadmap.md"
    if not roadmap_path.exists() or force:
        roadmap_content = f"""---
id: ROADMAP
title: Дорожная карта разработки (Roadmap)
status: active
type: roadmap
created: {today_str}
updated: {today_str}
tags:
  - roadmap
  - planning
  - milestones
---

# 🗺️ Дорожная карта разработки (Roadmap): {project_name}

> **Теги:** #roadmap #planning #milestones  
> **Связанный канбан:** [[Kanban|Канбан-доска]]  
> **Первоисточник:** [[../../SPEC|SPEC.md (Мастер-спецификация)]]  

---

## Фаза 1: Первичный MVP и проверка сборки
**Цель:** Создание базового каркаса проекта и проверка сборки/тестов.  
*Сформируйте концептуальный план первой фазы через команду `/kb-plan`.*

---

## 🔮 Перспективные направления (Future Horizons / Later)
*Идеи и гипотезы, находящиеся на стадии осмысления. Прорабатываются через Режим 1 (`/kb-plan`).*

* 💡 **[Идея 1]:** Краткое описание проблемы и ценности.
"""
        roadmap_path.write_text(roadmap_content, encoding="utf-8")



# --- GIT SETUP ---

def setup_git(target_dir: Path, git_choice: str):
    """
    Handles git initialization according to user choice: 'local', 'github', or 'none'.
    """
    if git_choice == "none":
        print("⏭️ Git setup skipped.")
        return

    # Check if git command exists
    git_cmd = shutil.which("git")
    if not git_cmd and sys.platform == "win32":
        # Check standard Windows paths
        win_candidates = [
            r"C:\Program Files\Git\cmd\git.exe",
            r"C:\Program Files\Git\bin\git.exe",
            os.path.expandvars(r"%LOCALAPPDATA%\Programs\Git\cmd\git.exe"),
        ]
        for cand in win_candidates:
            if os.path.isfile(cand):
                git_cmd = cand
                break

    if not git_cmd:
        print("⚠️ Warning: 'git' executable not found in PATH. Skipping automated Git operations.")
        print("   You can initialize Git manually later with: git init")
        return

    is_git_repo = (target_dir / ".git" / "HEAD").is_file()

    if not is_git_repo:
        try:
            subprocess.run([git_cmd, "init"], cwd=str(target_dir), check=True, capture_output=True, text=True, encoding="utf-8", errors="replace")
            print("📦 Initialized local Git repository.")
        except Exception as e:
            print(f"⚠️ Git init warning: {e}")

    # Prepare .gitignore if not present
    handle_gitignore(target_dir)

    # Scope git operations strictly to target_dir
    git_env = os.environ.copy()
    git_env["GIT_DIR"] = str((target_dir / ".git").resolve())
    git_env["GIT_WORK_TREE"] = str(target_dir.resolve())

    # Initial commit
    try:
        subprocess.run([git_cmd, "add", "-A"], cwd=str(target_dir), env=git_env, check=True, capture_output=True, text=True, encoding="utf-8", errors="replace")
        res = subprocess.run([git_cmd, "commit", "-m", "feat: initialize docs-as-code harness"], cwd=str(target_dir), env=git_env, capture_output=True, text=True, encoding="utf-8", errors="replace")
        subprocess.run([git_cmd, "branch", "-M", "main"], cwd=str(target_dir), env=git_env, check=False, capture_output=True, text=True, encoding="utf-8", errors="replace")
        if res.returncode == 0:
            print("✅ Created initial Git commit with Docs-as-Code harness (branch: main).")
    except Exception as e:
        print(f"⚠️ Git commit notice: {e}")

    if git_choice == "github":
        print("\n🐙 GitHub Remote Setup Instructions:")
        print("   1. Go to https://github.com/new and create a new repository.")
        print("   2. (Do NOT check README, .gitignore or license options).")
        print("   3. Run the following commands to link your repository:")
        print(f"      cd \"{target_dir.resolve()}\"")
        print("      git remote add origin https://github.com/<your-username>/<repo-name>.git")
        print("      git push -u origin main\n")


def deploy_ci_workflow(target_dir: Path, ci_provider: str = "none", assets: dict = None):
    if ci_provider == "github":
        wf_dir = target_dir / ".github" / "workflows"
        wf_dir.mkdir(parents=True, exist_ok=True)

        # 1. kb-lint.yml
        wf_lint = wf_dir / "kb-lint.yml"
        if assets and ".github/workflows/kb-lint.yml" in assets:
            wf_lint.write_text(assets[".github/workflows/kb-lint.yml"], encoding="utf-8")
        else:
            wf_lint_content = (
                "name: Docs-as-Code Knowledge Base Audit\n\n"
                "on:\n"
                "  push:\n"
                "    branches: [ main, master ]\n"
                "  pull_request:\n"
                "    branches: [ main, master ]\n\n"
                "jobs:\n"
                "  kb-lint:\n"
                "    runs-on: ubuntu-latest\n"
                "    steps:\n"
                "      - name: Checkout repository\n"
                "        uses: actions/checkout@v4\n\n"
                "      - name: Set up Python\n"
                "        uses: actions/setup-python@v5\n"
                "        with:\n"
                "          python-version: '3.11'\n\n"
                "      - name: Run Knowledge Base Linter\n"
                "        run: |\n"
                "          python scripts/kb_lint.py --path docs\n"
            )
            wf_lint.write_text(wf_lint_content, encoding="utf-8")

        # 2. release.yml
        wf_release = wf_dir / "release.yml"
        if assets and ".github/workflows/release.yml" in assets:
            wf_release.write_text(assets[".github/workflows/release.yml"], encoding="utf-8")
        else:
            wf_release_content = (
                "name: Release Automation\n\n"
                "on:\n"
                "  push:\n"
                "    tags:\n"
                "      - 'v*'\n\n"
                "permissions:\n"
                "  contents: write\n\n"
                "jobs:\n"
                "  build-and-release:\n"
                "    name: Build & Publish Release\n"
                "    runs-on: ubuntu-latest\n"
                "    steps:\n"
                "      - name: Checkout Repository\n"
                "        uses: actions/checkout@v4\n"
                "        with:\n"
                "          fetch-depth: 0\n\n"
                "      - name: Set up Python\n"
                "        uses: actions/setup-python@v5\n"
                "        with:\n"
                "          python-version: '3.11'\n\n"
                "      - name: Verify Knowledge Base Integrity\n"
                "        run: |\n"
                "          python scripts/kb_lint.py --path docs\n\n"
                "      - name: Execute Project Build Hook\n"
                "        run: |\n"
                "          if [ -f \"scripts/build_release.sh\" ]; then\n"
                "            bash scripts/build_release.sh\n"
                "          elif [ -f \"scripts/build_release.py\" ]; then\n"
                "            python scripts/build_release.py\n"
                "          elif [ -f \"package.json\" ]; then\n"
                "            npm ci && npm run build\n"
                "          fi\n\n"
                "      - name: Inspect Artifacts & Verify Checksums\n"
                "        id: release_meta\n"
                "        run: |\n"
                "          mkdir -p dist\n"
                "          python scripts/kb_release.py --version ${{ github.ref_name }} --ci-mode\n\n"
                "      - name: Publish GitHub Release\n"
                "        uses: softprops/action-gh-release@v2\n"
                "        if: startsWith(github.ref, 'refs/tags/')\n"
                "        with:\n"
                "          name: Release ${{ github.ref_name }}\n"
                "          draft: false\n"
                "          prerelease: false\n"
                "          body_path: dist/RELEASE_NOTES.md\n"
                "          files: |\n"
                "            dist/*\n"
            )
            wf_release.write_text(wf_release_content, encoding="utf-8")
        print("✅ Deployed GitHub Actions CI workflows (.github/workflows/kb-lint.yml, release.yml).")


# --- INSTALLATION ORCHESTRATOR & INFRASTRUCTURE HELPERS ---

def get_agent_rule_specs(target_dir: Path, project_name: str, stack_key: str, doc_lang: str):
    return [
        ("all", target_dir / "AGENTS.md", generate_agents_md(project_name, stack_key, doc_lang), "root AGENTS.md (Universal Agent Standard)"),
        ("gemini", target_dir / "GEMINI.md", generate_gemini_md(project_name, stack_key, doc_lang), "GEMINI.md (Google Antigravity & Gemini CLI)"),
        ("cline", target_dir / ".clinerules", generate_clinerules(project_name, stack_key, doc_lang), ".clinerules (VS Code Cline & Roo Code)"),
        ("claude", target_dir / "CLAUDE.md", generate_claude_md(project_name, stack_key, doc_lang), "CLAUDE.md (Claude Code CLI)"),
        ("cursor", target_dir / ".cursorrules", generate_cursorrules(project_name, stack_key, doc_lang), ".cursorrules (Cursor IDE)"),
        ("copilot", target_dir / ".github" / "copilot-instructions.md", generate_copilot_instructions(project_name, stack_key, doc_lang), ".github/copilot-instructions.md (GitHub Copilot)"),
        ("windsurf", target_dir / ".windsurfrules", generate_windsurfrules(project_name, stack_key, doc_lang), ".windsurfrules (Windsurf Cascade)"),
    ]


def deploy_infrastructure(target_dir: Path, assets: dict, stack_key: str, today_str: str) -> tuple:
    docs_dir = target_dir / "docs"
    tpl_dir = docs_dir / "00_Templates"
    tpl_dir.mkdir(parents=True, exist_ok=True)
    tpl_count = skills_count = 0

    for rel_path, content in assets.items():
        if rel_path.startswith("00_Templates/"):
            tpl_name = Path(rel_path).name
            customized = customize_templates_for_stack(tpl_name, content, stack_key, today_str)
            (tpl_dir / tpl_name).write_text(customized, encoding="utf-8")
            tpl_count += 1
        elif rel_path.startswith(".agents/skills/"):
            target_file = target_dir / rel_path
            target_file.parent.mkdir(parents=True, exist_ok=True)
            target_file.write_text(content, encoding="utf-8")
            skills_count += 1
        elif rel_path == ".obsidian/graph.json":
            target_file = docs_dir / ".obsidian" / "graph.json"
            target_file.parent.mkdir(parents=True, exist_ok=True)
            target_file.write_text(content, encoding="utf-8")
        elif rel_path.startswith("scripts/"):
            target_file = target_dir / rel_path
            target_file.parent.mkdir(parents=True, exist_ok=True)
            target_file.write_text(content, encoding="utf-8")
            try:
                target_file.chmod(0o755)
            except Exception:
                pass
    return tpl_count, skills_count


def run_linter_audit(target_dir: Path, docs_dir: Path):
    kb_lint_path = target_dir / "scripts" / "kb_lint.py"
    if kb_lint_path.is_file():
        print("\n🔍 Running knowledge base audit with kb_lint.py...")
        res = subprocess.run(
            [sys.executable, str(kb_lint_path), "--path", str(docs_dir)],
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
        )
        if res.returncode == 0:
            print("✅ Linter check passed: 0 broken links, valid YAML frontmatter!")
        else:
            print(f"⚠️ Linter reported warnings:\n{res.stdout}\n{res.stderr}")


def install_harness(
    target_dir: Path,
    project_name: str,
    stack_key: str,
    agent_choice: str,
    git_choice: str,
    doc_lang: str = "ru",
    force: bool = False,
    ci_choice: str = "none",
    idea: str = None,
):
    print(f"\n🚀 Installing Agent Docs-as-Code Harness into: {target_dir.resolve()}")
    print(f"   • Project Name: {project_name}")
    print(f"   • Stack: {STACK_PRESETS.get(stack_key, STACK_PRESETS['generic'])['name']}")
    print(f"   • AI Agent configs: {agent_choice}")
    print(f"   • Documentation language: {doc_lang}")
    print(f"   • Git mode: {git_choice}")
    if ci_choice != "none":
        print(f"   • CI mode: {ci_choice}")
    print()

    docs_dir = target_dir / "docs"
    if docs_dir.exists() and not force:
        print(f"⚠️ Warning: Directory '{docs_dir}' already exists.")
        print("   Existing files will be preserved. Only missing templates and directories will be created.")

    # 1. Unpack assets
    assets = unpack_assets()

    # 2. Create directory skeleton
    dirs_to_create = [
        docs_dir / "00_Templates",
        docs_dir / ".obsidian",
        docs_dir / "01_Architecture",
        docs_dir / "02_Tasks" / "Plans",
        docs_dir / "02_Tasks" / "Specs",
        docs_dir / "02_Tasks" / "Bugs",
        docs_dir / "02_Tasks" / "Releases",
        docs_dir / "03_Decisions_ADR",
        docs_dir / "04_Research",
        docs_dir / "05_Testing",
        target_dir / "scripts",
    ]

    for d in dirs_to_create:
        d.mkdir(parents=True, exist_ok=True)
        # Ensure .gitkeep in empty dirs so Git tracks them
        if not list(d.glob("*")):
            (d / ".gitkeep").touch()

    # 3. Write unpacked templates and scripts
    today_str = date.today().isoformat()
    tpl_count, skills_count = deploy_infrastructure(target_dir, assets, stack_key, today_str)
    print(f"✅ Deployed {tpl_count} templates and Obsidian graph configuration.")
    print("✅ Deployed scripts/kb_lint.py and scripts/kb_release.py.")
    if skills_count > 0:
        print(f"✅ Deployed {skills_count} AI agent skills (.agents/skills/).")

    # 4. Generate starter knowledge base documents
    create_starter_docs(target_dir, project_name, stack_key, assets=assets, force=force, idea=idea)
    print("✅ Created starter knowledge base docs (SPEC.md, 00_Index.md, Onboarding.md, Kanban.md, Roadmap.md, Devlog.md).")

    # 4.1. Handle README.md and .gitignore (non-destructive)
    handle_readme(target_dir, project_name, doc_lang)
    handle_gitignore(target_dir)

    # 5. Generate Agent rule files
    for agent_key, rule_path, content, desc in get_agent_rule_specs(target_dir, project_name, stack_key, doc_lang):
        if agent_choice == "all" or agent_choice == agent_key or agent_key == "all":
            rule_path.parent.mkdir(parents=True, exist_ok=True)
            rule_path.write_text(content, encoding="utf-8")
            print(f"✅ Created {desc}.")

    # 6. Verify knowledge base integrity with kb_lint.py
    run_linter_audit(target_dir, docs_dir)

    # 6.1. CI setup
    deploy_ci_workflow(target_dir, ci_choice, assets=assets)

    # 7. Git setup
    setup_git(target_dir, git_choice)

    # 8. Success banner and instructions
    print("\n" + "=" * 70)
    print(f"🎉 Agent Docs-as-Code Harness installed successfully in '{project_name}'!")
    print("=" * 70)
    print("\n📚 Next Steps for You & Your AI Agent:")
    print("  1. Open the project folder in VS Code / Cursor / Obsidian:")
    print(f"     code \"{target_dir.resolve()}\"")
    print("  2. In Obsidian: Open Vault -> choose folder 'docs/' to view the colored graph!")
    if stack_key == "undecided":
        print("  3. Ask your AI Agent (Start with Mode 0 Discovery & Tech Stack Research):")
        print("     \"Please read AGENTS.md and start Mode 0: /kb-research <исследование идеи и выбор стека>\"")
    else:
        print("  3. Ask your AI Agent:")
        print("     \"Please read AGENTS.md and let's start Mode 1 (Planning) for our first task.\"")
    print("  4. Verify your documentation anytime:")
    print("     python3 scripts/kb_lint.py --path docs\n")


# --- SAFE HARNESS UPDATE ---

def record_devlog_update(docs_dir: Path, today_str: str, doc_lang: str = "ru"):
    devlog_path = docs_dir / "Devlog.md"
    if not devlog_path.is_file():
        return
    content = devlog_path.read_text(encoding="utf-8")
    if doc_lang == "en":
        entry = (
            f"### [{today_str}] — Docs-as-Code Harness Components Update (`install.py --update`)\n"
            "- **What was updated:**\n"
            "  - Note templates in `docs/00_Templates/` refreshed to latest version.\n"
            "  - Standalone utilities (`scripts/kb_lint.py`, `scripts/kb_release.py`) updated.\n"
            "  - AI agent skills in `.agents/skills/` synchronized.\n"
            "  - Obsidian graph configuration `docs/.obsidian/graph.json` refreshed.\n"
            "- **Integrity verification:**\n"
            "  - Link integrity audit performed with `kb_lint.py`.\n"
            "- **Recommended Next Step (Awaiting user command):** Review updated components or resume task work via `/kb-task` or `/kb-implement`.\n\n---\n\n"
        )
    else:
        entry = (
            f"### [{today_str}] — Обновление компонентов Docs-as-Code Harness (`install.py --update`)\n"
            "- **Что обновлено:**\n"
            "  - Шаблоны заметок в `docs/00_Templates/` обновлены до актуальной версии.\n"
            "  - Автономный линтер и утилиты релизов в `scripts/` обновлены.\n"
            "  - Скиллы AI-агентов в `.agents/skills/` актуализированы.\n"
            "  - Конфигурация графа `docs/.obsidian/graph.json` актуализирована.\n"
            "- **Проверка:**\n"
            "  - Проведен контрольный аудит целостности ссылок через `kb_lint.py`.\n"
            "- **Рекомендуемый следующий шаг (Ожидает команды пользователя):** Ознакомиться с обновлениями или продолжить работу через `/kb-task` или `/kb-implement`.\n\n---\n\n"
        )
    if "### [" in content:
        idx = content.find("### [")
        new_content = content[:idx] + entry + content[idx:]
    else:
        new_content = content.rstrip() + "\n\n---\n\n" + entry
    devlog_path.write_text(new_content, encoding="utf-8")
    print("📝 Appended update record to docs/Devlog.md.")


def update_agent_rules_safe(target_dir: Path, project_name: str, stack_key: str, doc_lang: str, backup: bool = True):
    for _, rule_path, new_content, _ in get_agent_rule_specs(target_dir, project_name, stack_key, doc_lang):
        if rule_path.is_file():
            existing = rule_path.read_text(encoding="utf-8")
            if existing.strip() != new_content.strip():
                if backup:
                    bak = rule_path.with_name(rule_path.name + ".bak")
                    bak.write_text(existing, encoding="utf-8")
                    print(f"⚠️ Backed up modified {rule_path.name} to {bak.name} and updated to latest version.")
                rule_path.write_text(new_content, encoding="utf-8")
            else:
                print(f"ℹ️ {rule_path.name} is already up to date.")


def update_harness(
    target_dir: Path,
    assets: dict = None,
    stack_key: str = None,
    doc_lang: str = None,
    project_name: str = None,
    ci_provider: str = None,
    backup: bool = True,
) -> int:
    docs_dir = target_dir / "docs"
    if not (docs_dir / "00_Index.md").is_file():
        print(f"❌ Error: 'docs/00_Index.md' not found in {target_dir.resolve()}.")
        print("   This directory does not appear to be an initialized Agent Docs-as-Code project.")
        return 1

    print(f"\n🔄 Updating Agent Docs-as-Code Harness components in: {target_dir.resolve()}")

    if assets is None:
        assets = unpack_assets()

    today_str = date.today().isoformat()

    # Detect project attributes if not specified
    if not project_name:
        spec_path = target_dir / "SPEC.md"
        if spec_path.is_file():
            spec_txt = spec_path.read_text(encoding="utf-8")
            m = re.search(r'title:\s*["\']?(?:Мастер-спецификация:\s*)?([^"\'\n]+)', spec_txt)
            if m:
                project_name = m.group(1).strip()
        if not project_name:
            project_name = target_dir.name or "Project"

    if not stack_key or stack_key == "auto":
        stack_key = detect_project_stack(target_dir)

    if not doc_lang:
        agents_path = target_dir / "AGENTS.md"
        if agents_path.is_file() and ("Russian" in agents_path.read_text(encoding="utf-8") or "Русский" in agents_path.read_text(encoding="utf-8")):
            doc_lang = "ru"
        else:
            doc_lang = "en"

    print(f"   • Project: {project_name}")
    print(f"   • Stack: {STACK_PRESETS.get(stack_key, STACK_PRESETS['generic'])['name']}")
    print(f"   • Language: {doc_lang}\n")

    # Ensure Releases directory exists (safely preserving any existing releases)
    releases_dir = docs_dir / "02_Tasks" / "Releases"
    releases_dir.mkdir(parents=True, exist_ok=True)
    if not list(releases_dir.glob("*")):
        (releases_dir / ".gitkeep").touch()

    # Refresh templates, skills, linter, graph
    tpl_count, skills_count = deploy_infrastructure(target_dir, assets, stack_key, today_str)
    print(f"✅ Refreshed {tpl_count} templates and Obsidian graph configuration.")
    print("✅ Refreshed scripts/kb_lint.py and scripts/kb_release.py.")
    if skills_count > 0:
        print(f"✅ Refreshed {skills_count} skills in .agents/skills/.")

    # Safe update of agent rules with .bak
    update_agent_rules_safe(target_dir, project_name, stack_key, doc_lang, backup=backup)

    # Record update in docs/Devlog.md
    record_devlog_update(docs_dir, today_str, doc_lang)

    # Refresh CI workflow if requested or already existing
    if ci_provider == "github" or (target_dir / ".github" / "workflows" / "kb-lint.yml").is_file():
        deploy_ci_workflow(target_dir, "github", assets=assets)

    # Run kb_lint audit
    run_linter_audit(target_dir, docs_dir)

    print("\n" + "=" * 70)
    print("🎉 Docs-as-Code Harness components successfully updated to latest version!")
    print("=" * 70 + "\n")
    return 0


# --- INTERACTIVE CLI WIZARD ---

def prompt_user_input(prompt_text: str, default: str = "") -> str:
    default_hint = f" [{default}]" if default else ""
    try:
        val = input(f"{prompt_text}{default_hint}: ").strip()
        return val if val else default
    except (EOFError, KeyboardInterrupt):
        return default


def run_interactive_wizard(args) -> tuple:
    print("""
╭──────────────────────────────────────────────────────────╮
│  ✨ Agent Docs-as-Code Harness Installer                 │
│  Zero-Dependency AI Agent Discipline & Obsidian Vault   │
╰──────────────────────────────────────────────────────────╯
""")

    # Try reopening TTY if piped through curl
    if not sys.stdin.isatty():
        try:
            if os.name != "nt" and os.path.exists("/dev/tty"):
                sys.stdin = open("/dev/tty", "r")
            elif os.name == "nt":
                sys.stdin = open("CONIN$", "r")
        except Exception:
            pass

    target_dir = Path(args.target_dir).resolve()
    default_name = args.name or target_dir.name or "MyProject"

    # 1. Project Name
    project_name = prompt_user_input("? Enter Project Name", default=default_name)

    # 2. Documentation & Agent Communication Language
    print("\n? Preferred documentation & agent communication language:")
    print("  [1] Russian (Русский) [Recommended for RU teams]")
    print("  [2] English")
    print("  [3] Custom language (type name)")
    lang_choice_input = prompt_user_input("Select [1-3]", default="1")
    if lang_choice_input == "1":
        doc_lang = "ru"
    elif lang_choice_input == "2":
        doc_lang = "en"
    elif lang_choice_input == "3":
        doc_lang = prompt_user_input("Enter language name", default="ru")
    else:
        doc_lang = "ru"

    # 3. Technology Stack
    if getattr(args, "idea", None) and not args.stack:
        detected_stack = "undecided"
    else:
        detected_stack = detect_project_stack(target_dir)
        if args.stack and args.stack != "auto":
            detected_stack = args.stack
    stack_choice_map = {"swift": "1", "ts": "2", "python": "3", "dotnet": "4", "generic": "5", "undecided": "6"}
    detected_num = stack_choice_map.get(detected_stack, "1")

    print("\n? Select Technology Stack:")
    print(f"  [1] iOS / macOS (Swift, SwiftUI, Xcode) [Target Apple Stack]{' (Detected)' if detected_stack == 'swift' else ''}")
    print(f"  [2] Web / Node (TypeScript, JavaScript, Next.js){' (Detected)' if detected_stack == 'ts' else ''}")
    print(f"  [3] Python (Pytest, FastAPI, CLI){' (Detected)' if detected_stack == 'python' else ''}")
    print(f"  [4] .NET / C# (MAUI, ASP.NET, CoreCLR){' (Detected)' if detected_stack == 'dotnet' else ''}")
    print(f"  [5] Generic / Other{' (Detected)' if detected_stack == 'generic' else ''}")
    print(f"  [6] 💡 Undecided / Idea-First (Стек будет определен через /kb-research){' (Detected)' if detected_stack == 'undecided' else ''}")
    stack_choice = prompt_user_input("Select [1-6]", default=detected_num)
    stack_map = {"1": "swift", "2": "ts", "3": "python", "4": "dotnet", "5": "generic", "6": "undecided"}
    stack_key = stack_map.get(stack_choice, detected_stack)

    # If stack is undecided and no idea provided via flag, ask for idea
    if stack_key == "undecided" and not getattr(args, "idea", None):
        user_idea = prompt_user_input("? Enter your project idea / concept (or press Enter to describe later)", default="")
        if user_idea:
            args.idea = user_idea

    # 4. AI Agent Setup
    print("\n? Select AI Agent / IDE Setup:")
    print("  [1] All AI Agents (AGENTS.md, GEMINI.md, Cline, Claude, Cursor, Copilot, Windsurf) [Recommended]")
    print("  [2] VS Code Cline & Roo Code (.clinerules)")
    print("  [3] Claude Code CLI (CLAUDE.md)")
    print("  [4] Cursor IDE (.cursorrules)")
    print("  [5] GitHub Copilot (.github/copilot-instructions.md)")
    print("  [6] Google Antigravity & Gemini CLI (GEMINI.md)")
    print("  [7] Windsurf Cascade (.windsurfrules)")
    print("  [8] Universal AGENTS.md only")
    agent_choice_input = prompt_user_input("Select [1-8]", default="1")
    agent_map = {"1": "all", "2": "cline", "3": "claude", "4": "cursor", "5": "copilot", "6": "gemini", "7": "windsurf", "8": "generic"}
    agent_choice = agent_map.get(agent_choice_input, "all")

    # 5. Git Setup
    print("\n? Git Version Control Setup:")
    print("  [1] Local Git (Initialize repository & commit initial docs) [Recommended]")
    print("  [2] Connect to GitHub (Local commit + setup guidance)")
    print("  [3] Skip Git")
    git_choice_input = prompt_user_input("Select [1-3]", default="1")
    git_map = {"1": "local", "2": "github", "3": "none"}
    git_choice = git_map.get(git_choice_input, "local")

    # 6. CI Setup
    print("\n? Continuous Integration (CI) Workflow:")
    print("  [1] None (Local-Only / Skip CI) [Default]")
    print("  [2] GitHub Actions (.github/workflows/kb-lint.yml)")
    ci_choice_input = prompt_user_input("Select [1-2]", default="1")
    ci_map = {"1": "none", "2": "github"}
    ci_choice = ci_map.get(ci_choice_input, "none")

    return project_name, stack_key, agent_choice, git_choice, doc_lang, ci_choice


# --- MAIN ENTRY POINT ---

def main():
    parser = argparse.ArgumentParser(
        description="Agent Docs-as-Code Harness Installer",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""Examples:
  python3 install.py
  python3 install.py -y -n MyApp -s swift -a all -g local
  python3 install.py -y -d ../project -s ts -l en --ci github
""",
    )

    parser.add_argument("--name", "-n", type=str, help="Project name (default: current directory name)")
    parser.add_argument(
        "--idea",
        type=str,
        default=None,
        help="Краткое описание продуктовой идеи для Greenfield-инициализации (автоматически активирует пресет undecided, если --stack не указан)",
    )
    parser.add_argument(
        "--doc-lang", "-l",
        type=str,
        default=None,
        help="Preferred documentation & agent communication language (e.g. ru, en, custom; default: ru)",
    )
    parser.add_argument(
        "--stack", "-s",
        choices=["auto", "swift", "ts", "python", "dotnet", "generic", "undecided"],
        default=None,
        help="Target technology stack preset (default: auto)",
    )
    parser.add_argument(
        "--agent", "-a",
        choices=["all", "cline", "claude", "cursor", "copilot", "gemini", "windsurf", "generic"],
        default=None,
        help="AI agent / editor configuration files to generate (default: all)",
    )
    parser.add_argument(
        "--git", "-g",
        choices=["local", "github", "none"],
        default=None,
        help="Git version control strategy (default: local)",
    )
    parser.add_argument(
        "--ci",
        choices=["github", "none"],
        default=None,
        help="Continuous Integration workflow to deploy (default: none)",
    )
    parser.add_argument(
        "--target-dir", "-d",
        type=str,
        default=".",
        help="Target directory where the harness will be installed (default: current directory)",
    )
    parser.add_argument(
        "--non-interactive", "-y", "--yes",
        action="store_true",
        help="Run without interactive prompts, accepting flags or defaults",
    )
    parser.add_argument(
        "--force", "-f",
        action="store_true",
        help="Overwrite existing configuration files if present",
    )
    parser.add_argument(
        "--update", "-u",
        action="store_true",
        help="Update harness infrastructure (templates, linter, skills, graph) safely in existing project",
    )

    args = parser.parse_args()
    target_dir = Path(args.target_dir).resolve()

    # Handle --update mode directly
    if args.update:
        exit_code = update_harness(
            target_dir=target_dir,
            stack_key=args.stack,
            doc_lang=args.doc_lang,
            project_name=args.name,
            ci_provider=args.ci,
        )
        sys.exit(exit_code)

    # Determine whether to run interactively
    is_interactive = not args.non_interactive and (sys.stdin.isatty() or os.name == "nt" or os.path.exists("/dev/tty"))

    # If flags were all explicitly passed, run directly
    if args.stack and args.agent and args.git and args.name:
        is_interactive = False

    if is_interactive:
        project_name, stack_key, agent_choice, git_choice, doc_lang, ci_choice = run_interactive_wizard(args)
    else:
        project_name = args.name or target_dir.name or "MyProject"
        if args.idea and not args.stack:
            stack_key = "undecided"
        else:
            stack_key = detect_project_stack(target_dir) if (not args.stack or args.stack == "auto") else args.stack
        agent_choice = args.agent or "all"
        git_choice = args.git or "local"
        doc_lang = args.doc_lang or "ru"
        ci_choice = args.ci or "none"

    install_harness(
        target_dir=target_dir,
        project_name=project_name,
        stack_key=stack_key,
        agent_choice=agent_choice,
        git_choice=git_choice,
        doc_lang=doc_lang,
        force=args.force,
        ci_choice=ci_choice,
        idea=args.idea,
    )


if __name__ == "__main__":
    main()
